### ISSUE TITLE
Suspected invalid interactions — Plant associated genomovirus 3/Gemykibivirus cynas1

### ISSUE THREAD

**Issue by RandolphQuek** [globalbioticinteractions/globalbioticinteractions#1007]
Based on both NCBI and Mihara et al. (2016), plant associated genomovirus 3 is associated with the genus _Cynodon_, which is a fish.  _Cynodon_ is also a genus for a grass, which is an unfortunate coincidence, leading to the erroneous entry. 

The record for the RefSeq genome (NC_076284.1) refers to a plant from Africa, and not the fish (see below). 

Thank you for the comprehensive database!

![NC_0762841](https://github.com/user-attachments/assets/3d431cf5-5997-4ef1-bf99-b67dbd9b703d)

**Comment by jhpoelen** [comment]
@RandolphQuek thanks for sharing your observation. Can you please point to the GloBI search / record that pointed to  "The record for the RefSeq genome (NC_076284.1)" ? Having these and other details on how you found this interaction helps expedite the root cause analysis on this suspected invalid interaction. 

Thanks for being patient.

**Comment by RandolphQuek** [comment]
@jhpoelen I gathered this reference genome from Virus-Host DB (https://www.genome.jp/virushostdb), which got it from RefSeq. I suspect that this RefSeq record was perpetuated into GloBI, as a result of the shared genus name.

From the same database, I did observe a second missed record with the genus _Morus_, belonging to both mulberry and ganets, but this was not present in GlobBI.

Hope this helps!

**Comment by jhpoelen** [comment]
@RandolphQuek thanks for sharing additional details on the origin (or provenance) of the interaction records you discussed. 

Can you please add more details related to the interaction claims that you find suspicious? 

For instance, can you describe the steps you took to find the suspicious interaction claims, so that I can retrace your steps?

**Comment by RandolphQuek** [comment]
@jhpoelen Certainly!

The claims that are suspicious are as follows: Plant associated genomovirus 3 is a plant virus, with two records in Genbank (nt): NC_076284.1 (identical to MH939438) and MH939439. Based on ICTV taxonomy browser, it was first described in a 2020 submission, with the reference genome being MH939438 (see below screenshot).

![image](https://github.com/user-attachments/assets/a9db5737-52ed-467d-87e0-751091fe3492)

Based on the GenBank record, the virus was isolated from a leaf in a species found in South Africa within the _Cynodon_ genus, which is a grass. Unfortunately, _Cynodon_ shares the same genus name as a dogtooth characin from South America, likely leading to the assumption that the virus is also found in the vertebrate _Cynodon_ too.

Indeed, the Virus-Host DB lists both _Cynodon_ as hosts, one being the grass species, and the other being the fish (see below). Both lists RefSeq as their source.
(https://www.genome.jp/virushostdb/2584397)

![image](https://github.com/user-attachments/assets/35a6b7ff-6ba4-4535-a7c4-eecaa6a24875)

I found out about this suspicious interaction as I downloaded the list of viruses with host information from Virus-Host DB (https://www.genome.jp/virushostdb/) and was filtered for only "Vertebrata" under hosts to look at vertebrate hosts with viruses. Chancing upon this record, with a plant-associated virus, I then went to check GloBI, and found that the fish _Cynodon_ was listed as a host for this pathogen. However, it is a suspicious interaction for the fish being a host for plant associated genomovirus 3 as: (1) the virus was recently described from a plant in Africa, (2) the virus was isolated from a plant with the same genus name as the fish, and (3) the fish is found in South America. There is also no evidence to suggest that the fish was found with the virus isolated from it to date.

Hope this helps!

**Comment by jhpoelen** [comment]
Yes, thank you for retracing your steps. With your details, I believe I was able to locate the suspicious index record via https://www.globalbioticinteractions.org/?interactionType=ecologicallyRelatedTo&sourceTaxon=Cynodon&targetTaxon=Plant%20associated%20genomovirus%203 . 

with 

Mihara, T., Nishimura, Y., Shimizu, Y., Nishiyama, H., Yoshikawa, G., Uehara, H., Hingamp, P., Goto, S., and Ogata, H.; Linking virus genomes with host taxonomy. Viruses 8, 66 doi:10.3390/v8030066 (2016). Accessed at <ftp://ftp.genome.jp/pub/db/virushostdb/virushostdb.daily.tsv> on 10 Aug 2024. Provider: [⚙️](https://github.com/globalbioticinteractions/virus-host-db) [🔍](https://www.globalbioticinteractions.org/?interactionType=ecologicallyRelatedTo&accordingTo=globi%3Aglobalbioticinteractions%2Fvirus-host-db) Mihara, T., Nishimura, Y., Shimizu, Y., Nishiyama, H., Yoshikawa, G., Uehara, H., Hingamp, P., Goto, S., and Ogata, H.; Linking virus genomes with host taxonomy. Viruses 8, 66 doi:10.3390/v8030066 (2016). Accessed via <https://github.com/globalbioticinteractions/virus-host-db/archive/4928da32147a3a3668d41569a05a756b4a8619cf.zip> at 2024-08-10T15:31:56.118Z.

also see associated screenshot. 

![Screenshot from 2024-08-20 07-29-17](https://github.com/user-attachments/assets/7ed18da4-7470-418d-9703-e2b28af65cee)

I can tell that the name Cynodon has multiple links within some taxonomic resources (e.g., Catalogue of Life, NCBI Taxonomy).

Some examples include:

https://www.catalogueoflife.org/data/taxon/8V5BR (no longer exists or was removed)
https://www.catalogueoflife.org/data/taxon/8VWNP (a plant genus)
https://www.catalogueoflife.org/data/taxon/9JJTK (known unacceptable synonym of plant genus Distichium Bruch & Schimp.)

With this, I have enough information to dig into the details of the taxonomic alignment. Please stay tuned.

**Comment by jhpoelen** [comment]
On 2024-08-17T11:48:52.479Z, GloBI accessed 
 ftp://ftp.genome.jp/pub/db/virushostdb/virushostdb.daily.tsv with associated content id (aka hash)	hash://sha256/d7de060cc4071d404fdbfb72b9cc93dbb2717190d66d9f83bdc583cf038001b1

I've attached a copy .

In this virushostdb snapshot, the following two records related to Cynodon and Plant associated genomovirus 3 can be found:

| virus tax id | virus name | virus lineage | refseq id | KEGG GENOME | KEGG DISEASE | DISEASE | host tax id | host name | host lineage | pmid | evidence | sample type | source organism |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| 2584397 | Plant associated genomovirus 3 | Viruses; Monodnaviria; Shotokuvirae; Cressdnaviricota; Repensiviricetes; Geplafuvirales; Genomoviridae; Gemykibivirus; Gemykibivirus cynas1 | NC_076284 |  |  |  | 15437 | Cynodon | Eukaryota; Viridiplantae; Streptophyta; Streptophytina; Embryophyta; Tracheophyta; Euphyllophyta; Spermatophyta; Magnoliopsida; Mesangiospermae; Liliopsida; Petrosaviidae; commelinids; Poales; Poaceae; PACMAD clade; Chloridoideae; Cynodonteae; Eleusininae |  | RefSeq |  |  |
| 2584397 | Plant associated genomovirus 3 | Viruses; Monodnaviria; Shotokuvirae; Cressdnaviricota; Repensiviricetes; Geplafuvirales; Genomoviridae; Gemykibivirus; Gemykibivirus cynas1 | NC_076284 |  |  |  | 210603 | Cynodon | Eukaryota; Opisthokonta; Metazoa; Eumetazoa; Bilateria; Deuterostomia; Chordata; Craniata; Vertebrata; Gnathostomata; Teleostomi; Euteleostomi; Actinopterygii; Actinopteri; Neopterygii; Teleostei; Osteoglossocephalai; Otomorpha; Ostariophysi; Otophysi; Characiphysae; Characiformes; Characoidei; Characidae; Rhaphiodontinae |  | RefSeq |  |  |

Where one record, the host genus is associated with a plant, the other with a fish. 

So, it appears that the suspicious taxonomic alignment seems to originate from the source data also. 

Please confirm. 

[virushostdb-cynodon.tsv.txt](https://github.com/user-attachments/files/16675968/virushostdb-cynodon.tsv.txt)
[d7de060cc4071d404fdbfb72b9cc93dbb2717190d66d9f83bdc583cf038001b1.tsv.txt](https://github.com/user-attachments/files/16675969/d7de060cc4071d404fdbfb72b9cc93dbb2717190d66d9f83bdc583cf038001b1.tsv.txt)

**Comment by jhpoelen** [comment]
Note that GloBI should have listed two records - one for the plant, one for the fish, as the source uses two specific ncbi taxon identifiers to point to the homonyms:

https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=15437

and 

https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=210603

instead, the two ncbi taxonomic identifiers are grouped into a single taxonomic classification. I need to dig a little deeper to find out why GloBI got confused here.

**Comment by RandolphQuek** [comment]
@jhpoelen Sorry for the delayed response, I got caught some stuff this week!

1. Indeed, it is an unfortunate coincidence that both the fish and the plant shares the same genus name, leading to the confusion across the different databases. I observe the same phenomenon for _Morus_, a genus shared by mulberry and a ganet (bird) (see point 3).

2. Indeed, the suspicious record originates from the database from VirusHost-DB, due to the record in RefSeq associating it with both the plant and the fish from _Cynodo_.

3. The confusion is similar to a related case of _Morus_. While most of the records on virushost-db are correct for mulberry viruses, the record for Mulberry mosaic dwarf associated virus is wrong (see highlighted below). This erroneous record is *not* reflected in GlobBI, which probably managed to separate the two taxa out properly.

![image](https://github.com/user-attachments/assets/2e4a7633-bd30-4232-86d9-9c307cd1a69d)

Thanks for looking into this!

**Comment by jhpoelen** [comment]
Thanks for the discussion earlier this year @RandolphQuek . Please feel free to comment / reopen if you feel this issue needs a little more attention.
