### ISSUE TITLE
A single most updated file of all pair-wise interactions

### ISSUE THREAD

**Issue by kpmainali** [globalbioticinteractions/globalbioticinteractions#1034]
I would like to obtain every single pair-wise interaction detail (such as the name of the two species involved in interaction, type of interaction, study location, etc). I prefer to receive the most recent version of the entire database in a single file. Reading your website, it seems that the following page:
https://zenodo.org/records/11552565
has the following file that I should use:"interactions.tsv.gz".

Could you please confirm if I have the correct interpretation of your database?

**Comment by jhpoelen** [comment]
@kpmainali interactions.tsv.gz is contains all indexed interaction claim 
 with interpreted taxonomic names. For verbatim taxonomic names, you'd use verbatim-interactions.tsv.gz . See https://globalbioticinteractions.org/process for some details on how these datasets are compiled. 

 Does this answer your question?

**Comment by kpmainali** [comment]
Yes, thank you @jhpoelen

**Comment by jhpoelen** [comment]
One place you can find a summary on top of the https://globalbioticinteractions.org/references . 

You can also use the recipes at https://globalbioticinteractions.org/how-to to create your own.
