### ISSUE TITLE
automatically discover interaction data across known data repositories

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions#163]
Many data repositories for scientific data repositories now exist: dryad, zenodo, figshare and ecological archives. In order for GloBI to keep up with discovering and integrating the wealth of interaction data out there, we might have to go beyond manual checking of known repositories and word-of-mouth.

I think it would be nice to develop method to automatically ingest meta-data associated to possible species interaction studies. In the future, we'd develop clever ways to automatically ingest the interaction data as well if the data formats are supported by GloBI.

Here's a list of datasets on dryad related to "diet database": 
http://datadryad.org/discover?query=diet+database&submit=Go

**Comment by cmungall** [comment]
Maybe some journals could help with this? If they were to require conformance to some fairly simple standards when depositing in dryad/wherever, then interactions become not only more easily discovered, but auto-ingestible

**Comment by jhpoelen** [comment]
Collaborating with a journal would definitely be a big help. Would you happen to know anyone on the editorial board of Ecological Society of America journals? We've already ingested many of their data papers published in http://esapubs.org/archive/default.htm (e.g. [Planque et al. 2014](http://dx.doi.org/10.1890/13-1062.1), [Barnes et al. 2008](http://dx.doi.org/10.1890/07-1551.1) ). In addition to making the data more easily to discover, I can see GloBI play a roll in the peer review of the datasets: the act of integrating the datasets: many of ingested datasets have published revised version of their published data following improvement suggestions by GloBI.

**Comment by jhpoelen** [comment]
See related issue #212 - zenodo integration is now supported by GloBI. Curation process is now for authors to submit their datasets on zenodo to https://zenodo.org/communities/globalbioticinteractions .

**Comment by jhpoelen** [comment]
automated discovery has been implemented in various ways: IPT RSS feeds, automated GitHub repository discovery, Zenodo discovery. If more avenues become feasible, suggest to open separate issues.
