### ISSUE TITLE
rearranging attribution in DwC-A export to include the browser link for the taxon

### ISSUE THREAD

**Issue by jhammock** [globalbioticinteractions/globalbioticinteractions#171]
The source link should contain a link to the GloBI browser query for all interaction data for that species. If the previous source link was redundant with the Reference, it can simply be replaced. If it contains a url for a domain not mentioned in the References, it should be appended to each existing Reference, with conjunction text like, "Compiled by"

Examples:

Current behavior:

source: http://gomexsi.tamucc.edu
Scientific name: Centropomidae
Reference: Blewett DA, Hensley RA, and Stevens PW, Feeding Habits of Common Snook, Centropomus Undecimalis, in Charlotte Harbor, Florida, Gulf and Caribbean Research Vol 18, 1-13, 2006

source: A. Thessen. 2014. Species associations extracted from EOL text data objects via text mining. Accessed at https://raw.githubusercontent.com/EOL/pseudonitzchia/master/assoc on 08 Apr 2015
scientific name: Pomatomus
Reference: A. Thessen. 2014. Species associations extracted from EOL text data objects via text mining. Accessed at https://raw.githubusercontent.com/EOL/pseudonitzchia/master/assoc on 08 Apr 2015

source: http://iNaturalist.org is a place where you can record what you see in nature, meet other nature lovers, and learn about the natural world. Accessed at http://inaturalist.org on 08 Apr 2015
scientific name: Phalacrocoracidae
Reference: Ryan Blankenship. 2015. Phalacrocorax auritus eating Arius felis. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/1298913 on 08 Apr 2015. 

Desired behavior:

source: http://www.globalbioticinteractions.org/browse/index.html#interactionType=interactsWith&resultType=json&sourceTaxon=Centropomidae
Scientific name: Centropomidae
Reference: Blewett DA, Hensley RA, and Stevens PW, Feeding Habits of Common Snook, Centropomus Undecimalis, in Charlotte Harbor, Florida, Gulf and Caribbean Research Vol 18, 1-13, 2006 Compiled by <a href="http://gomexsi.tamucc.edu">gomexsi</a>

source: http://www.globalbioticinteractions.org/browse/index.html#interactionType=interactsWith&resultType=json&sourceTaxon=Pomatomus
scientific name: Pomatomus
Reference: A. Thessen. 2014. Species associations extracted from EOL text data objects via text mining. Accessed at https://raw.githubusercontent.com/EOL/pseudonitzchia/master/assoc on 08 Apr 2015

source: http://www.globalbioticinteractions.org/browse/index.html#interactionType=interactsWith&resultType=json&sourceTaxon=Phalacrocoracidae
scientific name: Phalacrocoracidae
Reference: Ryan Blankenship. 2015. Phalacrocorax auritus eating Arius felis. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/1298913 on 08 Apr 2015.

**Comment by jhpoelen** [comment]
Closing stale issue.
