### ISSUE TITLE
introduce 3-way (or n-way) interactions

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions#207]
from https://github.com/jhpoelen/eol-globi-data/issues/206#issuecomment-184008571 -

`Since vectors can be host-specific, we would ideally describe a 3-way relationship here, i.e., Aedes aegypti is vector for Zika virus (ZIKV) in Homo sapiens. Has this sort of thing ever come up before? Has a solution been discussed?`

@cmungall any ideas?

**Comment by cmungall** [comment]
The solution I would favor for GloBI would be to make 3 distinct statements, and then link them. The linkages may be at the level of individual, but as the individual is formally the specimen is globally this is problematic (it's not the same specimen of zika in all 3 cases).

I know neo4j doesn't have edge identifiers, but we could have properties on the edges that allow them to be grouped, or even causally connected (e.g. using RO evidence-for type relationships).

As noted in the ticket, another possibility is to add an additional 'vector' property to the pathogen-host edge, but I'm not so keen on this.

Either way, we must think how the representation relates to simple TSV style exchanges. Can we always make the assumption that if we see

 1. `A pathogen-of H`
 2. `V vector-for A`
 3. `A parasite-of V`

In a single TSV document, then we can assume a causal bundling?

**Comment by jhpoelen** [comment]
@cmungall provided example of "ternary" (or three-way) interactions http://blogs.plos.org/ecology/2016/03/02/the-enemy-of-my-enemy-ismy-alligator-mutualism-and-protection-rackets-in-the-florida-everglades/ .

**Comment by jhpoelen** [comment]
still thinking about ways to represent the three-way interaction is a practical way . . . more later.

**Comment by jhammock** [comment]
@cmungall I'm fuzzy on the inference scenario. Did you mean this?

A pathogen-of H
V vector-for A
V parasite-of H

I'm afraid that leaves open the possibility of 
A pathogen-of H (no vector needed)
V vector-for A (to infect G)
V parasite-of H (carrying no pathogen)

and other variants. I believe any bundling would have to be explicit.

**Comment by arw36** [comment]
Checking in as I was curious about this in recent discussions for co-roosting (see #583). A discovery that Species A-Species B-Species C all co roost is different than single instances of pairwise interactions (Species A-Species B, Species B-Species C, Species C-Species A) and then inferring the potential ternary or n-ary interaction. Other scenarios would be the detection of a pathogen A from a vector V collected from a host H. This  ternary interaction on site is much more important than inferring a relationship from A pathogen-of H, V vector-for A, V parasite-of H. Other instances I could envision include hyperparasitism, necropsies that document parasites and stomach contents, or co-infections showcasing parasite communities within a host.

**Comment by jhpoelen** [comment]
@arw36 thanks for chiming in. And I agree that an observations at some point in time at some location that individuals of species A,B,C in fact co-roost is different than some other observations that provide evidence to support that A-[:co_roosts]->B and B-[:co_roosts]->C and C-[:co_roosts]->A where the evidence comes from observations at different points in time and/or different locations.

The date/time/location is an intuitive way to document ternary on-site interaction, and other methods (like occurrence id to identify the physical specimen, or some network id) can be used also.

I am curious to hear your thoughts on how you would capture ternary interactions in digital form.

Note that GloBI indexes time/location etc. even though this might not be prominently displayed in the basic web ui that https://globalbioticinteractions.org provide.

**Comment by arw36** [comment]
ugh, I'd hate to break away from the current data format. I wonder if there could be a "non-directed" version for interactions.tsv without this "source" "target" dichotomy. There's likely a better term for this. In this case, you would have one file which lists "interactors" and their interaction, each species as a row. Then coding would wrap them all together? This would suffice for "co-occurs with" type interaction. Hyperparasitism or host-vector-pathogen detections may be more difficult.

**Comment by jhpoelen** [comment]
hey @arw36 - no need to break away from the source/target idea in my opinion. Depending on the verb used (e.g., co-roosting, eats), the left/right (or subject/object) side of the sentence will take on different meanings. But perhaps I am missing something. Please elaborate if I am.

**Comment by jhpoelen** [comment]
Just to add @arw36 - the table template provided via https://github.com/globalbioticinteractions/template-dataset is just one of the many data formats supported by GloBI. If you find some other format more suited for your use case, please don't hesitate to share!

**Comment by jhpoelen** [comment]
closing stale issue
