### ISSUE TITLE
ncbi taxa resolved through globalnames include unexpected results

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions#243]
@dimus I think we discussed this some time ago. Just putting this issue in as a reminder for myself. If you have an open issue on this, please do link it. I tried to look for it, but failed to find it.

When resolving a taxon name like `Triticum` to NCBI taxon using globalnames resolver, many NCBI links are reported, including [Triticum aestivum/Septoria tritici mixed cDNA library](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=1324879)  [Triticum aestivum/Puccinia triticina mixed EST library](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=209538), [Triticum aestivum/Gaeumannomyces graminis mixed EST library](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=246825) and [
Triticum aestivum/Phaeosphaeria nodorum mixed EST library](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=331356).

Expected result is a single NCBI hit to genus [Triticum](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=4564).

from http://www.globalbioticinteractions.org/?sourceTaxon=Triticum&interactionType=interactsWith : 
![screen shot 2016-08-05 at 4 24 53 pm](https://cloud.githubusercontent.com/assets/1084872/17452922/35340c6e-5b29-11e6-8a0d-52deea66c363.png)

from http://resolver.globalnames.org with `Triticum` : 
![screen shot 2016-08-05 at 4 23 19 pm](https://cloud.githubusercontent.com/assets/1084872/17452900/05dee5ce-5b29-11e6-995c-b94bedce2a29.png)

**Comment by jaiswalp** [comment]
Does this help http://tnrs.iplantcollaborative.org/about.html

**Comment by jaiswalp** [comment]
available from here https://github.com/iPlantCollaborativeOpenSource/TNRS/

**Comment by jhpoelen** [comment]
@jaiswalp thanks for your suggestions to use iplant name resolution service. Had a chat with @dimus yesterday and I understood that he expects to improve the ncbi name resolution services with global names resolver for the next major release. This release is expected before tdwg (Dec 2016). I see the global names resolver as an evolution of the iplant name resolution. If @jaiswalp feels strongly about using iplant name resolver, I'd be happy to consider adding it in addition to the global names resolver for the benefit of https://github.com/jhpoelen/samara outcomes.

Leaving this issue open until issue has been addressed by global names resolver or other name resolver used by GloBI.

**Comment by jhpoelen** [comment]
see related issues https://github.com/globalbioticinteractions/globalbioticinteractions/issues/569 and https://github.com/GlobalNamesArchitecture/gni/issues/48 .

**Comment by jhpoelen** [comment]
closing stale issue
