### ISSUE TITLE
integrate with Tri-Trophic Interactions - Texas A&M

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions#262]
As pointed out by Joanna M. of iDigBio:

from https://www.idigbio.org/portal/recordsets/9d8291f9-5c59-4630-8dea-4ac6cc0b1f78 : 
```These data represent the segment of the Tri-Trophic Interactions Project housed at Texas A&M University.```

**Comment by millerse** [comment]
@jhpoelen While large, there is no interaction data recorded in this data.  We might have to ignore this one.

**Comment by jhpoelen** [comment]
Interesting ... did you contact the authors like Dr. John D. Oswald listed on https://www.idigbio.org/portal/recordsets/9d8291f9-5c59-4630-8dea-4ac6cc0b1f78 ? Perhaps they know of a place to extract the tri-trophic interactions.

**Comment by millerse** [comment]
No I just checked the data they had on idigbio.  I also looked at another site where the data was published and there were no signs of interaction data.  I just emailed Dr. Oswald so we might get an answer to that question.

**Comment by millerse** [comment]
Got a response: 

> Hi Sarah,
>     The role of the Texas A&M University Insect Collection (TAMUIC) in the larger Tri-Trophic project was to capture specimen-level data on selected insect groups. However, the Tri-Trophic project was a consortium that included ca. 40 natural history collections, and specifically included collections that contributed both entomological and botanical data, and association data between plants and insects. I believe that the data derived from the Tri-Trophic project (including data from the TAMUIC) is currently being hosted primarily by iDigBio, who should be contacted for information about accessing those data. In its role as a major biodiversity data aggregator, iDigBio is always looking for new uses of the data, so this is a topic that you should pick up with them. I am copying this note to Gil Nelson, who would be a good person to start your inquiries with at iDigBio.
> Cheers,
> John

**Comment by jhpoelen** [comment]
Tri-trophic data is being indexed via @seltmann 's https://github.com/globalbioticinteractions/arthropodEasyCaptureAMNH .

![Screenshot from 2020-12-30 17-09-54](https://user-images.githubusercontent.com/1084872/103389139-de151800-4ac1-11eb-92d3-c0983c77a5e8.png)

**Comment by seltmann** [comment]
@jhpoelen @millerse sorry I just saw this thread and I may be able to give a little information (although late). The Tri-Tropic dataset on iDigBio only includes those collections that used the Arthropod Easy Capture data portal at AMNH. Texas did not use the AMNH portal, thus their Tri-Tropic records are with the rest of the insect data from TAMUIC and are not included in the larger dataset.

**Comment by seltmann** [comment]
The interaction data are largely contained within custom fields (https://docs.google.com/spreadsheets/d/1Vc05OLwd2dBg41pcJdZnBG_zzqZ-OHI696FWU3gAQb0/edit?usp=sharing) that are not visible on the iDigBio portal. Those are also largely also repeated in the associatedTaxa field. If memory serves me, very little (if any) association data came from the collection in Texas to the project.

I just looked at the data today and it looks like some house cleaning at iDigBio was done and the fields were combined into a aec:associatedTaxa field found in the occurrences_raw file.

`"[{""aec:associatedScientificName"": ""Salix"", ""aec:associatedFamily"": ""Salicaceae"", ""aec:associatedRelationshipURI"": ""http://purl.obolibrary.org/obo/RO_0002437"", ""coreid"": ""urn:uuid:865e47f8-d8e1-11e2-99a2-0026552be7ea_RID"", ""aec:associatedRelationshipTerm"": ""associated with"", ""aec:associatedGenus"": ""Salix"", ""dwc:basisOfRecord"": ""LabelObservation"", ""aec:associatedCondition"": ""Unknown"", ""aec:isCultivar"": ""Unknown""}]"`
