### ISSUE TITLE
US National Parasite Collection

### ISSUE THREAD

**Issue by jhammock** [globalbioticinteractions/globalbioticinteractions#296]
For some reason I thought this was in GloBI already, but I can't find it in the status page.

There's a static download at http://invertebrates.si.edu/parasites.htm. I don't think the collection is growing noticeably, but a search of the NMNH catalog records (at any of their locations) with "Collection Name=Parasite Collection" should also work. Not sure if it's worth much extra effort, though.

**Comment by jhpoelen** [comment]
Nice! At first glance, this should be relatively easy to ingest using the meta-table approach like @millerse used in https://github.com/millerse/Dapstrom-integrated-database-and-portal-for-fish-stomach-records - point to a table and provide exhaustive description of columns in the globi.json / schema.json . Please let me know if you need help with this.

**Comment by jhpoelen** [comment]
Also, I'd say probably best to cache the dataset (csv and xls) as part of the repository - just in case the website has up-time issues.

**Comment by millerse** [comment]
Okay so I have the data set up in the meta-table as best as I can remember [here](https://github.com/millerse/US-National-Parasite-Collection/blob/master/schema.json). I do have a major question.

The dataset broke up the species name into two columns: one for genus and one for species.  Any way I can combine the two into one column?  There must be a way.

**Comment by jhpoelen** [comment]
thanks for taking a stab at setting up the meta-table!

About your question - one way to go about it is to introduce (source/target)TaxonGenus and (source/target)TaxonSpecificEpithet in addition to the more generic (source/target)TaxonName. This way, we retain the granular information, and leave it up to the consumer (in this case GloBI) to figure out how to combine them.

Would that work for you?

**Comment by millerse** [comment]
It does.  Thanks for the tip. Take a look at the meta-table now and let me know if there is anything I can do to fix the table.

**Comment by jhpoelen** [comment]
Looks good to me! Suggest to enable travis-ci for this repository (using .travis.yaml + enable on travis), and convert the xlsx to a tsv file, updating the globi.json accordingly.

**Comment by jhpoelen** [comment]
then travis should tell you whether globi can read it ok

**Comment by jhpoelen** [comment]
@millerse thanks again for transcribing the dataset !
