### ISSUE TITLE
introduce explicit did-not-interact interactions

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions#309]
@seltmann suggested to add ability to introduce a way to express "this plant was not visited by bees at this particular date/time/location" .

**Comment by jhammock** [comment]
Oooh... absence data. A bold step. I believe that for occurrence databases where this is not explicitly handled, desperate data owners have been known to get Creative. This data may be rare, but it can be very important. It's also a nice entry point for novice naturalists in citizen science projects. The ID distinction between Somebody and Nobody is not intimidating.

**Comment by cmungall** [comment]
Remember to be clear about the semantics if negation is introduced. If the time point is unspecified does it mean that this plant was never visited by this bee, or any bee?

Is this primarily for recording statements about instances (this plant, this bee) or classes (e.g. taxa)? For example, a statement that carrion flowers are never pollinated by bees, only by flies and beetles.

**Comment by jhpoelen** [comment]
I see two use cases - first is to introduce a way to express expert rule of thumb like the one you mentioned: carrion flowers are not pollinated by bees. This could be used for validation purpose or annotate/express disagreement. The second use case (instance interaction negation, e.g. I've been looking at this flower for days, and I haven't seen a particular bee visiting this particular plant) also came up in a conversation with @seltmann .

**Comment by jhpoelen** [comment]
And yes, depending on the use case, we'd have to be careful to assist data consumers with interpreting the negated interactions.

**Comment by j-oswald** [comment]
A negation relation in the form of "did not visit" might be appropriate. It is past tense so could be applied to past occurrence records while still being silent on the possibility of future visitations; e.g., bee A "did not visit" plant B during time C. 

For a broader and more cautious class negation a relation in the form of "[is] not known to visit" would emphasize that the relation was applied by the user within the scope of knowledge available to the recorder at the time of recording.

Both of these negation forms are weaker than an express negation in the form of "does not visit", which would seem to imply a broader knowledge of past and predicted future behavior that could justify the more definitive statement.

"Did not visit" suggests direct instance observation; "[is] not known to visit" and "does not visit" suggest interpretation based on multiple observations of undisclosed source.

**Comment by jhpoelen** [comment]
explicit did-not-interaction interactions can be described by stating the claim in the positive (e.g., bee visited flower in 2021), and that refute that claim (e.g., I refute that a bee visited this kind of flower in 2021). See also #552
