### ISSUE TITLE
Error in get_interactions_by_type()

### ISSUE THREAD

**Issue by Irallia** [globalbioticinteractions/globalbioticinteractions#332]
I faced the following problem:

When I run my script for a while, I get an error which I don't understand:

Error in file(file, "rt") : cannot open connection
Calls: main ... get_interactions_by_taxa -> read_csv -> <Anonymous> -> read.table -> file
In addition: Warning message:
In file(file, "rt") :
  URL 'https://api.globalbioticinteractions.org:443/interaction?&interactionType=parasiteOf&interactionType=pathogenOf&field=source_taxon_external_id&field=source_taxon_name&field=source_taxon_path&field=source_specimen_life_stage&field=interaction_type&field=target_taxon_external_id&field=target_taxon_name&field=target_taxon_path&field=target_specimen_life_stage&field=latitude&field=longitude&field=study_citation&field=study_external_id&field=study_source_citation&limit=50000&skip=1450000&taxonIdPrefix=OTT&bbox=&includeObservations=f&type=csv': status was '500 Internal Server Error'
Execution halted

Here is my CodeSnippet:

limit <- 50000
// while(i < 30) {
while(nrow(raw_data) >= limit) {
    i <- i + 1
    skip <- i * limit
    otherkeys = list("limit"=limit, "skip"=skip, "taxonIdPrefix"="OTT")
    raw_data <- get_interactions_by_type(interactiontype = interactions, otherkeys = otherkeys)
    ...
}

Sometimes the while loop ends like it has to, but sometimes I got this error. If I run my 'while loop' in the script only 30 times, it works with no problems, but then I get not all of my data. 
I thought about running it 30 times and than run it again starting with i = 30.
At my laptop it breaks off sooner than at the server. Maybe there is a time limit?

**Comment by jhpoelen** [comment]
@Irallia thanks for the detail . . . I poked around a bit and it looks we're hitting a resource constraint issue - pages of 50k interactions with offsets in the order of millions is putting quite some strain on the system. Am thinking about ways to make this work. Meanwhile ... @derele any update on the server hosting ?

**Comment by Irallia** [comment]
I have to adapt my problem description.
For free-livings I get even with the first request this error. At the parasites later. I have adapted my code a bit to request only partial information. That has shown this problem.
I can't see the difference. I tried to run it with less interactions in one query, but this changed nothing.
And I do not understand why I got some free-livings before. Here is my output:

[1] "2018-01-27 17:51:40 CET"
[1] "--------  Freeliving : --------"
[1] "Freeliving source:"
Error in file(file, "rt") : cannot open connection
Calls: main ... get_interactions_by_taxa -> read_csv -> <Anonymous> -> read.table -> file
In addition: Warning message:
In file(file, "rt") :
  URL 'https://api.globalbioticinteractions.org:443/interaction?&interactionType=preysOn&interactionType=eats&interactionType=flowersVisitedBy&interactionType=hasPathogen&interactionType=pollinatedBy&interactionType=hasParasite&interactionType=hostOf&field=source_taxon_external_id&field=source_taxon_name&field=source_taxon_path&field=source_specimen_life_stage&field=interaction_type&field=target_taxon_external_id&field=target_taxon_name&field=target_taxon_path&field=target_specimen_life_stage&field=latitude&field=longitude&field=study_citation&field=study_external_id&field=study_source_citation&limit=40000&skip=0&taxonIdPrefix=OTT&bbox=&includeObservations=f&type=csv': status was '500 Internal Server Error'
Execution halted

https://github.com/Irallia/IZW-HU-Parasites/blob/master/metadata/get_interactions.R

I hope I do not bother you and it is in truth a problem in my code.

**Comment by derele** [comment]
Hi @jhpoelen 
sorry for the long silence. We will find a quick solution now with a commercial hosting service. See your Email for details.

**Comment by jhpoelen** [comment]
@Irallia thanks for sharing - I think your code is looking just fine - the requests you are making are quite computationally intensive because of the large number of records requested. I've been working on an alternate approach that might suit your situation a little better. Thanks for being patient!

**Comment by jhpoelen** [comment]
@Irallia I've prepared an archive at https://depot.globalbioticinteractions.org/datasets/org/globalbioticinteractions/interactions/0.1/interactions-0.1-ott.zip . This archive contains *all* GloBI interaction records expressed in Open Tree of Life Taxa (OTT) whenever possible. Could you please have a look at the archive and let me know whether (1) you can access the data and (2) whether the archive contains the information you need to do your analysis. Please note that interactions are expressed in the "direction" expressed in the original datasets. This means that trophic interactions might be expressed as ```man eats dog``` or ```dogs eatenBy man```. You can find all interaction types here: https://github.com/jhpoelen/eol-globi-data/blob/master/eol-globi-lib/src/main/java/org/eol/globi/domain/InteractType.java . 

With this approach, you should be able to do fast data processing without having to wait for a server to do some crunching. Also, you can easily archive/republish the datasets you are working with. 

Curious to hear your thoughts on this approach.

**Comment by Irallia** [comment]
Yes I can access the data and it is perfect for me. Thank you! I got all my data now. :)

**Comment by jhpoelen** [comment]
@Irallia happy to hear that the file archives work out for you. Am curious to hear about the outcomes of your research!

It still leaves this issue related to paging through relatively large datasets through the web api, so we should probably keep this issue open.

**Comment by jhpoelen** [comment]
I was able to download data using original query . Downloads are now more efficient after introducing streaming in https://github.com/globalbioticinteractions/globalbioticinteractions/releases/tag/v0.12.3 . Please see attached result of executing:

```shell
$ curl "https://api.globalbioticinteractions.org/interaction?&interactionType=preysOn&interactionType=eats&interactionType=flowersVisitedBy&interactionType=hasPathogen&interactionType=pollinatedBy&interactionType=hasParasite&interactionType=hostOf&field=source_taxon_external_id&field=source_taxon_name&field=source_taxon_path&field=source_specimen_life_stage&field=interaction_type&field=target_taxon_external_id&field=target_taxon_name&field=target_taxon_path&field=target_specimen_life_stage&field=latitude&field=longitude&field=study_citation&field=study_external_id&field=study_source_citation&limit=40000&skip=0&taxonIdPrefix=OTT&bbox=&includeObservations=f&type=csv" | pv -l > interaction-issue332.csv 
```
[interaction-issue332.zip](https://github.com/globalbioticinteractions/globalbioticinteractions/files/3638171/interaction-issue332.zip)

Please re-open if the issue remains.
