### ISSUE TITLE
include scan-bugs http://scan-bugs.org/portal/collections/datasets/datapublisher.php

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions#357]
as suggested by @neilcobb - 

[...] harvest association data from our archives  http://scan-bugs.org/portal/collections/datasets/datapublisher.php

 
If so it would be nice to add SCAN to the list on your contribute site.  We have associatedTaxa as a field and in the SCAN data entry we list it as Host per a request by data providers.  We have “habitat” and a nonDwC term “substrate” and both fields could refer to an associated taxa.  We also have a check box for “reared” but I just realized I do not know how that is displayed, [...]

**Comment by jhpoelen** [comment]
@neilcobb - Is there a specific dataset / collection that has good examples in it?

**Comment by jhpoelen** [comment]
Some sample associatedTaxa values from referenced datasets

collection | occurrenceId  | associatedTaxa 
 --- | --- | --- 
Colorado Plateau Museum of Arthropod Biodiversity | [00d3a3a9-2cc6-489d-9c9b-a8b8ea223c84](http://scan-bugs.org/portal/collections/individual/index.php?occid=31925833) | Visiting Baptisia tinctoria. Much pollen of Cleistesiopsis bifaria on dorsal thorax, a few tetrads in abdominal hairs. Dorsal hairs matted down with stigmatic fluid.  
Colorado Plateau Museum of Arthropod Biodiversity | [60024217-6ca4-4130-ac18-d0d5b6431c89](http://scan-bugs.org/portal/collections/individual/index.php?occid=802554) | Dalea carthagenesis var barbata 
The Kenneth S. Norris Center for Natural History at University of California Santa Cruz | [506892eb-4ff7-471b-a6f6-894d3797cded](http://scan-bugs.org/portal/collections/individual/index.php?occid=30612276) | Arctostaphylos hookeri subsp. hookeri
University of Wyoming Dillon Lab Insect Collection |  | N/A

**Comment by neilcobb** [comment]
That is good, the first one is from West Virginia Wesleyan College and the second one is actually a reared specimen (Yeah!)

I assume the Dillon lab has not yet filled out host data

**Comment by jhpoelen** [comment]
(via github) would it be hard to add a label to the associatedTaxa values to indicate the kind of association (e.g., pollination, visitsFlowerOf, visits, or less precise hasHost: ) ala examples mentioned in http://rs.tdwg.org/dwc/terms/index.htm#associatedTaxa ?

**Comment by jhpoelen** [comment]
In the case of removing pollen from an insect, I'd model the individual pollen as occurrence records that were related to the occurrence record describing the insect. The association between the occurrences can then be specified in a resource relationship record. 

Perhaps a review of a recent example/discussion related to Rust Fungi of Belgium might be useful:
https://www.globalbioticinteractions.org/2018/08/16/models-in-fashion/#darwin-core-archive--uredinales-of-belgium-flavor

**Comment by neilcobb** [comment]
Sounds good

**Comment by jhpoelen** [comment]
See also https://github.com/trias-project/uredinales-belgium-checklist/issues/8 with associated proposals https://github.com/tdwg/dwc/issues/186 and https://github.com/tdwg/dwc/issues/187 .

**Comment by jhpoelen** [comment]
@neilcobb @seltmann @zaspelj SCAN is now being indexed by GloBI . Over 100k association records across about 18k taxa. Anecdotal evidence suggests that there's much room for improving data extraction from existing records. My hope is that with (minor) tweaks in familiar transcription workflows, we can increase quality and granularity of newly acquired association data.

For a glimpse of indexed SCAN data, see www.globalbioticinteractions.org/?accordingTo=globi%3Aglobalbioticinteractions%2Fscan (entire collection), www.globalbioticinteractions.org/?accordingTo=globi%3Aglobalbioticinteractions%2Fscan (individual record) and attached screenshots.

I am curious to see how this first integration with scan/symbiota will evolve into linkage of records that benefit researchers.

![Screenshot from 2019-09-25 09-00-53](https://user-images.githubusercontent.com/1084872/65618384-0c2cb380-df73-11e9-81c6-9e504b9899b7.png)

![Screenshot from 2019-09-25 09-08-02](https://user-images.githubusercontent.com/1084872/65618932-0e434200-df74-11e9-8b31-1747bbd9aa88.png)

**Comment by jhpoelen** [comment]
btw - please note that the GloBI's taxon graph is still updating, so some of the newly introduced records might not show up in an explicit taxon query.

**Comment by neilcobb** [comment]
Thanks and I am taking all of this in but may not be able to really get engaged until next week at the Summit meeting.  Jorrit are you going to be available for skype or phone?

**Comment by zaspelj** [comment]
Same for me but this is a great update!!!

*Jennifer M. Zaspel, PhD*

Associate Curator and Head of Zoology

Director of Puelicher Butterfly Wing

Milwaukee Public Museum

800 West Wells Street, Milwaukee, WI
<https://maps.google.com/?q=800+West+Wells+Street,+Milwaukee,+WI&entry=gmail&source=g>

414-278-6158| zaspelj@mpm.edu <youremail@mpm.edu> | www.mpm.edu

**Comment by jhpoelen** [comment]
@neilcobb please coordinate with @seltmann about workshop format. I'd be happy to reserve some time for q&a.

**Comment by seltmann** [comment]
I actually like for the pollinator thing:

interactionTypeName=visits ; interactionTypeId=http://purl.obolibrary.org/obo/RO_0002618; targetTaxonName=Lupinus succulentus ; targetTaxonId=https://www.gbif.org/species/2964314 ; targetBodyPartName=flower ; targetBodyPartID=http://purl.obolibrary.org/obo/PO_0009046

**Comment by seltmann** [comment]
Started a document with pollinator interactions embedded in barcodes.
https://docs.google.com/document/d/1ueExpKylf9j1TVNihQG1rs37b8Jcv4DvsQcGHmnZzxo/edit?usp=sharing

**Comment by seltmann** [comment]
Updated link with commenting enabled:
https://docs.google.com/document/d/1ueExpKylf9j1TVNihQG1rs37b8Jcv4DvsQcGHmnZzxo/edit?usp=sharing
