### ISSUE TITLE
NSF's "plant biotic interactions" program

### ISSUE THREAD

**Issue by jhammock** [globalbioticinteractions/globalbioticinteractions#360]
"The Plant Biotic Interactions (PBI) program supports research on the processes that mediate beneficial and antagonistic interactions between plants and their viral, bacterial, oomycete, fungal, plant, and invertebrate symbionts, pathogens and pests. This joint NSF/NIFA program supports projects focused on current and emerging model and non-model systems, and agriculturally relevant plants. The program’s scope extends from fundamental mechanisms to translational efforts, with the latter seeking to put into agricultural practice insights gained from basic research on the mechanisms that govern plant biotic interactions. "

more detail at https://www.nsf.gov/pubs/2018/nsf18590/nsf18590.htm?WT.mc_id=USNSF_179

recent awards: https://www.nsf.gov/bio/pubs/awards/IOS_awards_list.htm

**Comment by jhpoelen** [comment]
@jhammock nice! I wish NSF kept a machine readable registry of all the datasets produced via these program. Any way we can convince them to do so?

**Comment by jhammock** [comment]
I wish that too, but nothing springs to mind. I think the problem is that
few datasets are created (or made public) before the grant period ends, at
which point NSF has little leverage to motivate any further reporting of
things like where the data went.

**Comment by jhpoelen** [comment]
many years later, I am wondering how many of the awarded projects have left behind species interaction datasets . . . 


Fiscal Year 2018 PBI Awards
--
Program Announcement | Award # | Principal Investigator | Lead Institution | Title | Expected Total Awards ($) | Award Abstract
PBI 17-551 | 1758459 | Alfano, J | University of Nebraska-Lincoln | The microtubule network and cell wall-based extracellular immunity | $600.000 | Award Abstract
PBI 17-551 | 1758857 | Atamian, H | Chapman University | RUI: Diurnal and circadian regulation of the plant microbiome | $292,217 | Award Abstract
PBI 17-551 | 2018-05102 | Axtell, M | Penn State University | MicroRNAs as trans-species virulence factors during dodder parasitism | $797,504 | Award Abstract
PBI 17-551 | 1759030 | Brueggeman, R | North Dakota State University | A resistance and susceptibility gene cluster in barley is targeted by diverse Pyrenophora teres f. teres effectors | * $600,000 | Award Abstract
2018-05353 | Award Abstract
PBI 17-551 | 1758820 | Chen, S | Univ. of Florida | Deciphering the guard cell metabolome in plant pathogen defense | $91,288 | Award Abstract
PBI 17-551 | 1758767 | Chen, ZH | Purdue University | A pathogen-activated transcription program directed by TFIIB-related pBrp1 in plant immunity | $745,874 | Award Abstract
PBI 17-551 | 1758046 | Citovsky, V | SUNY at Stony Brook | Pathways for Colonization of Plant Genome by Agrobacterium | $480,000 | Award Abstract
PBI 17-551 | 2018-05374 | Cook, D | Kansas State University | Deciphering the control network and genome dynamics during fungal plant pathogenesis | $687,000 | Award Abstract
PBI 17-551 | 1758400 | Dangl, J | Univ. of N. Carolina, Chapel Hill | Structure-Function Analyses of Plant NLR receptors | $1,200,000 | Award Abstract
PBI 17-551 | 2018-05014 | Di, R | Rutgers University | CRISPR-editing of sweet basil susceptibility genes to improve downy mildew resistance | $300,000 | Award Abstract
PBI 17-551 | 1750280 | Dlugosch, K | Univ. of Arizona | CAREER: Rapid evolution of an invasive plant: the role of microbial interactions | ** $1,069,152 | Award Abstract
PBI 17-551 | 1758994 | Fu, Z | Univ. of S. Carolina | Targeting of salicylic acid-activated NPR1 by a bacterial type III effector | $487,567 | Award Abstract
FELS ROLS EAGER 18-1 | 1837824 | Greenberg, J | Univ. of Chicago | RoL:FELS:EAGER:Emergent Functions of Secreted Microbial Effectors | *** $300,000 | Award Abstract
PBI 17-551 | 1758843 | Heese, A | University of Missouri-Columbia | Roles of Epsin1-dependent clathrin-coat in plant immunity against bacteria | $622,911 | Award Abstract
PBI 17-551 | 2018-05040 | Jacobs, J | Ohio State Univ. | Basis of Xanthomonas Tissue-Specific Behavior During Plant Pathogenesis | $700,000 | Award Abstract
PBI 17-551 | 2018-05372 | Judelson, H | Univ. of Calif., Riverside | Molecular mechanisms and plant signals regulating effector expression in Phytophthora pathosystems | $747,000 | Award Abstract
PBI 17-551 | 2018-04789 | Kistler, H | USDA-Agricultural Research Service, Midwest Area | The toxisome and its importance for terpene synthesis and fungal virulence | $370,000 | Award Abstract
FELS ROLS EAGER 18-11 | 1837583 | Klavins, E | University of Washington | RoL:FELS:EAGER: Exploring the adaptive possibilities of 'redundancy' in a plant defense hormone signaling pathway | $300,000 | Award Abstract
FELS ROLS EAGER 18-1 | 1838299 | Koskella, B | Univ. of Calif., Berkeley | RoL: FELS: EAGER: Disease resistance as a product of synergy between host immunity and the microbiome | $299,530 | Award Abstract
PBI 17-551 | 2018-05041 | Liu, S | Kansas State University | Analyses of Bacterial Avirulence and Virulence Loci and Host Resistance of Maize Goss's Wilt | $700,000 | Award Abstract
PBI 17-551 | 1758889 | Ma, W | Univ. of Calif., Riverside | Targeting a conserved structural module in Phytophthora effectors for disease resistance | * $859,592 | Award Abstract
2018-05042 | NIFA Award Abstract
LTREB 17-513 | 1754468 | Miller, T | William Marsh Rice University | LTREB: Collaborative Research: Host-microbe symbiosis through the lens of stochastic demography | ** $320,195 | Award Abstract
1754433 | Rodgers, J | University of New Mexico | ** $178,630 | Award Abstract
PBI 17-551 | 1758932 | Rollins, J | University of Florida | Testing a two phase model of broad-host range necrotrophic compatibility | $667,537 | Award Abstract
MCB PBI 17-589 | 1817652 | Scharf, B | Virginia Polytechnic Institute and State University | Specificity of chemotaxis-driven motility in Sinorhizobium meliloti host interaction | *** $991,202 | Award Abstract
PBI 17-551 | 1758976 | Schmelz, E | Univ. of Calif., San Diego | Modular biochemical networks of maize anti-pathogen defense defined by integrating synthetic biochemistry, genetics and physiological function | $856,000 | Award Abstract
PBI 17-551 | 2018-05152 | Shan, L | Texas A&M AgriLife Research | Cotton resistance and susceptibility to bacterial blight | $700,000 | Award Abstract
PBI 17-551 | 1758947 | Silva, L | Univ. of Oregon, Eugene | Harnessing biological complexity to improve food security: How do mycorrhizal networks control resource transfer and plant productivity in inter- and mono-crop model systems | $294,705 | Award Abstract
PBI 17-551 | 1759048 | Simms, E | Univ. of Calif., Berkeley | Did rhizobia associated with invading legumes escape bacteriophage enemies? | $54,586 | Award Abstract
PBI 17-551 | 2018-04812 | Tyler, B | Oregon State University | Genomic mechanisms of pathogenic adaptation in Phytophthora sojae | $700,000 | Award Abstract
PBI 17-551 | 2018-05351 | Ullman, D | Univ. of Calif., Davis | Integrative Approaches to Understanding How Insect Vectors and Plant Viruses Interact and Manipulate Their Plant Hosts | $1,060,000 | Award Abstract
PBI 17-551 | 2018-05399 | Vaillancourt, L | University of Kentucky Research Foundation | A Novel Function for the Highly Conserved Signal Peptidase in the Regulation of Biotrophy in a Plant Pathogenic Fungus | $1,250,000 | Award Abstract
PBI 17-551 | 1759034 | Verchot, JM | Texas A&M AgriLife Research | Investigating how the cellular ER stress machinery regulates plant virus infection | $573,792 | Award Abstract
PBI 17-551 | 1759023 | Walley, J | Univ. of Iowa | Elucidation of roles that protein acetylation plays in mediating plant-pathogen interactions | $750,000 | Award Abstract
PBI 17-551 | 1750717 | Werner, S | University of Tennessee Knoxville | CAREER: Defining colonization mechanisms and functions of Streptomyces strains in root microbiomes | $699,380 | Award Abstract
PBI 17-551 | 1758037 | Zhu, H | University of Kentucky Research Foundation | Elucidating genetic and molecular mechanisms underlying symbiotic specificity in the Medicago-Sinorhizobium mutualism | $750,734 | Award Abstract


</body>

</html>
Fiscal Year 2018 PBI Awards						
Program Announcement	Award #	Principal Investigator	Lead Institution	Title	Expected Total Awards ($)	Award Abstract
PBI 17-551	1758459	Alfano, J	University of Nebraska-Lincoln	The microtubule network and cell wall-based extracellular immunity	$600.000	[Award Abstract](https://www.nsf.gov/awardsearch/showAward?AWD_ID=1758459)
PBI 17-551	1758857	Atamian, H	Chapman University	RUI: Diurnal and circadian regulation of the plant microbiome	$292,217	[Award Abstract](https://www.nsf.gov/awardsearch/showAward?AWD_ID=1758857)
PBI 17-551	2018-05102	Axtell, M	Penn State University	MicroRNAs as trans-species virulence factors during dodder parasitism	$797,504	[Award Abstract](https://cris.nifa.usda.gov/cgi-bin/starfinder/0?path=fastlink1.txt&id=anon&pass=&search=R=79991&format=WEBLINK)
PBI 17-551	1759030	Brueggeman, R	North Dakota State University	A resistance and susceptibility gene cluster in barley is targeted by diverse Pyrenophora teres f. teres effectors	* $600,000	[Award Abstract](https://www.nsf.gov/awardsearch/showAward?AWD_ID=1759030)
	2018-05353					[Award Abstract](https://cris.nifa.usda.gov/cgi-bin/starfinder/0?path=fastlink1.txt&id=anon&pass=&search=R=80453&format=WEBLINK)
PBI 17-551	1758820	Chen, S	Univ. of Florida	Deciphering the guard cell metabolome in plant pathogen defense	$91,288	[Award Abstract](https://www.nsf.gov/awardsearch/showAward?AWD_ID=1758820)
PBI 17-551	1758767	Chen, ZH	Purdue University	A pathogen-activated transcription program directed by TFIIB-related pBrp1 in plant immunity	$745,874	[Award Abstract](https://www.nsf.gov/awardsearch/showAward?AWD_ID=1758767)
PBI 17-551	1758046	Citovsky, V	SUNY at Stony Brook	Pathways for Colonization of Plant Genome by Agrobacterium	$480,000	[Award Abstract](https://www.nsf.gov/awardsearch/showAward?AWD_ID=1758046)
PBI 17-551	2018-05374	Cook, D	Kansas State University	Deciphering the control network and genome dynamics during fungal plant pathogenesis	$687,000	[Award Abstract](https://cris.nifa.usda.gov/cgi-bin/starfinder/0?path=fastlink1.txt&id=anon&pass=&search=R=80498&format=WEBLINK)
PBI 17-551	1758400	Dangl, J	Univ. of N. Carolina, Chapel Hill	Structure-Function Analyses of Plant NLR receptors	$1,200,000	[Award Abstract](https://www.nsf.gov/awardsearch/showAward?AWD_ID=1758400)
PBI 17-551	2018-05014	Di, R	Rutgers University	CRISPR-editing of sweet basil susceptibility genes to improve downy mildew resistance	$300,000	[Award Abstract](https://cris.nifa.usda.gov/cgi-bin/starfinder/0?path=fastlink1.txt&id=anon&pass=&search=R=80339&format=WEBLINK)
PBI 17-551	1750280	Dlugosch, K	Univ. of Arizona	CAREER: Rapid evolution of an invasive plant: the role of microbial interactions	** $1,069,152	[Award Abstract](https://www.nsf.gov/awardsearch/showAward?AWD_ID=1750280)
PBI 17-551	1758994	Fu, Z	Univ. of S. Carolina	Targeting of salicylic acid-activated NPR1 by a bacterial type III effector	$487,567	[Award Abstract](https://www.nsf.gov/awardsearch/showAward?AWD_ID=1758994)
FELS ROLS EAGER 18-1	1837824	Greenberg, J	Univ. of Chicago	RoL:FELS:EAGER:Emergent Functions of Secreted Microbial Effectors	*** $300,000	[Award Abstract](https://www.nsf.gov/awardsearch/showAward?AWD_ID=1837824)
PBI 17-551	1758843	Heese, A	University of Missouri-Columbia	Roles of Epsin1-dependent clathrin-coat in plant immunity against bacteria	$622,911	[Award Abstract](https://www.nsf.gov/awardsearch/showAward?AWD_ID=1758843)
PBI 17-551	2018-05040	Jacobs, J	Ohio State Univ.	Basis of Xanthomonas Tissue-Specific Behavior During Plant Pathogenesis	$700,000	[Award Abstract](https://cris.nifa.usda.gov/cgi-bin/starfinder/0?path=fastlink1.txt&id=anon&pass=&search=R=80491&format=WEBLINK)
PBI 17-551	2018-05372	Judelson, H	Univ. of Calif., Riverside	Molecular mechanisms and plant signals regulating effector expression in Phytophthora pathosystems	$747,000	[Award Abstract](https://cris.nifa.usda.gov/cgi-bin/starfinder/0?path=fastlink1.txt&id=anon&pass=&search=R=80459&format=WEBLINK)
PBI 17-551	2018-04789	Kistler, H	USDA-Agricultural Research Service, Midwest Area	The toxisome and its importance for terpene synthesis and fungal virulence	$370,000	[Award Abstract](https://cris.nifa.usda.gov/cgi-bin/starfinder/0?path=fastlink1.txt&id=anon&pass=&search=R=79963&format=WEBLINK)
FELS ROLS EAGER 18-11	1837583	Klavins, E	University of Washington	RoL:FELS:EAGER: Exploring the adaptive possibilities of 'redundancy' in a plant defense hormone signaling pathway	$300,000	[Award Abstract](https://www.nsf.gov/awardsearch/showAward?AWD_ID=1837583)
FELS ROLS EAGER 18-1	1838299	Koskella, B	Univ. of Calif., Berkeley	RoL: FELS: EAGER: Disease resistance as a product of synergy between host immunity and the microbiome	$299,530	[Award Abstract](https://www.nsf.gov/awardsearch/showAward?AWD_ID=1838299)
PBI 17-551	2018-05041	Liu, S	Kansas State University	Analyses of Bacterial Avirulence and Virulence Loci and Host Resistance of Maize Goss's Wilt	$700,000	[Award Abstract](https://www.nsf.gov/bio/pubs/awards/IOS_awards_list.htm)
PBI 17-551	1758889	Ma, W	Univ. of Calif., Riverside	Targeting a conserved structural module in Phytophthora effectors for disease resistance	* $859,592	[Award Abstract](https://www.nsf.gov/awardsearch/showAward?AWD_ID=1758889)
	2018-05042					[NIFA Award Abstract](https://cris.nifa.usda.gov/cgi-bin/starfinder/0?path=fastlink1.txt&id=anon&pass=&search=R=80469&format=WEBLINK)
LTREB 17-513	1754468	Miller, T	William Marsh Rice University	LTREB: Collaborative Research: Host-microbe symbiosis through the lens of stochastic demography	** $320,195	[Award Abstract](https://www.nsf.gov/bio/pubs/awards/IOS_awards_list.htm)
	1754433	Rodgers, J	University of New Mexico		** $178,630	[Award Abstract](https://www.nsf.gov/awardsearch/showAward?AWD_ID=1754433)
PBI 17-551	1758932	Rollins, J	University of Florida	Testing a two phase model of broad-host range necrotrophic compatibility	$667,537	[Award Abstract](https://www.nsf.gov/awardsearch/showAward?AWD_ID=1758932)
MCB PBI 17-589	1817652	Scharf, B	Virginia Polytechnic Institute and State University	Specificity of chemotaxis-driven motility in Sinorhizobium meliloti host interaction	*** $991,202	[Award Abstract](https://www.nsf.gov/awardsearch/showAward?AWD_ID=1817652)
PBI 17-551	1758976	Schmelz, E	Univ. of Calif., San Diego	Modular biochemical networks of maize anti-pathogen defense defined by integrating synthetic biochemistry, genetics and physiological function	$856,000	[Award Abstract](https://www.nsf.gov/awardsearch/showAward?AWD_ID=1758976)
PBI 17-551	2018-05152	Shan, L	Texas A&M AgriLife Research	Cotton resistance and susceptibility to bacterial blight	$700,000	[Award Abstract](https://cris.nifa.usda.gov/cgi-bin/starfinder/0?path=fastlink1.txt&id=anon&pass=&search=R=80023&format=WEBLINK)
PBI 17-551	1758947	Silva, L	Univ. of Oregon, Eugene	Harnessing biological complexity to improve food security: How do mycorrhizal networks control resource transfer and plant productivity in inter- and mono-crop model systems	$294,705	[Award Abstract](https://www.nsf.gov/awardsearch/showAward?AWD_ID=1758947)
PBI 17-551	1759048	Simms, E	Univ. of Calif., Berkeley	Did rhizobia associated with invading legumes escape bacteriophage enemies?	$54,586	[Award Abstract](https://www.nsf.gov/awardsearch/showAward?AWD_ID=1759048)
PBI 17-551	2018-04812	Tyler, B	Oregon State University	Genomic mechanisms of pathogenic adaptation in Phytophthora sojae	$700,000	[Award Abstract](https://cris.nifa.usda.gov/cgi-bin/starfinder/0?path=fastlink1.txt&id=anon&pass=&search=R=80329&format=WEBLINK)
PBI 17-551	2018-05351	Ullman, D	Univ. of Calif., Davis	Integrative Approaches to Understanding How Insect Vectors and Plant Viruses Interact and Manipulate Their Plant Hosts	$1,060,000	[Award Abstract](https://cris.nifa.usda.gov/cgi-bin/starfinder/0?path=fastlink1.txt&id=anon&pass=&search=R=80458&format=WEBLINK)
PBI 17-551	2018-05399	Vaillancourt, L	University of Kentucky Research Foundation	A Novel Function for the Highly Conserved Signal Peptidase in the Regulation of Biotrophy in a Plant Pathogenic Fungus	$1,250,000	[Award Abstract](https://cris.nifa.usda.gov/cgi-bin/starfinder/0?path=fastlink1.txt&id=anon&pass=&search=R=80465&format=WEBLINK)
PBI 17-551	1759034	Verchot, JM	Texas A&M AgriLife Research	Investigating how the cellular ER stress machinery regulates plant virus infection	$573,792	[Award Abstract](https://www.nsf.gov/awardsearch/showAward?AWD_ID=1759034)
PBI 17-551	1759023	Walley, J	Univ. of Iowa	Elucidation of roles that protein acetylation plays in mediating plant-pathogen interactions	$750,000	[Award Abstract](https://www.nsf.gov/awardsearch/showAward?AWD_ID=1759023)
PBI 17-551	1750717	Werner, S	University of Tennessee Knoxville	CAREER: Defining colonization mechanisms and functions of Streptomyces strains in root microbiomes	$699,380	[Award Abstract](https://www.nsf.gov/awardsearch/showAward?AWD_ID=1750717)
PBI 17-551	1758037	Zhu, H	University of Kentucky Research Foundation	Elucidating genetic and molecular mechanisms underlying symbiotic specificity in the Medicago-Sinorhizobium mutualism	$750,734	[Award Abstract](https://www.nsf.gov/awardsearch/showAward?AWD_ID=1758037)
