### ISSUE TITLE
North American arthropod partners of Ash trees, threatened by Emerald Ash Borer

### ISSUE THREAD

**Issue by jhammock** [globalbioticinteractions/globalbioticinteractions#364]
https://doi.org/10.1007/s10530-009-9594-1

Supplementary material, table in Word file

**Comment by jhpoelen** [comment]
Hey Jen - I am sorry to hear about that Emerald Ash Borer causing havoc with your Arthropod partners of Ash trees. I've started a repo here: https://github.com/globalbioticinteractions/gandhi2009 . Would you happen to have a file that maps the short references to the long ones + dois ?

**Comment by jhammock** [comment]
Alas, no, I have only a passing acquaintance with this dataset. It doesn't look like there's a mapping, but there is an html references list on the article page...

**Comment by jhpoelen** [comment]
Cool - if you extract the references in a tsv, I'd be happy to the rest of the mapping, or do you have something else in mind?

**Comment by jhpoelen** [comment]
Cool! . . . hmm didn't see the pull request. Let me know how I can help

**Comment by jhpoelen** [comment]
@jhammock I transformed your references into a tsv file. Also, I was wondering about the interpretation of things like:

host species | ... | references
--- | --- | ---
host species1, host species2 | ... | reference 1, reference 2, reference 3

Do you think this is the same as:

host species | ... | references
--- | --- | ---
host species1 | ... | reference 1
host species1 | ... | reference 2
host species1 | ... | reference 3
host species2 | ... | reference 1
host species2 | ... | reference 2
host species2 | ... | reference 3

?

**Comment by jhpoelen** [comment]
Do you think this expansion is an ok inference to make?

**Comment by jhammock** [comment]
Mapping all refs to all species per row may not be perfect, but I think it is the safest course. It *might* be perfect, but I have also seen references listed that way when the grouping of values per row was based on something else. At worst, spurious ref associations may be created, but none should be lost.

**Comment by jhpoelen** [comment]
Please have a look at https://github.com/globalbioticinteractions/gandhi2009 . I've left the original interactions.tsv and references format around. The interactions.tsv is the main file. Is this was you expected?

**Comment by jhammock** [comment]
Looks good (and reasonably explained) to me! There are a couple of "taxa" that could use a re-map. There's a place for that, isn't there? And I may want to remap one of them to "discard this record" if that's an option...

**Comment by jhpoelen** [comment]
A discard configuration sounds good. Can you take a shot at representing this in a text-based format that suits you in the gandhi2009 repository? I was hoping that someone would suggest to add a similar feature.

**Comment by jhpoelen** [comment]
Cool! Perhaps we can also introduce a taxonomic context (or range) while we are at it, so avoid things like #361 . What do you think?

**Comment by jhpoelen** [comment]
Something like: 

The context of this dataset is: plants eating mammals. 

with this GloBI can protest each time there's fish or insect taxa getting involved by the taxonomic resolution.

**Comment by jhpoelen** [comment]
While I am still contemplating the name mapping, could you please review the Ash interactions that got indexed at http://globalbioticinteractions.org/?accordingTo=globi:globalbioticinteractions/template-dataset ?

**Comment by jhammock** [comment]
Context by dataset sounds like easy, useful validation. 

Sorry, I'm missing something about globalbioticinteractions/template-dataset. I tried filtering it for Fraxinus, but there's nothing there.

**Comment by jhpoelen** [comment]
Oops, wrong link, please use: https://www.globalbioticinteractions.org/?accordingTo=globi:globalbioticinteractions/gandhi2009 . To download GloBI's idea of the dataset, try "open results in interaction browser", then download details.

**Comment by jhammock** [comment]
ah, there it is. Apart from the odd names, it looks nice!

**Comment by jhammock** [comment]
oh- per the paper, the animals are associated with the plants "for feeding or breeding". I think the use of "hosts" is justified; they also use that word in the data supplement.

**Comment by jhpoelen** [comment]
@jhammock thanks for having a look - which odd names?

**Comment by jhammock** [comment]
they look a lot like the ones in the mapping file. "Other species", etc

**Comment by jhpoelen** [comment]
https://www.globalbioticinteractions.org/?accordingTo=globi:globalbioticinteractions/gandhi2009 shows indexed records related to:
Gandhi, K.J.K. & Herms, D.A. North American arthropods at risk due to widespread Fraxinus mortality caused by the Alien Emerald ash borer . Biol Invasions (2010) 12: 1839. https://doi.org/10.1007/s10530-009-9594-1
