### ISSUE TITLE
integrate with http://vectormap.si.edu

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions#366]
@jhammock would you happen to know if the VectorMap folks are willing to openly share their association data?

**Comment by jhammock** [comment]
hmm... I'm not familiar with the Walter Reed Biosystematics Unit, but they sound like another government group based at SI (we have similar in house collaborators from NOAA, USDA, etc.) 

[Terms of use](http://vectormap.si.edu/dataportal.htm) are singularly discouraging

**Comment by jhpoelen** [comment]
Ok, thanks for looking into it. I created a new label "non-open data" to help classify these kinds of resources.
