### ISSUE TITLE
explore integration with TaxonWorks

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions#373]
See e.g., 
https://github.com/SpeciesFileGroup/taxonworks/issues/471

**Comment by mjy** [comment]
@jhpoelen  I can certainly appreciate your [plurality based approach](https://www.globalbioticinteractions.org/2018/08/16/models-in-fashion/) to data formats (manditory reference to https://xkcd.com/927/).  Also reread your paper (briefly).  You nevertheless hint that some formats for ingestion are preferred over others (https://github.com/jhpoelen/eol-globi-data/issues/81).  Whether or not you want to influence things towards a standard _you_ do have perhaps one of the better feelings for what the data "standard" looks like that maximizes interoperability with Globi, and I'd argue, by prox, downstream "real science". Given this I'd ask the following, what is the data format that:

* minimizes time required to integration in Globi
* minimizes losiness during integration (for every one of those formats somethign is lost in translation)
* gets used most by users of Globi that point to raw data(?) <- unfamiliar with whether this is a thing
* gets the most downstream exposure by other wrappers (e.g. EOL)
* ... etc.

All this to point out that we're at the point where we could envision discussing things like:
* Dumping to the format you most prefer.  Our data model largely overlaps yours, with some differences in resolution (both more, and less in parts)
* Figuring out a micro format/service by which users could ingest GLOBI data per their clade of interest for editing/integration/long term curation.  I'm not thinking of "edit the whole dataset", we're not really setup for that, I am thinking "as I work towards a monograph of taxon X, then I want to gather everything known about them".  I'm thinking along the lines of the story that we've enabled for importing references: "user browses <somewhere> (globi), user finds <sha>, user adds that to input field in TW, ... <whirring>, ... PROFFIT!".

Perhaps we could guide this forward, slowly, with the use case along these lines: https://github.com/SpeciesFileGroup/taxonworks/issues/673

Ping to @reptalus.

**Comment by jhpoelen** [comment]
@mjy I like your idea to establish a bi-directional link between GloBI and TaxonWorks, in which TaxonWorks uses to GloBI to lookup prior art as well as a way to make it easier biological associations data documented in monographs by openly sharing the data with GloBI.

As far as data formats / models go, I've been working towards writing up a more organized version of [Models in Fashion](https://www.globalbioticinteractions.org/2018/08/16/models-in-fashion/) to help better understand and dissect which formats/ models are suited in specific situations in [On Species Interaction Data Models and Format](https://github.com/jhpoelen/globis-b-interactions/blob/master/text/on-species-interaction-data-models-and-formats.md). In that document, I did venture out to share [best practices](https://github.com/jhpoelen/globis-b-interactions/blob/master/text/on-species-interaction-data-models-and-formats.md#best-practices) . 

Given your team's software engineering skills/ intuition and willingness to experiment and assuming that you are now aware of existing approaches via ([Models in Fashion]((https://www.globalbioticinteractions.org/2018/08/16/models-in-fashion/)  and [On Species Interaction Data Models and Formats](https://github.com/jhpoelen/globis-b-interactions/blob/master/text/on-species-interaction-data-models-and-formats.md) , I would suggest a periodically updated, stream-able, discoverable, data dump of all taxonworks datasets that contain biotic associations in as much granularity as you can provide in your native encoding scheme (e.g., taxon ids, lifestage id, common names, interaction types, dois, explicit links back into taxonworks). 

What is the easiest way for you to provide such data publications/archives with your current setup and enable this *today* without too many modifications?

**Comment by jhpoelen** [comment]
A list of all "open" projects in Species File TaxonWork instance can be reached via - 

```bash
curl "https://sfg.taxonworks.org/api/v1" | jq .
```

```json
{
  "success": true,
  "open_projects": [
    {
      "UndtpSwdHsSRw8K3ddsTNQ": "Terrestrial Parasite Tracker (TPT)"
    },
    {
      "VVpT9aMPkqtnzmRVUx5jtg": "Opiliones of the World"
    },
    {
      "adhBi59dc13U7RxbgNE5HQ": "Universal Chalcidoidea Database (UCD)"
    },
    {
      "c5lh0vgnBGTOQDOSfRYC8g": "Global Lepidoptera Index"
    },
    {
      "BS2jGvMz1w4CDxZyQ1h1Qg": "UNH Insects"
    },
    {
      "JHfGs7VYEihc5QkqvKnvxw": "Ceraphronoids"
    },
    {
      "FV3se0XDYEdAQH_2pojdGA": "Tenebrionidae"
    },
    {
      "Rugp5rLnuhLu8qA3yzKTVw": "Cucujoidea World Catalog"
    },
    {
      "2GkoX1NjlZylDmr6dDpQ6g": "Frost Museum"
    },
    {
      "ekMTicbZWijqmdpHKqs_TA": "Purdue Entomological Research Collection"
    },
    {
      "iu4ty6tOdWg_-cceoQjhyQ": "Odonata"
    },
    {
      "X4DtgGPunYwPr9NEjH-SoQ": "Small Beetle Groups"
    },
    {
      "ZEJhFp9sq8kBfks15qAbAg": "3i World Auchenorrhyncha Database"
    },
    {
      "e-udR-5oT2THWfw9dLMJbw": "Dung_Beetles"
    },
    {
      "Ots0-yen4dVefn0Etyxvgw": "Curculionidae"
    },
    {
      "6IWD_06Pw-N2BRLtA20W8w": "Aphelinidae Workshop"
    },
    {
      "xQ9bKrhfQtHYfro9t6YY0A": "INHS Insect Collection"
    }
  ]
}
```

**Comment by jhpoelen** [comment]
And some biological associations with project token for UCD - 

```bash
curl --silent "https://sfg.taxonworks.org/api/v1/biological_associations?project_token=adhBi59dc13U7RxbgNE5HQ"\
 | jq '.[0]'  
```

```json
{
  "id": 28368,
  "biological_relationship_id": 8,
  "biological_association_subject_id": 97846,
  "biological_association_subject_type": "Otu",
  "biological_association_object_id": 100720,
  "biological_association_object_type": "Otu",
  "created_by_id": 78,
  "updated_by_id": 78,
  "project_id": 16,
  "created_at": "2019-10-01T08:11:58.379Z",
  "updated_at": "2019-10-01T08:11:58.379Z",
  "object_tag": "<span class=\"otu_tag\"><span class=\"otu_tag_taxon_name\" title=\"461256\"><i>Ablerus bajacalifornicus</i> Myartseva, 2012</span> &#10003;</span> <span class=\"notice\">compared with / reference for</span> <span class=\"otu_tag\"><span class=\"otu_tag_taxon_name\" title=\"461247\"><i>Ablerus aligarhensis</i> (Khan & Shafee, 1976)</span> &#10003;</span>",
  "object_label": null,
  "global_id": "gid://taxon-works/BiologicalAssociation/28368",
  "base_class": "BiologicalAssociation",
  "url_for": "https://sfg.taxonworks.org/api/v1/biological_associations",
  "object_url": "/biological_associations/28368"
}
```

**Comment by jhpoelen** [comment]
related to https://github.com/globalbioticinteractions/natural-history-museum-london-interactions-bank/issues/6 and https://github.com/ropensci/rglobi/issues/50#issuecomment-1503164356 .

**Comment by jhpoelen** [comment]
with individual endpoint 

```bash
curl --silent "https://sfg.taxonworks.org/api/v1/biological_associationsq .368?project_token=adhBi59dc13U7RxbgNE5HQ" \
 | jq .
``` 

```json
{
  "id": 28368,
  "biological_relationship_id": 8,
  "biological_association_subject_id": 97846,
  "biological_association_subject_type": "Otu",
  "biological_association_object_id": 100720,
  "biological_association_object_type": "Otu",
  "created_by_id": 78,
  "updated_by_id": 78,
  "project_id": 16,
  "created_at": "2019-10-01T08:11:58.379Z",
  "updated_at": "2019-10-01T08:11:58.379Z",
  "object_tag": "<span class=\"otu_tag\"><span class=\"otu_tag_taxon_name\" title=\"461256\"><i>Ablerus bajacalifornicus</i> Myartseva, 2012</span> &#10003;</span> <span class=\"notice\">compared with / reference for</span> <span class=\"otu_tag\"><span class=\"otu_tag_taxon_name\" title=\"461247\"><i>Ablerus aligarhensis</i> (Khan & Shafee, 1976)</span> &#10003;</span>",
  "object_label": null,
  "global_id": "gid://taxon-works/BiologicalAssociation/28368",
  "base_class": "BiologicalAssociation",
  "url_for": "https://sfg.taxonworks.org/api/v1/biological_associations/28368",
  "object_url": "/biological_associations/28368"
}
```

**Comment by jhpoelen** [comment]
ways to page through all the interaction claims for a project - 

```bash
curl --silent "https://sfg.taxonworks.org/api/v1/biological_associations?page=0&per=5&project_token=adhBi59dc13U7RxbgNE5HQ" 
```

where `page` is page number and `per` is number of interactions per page.

**Comment by jhpoelen** [comment]
likely better starting point - because biological_associations endpoint doesn't point to sources / citations. 

```
curl --silent "https://sfg.taxonworks.org/api/v1/\
citations\
?page=0\
&per=5\
&project_token=adhBi59dc13U7RxbgNE5HQ" 
```

**Comment by jhpoelen** [comment]
@mjy @debpaul any suggestions on how to lookup source_id 49000 ? 

I tried 

```bash
curl --silent "https://sfg.taxonworks.org/api/v1/\
sources\
?page=0\
&per=1\
&project_token=adhBi59dc13U7RxbgNE5HQ"
```

but I got:

```
{"success":false}
```

**Comment by mjy** [comment]
@jhpoelen i think there may be a bug with the sources resource.  It shouldn't require any authentication tokens at all.  Will confirm/followup today.  `.../sources/123` should also work to get a single source (semi-RESTful).

**Comment by jhpoelen** [comment]
@mjy thanks for your prompt reply and looking forward to better understand how to trace the TaxonWorks `source` records.

**Comment by jhpoelen** [comment]
Just tried to access `source` resources in taxonworks through the API using:

```
curl --silent "https://sfg.taxonworks.org/api/v1/\
sources\
?page=0\
&per=1\
&project_token=adhBi59dc13U7RxbgNE5HQ"
```

and

```
curl --silent "https://sfg.taxonworks.org/api/v1/\
sources/49000\
&project_token=adhBi59dc13U7RxbgNE5HQ"
```

both returned result `{"success":false}`

@debpaul @mjy How can I get to the `source` records referenced in the biological associations records?

**Comment by mjy** [comment]
@jhpoelen Great. 2 extra bits:

* You don't need a token now: `curl --silent "https://sfg.taxonworks.org/api/v1/sources/49000`
* You can get Bibtex back with `https://sfg.taxonworks.org/api/v1//sources/49000?extend[]=bibtex`

**Comment by jhpoelen** [comment]
@mjy After 5 years, I feel that indexing biotic associations from taxon works is like drinking the ocean through a straw. Perhaps I am missing something. Are there any archives being published in which I can download data in bulk, rather than having to rely on APIs to seemingly endlessly scroll through pages of json formatted results?

**Comment by jhpoelen** [comment]
@mjy apologies for coming across as a bit frustrated . . . I am just hoping to finally get into taxonworks, and so far the API design seems counter intuitive to me, and I am barely scratching the surface.

**Comment by jhpoelen** [comment]
are there any non-taxonworks projects that I can use as integration examples?

**Comment by jhpoelen** [comment]
another update - 

in order to resolve the information needed to make a species interaction claim, the following workflow is currently implemented:

1. retrieve all open project_tokens via https://sfg.taxonworks.org/api/v1
2. for each project_token, retrieve all citations related to biological_association, paging through results when needed
3. for each citation, retrieve associated source, and related biological associations, propagating the project_token for data access
4. for each biological_association, retrieve information associated with the subject/object OTUs 
5. for each OTU, retrieve the associated taxon name
6. for each taxon name, resolve its parent. Do this until the parent_id is null

a preliminary implementation to track results of scraping taxonworks via their API can be found at:

https://github.com/bio-guoda/preston/blob/ee4b036728b6b4c05cdd765849460ea1c88feb09/preston-track/src/main/java/bio/guoda/preston/process/RegistryReaderTaxonWorks.java#L43

If there's an easier way to do this, please do let me know. 

Ideally, I'd be able to stream all species interactions with fully resolved taxonomic names, citations, and versioned digital provenance, with references to public landing pages for folks to click on if they'd like to learn more about the basis (or origin) of a specific species interaction claim.

**Comment by jhpoelen** [comment]
So, for a single interactions, I'd expect, tens of API calls to resolve data elements needed to index an interaction (or biological association claim). With expected hundreds of thousands of interaction claims, I'd estimate in the order of millions of API calls just to get the current state of the system, with periodic repeats to incorporate updates that may or may not have happened. 

Lets say 10 million API calls are needed to index the biotic associations where 1 API call taking 100ms (pretty generous), 10M/10 requests per second = 1M requests / s or about 12 days to process 10M requests. This could be parallelized, but I imagine that would put quite some load on the taxonworks servers. 

I imagine that an API driven approach works nicely with humans clicking on buttons in web interfaces, and I hope that this will also work when indexing all the data. We'll soon find out!

**Comment by jhpoelen** [comment]
@mjy thanks for chiming in! I'll experiment a little more with your rich data models so that I know what to ask for.

**Comment by jhpoelen** [comment]
@mjy I've added a note in https://github.com/SpeciesFileGroup/taxonworks/issues/1483 to express my desires on how to access the wealth of biological associations data kept in TaxonWorks.

**Comment by jhpoelen** [comment]
For now, I'll try to work with what is available: the TaxonWorks API in its current state.

**Comment by jhpoelen** [comment]
After spending some more hours on getting an integration with taxonworks going, I am now able to do something like this:

```
preston track https://sfg.taxonworks.org/api/v1\
 | preston tw-stream\
 | head -n1\
 | jq .
```

to generate a stream of biological associations stored in open projects of taxon works. 

yielding:

```
{
  "http://www.w3.org/ns/prov#wasDerivedFrom": "hash://sha256/3ff24e32814a418dc56233b2c852ab3723a0d98e25ab0b63a08b2f0422f285d3",
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#type": "application/vnd.taxonworks+json",
  "interactionTypeId": "gid://taxon-works/BiologicalRelationship/14"
}
```
@mjy how can I lookup your biological relationship definitions?

**Comment by jhpoelen** [comment]
After implementing a streaming approach to indexing taxonworks biological associations (oef that was fun!), I was able to run:

```
preston track https://sfg.taxonworks.org/api/v1\
 | preston tw-stream\
 | head -n1\
 | jq .
```

to generate:

```
{
  "http://www.w3.org/ns/prov#wasDerivedFrom": "hash://sha256/2a9f086a5dbd4a66633311f247102fe660723840197df434ff989934b9e8b448",
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#type": "application/vnd.taxonworks+json",
  "referenceId": "https://sfg.taxonworks.org/api/v1/sources/49013",
  "interactionId": "https://sfg.taxonworks.org/api/v1/biological_associations/84748",
  "taxonRootsResolved": 2,
  "referenceResolved": true,
  "referenceCitation": "@article{49013,\n  author = {Abate, T.},\n  booktitle = {Journal of Applied Entomology},\n  journal = {Journal of Applied Entomology},\n  month = {mar},\n  day = {31},\n  pages = {278-285},\n  title = {The bean fly <i>Ophiomyia phaseoli</i> Tryon (Diptera: Agromyzidae) and its parasitoids in Ethiopia.},\n  volume = {111(3)},\n  year = {1991},\n  stated_year = {1991},\n  year_suffix = {a},\n  issn = {0044-2240}\n}\n",
  "interactionTypeId": "gid://taxon-works/BiologicalRelationship/14",
  "sourceTaxonName": "Eupelmus",
  "sourceTaxonId": "gid://taxon-works/TaxonName/456381",
  "sourceTaxonRank": "genus",
  "sourceTaxonPath": "Root | Animalia | Arthropoda | Insecta | Hymenoptera | Chalcidoidea | Eupelmidae | Eupelminae | Eupelmus",
  "sourceTaxonPathIds": "gid://taxon-works/TaxonName/455455 | gid://taxon-works/TaxonName/703648 | gid://taxon-works/TaxonName/703653 | gid://taxon-works/TaxonName/703658 | gid://taxon-works/TaxonName/455456 | gid://taxon-works/TaxonName/455458 | gid://taxon-works/TaxonName/455504 | gid://taxon-works/TaxonName/455506 | gid://taxon-works/TaxonName/456381",
  "sourceTaxonPathNames": "nomenclatural rank | kingdom | phylum | class | order | superfamily | family | subfamily | genus",
  "targetTaxonName": "Agromyzidae",
  "targetTaxonId": "gid://taxon-works/TaxonName/513569",
  "targetTaxonRank": "family",
  "targetTaxonPath": "Root | Animalia | Arthropoda | Insecta | Diptera | Agromyzidae",
  "targetTaxonPathIds": "gid://taxon-works/TaxonName/455455 | gid://taxon-works/TaxonName/703648 | gid://taxon-works/TaxonName/703653 | gid://taxon-works/TaxonName/703658 | gid://taxon-works/TaxonName/513567 | gid://taxon-works/TaxonName/513569",
  "targetTaxonPathNames": "nomenclatural rank | kingdom | phylum | class | order | family"
}
```

This  json object contains some of the basics related to interaction claims: an interaction type, two interacting named things, and a reference. Note that the taxonomic hierarchy is getting traversed to their root taxon (the taxon without parent taxon). 

@mjy still curious whether you have any thoughts on how to resolve the biological relationship type metadata (e.g., relationship type label). . . also, would you happen to have pretty landing pages to point to in case folks want to learn more about the claim in their native taxonworks environment (preferably without have to login).

**Comment by jhpoelen** [comment]
Just found a way to `extend` the biological associations with biological relation metadata via - 

```https://sfg.taxonworks.org/api/v1/biological_associations/56684?project_token=adhBi59dc13U7RxbgNE5HQ&extend[]=biological_relationship```

```json
{
  "id": 56684,
  "biological_relationship_id": 12,
  "biological_association_subject_id": 101719,
  "biological_association_subject_type": "Otu",
  "biological_association_object_id": 135972,
  "biological_association_object_type": "Otu",
  "created_by_id": 78,
  "updated_by_id": 78,
  "project_id": 16,
  "created_at": "2019-10-01T12:43:24.494Z",
  "updated_at": "2019-10-01T12:43:24.494Z",
  "object_tag": "<span class=\"otu_tag\"><span class=\"otu_tag_taxon_name\" title=\"465783\"><i>Callitula bicolor</i> Spinola, 1811</span> &#10003;</span> <span class=\"notice\">Parasitoid host</span> <span class=\"otu_tag\"><span class=\"otu_tag_taxon_name\" title=\"535319\"><i>Platygaster zosine</i> (Walker)</span> &#10003;</span>",
  "object_label": null,
  "global_id": "gid://taxon-works/BiologicalAssociation/56684",
  "base_class": "BiologicalAssociation",
  "url_for": "https://sfg.taxonworks.org/api/v1/biological_associations/56684",
  "object_url": "/biological_associations/56684",
  "biological_relationship": {
    "id": 12,
    "name": "Parasitoid host",
    "definition": null,
    "inverted_name": null,
    "is_transitive": null,
    "is_reflexive": null,
    "created_by_id": 78,
    "updated_by_id": 78,
    "project_id": 16,
    "created_at": "2019-10-01T12:18:23.135Z",
    "updated_at": "2019-10-01T12:18:23.135Z",
    "object_tag": "Parasitoid host",
    "object_label": "Parasitoid host",
    "global_id": "gid://taxon-works/BiologicalRelationship/12",
    "base_class": "BiologicalRelationship",
    "url_for": "https://sfg.taxonworks.org/api/v1/biological_associations/56684",
    "object_url": "/biological_relationships/12"
  }
}
```

**Comment by jhpoelen** [comment]
A first snapshot of biological associations in TaxonWorks has been published at:

Poelen, Jorrit H. (2023). A biodiversity dataset graph: Biological Associations in TaxonWorks hash://sha256/ab7550368905e7c919e70a306efbb97719a1edbba2cfe4c4515f635ebc0be4bb hash://md5/8771b9560146cb7af895a1a6de23bd87 (0.1) [Data set]. Zenodo. https://doi.org/10.5281/zenodo.8252844

**Comment by mjy** [comment]
And a side note, please do let us know if/when we can see these data in GLOBI context?!

**Comment by jhpoelen** [comment]
Just posted a minor update on the taxonworks corpus, with an slightly different transformation, but same ~4M source data:

Poelen, Jorrit H. (2023). A biodiversity dataset graph: Biological Associations in TaxonWorks hash://sha256/a4d651aac5220487835e6178511886e98b845b2d98cb7c5447fb2b042e0654d2 hash://md5/849edbe55e31e54ea5cdaba0188c5655 (0.2) [Data set]. Zenodo. https://doi.org/10.5281/zenodo.8253729

> And a side note, please do let us know if/when we can see these data in GLOBI context?!
Will do!

**Comment by jhpoelen** [comment]
@mjy a first data review of biological associations at:

https://depot.globalbioticinteractions.org/reviews/globalbioticinteractions/taxonworks/ (temporary html landing page)

https://depot.globalbioticinteractions.org/reviews/globalbioticinteractions/taxonworks/review.zip 

Note that these reviews are not being archived, so I've included some docx review index
 versions in this issue:

[index.docx](https://github.com/globalbioticinteractions/globalbioticinteractions/files/12420080/index.docx)

One thing that struck me was the taxonomic coverage from the tpt taxonomic perspective:

catalog | alignment type | count
-- | -- | --
tpt | NONE | 36147
tpt | HAS_ACCEPTED_NAME | 60
tpt | SYNONYM_OF | 7

which tells me that 60 names out of thousands were aligned with the Terrestrial Parasite Tracker Taxonomy [1]. 

I am trying to figure out how to square this with the expected numbers retrieved from the TPT collections using TaxonWorks as their management system (noting that UNHC appears in the TaxonWorks open list of projects):

| institution_code | institution | collection_code | collection | contact | email | platform | platform_detail | globi_id | review_id |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| INHS | Illinois Natural History Survey, University of Illinois at Urbana-Champaign |  | INHS Insect Collection | Dmitry A Dmitriev, Matt Yoder | arboridia@gmail.com | TaxonWorks |  | globi:globalbioticinteractions/inhs-insects | globalbioticinteractions/inhs-insects |
| PSUC | Pennsylvania State University | ENTO | Frost Entomological Museum | Andy Deans, Joyce Sakamoto, Laura Porturas | ard19@psu.edu | TaxonWorks |  | globi:globalbioticinteractions/psuc-ento | globalbioticinteractions/psuc-ento |
| UNHC | University of New Hampshire |  | UNH Collection of Insects and other Arachnids | Istvan Miko | istvan.miko@gmail.com | Filemaker Pro | Filemaker Pro | globi:globalbioticinteractions/unhc | globalbioticinteractions/unhc |

Before I start digging into this, I was hoping you might have some context to help me understand how these collections help manage their TPT associated collections in TaxonWorks, and how their are capturing their biological associations.

Curious to hear your thoughts,
-jorrit

# References 

[1] Dr. Nicolas J. Dowdy, Dr. Erika M. Tucker, Jorrit Poelen, Dr. Vijay Barve, Teresa Mayfield-Meyer, Kathryn Sullivan, & Dr. Jennifer M. Zaspel. (2022). njdowdy/tpt-taxonomy: TPT Taxonomic Resource v2.0.0 (v2.0.0) [Data set]. Zenodo. https://doi.org/10.5281/zenodo.7215550 https://github.com/njdowdy/tpt-taxonomy/tree/d820e7e036483b48906deb5f3a62fc089f10d9e8
</body>
</html>

**Comment by jhpoelen** [comment]
After about 5 years of integration attempts, GloBI was able to index a first version of TaxonWorks derived biotic associations. For some visual evidence of GloBI's newly added TaxonWorks associated association claims see below.

To summarize the current approach:

1. Using a specialized [Preston](https://github.com/bio-guoda/preston) feature made available in [Preston v0.7.4](https://github.com/bio-guoda/preston/releases/tag/0.7.4), TaxonWorks biotic association claims were tracked, packaged, and transformed into format that allows for _stream_ processing the records 
2. These versioned, packaged and transformed TaxonWorks data resources were then made (openly) available via Zenodo [1] .
3. A [TaxonWorks GloBI index configuration](https://github.com/globalbioticinteractions/taxonworks) was created to aid discovery of these data via GloBI tools like [elton](https://github.com/globalbioticinteractions/elton) and [nomer](https://github.com/globalbioticinteractions/nomer).

with approach 1-3, manual work is needed to extract, version, package and publish TaxonWorks biotic associations such that they are able to be indexed by GloBI. This work involves making millions of Web API calls to the TaxonWorks Web API, dedicated hardware, and specialized data tracking/publication tools/knowledge. And, this is only a first pass at tapping into the vast amount of knowledge that the TaxonWorks platform keeps.

# References 

[1] Poelen, Jorrit H. (2023). A biodiversity dataset graph: Biological Associations in TaxonWorks hash://sha256/a4d651aac5220487835e6178511886e98b845b2d98cb7c5447fb2b042e0654d2 hash://md5/849edbe55e31e54ea5cdaba0188c5655 (0.2) [Data set]. Zenodo. https://doi.org/10.5281/zenodo.8253729


https://www.globalbioticinteractions.org/?accordingTo=globi%3Aglobalbioticinteractions%2Ftaxonworks&interactionType=ecologicallyRelatedTo

https://www.globalbioticinteractions.org/browse/?accordingTo=globi%3Aglobalbioticinteractions%2Ftaxonworks&interactionType=ecologicallyRelatedTo&resultType=json

![image](https://github.com/globalbioticinteractions/globalbioticinteractions/assets/1084872/93c0c106-0e88-43e8-8236-8bcf81555aa5)

![Screenshot from 2023-08-25 08-15-25](https://github.com/globalbioticinteractions/globalbioticinteractions/assets/1084872/c81448c6-c972-4040-8fe7-41cbb1044c38)

**Comment by jhpoelen** [comment]
Note that another "crawl" of TaxonWorks biological associations done over period 2024-05-07T09:06:26.146Z/2024-05-07T23:40:41.811Z, taking about 14h34m over a 500Mb US-based fiber internet connection to complete the 4.75M api calls* needed to retrieve the biotic associations and their associated records (e.g., citations, names, otu's), downloading 4.14GiB of api response data**. After versioning and packaging the data, the same data was accessible in 7m22s, amounting to a couple of magnitude increase in access speeds (7 mins vs 14 hours). Also, because the responses are now packaged, verifiable, clonable, and citable, this corpus of taxonworks biotic associations can be used as a stable dataset of known origin.

The citable and verifiable data archive of these tracked biotic associations is available via:

Poelen, J. H. (2024). A biodiversity dataset graph: Biological Associations in TaxonWorks hash://sha256/e4a47c067d6c125da60c9a1b92b5eecdea539cb8666cd3aed99db347ae5b8ed0 hash://md5/686007de79cc2a49ab23fd3debe56e3f [Data set]. Zenodo. https://doi.org/10.5281/zenodo.11151783

In conclusion, the evidence above suggests that accessing *all* Biotic Associations records in TaxonWorks using a verifiable, citable and reusable data archive takes over 14 hours, requires specialized software (e.g. Preston) and an intermediate data publication [1]. 


## Footnotes

* number of taxonworks api calls calculated using 

```bash
preston cat hash://sha256/c1b081afa6ea0f60570c24cca85c4d9acd91eeefe36b9cacd1fe53b6893ea154 | grep hasVersion | pv -l  >/dev/null
4.75M 0:00:07 [ 662k/s]
```
 
** volume of TaxonWorks API responses calculated using 

```
preston cat hash://sha256/c1b081afa6ea0f60570c24cca85c4d9acd91eeefe36b9cacd1fe53b6893ea154 | grep hasVersion | preston cat | pv > /dev/null
4.14GiB 0:07:22 [9.58MiB/s]
```

## References

Poelen, J. H. (2024). A biodiversity dataset graph: Biological Associations in TaxonWorks hash://sha256/e4a47c067d6c125da60c9a1b92b5eecdea539cb8666cd3aed99db347ae5b8ed0 hash://md5/686007de79cc2a49ab23fd3debe56e3f [Data set]. Zenodo. https://doi.org/10.5281/zenodo.11151783

fyi @mjy

**Comment by jhpoelen** [comment]
Please see attached pdf for an automatically generated review report of the TaxonWorks interactions. 

[index.pdf](https://github.com/globalbioticinteractions/globalbioticinteractions/files/15253859/index.pdf)


Note that this report was generated in less than 15 minutes as part of an automated GitHub actions driven workflow. This includes alignment of *all* names against taxonomies like itis, gbif, catalogue of life, ncbi, and more. 



https://github.com/globalbioticinteractions/taxonworks/actions/runs/9006936511



![Screenshot from 2024-05-08 14-22-29](https://github.com/globalbioticinteractions/globalbioticinteractions/assets/1084872/5f5aa618-1bb8-4ae5-ae87-a0953dbfc755)
