### ISSUE TITLE
provide table with OBO RO biotic interaction terms

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions#386]
Using the http://obofoundry.org/ontology/ro.html to discover biotic interaction terms in OBO Relations ontology can be a bit intimidating by non-ontologists (including myself!). 

Suggest to make a tabular list of biotic interaction terms currently supported.

**Comment by cmungall** [comment]
We could add this to the release process for RO, easy to do with a sparql query

**Comment by jhpoelen** [comment]
@cmungall that'd be excellent - let me know how I can help make this happen.

**Comment by jhpoelen** [comment]
A table of OBO RO terms can be found at:
https://github.com/globalbioticinteractions/nomer/blob/main/nomer/src/test/resources/org/globalbioticinteractions/nomer/match/ro.tsv
