### ISSUE TITLE
Include data for higher taxonomic ranks and other taxonomic sources

### ISSUE THREAD

**Issue by DAntoszyk** [globalbioticinteractions/globalbioticinteractions#391]
This issue is related to closed issue #380.  

The aggregated interaction data sets include columns for source and target rank names: 
sourceTaxonSpeciesName, sourceTaxonGenusName, sourceTaxonFamilyName, sourceTaxonOrderName, sourceTaxonClassName, sourceTaxonPhylumName, sourceTaxonKingdomName
and
targetTaxonSpeciesName, targetTaxonGenusName, targetTaxonFamilyName, targetTaxonOrderName, targetTaxonClassName, targetTaxonPhylumName, targetTaxonKingdomName

Observations that occur at a lower taxonomic rank don’t reliably include information about their higher ranks even when this information is available. For example, Lepidochelys kempii, a species level observation, includes taxon path names and IDs for it’s family, genus, and species, but not for it’s Kingdom, Phylum, Class, or Order. 

Is it possible to force the inclusion of ranks higher than the observation level. e.g. species level observations would have coverage for kingdom, phylum, class, order, family, genus, and species. While and observation at the order level would have coverage from kingdom, phylum, class, and order.

If the information is not already part of globi could it be added using EOL’s, or the other available taxonomic databases, api?

If possible it would also be helpful to include a standard set of ranks from the other available taxonomies shown in sourceTaxonIds: Worms, WD, OTT, etc. The attached file shows what that could look like.

[globi_github_issue.zip](https://github.com/jhpoelen/eol-globi-data/files/3036821/globi_github_issue.zip)

We’d like to be able to group lower level interactions at higher taxonomic ranks in order to generate probabilities based on the grouped data. Grouping the whole data by higher ranks will allow us to use a large number of observation to support general statements at each rank level. As an example, with data grouped by kingdom we can calculate the probability that an organism eats a plant given it’s own kingdom.

P(Eats_Plantae | Plantae)  or P(Eats_Plantae | Animalia) or P(Eats_Plantae | Fungi) 

Creating these conditional probabilities at many levels count be a good way of generating evidence to support or reject specific claims.

Thanks.

**Comment by jhpoelen** [comment]
@DAntoszyk thanks for your detailed request. Higher order taxonomic information for many species, including _Lepidochelys kempii_ is available via many taxonomies other than EOL. 

For instance, ```curl -L https://depot.globalbioticinteractions.org/snapshot/target/data/taxa/taxonCache.tsv.gz | gunzip | grep "Lepidochelys kempii" > Lepidochelys_kempii.tsv.txt```, results in attached file.

[Lepidochelys_kempii.tsv.txt](https://github.com/jhpoelen/eol-globi-data/files/3040115/Lepidochelys_kempii.tsv.txt)

I am planning to spend some time today to come up with a representation that helps to access to more complete higher order taxonomic ranks. More soon...

**Comment by jhpoelen** [comment]
Hi @DAntoszyk - as promised, I took a look at ways to get access to full hierarchies available via taxonCache.tsv.gz that are linked in the sourceTaxonIds / targetTaxonIds fields of the interactions.tsv.gz .  

Some notes:
1. the single full hierarchy listed in interactions.tsv.gz may or may not include kingdom, depending on the taxonomy that was first used to link the name. However, many do have kingdom name fields populated. 
2. I wrote used the apache spark shell to join the taxonCache.tsv.gz woith the sourceTaxonIds and targetTaxonIds fields in interaction.tsv.gz extracting only the kingdom rank if available. With this, I was able to create a kingdom2kingdom interaction table by sourceNamespace. The sourceNamespace is a proxy associated with the dataset from which the data was extracted.
3. Some taxonomies, like NCBI have a different naming scheme for "kingdom" than others (e.g., ITIS, WORMS, GBIF, INAT_TAXON). To avoid inconsistencies, it might be wise to use ITIS, WORMS, GBIF, and INAT_TAXON taxonomies when attempting to join interactions.tsv.gz and taxonCache.tsv.gz .

I've attached the preliminary results related to my experiments with  2. in attached kingdom2kingdom.tsv.txt . The first 4 lines look like:

sourceKingdom | interactionTypeName | targetKingdomName | sourceNamespace
-- | -- | -- | --
Chromista | hasHost | Animalia | millerse/Wardeh-et-al.-2015
Animalia | eats | Bacteria | hurlbertlab/dietdatabase
Animalia | eats | Chromista | jhpoelen/Dapstrom-integrated-database-and-portal-for-fish-stomach-records
 
Is this the kind of information you are looking for? If not, please propose a mock data structure with some representative data that would suit your needs.

Also, please note that if you are running out of time or don't have the skills to take on joining big datasets, you might want to consider using the kingdom fields available directly via interactions.tsv.gz and focus on developing the downstream analysis and visualizations instead. 

Curious to hear your thoughts!

[kingdom2kingdom.tsv.txt](https://github.com/jhpoelen/eol-globi-data/files/3041223/kingdom2kingdom.tsv.txt)

**Comment by jhpoelen** [comment]
In case you are interested: here's a gist that contains the code used to generate the kingdom2kingdom file, using apache spark 2.4, ubuntu linux and bash : https://gist.github.com/jhpoelen/9cac3897fc930b17fa6dcd0cacfc5ec2

**Comment by jhpoelen** [comment]
Closing stale issue. @DAntoszyk Please comments or share insights if this remains a concern.
