### ISSUE TITLE
Scientific Committee On Antarctic Research, S. (2018, updated 2018) SCAR Southern Ocean Diet and Energetics Database Australian Antarctic Data Centre - doi:10.26179/5ba3396f46e42

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions#398]
@raymondben Ben Raymond's Southern Ocean Diet Database (see #38 and https://github.com/globalbioticinteractions/raymond) seems to have seeded another database: Scientific Committee On Antarctic Research, S. (2018, updated 2018) SCAR Southern Ocean Diet and Energetics Database Australian Antarctic Data Centre - doi:10.26179/5ba3396f46e42 .

The newly seeded database available at https://data.aad.gov.au/eds/4722/download has similar, but different, file naming conventions and schema.

**Comment by jhpoelen** [comment]
According to GloBI records,  the previous trophic.zip became unavailable around end of May 2019:

dataset | url | sha256 | date seen 
--- | --- | --- | ---
globalbioticinteractions/raymond | https://data.aad.gov.au/aadc/trophic/trophic.zip	2c50ad9c64ae8e5620c4ffc16b56a3675cc4078a8f89ed0c9b90365b6a45362f | 2019-05-30T23:08:48.381Z

**Comment by jhpoelen** [comment]
also see https://github.com/globalbioticinteractions/raymond/issues/2 .

**Comment by raymondben** [comment]
Whoah, this is old. Glad I'm replying right on time ... (sorry about that!!)
Yes, the original version of this database was superseded by a bigger effort coordinated through SCAR, which is still ongoing. It is hosted on Zenodo (the concept DOI is https://zenodo.org/doi/10.5281/zenodo.5072527, each new version gets a new DOI but the concept always resolves to the most recent). Also https://diet.apps.aq/

BTW the AODN data mentioned above are separate, nothing to do with either this database or SCAR.

**Comment by jhpoelen** [comment]
@raymondben thanks for confirming . . . and for your pointers.

**Comment by jhpoelen** [comment]
Took a first pass at creating a GloBI index configuration for: 

Scientific Committee on Antarctic Research. (2023). SCAR Southern Ocean Diet and Energetics Database (2023-04-04) [Data set]. Zenodo. https://doi.org/10.5281/zenodo.7796465

at

https://github.com/globalbioticinteractions/scar 

question for @raymondben - I was looking for columns in scar_diet.csv 


> - SOURCE_DETAILS, SOURCE_DOI: The details and DOI of the source, copied from the sources data table for convenience

But, for some reason, the columns were missing. Was this intended?

**Comment by raymondben** [comment]
> Was this intended?
Erm, nope. Whoops, sorry! Will fix on the next release. But that might be a while. It's just a join from the sources table, so don't let it slow you down in the meantime ;)

**Comment by jhpoelen** [comment]
@raymondben thanks for confirming that the columns SOURCE_DETAILS, SOURCE_DOI . I've reported a separate issue on that at https://github.com/globalbioticinteractions/scar/issues/1 .

Looking forward to your next release!
