### ISSUE TITLE
Calling APIs in C# applications

### ISSUE THREAD

**Issue by Dina-Sharafeldeen** [globalbioticinteractions/globalbioticinteractions#404]
Hallo, 
I am trying to call some APIs like 
https://api.globalbioticinteractions.org/imagesForName/Homo%20sapiens
from C# windows application using HttpWebRequest
I got the following exception
: 'The remote server returned an error: (405) Method Not Allowed.'
Are these methods are not allowed to be called in other applications?
OR what do you recommend to use these APIs?
Thanks in advance,
Dina

**Comment by jhpoelen** [comment]
Hi @Dina-Sharafeldeen  -

Thanks for your message and apologies for the delay.

Could you please share a c# code snippet that is causing the 405 http status code ?

**Comment by jhpoelen** [comment]
Closing stale issue. @Dina-Sharafeldeen please comment if this issue remains a concern.
