### ISSUE TITLE
support indexing DwC-A w/ Resource Relationship extension

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions#406]
Kate W. @magpiedin provided an example of a DwC-A with Resource Relationship extension (see attached zip). The intent is to use this extension to record biotic interactions. The approach is similar to a past discussion https://github.com/trias-project/uredinales-belgium-checklist/issues/8 with @peterdesmet @qgroom @LienReyserhove and @baskaufs . 

Note that resolving https://github.com/tdwg/dwc/issues/186 is expected to help to make the recorded relationship easier to read for machines. Until identifiers for resource relationship types are supported,  the free text field [relationshipOfResource](http://rs.tdwg.org/dwc/terms/#relationshipOfResource) will be used to derive the type of recorded interaction.

[dwca-fmnh-rr-test-v1.1.zip](https://github.com/jhpoelen/eol-globi-data/files/3586074/dwca-fmnh-rr-test-v1.1.zip)

**Comment by jhpoelen** [comment]
fyi @seltmann .

**Comment by qgroom** [comment]
This seems like something that could easily be achieved. @tucotuco doesn't this just need approval of the Darwin Core Maintainance Group?

**Comment by jhpoelen** [comment]
@qgroom @seltmann @magpiedin @peterdesmet Exemplar dataset https://github.com/globalbioticinteractions/uredinales-belgium-checklist now indexed by GloBI , showing that Resource Relation extensions are now supported. See https://www.globalbioticinteractions.org/?accordingTo=globi%3Aglobalbioticinteractions%2Furedinales-belgium-checklist&interactionType=ecologicallyRelatedTo, reference and screenshot.

Vanderweyen A, Fraiture A, Groom Q, Desmet P, Reyserhove L (2019). Catalogue of the Rust Fungi of Belgium. Botanic Garden Meise. Checklist dataset. https://doi.org/10.15468/2dboyn . See also https://ipt.biodiversity.be/resource.do?r=uredinales-belgium-checklist , https://github.com/trias-project/uredinales-belgium-checklist and https://trias-project.github.io/uredinales-belgium-checklist .

![Screenshot from 2019-09-22 20-32-23](https://user-images.githubusercontent.com/1084872/65400628-28183580-dd78-11e9-9334-19f5b22d12ff.png)
