### ISSUE TITLE
include validated meta-foodweb links from Olivier et al. 2019 Exploring the temporal variability of a food web using long-term biomonitoring data

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions#412]
Olivier et al. 2019 used some records from GloBI and subjected them to review. Suggest to re-import to provide more support for "trusted" interactions. 

fyi @pierreocean 

See:

Olivier, Pierre et al. (2019), Data from: Exploring the temporal variability of a food web using long-term biomonitoring data, Dryad, Dataset, https://doi.org/10.5061/dryad.9tg3t75

and 

Olivier, Pierre et al. (2019), Exploring the temporal variability of a food web using long‐term biomonitoring data, Wiley, Article-journal, https://doi.org/10.1111/ecog.04461

**Comment by PierreOcean** [comment]
Hi,
Globi is a great tool. As mentioned in previous conversations, it is sometimes hard to access and discriminate the links between life stages, which matters in most food webs.
Also, as we did in the paper, it is good to ascribe a quality value to a link: what has been observed _in situ_, in the lab, what is inferred...

It is something I want to continue investigating.

**Comment by jhpoelen** [comment]
@PierreOcean thanks for you comment and congrats on your paper! 

I much agree with your comments on the importance of (a) capturing life stages of interacting organisms, (b) documenting the method used to make the interactions claim and (c) have a way to assess the quality of a claim.

As we discussed some time ago (see #378), life stages and basis of record information are being captured when available. However, as you found, the fields are sparsely populated and are not exposed in the various web UIs (see #379). 

I hope your work on quality metrics can help inspire GloBI and other researches to improve of methods to measure how "good" links are. GloBI now has basic measures like taxonomic name linking, ability to refute claims (see #376), cross reference claims across different data sources, and, more recently, integration with records from natural history collections (see https://www.globalbioticinteractions.org/2019/07/10/associating-with-natural-history-collections/ ) .

**Comment by jhpoelen** [comment]
Olivier 2019 is now being indexed by GloBI via https://github.com/globalbioticinteractions/olivier2019 . See https://www.globalbioticinteractions.org/?accordingTo=globi%3Aglobalbioticinteractions%2Folivier2019&interactionType=ecologicallyRelatedTo and attached image.
![Screenshot from 2020-10-05 17-40-45](https://user-images.githubusercontent.com/1084872/95146186-0e068680-0732-11eb-9420-9a321aac7585.png)
