### ISSUE TITLE
suspicious interaction from NHM IB: Nasonia vitripennis parasite of Wolbachia pipientis

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions#416]
fyi @edwbaker 

suspicious interaction from NHM IB: Nasonia vitripennis parasite of Wolbachia pipientis See also attached or https://www.globalbioticinteractions.org/?interactionType=hasParasite&sourceTaxon=Wolbachia%20pipientis . 

```
$ https://data.nhm.ac.uk/dataset/82e807f0-6273-4f19-be0a-7f7558442a25/resource/f84ad9f1-bd0c-4811-8108-8dcd83f224a4/download/NHMInteractionsBank.csv
 | tr  '\r' '\n' | grep "Wolbachia pipientis"
,,Nasoni vitriW,Nasonia vitripennis,,,,is parasite of,http://purl.obolibrary.org/obo/RO_0002444,17597,Wolbachia pipientis,,,,,,,,,,McCook2001 via Universal Chalcidoidea Database,,17,,,,,,,,,,,,,,,,,,,,,,,
,,Nasoni vitriW,Nasonia vitripennis,,,,is parasite of,http://purl.obolibrary.org/obo/RO_0002444,17597,Wolbachia pipientis,,,,,,,,,,BourtzNiOn994 via Universal Chalcidoidea Database,,131-142,,,,,,,,,,,,,,,,,,,,,,,
```
![Screenshot from 2019-10-06 17-27-56](https://user-images.githubusercontent.com/1084872/66278523-b43d5900-e85e-11e9-9abd-b2b87400af47.png)

**Comment by edwbaker** [comment]
Yes, that should not be a parasitism association. I shall take a look.

**Comment by jhpoelen** [comment]
Hey @edwbaker - I've recorded your statement that refutes that Nasonia vitripennis parasite of Wolbachia pipientis in dataset at https://github.com/globalbioticinteractions/refuted-interaction-data/commit/d6de4b8748188158e9e85329ba40a98f079b907d .

Now, when searching for the parasitic interaction, your statement is captured in the "refuted by" section using:

```
Ed Baker. 2019. GitHub. https://github.com/globalbioticinteractions/globalbioticinteractions/issues/416#issuecomment-540011739 show Provider: Jorrit H. Poelen. 2019. Collection of refuted species associations claims.. Accessed at <https://github.com/globalbioticinteractions/refuted-interaction-data/archive/95e8adc7ecc0098ba99531f6a70ee9570d406af0.zip> on 27 Oct 2019.
```

Also, see attached screenshot that shows the refuted statement.

![Screenshot from 2019-10-28 17-25-16](https://user-images.githubusercontent.com/1084872/67727895-6cff3f80-f9a8-11e9-8d8d-3891414dcee3.png)
