### ISSUE TITLE
index University of Michigan Insect Collection (UMMZ / UMMZI ) and related host records

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions#452]
index University of Michigan Insect Collection (UMMZ / UMMZI ) and related host records.

UMMZ is affiliated with the Parasite Tracker project (https://parasitetracker.org). For meeting notes to outline a way to index the UMMZ records, please see [UMMZ 2020-01-23 notes](https://globalbioticinteractions/parasitetracker/ummz-2020-01-23-notes) .

**Comment by jhpoelen** [comment]
Exchange highlighted to importance of exposing life stage information in GloBI search pages https://github.com/globalbioticinteractions/globalbioticinteractions/issues/379 .

**Comment by jhpoelen** [comment]
Note that UMMZ appears to be registered with GBIF, iDigBio and SCAN. See details below:

https://www.gbif.org/dataset/search?publishing_org=6ea87510-0561-11d8-b851-b8a03c50a862 as a publisher with one of the registered datasets being the UMMZ insect collection https://www.gbif.org/dataset/13e7869e-0c76-473a-a227-53d6e3d6fbf2 .

GBIF appears to source the UMMZ data from source ipt is hosted at https://ipt.lsa.umich.edu/ e.g., https://ipt.lsa.umich.edu/archive.do?r=ummz_insects .

On iDigBio, UMMZ insect collections appears to be available via https://www.idigbio.org/portal/recordsets/a47eacbb-22d0-4a8b-8853-989b26fd8290 . Also from iDigBio's https://www.idigbio.org/portal/publishers page, it appears that UMMZ collections are being ingested/indexed by iDigBio via various RSS feeds, including the one hosted at https://ipt.lsa.umich.edu/rss.do . 

Via https://scan-bugs.org, the UMMZ insect collection is available via https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=221 .

**Comment by jhpoelen** [comment]
In existing UMMZ dataset retrieved from https://ipt.lsa.umich.edu/resource?r=ummz_insects  with [hash://sha256/88c8bebc9a1831a240d7de19765c577845ccc8f7242f08eac796b290b1b3e6b9](https://deeplinker.bio/88c8bebc9a1831a240d7de19765c577845ccc8f7242f08eac796b290b1b3e6b9), no associatedOccurrences, associatedTaxa or dynamicProperties fields were found. However, associatedOrganisms and organismRemarks were present. 

```cat occurrence.txt | cut -f13,14 | tail -n+2 | sort | uniq > ummz-associatedOrganisms-organismRemarks-2020-01-23.txt``` produced file 
[ummz-associatedOrganisms-organismRemarks-2020-01-23.txt](https://github.com/globalbioticinteractions/globalbioticinteractions/files/4106310/ummz-associatedOrganisms-organismRemarks-2020-01-23.txt)

in which some hints of species interactions can be found:


associatedOrganisms | organismRemarks
-- | --
#006f-2 | host ssp. nigra. 1 Siphonaptera: Ctenophthalmidae: Catallagia charlottensis (Baker, 1898), det. R.E. Lewis
#029f-10 | host ssp. nigra. 1 Siphonaptera: Ceratophyllidae: Malaraeus telchinus (Rothschild, 1905), det. R.E. Lewis
#031-m-1-3 | host ssp. nigra. 2 Siphonaptera: Histrichopsyllidae: Histrichopsylla schefferi Chapin, 1919 Hoyer's 2005 [might be mounting medium and preparation date]
#037m-11 | host ssp. nigra. 1 Siphonaptera: Histrichopsyllidae: Histrichopsylla schefferi Chapin, 1919
#05m-3 | host ssp. nigra. 1 Siphonaptera: Histrichopsyllidae: Histrichopsylla schefferi Chapin, 1919 Hoyer's 2005 [might be mounting medium and preparation date]
  | Euparal Host ID:Northern short-tailed shrew
  | Euparal, Nov 56 [Could be prepartation material and date]
  | Euparal Nov 56[might be mount medium and preparation date] Host ID:Northern short-tailed shrew
  | Euparal Oct 56[might be mount medium and preparation date] Host ID:Northern short-tailed shrew
  | Euparal Oct56[might be mount medium and preparation date] Host ID:Northern short-tailed shrew
  | Euparol Host ID:Mink
  | Eup. Host ID:Northern short-tailed shrew
  | Eup.[might be mount medium] Host ID:Northern short-tailed shrew
  | Europe R-5784
  | Europe R-594
  | ex Blarina brevicauda Host ID:Deer mouse
  | Ex Cat
  | Ex. Clethrionomys gapperi Host ID:Southern red-backed vole
  | ex Coniger ridiculus/ Spurius dichotomus (Coleoptera: Passalidae)
  | ex Dynastes hercules trinidadensis ventral Host ID:Hercules Beetle
  | Ex. from Dog
  | Ex. from Dog Host ID:Dog
  | ex larvae on Alnus
  | ex larvae on smilax
  | ex larvae -Quercus
  | ex larva on Alder
  | ex larva on Alder 10 Oct
  | ex larva on Alder 6 Sept
  | ex larva on Alnus
  | ex larva, polygam aquatia
  | Ex litter under pigeon cages in poultry barn
  | Ex. Microtus sp.
  | ex. nest, Castor canadensis (Castoridae) Host ID:North American Beaver
  | Ex. nest - Microtus pennsylvanicus
  | Ex. nest - Microtus pennsylvanicus Host ID:Meadow Vole
  | Ex. nest of Microtus Host ID:Deer mouse
  | Ex. nest of Microtus pennsylvanicus Host ID:Meadow vole
  | Ex. nest of Microtus pennsylvanicus Host ID:Meadow Vole
  | Ex. nest of Sciurus carolinensis Host ID:Fox squirrel
  | Ex. nest of Sciurus carolinensis in tree branches Host ID:Fox squirrel
  | ex ova on Aruncus
  | ex ova on Aruncus,
  | ex ova on Aruncus 18 Apr, 2 May 1976
  | ex ova on Aruncus 2 May
  | ex ova on Aruncus date: 18 Apr, 2 May 1976
  | ex ova on Aruncus emerged 1
  | ex ova on Aruncus, emerged 1
  | ex ova on Aruncus loc 3
  | ex ova on Aruncus X emerged 23 May to 12-19 June1976 X
  | ex Peromyscus sp. Host ID:Deer mouse
  | Ex. Peromyscus sp. Host ID:Deer mouse
  | EX. Unidentified bird nest fragments
  | from nest of Aplodontia rufa (Rodentia: Aplodontidae) Acaridae: Trichopsyllopus oregonensis (14) dns under tergites & sternites.
  | from nest of opossum Didelphis virginiana (Marsupialia: Didelphidae) in hollow trunk of Liquidambar styracillua (Hamamelidaceae) Host ID:Virginia Opossum
  | Host: antelope chipmunk
  | HOST: aq. net sweeping in weeds of creek
  | host: creek sweeping w/ aq. net
  | Host: Harvest Mouse
  | Host ID:White-footed mouse
  | Host ID:Woodland Jumping Mouse
  | host ssp. oriantha. 1 Siphonaptera: Ceratophyllidae: Ceratophyllus diffinis Jordan, 1925
  | host ssp. oriantha. 1 Siphonaptera: Ceratophyllidae: Ceratophyllus garei Rothschild, 1902
  | in nest of Peromyscus sp. in bird nest in tree Host ID:Deer mouse
MSU 17684 |  
MSU 17703 | 1 Listrophoridae: Geomylichus (?contaminant)
  | Nest of Microtus pennsylvanicus.   Siphonaptera: Megabothris asio asio (Baker, 1904)
  | Nest of M. pennsylvanicus - old field west of Holiday Inn off Triphammer Rd. Nest occupied, found in low area in field.  ~50% water soaked.  Temp. ~50Â°F., no snow on ground.   Balsam [might be mounting medium]
  | nest of Peromyscus leucopus under bark of tree Host ID:White-footed mouse
  | Nest of Peromyscus leucopus under bark of tree Host ID:White-footed mouse
  | Nest of P. leucopus or maniculatus .
  | Nest of P. leucopus or maniculatus . Balsam [might be mounting medium] [Verbatim BMOC #: 74-0225-3]
  | nest of shrew - nest under piece of roofing insulation near stream.   Siphonaptera: Histrichopsyllidae: Ctenophthalmus pseudogyrtes Baker, 1945; Pseudoscorpionida Balsam[might be mounting medium]
  | nest-Ondatra zibethica Host ID:Muskrat
  | on oak
  | on Passalid beetle
  | on Polygonus aquaticum
  | on smilax aphids
  | on Typha leaf
  | on wh. cedar
  | site=1; original nest id = Cynosure. Erythraeidae: Balaustium larvae; 1 Cunaxidae; oribatids: #1; Siphonaptera: Ceratophyllidae: Ceratophyllus (Emmareus) garei Rothschild, 1902, det. R. E. Lewis; 1 Diptera larva.
  | site=2; original nest id = Denouement. Siphonaptera: Ceratophyllidae: Ceratophyllus (Emmareus) garei Rothschild, 1902, det. R. E. Lewis, 1 adult, numerous larvae.
  | site=2; original nest id = Shat el Arab. Siphonaptera: Ceratophyllidae: Ceratophyllus (Emmareus) garei Rothschild, 1902, det. R. E. Lewis, 1 female, larvae numerous.
  | site=2; original nest id = Standoff. Siphonaptera: Ceratophyllidae: Ceratophyllus (Emmareus) garei Rothschild, 1902, det. R. E. Lewis.
  | site=2; original nest id = Substitution. Siphonaptera: Ceratophyllidae: Ceratophyllus (Emmareus) garei Rothschild, 1902, det. R. E. Lewis.
  | site=2; original nest id = Water Ouzel Poser. Bdellidae; Siphonaptera: Ceratophyllidae: Megabothris abantis (Rothschild, 1905) 1 male, det. R. E. Lewis, few larvae.
  | site=3; original nest id = Jay watch. Erythraeidae: Erythraeus (not mounted); oribatids: #13, #13; Siphonaptera: Ceratophyllidae: Ceratophyllus (Emmareus) garei Rothschild, 1902, det. R. E. Lewis; 1 Diptera puparium.
  | site=4; original nest id = Careless Hypsibiont. Siphonaptera: Ceratophyllidae: Ceratophyllus (Emmareus) garei Rothschild, 1902, det. R. E. Lewis, 1 adult, larvae numerous; Diptera puparia.
  | site=4; original nest id = Omphalos. oribatids: #1; Siphonaptera: Ceratophyllidae: Ceratophyllus (Emmareus) garei Rothschild, 1902, det. R. E. Lewis, 2 adults, larvae & pupae abundant.
  | site=4; original nest id = Subterfuge not!. Erythraeidae: 1 Erythraeus nymph; oribatids: #5; Siphonaptera: Ceratophyllidae: Ceratophyllus (Emmareus) garei Rothschild, 1902, det. R. E. Lewis, 1 adult, larvae & pupae abundant; Diptera puparia & 1 larva.
  | site=4; original nest id = Sweet Sassy Molassy. Erythraeidae: 1 Erythraeus ad; Siphonaptera: Ceratophyllidae: Ceratophyllus (Emmareus) garei Rothschild, 1902, det. R. E. Lewis, 1 adult, larvae; Diptera puparia.
  | site=4; original nest id = Symphysis. oribatids: #1; Siphonaptera: Ceratophyllidae: Ceratophyllus (Emmareus) garei Rothschild, 1902, det. R. E. Lewis; Diptera puparia abundant
UMMZ 162551 | - skel - 5 Laelapidae: Androlaelaps fahrenholzi (Berlese, 1911); Ixodidae: Dermacentor andersoni Stiles, 1908 larvae, Ixodes sculptus Neumann, 1904, 1 nymph; 1 louse, Enderleinellidae: Enderleinellus suturalis (Osborn, 1891) nymph - 3 fleas (below) w/mites, 3 others without.
UMMZ 162551 | - skel - 5 Laelapidae: Androlaelaps fahrenholzi (Berlese, 1911); Ixodidae: Dermacentor andersoni Stiles, 1908 larvae, Ixodes sculptus Neumann, 1904, 1 nymph; 1 louse, Enderleinellidae: Enderleinellus suturalis (Osborn, 1891) nymph - 3 fleas (below) w/mites, 3 others without.  Mites removed: BMOC 85-1125-003
UMMZ 162551 | - skel - 5 Laelapidae: Androlaelaps fahrenholzi (Berlese, 1911); Ixodidae: Dermacentor andersoni Stiles, 1908 larvae, Ixodes sculptus Neumann, 1904, 1 nymph; 1 louse, Enderleinellidae: Enderleinellus suturalis (Osborn, 1891) nymph - 3 fleas (below) w/mites, 3 others without.  Mites removed: BMOC 85-1125-004
UMMZ 175910 | Juvenile, captive; w/alopecia over entire body except head, forefeet & hind feet. Echimyopodidae: Echimyopus dn's numerous in follicles of head & hind feet (where hair was remaining) (all (4) HDNs used up for DNA extraction, P. Klimov, 2006); 1 Myocoptidae: Sciurocoptes female on head (other cast skins attached to hairs of head).  2 old chigger lesions observed, but no mites.  1 flea: Orchopeas howardii
UMMZ 176633 | 2006-083. Ixodidae on ears; few red Trombiculidae few on ears, numerous posterior ventral, on hindlegs; few Glycyphagidae dn's on hairs anterior dorsal;  few Atopomelidae dorsal; 1 flea Siphonaptera: Stephanocircidae.
UMMZ 53460-53464 | multiple host specimens listed. Host ID:Deer mice
UMMZ 54464-54466 | 2 host specimens
UMMZ 54582-54583 | 2 host specimens
UMMZ 55549 | Peromyscus leucopus/maniculatus UMMZ 55549 et al. Host ID:Deer mice
UMMZ 56080-56084 | 2 host specimens
UMMZ 63760 | P.M.B.# 18 Host: Citellus H.harrisii (Audubon & Bach)
UMMZ 638989 | arizonae mearns Host ID:Western spotted skunk
UMMZ 63902 |  
UMMZ 63902 | Bassariscus astutus arizonensis Goldman Host ID:Ring-tailed cat
UMMZ 63902 | Bassariscus astutus Goldman Host ID:Ring-tailed cat
UMMZ 63905 |  
UMMZ 63905 | Bassariscus astutus Goldman Host ID:Ring-tailed cat
UMMZ 63905 | P.M.B. #205 Host author: (Goldman)
UMMZ 63960 | P.M.B.# 18 Host: Citellus H.harrisii (Audubon & Bach)
UMMZ 63989 | illegible "mephitis"
UMMZ 63998-9 |  
UMMZ 63998.9 | arizonae mearns Host ID:Western spotted skunk
UMMZ 63998.9 | Mearns Host ID:Western spotted skunk
UMMZ 63998-9 | Spilogale gracilis arizonae mearns Host ID:Western spotted skunk
UMMZ 86593-86599 | 2 host specimens listed
UMMZ 86593-86599 | multiple host specimens listed.
UMMZ 86593-86599 | Multiple host specimens listed.
UMMZ 86613-86614 | 2 host specimens listed

**Comment by jhpoelen** [comment]
fyi @seltmann @neilcobb @zaspelj 

A first pass at indexing UMMZI parasite-host records are now available via GloBI.  From https://globalbioticinteractions.org/status page, 67.8k interactions between 9.6k taxa are reportedly indexed from UMMZI. 
![Screenshot from 2020-02-03 10-32-18](https://user-images.githubusercontent.com/1084872/73680185-afec4580-4670-11ea-8104-1bf74d231023.png)

Also, attached screenshot of https://www.globalbioticinteractions.org/?accordingTo=globi%3Aglobalbioticinteractions%2Fummzi :

![Screenshot from 2020-02-03 10-31-12](https://user-images.githubusercontent.com/1084872/73680264-ceead780-4670-11ea-9c07-0f59f98160b1.png)

**Comment by zaspelj** [comment]
This is great!

*Jennifer M. Zaspel, PhD*

Associate Curator and Head of Zoology

Director of Puelicher Butterfly Wing

Milwaukee Public Museum

800 West Wells Street, Milwaukee, WI
<https://maps.google.com/?q=800+West+Wells+Street,+Milwaukee,+WI&entry=gmail&source=g>

414-278-6158| zaspelj@mpm.edu <youremail@mpm.edu> | www.mpm.edu
