### ISSUE TITLE
Downloading Globi networks

### ISSUE THREAD

**Issue by michaldrori** [globalbioticinteractions/globalbioticinteractions#454]
Hi,

We're working on analyzing plants&pollinators networks and your database seems perfect as a source for data. Can you please explain how I can download the entire network data (and not perform specific queries as explained in your site)?
That would be very helpful,

Thanks
Michal

**Comment by jhpoelen** [comment]
@michaldrori Thanks for your message. 

You can download all the network data in various formats (e.g., csv, tsv, nquads, dwca, neo4j) using the links at the data page on:

https://globalbioticinteractions.org/data 

Please let me know if you have any additional questions. If not, please let me know and I'll close this issue.

**Comment by jhpoelen** [comment]
@michaldrori asked a follow up question via #456 .
