### ISSUE TITLE
plant-pollinator networks

### ISSUE THREAD

**Issue by michaldrori** [globalbioticinteractions/globalbioticinteractions#456]
Dear GLOBI developers,

My name is Michal Drori and I am a researcher at Tel Aviv University working at the lab of Prof. Itay Mayrose. In my current research, I study the interaction between whole genome duplication and the pollination niche across many plant-pollinator networks. It seems that the GLOBI resource could be especially useful for our purpose. Specifically, I need to download all plant-pollinator networks data . I succeeded in downloading the data from the browse tab in the online GLOBI server. The downloaded file contained 4096 entries obtained from 56 unique studies (column name is "study_citation").
Could you please let me know if this covers all plant-pollinator networks that exist in the GLOBI database? I  would greatly appreciate your response.

Regards,
Michal

**Comment by jhpoelen** [comment]
Hi Michal - Thanks for your message. The GloBI Browse tool exists to assist quick discovery of indexed interaction records. The download button on the discovery tool only returns up to 4096 records. If you intend to do research with the data, I would recommend using a copy of the full index via the gzipped tab-separated-values file at https://depot.globalbioticinteractions.org/snapshot/target/data/tsv/interactions.tsv.gz and select rows with pollinator related interactions (e.g., "pollinates", "pollinatedBy", "visitsFlowersOf", "flowersVisitedBy", "visits", "visitedBy") using some script or computer program that you are familiar with. 

For instance, using a linux command-line, a crude sub-selection of pollinator data can be made by:

```
curl -L https://depot.globalbioticinteractions.org/snapshot/target/data/tsv/interactions.tsv.gz > interactions.tsv.gz 
zcat interactions.tsv.gz | grep -P "(pollinates)|(pollinatedBy)|(visitsFlowersOf)|(flowersVisitedBy)|(visits)|(visitedBy)```
```
Similar operations can be done using [R](https://r-project.org) in combination with tidyverse or other R packages . 

Please let me know if you have more questions.

Related to #454 .

**Comment by jhpoelen** [comment]
By the way - a quick and dirty count using method described above tells me that there's about 89k pollinator related interaction records. Please reproduce and confirm.

**Comment by jhpoelen** [comment]
I am assuming that you question was answered. If not, please comment and I'll re-open the issue. Thanks for reaching out!
