### ISSUE TITLE
TTD data and SCAN

### ISSUE THREAD

**Issue by seltmann** [globalbioticinteractions/globalbioticinteractions#458]
A dataset in GloBI 
https://github.com/globalbioticinteractions/globalbioticinteractions/issues/126
Is also served from SCAN (so it is being indexed from 2 sources presently).

Also, this dataset is interesting in another way because it is static, in the sense that it is not going to be re-generated from the database. However, the data is starting to be released by the originating institutions. 

This means that information about single specimens will come in through different information channels (e.g., different dwca describing the same specimen record)?

The expectation is that the reference for that association will change. Eventually the entire static TTD-TCN dataset will disappear. I understand this is likely problematic.
--

**Comment by jhpoelen** [comment]
Yes, information for the same specimen record can arrive from different channels. GloBI keeps the datasets is receives and publishes them as part of the GloBI dataset cache at Poelen, Jorrit H. (2019). Global Biotic Interactions: Elton Dataset Cache (Version 0.3) [Data set]. Zenodo. http://doi.org/10.5281/zenodo.3523403 . However, more systematic methods can be deployed to keep specific dataset version around and reference them reliable. See e.g., Elliott, M. J., Poelen, J. H., & Fortes, J. (2020, January 3). Toward Reliable Biodiversity Dataset References. https://doi.org/10.32942/osf.io/mysfp .

@seltmann Please re-open this issue or comment if you feel this issue has not been resolved.
