### ISSUE TITLE
suggest to index  Grundler MC (2020) SquamataBase: a natural history database and R package for comparative biology of snake feeding habits. Biodiversity Data Journal 8: e49943. https://doi.org/10.3897/BDJ.8.e49943 

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions#469]
Grundler MC (2020) SquamataBase: a natural history database and R package for comparative biology of snake feeding habits. Biodiversity Data Journal 8: e49943. https://doi.org/10.3897/BDJ.8.e49943

**Comment by jhpoelen** [comment]
Hey @blueraleigh - congrat on your recent publication in Biodiversity Data and for referencing GloBI. I took the time today to index your predator-prey records and committed the results in https://github.com/globalbioticinteractions/squamatabase . I expect that that your records will be available for discovery (with citation) so that others have another way to find your work. 

As I was setting up indexing Squamatabase, I noticed a few suspicious record - I'll record those separately as issue in your repository at https://github.com/blueraleigh/squamatabase momentarily.

**Comment by jhpoelen** [comment]
related issues 
https://github.com/blueraleigh/squamatabase/issues/1
https://github.com/blueraleigh/squamatabase/issues/2
https://github.com/blueraleigh/squamatabase/issues/3
https://github.com/blueraleigh/squamatabase/issues/4

Thanks for openly sharing your data .

Am keeping this issue open until Squamatabase has been indexed.

**Comment by blueraleigh** [comment]
Thanks for flagging these @jhpoelen, I've gone ahead and corrected these issues at https://github.com/blueraleigh/squamatabase. And thanks for incorporating into GloBI, great stuff!

**Comment by jhpoelen** [comment]
@blueraleigh I re-ran GloBI's Elton review and can confirmed that you resolved the suspicious dates. Thanks for taking such quick action. Also, I was to detect 10983 - 1 (the header) = 10982 interactions using:

```
$ elton interactions | wc -l
10983
```

Am keeping this issue open until your dataset is discoverable via https://globalbioticinteractions.org . This should take a couple of days.

**Comment by jhpoelen** [comment]
@blueraleigh squamatabase was indexed by GloBI closing issue . See attached screenshots related to https://www.globalbioticinteractions.org/?accordingTo=globi%3Aglobalbioticinteractions%2Fsquamatabase&interactionType=ecologicallyRelatedTo .

Please do holler if you have comments or questions. 

![Screenshot from 2020-04-06 10-46-52](https://user-images.githubusercontent.com/1084872/78588798-1833e080-77f4-11ea-83c1-0eca592f80b4.png)
![Screenshot from 2020-04-06 10-46-35](https://user-images.githubusercontent.com/1084872/78588802-18cc7700-77f4-11ea-945f-9f05511d2455.png)
