### ISSUE TITLE
use of existing GloBI geospatial-indexes using TEOW, FEOW, MEOW, longhurst

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions#473]
Ever since 2013, when GloBI was first launched, record locations were indexed against ecoregions of the world (e.g., Terrestrial Ecoregions of the World (TEOW), Marine Ecoregions of the World (MEOW), and Terrestrial Ecoregions of the World (TEOW), and Longhurst biochemical provinces) .

These ecoregion schemes provide an ecologically relevant way to group locations of species interactions . The ecoregion indexes provided by GloBI allow for searching by well-defined terrestrial, marine, and freshwater regions. While the feature is described in the GloBI paper (see https://doi.org/10.1016/j.ecoinf.2014.08.005 ), the indexes are not prominently featured, so many users probably don't know of their existence. And, the indexing takes quite some compute power. 

This issue is to document the geospatial indexing feature as well as a way to reconsider whether the ecoregion indexing is something that should be continued.

@jhammock @seltmann @diatomsRcool @BrianHayden - I'd be curious to hear input from y'all on the topic. Have you ever used ecoregions in your research?

Citations for the related ecoregion schemes are:

Olson, D. M., Dinerstein, E., Wikramanayake, E. D., Burgess, N. D., Powell, G. V. N., Underwood, E. C., D'Amico, J. A., Itoua, I., Strand, H. E., Morrison, J. C., Loucks, C. J., Allnutt, T. F., Ricketts, T. H., Kura, Y., Lamoreux, J. F., Wettengel, W. W., Hedao, P., Kassem, K. R. 2001. Terrestrial ecoregions of the world: a new map of life on Earth. Bioscience 51(11):933-938.

Mark D. Spalding, Helen E. Fox, Gerald R. Allen, Nick Davidson, Zach A. Ferdaña, Max Finlayson, Benjamin S. Halpern, Miguel A. Jorge, Al Lombana, Sara A. Lourie, Kirsten D. Martin, Edmund McManus, Jennifer Molnar, Cheri A. Recchia, James Robertson, Marine Ecoregions of the World: A Bioregionalization of Coastal and Shelf Areas, BioScience, Volume 57, Issue 7, July 2007, Pages 573–583, https://doi.org/10.1641/B570707

 Robin Abell, Michele L. Thieme, Carmen Revenga, Mark Bryer, Maurice Kottelat, Nina Bogutskaya, Brian Coad, Nick Mandrak, Salvador Contreras Balderas, William Bussing, Melanie L. J. Stiassny, Paul Skelton, Gerald R. Allen, Peter Unmack, Alexander Naseka, Rebecca Ng, Nikolai Sindorf, James Robertson, Eric Armijo, Jonathan V. Higgins, Thomas J. Heibel, Eric Wikramanayake, David Olson, Hugo L. López, Roberto E. Reis, John G. Lundberg, Mark H. Sabaj Pérez, Paulo Petry, Freshwater Ecoregions of the World: A New Map of Biogeographic Units for Freshwater Biodiversity Conservation, BioScience, Volume 58, Issue 5, May 2008, Pages 403–414, https://doi.org/10.1641/B580507

Reygondeau, G., Longhurst, A., Martinez, E., Beaugrand, G., Antoine, D., and Maury, O. ( 2013), Dynamic biogeochemical provinces in the global ocean, Global Biogeochem. Cycles, 27, 1046– 1058, doi:10.1002/gbc.20089.

**Comment by seltmann** [comment]
@jhpoelen  I did not know that ecoregion data was accessible in Globi. I am working on a paper at the moment where we are looking at insect diversity differences in various ecoregions of North America, specifically to see if the diversity of insects follows similar patterns of plants.

**Comment by jhpoelen** [comment]
Thanks for sharing that you are using ecoregions as a way to make ecologically relevant geospatial groupings . How did you assign locations to ecoregions?

**Comment by seltmann** [comment]
Using shp files in R

**Comment by jhpoelen** [comment]
Cool! So, lat/lng -> ecoregion via shp files. That what GloBI also does . . . you example tells me that folks already know how to index ecoregions using existing tools. So, I am removing existing ecoregion indexing. If there turns out to be a desire to add it again, am happy to reconsider.

**Comment by jhpoelen** [comment]
Closing issue - GloBI now assumes that geospatial-indexes can be made independently of GloBI using readily available tools like R and PostGIS / ArcGIS etc.
