### ISSUE TITLE
NEW bee interaction database

### ISSUE THREAD

**Issue by seltmann** [globalbioticinteractions/globalbioticinteractions#474]
Hi!
I forked a new bee interaction database to globalbioticinteractions/bee-interaction-database. Looking forward to our first review.

**Comment by jhpoelen** [comment]
Awesome! 

Looks like your data was already reviewed by Elton because you enabled travis (from https://travis-ci.org/github/seltmann/bee-interaction-database/jobs/673624158#L198 ). Looks like two record do not have source taxon name specified. Is this expected?

You can download the full review from the file.io link referenced below. 

If the file.io download link expired or was already used, you can recreate it by rerunning the review in travis by clicking the "rebuild" button. 

```
   _____ _       ____ _____   _____            _                
  / ____| |     |  _ \_   _| |  __ \          (_)               
 | |  __| | ___ | |_) || |   | |__) |_____   ___  _____      __ 
 | | |_ | |/ _ \|  _ < | |   |  _  // _ \ \ / / |/ _ \ \ /\ / / 
 | |__| | | (_) | |_) || |_  | | \ \  __/\ V /| |  __/\ V  V /  
  \_____|_|\___/|____/_____| |_|  \_\___| \_/ |_|\___| \_/\_/   
 | |           |  ____| | |                                     
 | |__  _   _  | |__  | | |_ ___  _ __                          
 | '_ \| | | | |  __| | | __/ _ \| '_ \                         
 | |_) | |_| | | |____| | || (_) | | | |                        
 |_.__/ \__, | |______|_|\__\___/|_| |_|                        
         __/ |                                                  
        |___/                                                   
Reviewing [https://raw.githubusercontent.com/seltmann/bee-interaction-database/master] using Elton version [0.9.1].

artifacts version 0.8.2 revision=cf2807bf86a9e57aea2585b0a3210040f8804f1c
creating review [local]... done.

Review of [seltmann/bee-interaction-database] included:
  - 9 interaction(s)
  - 2 note(s)
  - 9 info(s)

[seltmann/bee-interaction-database] has 2 reviewer note(s):
      2 source taxon name missing

Download the full review report with the single-use, and expiring, file.io link at:

{"success":true,"key":"68fpyG","link":"https://file.io/68fpyG","expiry":"14 days"}

If https://file.io link above no longer works, access review notes by:
  - installing GloBI's Elton via https://github.com/globalbioticinteractions/elton
  - running "elton update seltmann/bee-interaction-database && elton review --type note,summary seltmann/bee-interaction-database > review.tsv"
  - inspecting review.tsv

Please email info@globalbioticinteractions.org for questions/ comments.
```

**Comment by jhpoelen** [comment]
I provided first review of your new bee interaction database earlier. Please let me know if you have any questions / comments about the review. If not, please close this issue.

Note that reviews are now automatically generated whenever changes are made to your datasets.

**Comment by seltmann** [comment]
We can chat about this today in our meeting, but those records all have name identifiers, yet 2 are considered missing? There are only 2 source taxon names in these records, which means that all of the interactions do not have a source name.

**Comment by jhpoelen** [comment]
Thanks for the chat on Friday. Can we close this issue now that the your bee database is being indexed? Suggest to report individual data issues separately.
