### ISSUE TITLE
restart lod.globalbioticinteractions.org

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions#482]
As part of a recent (last week) server migration, the SPARQL endpoint hosted via https://lod.globalbioticinteractions.org is still being worked on . This service will be restarted momentarily.

**Comment by jhpoelen** [comment]
fyi @mdmtrv  GloBI sparql endpoint is back up and running , see https://lod.globalbioticinteractions.org/dataset.html?tab=query&ds=/globi and attached screenshot. 
![Screenshot from 2020-04-16 16-20-07](https://user-images.githubusercontent.com/1084872/79515685-2e188100-7ffe-11ea-8aee-9a07c35a4d8d.png)

Please note that rdf exports of GloBI are used sparingly, so any improvements suggestions are appreciated - changes are relatively easy to make because the triples are regenerated every other day or so.

**Comment by mdmtrv** [comment]
@jhpoelen Great! I will check it out!

**Comment by jhpoelen** [comment]
@mdmtrv Glad I found you on github! And, just to emphasize - there's many improvement that can be made to the triplified view into GloBI. Please also note that Elton's [Nanopublications support](https://github.com/globalbioticinteractions/globalbioticinteractions/wiki/Nanopubs) use a slightly different model than the one exposed via the sparql endpoint. As you seem to be experienced in rdf modeling, I would welcome any ideas (small or radical!) on improving GloBI's rdf related data products.
