### ISSUE TITLE
refresh interaction table

### ISSUE THREAD

**Issue by seltmann** [globalbioticinteractions/globalbioticinteractions#493]
@jhpoelen the interaction table found at 
eol-globi-lib/src/main/resources/org/globalbioticinteractions/interaction_types_mapping.csv
is it auto refreshed? If so, how often?

**Comment by jhpoelen** [comment]
This table is shipped with along with the software library. Elton uses this library, so Elton's default interactions will be updated on the next release. Note that you can define your own interaction mappings by providing your own interaction type mapping in the github repo. For example, see https://github.com/globalbioticinteractions/inhs-insects .

**Comment by jhpoelen** [comment]
@seltmann please close this issue if your question was answered. If not, please comment.
