### ISSUE TITLE
suggest to index Frier D (2020): Royal Saskatchewan Museum - Owl Pellet Collection. v2.1. Royal Saskatchewan Museum. Dataset/Occurrence. https://doi.org/10.5886/f0xsbu

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions#500]
as shared via https://twitter.com/idbdeb/status/1266756160432017409 by by Deb Paul @debpaul -

"😂 not your average specimens! But wait?! Isn’t it basisOfRecord = REGURGITATE? @GlobalBiotic what’s the ontological relationship reference for this? Is there a term for A throws up B? (Or are these owl pellets from the other end)?" 

Citation of related dataset:

> Frier D (2020): Royal Saskatchewan Museum - Owl Pellet Collection. v2.1. Royal Saskatchewan Museum. Dataset/Occurrence. https://doi.org/10.5886/f0xsbu

**Comment by jhpoelen** [comment]
A quick review of the data shows interaction data related to the pellet of 9 associated owl species are described in the following occurenceRemarks : 


number of records | occurrenceRemarks values
-- | --
54746 | Found in Burrowing Owl pellet
37560 | Found in Great Horned Owl pellet
219 | Found in owl pellet - species unknown
142 | Found in Northern Hawk Owl pellet
77 | Found in Long-eared Owl pellet
25 | Found in Short-eared Owl pellet
24 | Found in Snowy OWl pellet
24 | Found in Snowy Owl pellet
5 | Found in Northern Saw-Whet Owl pellet

with the suspected prey remains described using the familiar darwin core fields. See first four records for  example:

basisOfRecord | occurrenceID | catalogNumber | occurrenceRemarks | preparations | eventDate | countryCode | stateProvince | decimalLatitude | decimalLongitude | scientificName | kingdom | phylum | class | order | family | genus | specificEpithet | taxonRank
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
PreservedSpecimen | urn:catalog:RSKM:OWLPELLET:OP-1.0001 | RSKM_OWLPELLET_OP-1 | Found in Great Horned Owl pellet | partial skeletal and/or dental material | 4/25/2008 | CA | Saskatchewan | 49.36035 | -107.87387 | Lasiurus cinereus | Animalia | Chordata | Mammalia | Chiroptera | Vespertilionidae | Lasiurus | cinereus | species
PreservedSpecimen | urn:catalog:RSKM:OWLPELLET:OP-1.0002 | RSKM_OWLPELLET_OP-1 | Found in Great Horned Owl pellet | partial skeletal and/or dental material | 4/25/2008 | CA | Saskatchewan | 49.36035 | -107.87387 | Lasiurus cinereus | Animalia | Chordata | Mammalia | Chiroptera | Vespertilionidae | Lasiurus | cinereus | species
PreservedSpecimen | urn:catalog:RSKM:OWLPELLET:OP-1.0003 | RSKM_OWLPELLET_OP-1 | Found in Great Horned Owl pellet | partial skeletal and/or dental material | 4/25/2008 | CA | Saskatchewan | 49.36035 | -107.87387 | Lemmiscus curtatus | Animalia | Chordata | Mammalia | Rodentia | Muridae | Lemmiscus | curtatus | species
PreservedSpecimen | urn:catalog:RSKM:OWLPELLET:OP-1.0004 | RSKM_OWLPELLET_OP-1 | Found in Great Horned Owl pellet | partial skeletal and/or dental material | 4/25/2008 | CA | Saskatchewan | 49.36035 | -107.87387 | Lemmiscus curtatus | Animalia | Chordata | Mammalia | Rodentia | Muridae | Lemmiscus | curtatus | species

**Comment by jhpoelen** [comment]
I am leaning toward at indexing these records as an specific owl's regurgitated pellet (i.e. http://purl.obolibrary.org/obo/UBERON_0036018) containing the (dead) remains  (i.e. physiological state: dead) of some organism with some documented taxonomic classification found at specified location and time.

The reported association  term "found in" can be (conservatively) mapped to the http://www.ontobee.org/ontology/RO?iri=http://purl.obolibrary.org/obo/RO_0008506 until a better RO term presents itself.

**Comment by jhpoelen** [comment]
The curator of the collection, Danae Frier,  was kind enough to answer the following questions:

Q1. You mention, "found in" as a way to describe the association between the owl pellet and the associated organism. Would you say that this can be interpreted as "owl ate species X"?

> A1. Yes.


Q2. Also, I notice you use common names to describe the owls:

Burrowing Owl

Great Horned Owl

Northern Hawk Owl

Long-eared Owl

Short-eared Owl

Snowy OWl

Northern Saw-Whet Owl

Would it be correct to assume these where the names as found on the pellet labels?

> A2. Yes, but I am cc'ing Ray Poulin in in case he has anything to add, as he processed many of the pellets and developed the original spreadsheet.

Q3. I notice you are using date formatting like "4/25/2008" instead of the (recommended) ISO8601 format "2008-04-25" . Is there any way I can convince you to change to this date format?

> A3. I believe this format arose accidentally by converting between spreadsheet types, the intention was certainly to use the yyyy/mm/dd format. When we update to future versions I'll be sure to double check the error doesn't re-occur.

**Comment by jhpoelen** [comment]
fyi @ahhurlbert - I'd be curious to see how this owl pellet collection overlaps with your avian diet database at https://github.com/hurlbertlab/dietdatabase .

**Comment by ahhurlbert** [comment]
We have so far only incorporated diet data (including owl pellet analysis) from published papers, so if these data have never been included in other publications then we don't have them. We would certainly love to incorporate them.

If we do, hopefully it doesn't cause a problem of duplicate records from GloBI's perspective.

**Comment by jhpoelen** [comment]
A first pass at integrating the Royal Saskatchewan Museum - Owl Pellet Collection. v2.1. Royal Saskatchewan Museum. Dataset/Occurrence. https://doi.org/10.5886/f0xsbu is available via globalbioticinteractions/rskm-owlpellet with reviews and list of indexed interactions (per specimen) at https://travis-ci.com/globalbioticinteractions/rskm-owlpellet . 

Also, attached screenhots via https://www.globalbioticinteractions.org/?accordingTo=globi%3Aglobalbioticinteractions%2Frskm-owlpellet and https://www.globalbioticinteractions.org/browse/?accordingTo=globi%3Aglobalbioticinteractions%2Frskm-owlpellet&interactionType=interactsWith&resultType=json . 

![Screenshot from 2020-06-06 09-29-25](https://user-images.githubusercontent.com/1084872/83949379-563f8780-a7d8-11ea-98c8-2faabe70181f.png)
![Screenshot from 2020-06-06 09-25-51](https://user-images.githubusercontent.com/1084872/83949384-58094b00-a7d8-11ea-804f-126f1689d253.png)

Note that the foodweb visualization only a partial visualization of the 90k+ diet records associated with the owls.

**Comment by jhpoelen** [comment]
@ahhurlbert I hope this pellet collection will help improve your diet database and I am curious to see how you'll incorporate the data into your Avian Diet Database https://github.com/hurlbertlab/dietdatabase/issues/133 . Not too worried about duplication, especially if you keep the occurrence id (or other identifying information of the specimen / collection) of the records around in the reference.

**Comment by jhpoelen** [comment]
@ahhurlbert question to you, a bird expert. Which taxonomic names would you assign the owl common names mentioned in this dataset? 

Burrowing Owl
Great Horned Owl
Northern Hawk Owl
Long-eared Owl
Short-eared Owl
Snowy Owl
Northern Saw-Whet Owl

**Comment by ahhurlbert** [comment]
Since a record in our database is a % of diet for a given prey, then it will be a synthesis of many records in the Owl Pellet Collection database, e.g., within a given pellet ID, X records were for prey species A out of Y total prey items in the pellet. Not sure how this would be mapped to original occurrence IDs.

Re: bird taxonomy, we use eBird/Clements, which can be downloaded here: https://www.birds.cornell.edu/clementschecklist/download/
