### ISSUE TITLE
index interactions from 262 year old biodiversity knowledge graph:  Linneaus' Systema naturae from 1758 

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions#512]
about 262 years ago, in 1758, Carl Linneaus published what would currently describe as a biodiversity knowledge graph: Systema naturae. 

@myrmoteras took a first pass at helping to index the species interaction contained in this landmark publication. He started with the taxonomic treatment of _Apis mellifera_ from:

> Linné, C. von, 1758. Systema naturae per regna tria naturae :secundum classes, ordines, genera, species, cum characteribus, differentiis, synonymis, locis. Available at: http://dx.doi.org/10.5962/bhl.title.542. 

Luckily, the Biodiversity Heritage Library has digitized a copy, so the _Apis mellifera_ page like https://www.biodiversitylibrary.org/page/727487 (see attached screenshot) is openly accessible.

![mobot31753000798865_0598](https://user-images.githubusercontent.com/1084872/84822719-02038700-afd2-11ea-8090-cb413b2d5378.jpg)

**Comment by jhpoelen** [comment]
A first pass at indexing transcribed interactions from Linnaeus can be found via https://github.com/globalbioticinteractions/linnaeus1758 .

**Comment by jhpoelen** [comment]
GloBI has first indexed the Linnaeus publication. See e.g., https://www.globalbioticinteractions.org/?accordingTo=globi%3Aglobalbioticinteractions%2Flinnaeus1758&interactionType=ecologicallyRelatedTo and attached screenshot. 

As expected, many of taxon names from 1758 could not be matched.

 @myrmoteras @n8upham any suggestions on how to best resolve these ancient taxon names?

**Comment by myrmoteras** [comment]
The names, e.g. Aconitum, are generic names, not species names. that means that you can say this is a Aconitum that has been growing in SE Europe, around the Black sea (ponticis) if this is the right translation. It might be wrong, because none of these species are listed from there though. He included five species. They are here in the typification book, and the original treatments will follow soon http://tb.plazi.org/GgServer/summary/AE82AC14FF260691E35B55D432A46BB5

So you could make a one to many relationship, or just keep it generic.

**Comment by jhpoelen** [comment]
Thanks for pointing out that ```Aconitum ponticis``` is a contraction of a genus name ```Aconitum``` and a location ```ponticis```. Perhaps we can account for this by adding/populating a locality column to our transcription sheet.

**Comment by myrmoteras** [comment]
I probably wold add the species name of the five species? They are all bee plants - or is this against the grain?

**Comment by jhpoelen** [comment]
I'd first transcribe the names as is, then define the name mapping separately. Would these names be referenced in the Linnaeus work or are these the "modern" names from some recent taxonomic naming scheme?

**Comment by myrmoteras** [comment]
the name in Linnaeus 1753, and then the name in Jarvis 2016 where he provides the currently accepted name and the link to the types in the Linnaeus collectin.
We will have for some the original treatments, and all the ones in Jarvis. Unfortunately, there is only volume 1 transcribed, and without a great effort, get this done is not possible.

**Comment by jhpoelen** [comment]
@myrmoteras I've added an extra column for locality, which increased the taxonomic linkages (see attached screenshot) accessed via https://www.globalbioticinteractions.org/?accordingTo=globi%3Aglobalbioticinteractions%2Flinnaeus1758 . 

[![Screenshot from 2020-06-19 07-56-54](https://user-images.githubusercontent.com/1084872/85147006-15e1ff80-b203-11ea-89ae-18407b170fe6.png)](https://www.globalbioticinteractions.org/browse/?accordingTo=globi%3Aglobalbioticinteractions%2Flinnaeus1758&interactionType=ecologicallyRelatedTo&resultType=json)

Please note that more work is needed to resolve other "ancient" taxonomic names, especially those that describe the "enemies" of honey bee (_Apis mellifera_). A list of these can be found via https://www.globalbioticinteractions.org/?accordingTo=globi%3Aglobalbioticinteractions%2Flinnaeus1758&interactionType=ecologicallyRelatedTo&sourceTaxon=no%3Amatch .
