### ISSUE TITLE
Suggestion to include: Thompson et al. (2020)

### ISSUE THREAD

**Issue by dswdejonge** [globalbioticinteractions/globalbioticinteractions#514]
Hi there, 
Found out about Globi just a short while ago, looks very nice! I came across this article, which might be interesting to incorporate:

Thompson et al. (2020) A feeding guild indicator to assess environmental change impacts on marine ecosystem structure and functioning. https://doi.org/10.1111/1365-2664.13662

They say: "Here, we compile a new marine dataset containing 8092 unique predator‐prey interactions from 415,294 fish stomachs.".

**Comment by jhpoelen** [comment]
@dswdejonge thanks for pointing out this work. Unfortunately, I was unable to read the article, because it is not open access. However, in reading the abstract and associated information, it looks like the authors used ICES and CEFAS stomach datasets, both of which are indexed by GloBI. However, more information is needed to better understand their dataset. Would you happen to have a link to their dataset or some pre-print copy of the article?

**Comment by dswdejonge** [comment]
@jhpoelen I managed to find a pre-print. You are right, they used the CEFAS (DEPSTOM) and ICES (ICES Year of The Stomach Dataset) databases and didn't add any data themselves, so no need to include then. 
I'll keep my eyes open for more :)

**Comment by jhpoelen** [comment]
@dswdejonge Thanks for checking the Thompson et al. 2020 data sources . Am looking forward to your suggestions for other data sets to index.

Also, after re-reading their abstract:

> Inventories of trophic interactions have been collated worldwide and across biomes, and can be applied to infer food web structure and energy flow. Here, we compile a new marine dataset containing 8092 unique predator‐prey interactions from 415,294 fish stomachs. We demonstrate how feeding guilds (i.e. groupings based on diet and life stage) could be defined systematically and in a way that is conducive to their application internationally across ecosystems; and apply them to the North Sea fish assemblage to demonstrate their responsiveness to anthropogenic pressures.

, I wonder what their results would produce for other GloBI-indexed stomach datasets like GoMexSI, NOAA REEM and the Southern Ocean Dietary Database:

https://gomexsi.tamucc.edu 

Resource Ecology and Ecosystem Modeling (REEM) - Groundfish Diet Data of Aleutian Islands, Alaska Fisheries Science Center, NOAA; Resource Ecology and Ecosystem Modeling (REEM) - Groundfish Diet Data of Gulf of Alaska, Alaska Fisheries Science Center, NOAA; Resource Ecology and Ecosystem Modeling (REEM) - Groundfish Diet of Data Bering Sea, Alaska Fisheries Science Center, NOAA 

Raymond, B., Marshall, M., Nevitt, G., Gillies, C., van den Hoff, J., Stark, J.S., Losekoot, M., Woehler, E.J., and Constable, A.J. (2011) A Southern Ocean dietary database. Ecology 92(5):1188. Available from http://dx.doi.org/10.1890/10-1907.1
