### ISSUE TITLE
Output data files are empty

### ISSUE THREAD

**Issue by qgroom** [globalbioticinteractions/globalbioticinteractions#517]
The download files of GloBI here https://www.globalbioticinteractions.org/data.html are all empty.

**Comment by jhpoelen** [comment]
@qgroom Thanks - I am glad you noticed! 

The files are back up after some (code) maintenance yesterday. Please confirm and close this issue once you are able to download the data again.

 Please note that versions of GloBI data sources and resulting data products are kept and the indexing process is continuous and automated. All this is to facilitate recovery. Needless to say, it probably wouldn't hurt to work towards #475 in addition to already existing publications like http://doi.org/10.5281/zenodo.3905244 (taxon name mapping) and http://doi.org/10.5281/zenodo.3523403 (source datasets). Am open to suggestions.

**Comment by qgroom** [comment]
Looks good, thanks!
