### ISSUE TITLE
provide soft checks for incorrect interactions

### ISSUE THREAD

**Issue by arw36** [globalbioticinteractions/globalbioticinteractions#527]
in looking up predators for Monarchs butterfly, milkweed is listed as eating monarchs. This is a data quality issue that could perhaps be regulated by certain taxon limits to interactions? like plants (other than carnivorous) can't eat animals. Seems like iNat is frequently the culprit for backward interactions (Monarch flowersVisitedBy plant).

**Comment by jhpoelen** [comment]
@arw36 Thanks for sharing these suspicious interactions. A recent collaboration with the Encyclopedia of Life has resulted in some "refutation" records. These records offer a way to independently document suspicious interactions. 

@jhammock @KatjaSchulz any idea why the https://www.globalbioticinteractions.org/?interactionType=flowersVisitedBy&sourceTaxon=Danaus%20plexippus were not included in the EOL refutation collection?

**Comment by KatjaSchulz** [comment]
Funny, Jen also discovered this problem just a week ago.  Eli is adding these cases (non-plants having flower visitors) to the refutation file.  They should be in there shortly.

**Comment by jhpoelen** [comment]
@KatjaSchulz thanks for your prompt reply and let me know when the updates are made, so I can verify that GloBI picked them up as expected. 

@arw36 Once the refutations are in place, I am hoping to work with you to make sure that you can apply the refutations as a way to apply the "soft checks" for incorrect/suspicious interactions. Thanks again for raising the issue and let me know if you have other ideas on how to make sure to label or otherwise deal with funky interaction records.

**Comment by jhpoelen** [comment]
@arw36 In reviewing suspicious interactions like Milkweed (Asclepias) eating monarchs (Danaus plexippus), I found four indexed interactions supporting the claim, all of which were refuted by @KatjaSchulz et al.  

I attached screenshot of current result of https://www.globalbioticinteractions.org/?interactionType=eatenBy&sourceTaxon=Danaus%20plexippus&targetTaxon=Asclepias:  
![Screenshot from 2020-08-20 11-16-13](https://user-images.githubusercontent.com/1084872/90809952-19633700-e2d7-11ea-80f9-0acf374f142b.png)

However . . . for related (suspicious) interactions like records that support claims that milkwood visit the flowers of a monarch butterfly, none of the records are refuted for some reason. 

attached screenshot from https://www.globalbioticinteractions.org/?interactionType=flowersVisitedBy&sourceTaxon=Danaus%20plexippus&targetTaxon=Asclepias - 

![Screenshot from 2020-08-20 11-23-17](https://user-images.githubusercontent.com/1084872/90810295-942c5200-e2d7-11ea-9cf5-411ccaecf7dd.png)

Note, however, that no suspicious interactions of monarch flowers being visited appear on EOL (e.g., https://eol.org/pages/56962473/data) . 

So, yes, soft checks are available via contributed refutation dataset by @KatjaSchulz et al. and more work is needed to improve the extend and integration of this dataset.

@arw36 note that you can contribute refutation dataset yourself to record your list of suspicious interactions. See https://github.com/globalbioticinteractions/refuted-interaction-data for example. 

Please re-open issue if you have more questions / comments.
