### ISSUE TITLE
suggest to index  Shaw, LP, Wang, AD, Dylus, D, et al. The phylogenetic range of bacterial and viral pathogens of vertebrates. Mol Ecol. 2020; 29: 3361– 3379. https://doi.org/10.1111/mec.15463

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions#533]
as suggested by Marcelo Weksler :

Shaw, LP, Wang, AD, Dylus, D, et al. The phylogenetic range of bacterial and viral pathogens of vertebrates. Mol Ecol. 2020; 29: 3361– 3379. https://doi.org/10.1111/mec.15463

**Comment by jhpoelen** [comment]
Related github repo: https://github.com/liampshaw/Pathogen-host-range/ . 

@liampshaw - I learned about your publication via https://globalbioticinteractions.org/covid19 collaboration.  Would you be open to getting your data indexed by Global Biotic Interactions? If so, I can prepare a pull request so that GloBI knows how to find you.

**Comment by liampshaw** [comment]
**@jhpoelen** - thanks! Indexing as part of GloBI sounds good to me. The repository is also available on Zenodo (https://doi.org/10.5281/zenodo.3823899), I don't know if that's an easier route.

**Comment by jhpoelen** [comment]
@liampshaw I've prepared a pull request for you to enable your repository for GloBI indexing. As far as Zenodo goes: if you create a new release following the pull request to automatically publish to Zenodo, and then request for the Zenodo publication to be added to the Global Biotic Interactions Zenodo community, then GloBI will use the Zenodo published dataset instead of the latest and greatest from GitHub. 

Please let me know if you have any questions / comments.

thx,
-jorrit

**Comment by jhpoelen** [comment]
For the time being, Shaw et al. 2020 is index via https://github.com/globalbioticinteractions/shaw2020 . See attached images related to https://www.globalbioticinteractions.org/?accordingTo=globi%3Aglobalbioticinteractions%2Fshaw2020&interactionType=ecologicallyRelatedTo .

Whenever @liampshaw decided to accept [my pull request](https://github.com/liampshaw/Pathogen-host-range/pull/3), the dataset can be indexed directly from the https://github.com/liampshaw/Pathogen-host-range repository.

![Screenshot from 2020-09-28 11-41-06](https://user-images.githubusercontent.com/1084872/94472619-d884fa80-017f-11eb-97dc-dd5b3810f3df.png)
![Screenshot from 2020-09-28 11-40-38](https://user-images.githubusercontent.com/1084872/94472626-dae75480-017f-11eb-88cb-ad90e209b8da.png)
![Screenshot from 2020-09-28 11-44-19](https://user-images.githubusercontent.com/1084872/94472706-fbafaa00-017f-11eb-81b0-19163cd72efb.png)
