### ISSUE TITLE
suggested to index BENSCH, S., HELLGREN, O. & PÉREZ-TRIS, J., 2009. MalAvi: a public database of malaria parasites and related haemosporidians in avian hosts based on mitochondrial cytochromeblineages. Molecular Ecology Resources, 9(5), pp.1353–1358. Available at: http://dx.doi.org/10.1111/j.1755-0998.2009.02692.x.

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions#537]
as suggested by @qgroom via https://covid19taf.slack.com/x-p1040778717233-1076591129936-1396671264196/archives/D0138467GP2/p1601222627000100 -

```
Quentin Groom   September 27th at 9:03 AM
This would be a good paper to include in GloBI. Needless to say the link is broke in the paper https://onlinelibrary.wiley.com/doi/pdf/10.1111/j.1755-0998.2009.02692.x
```

BENSCH, S., HELLGREN, O. & PÉREZ-TRIS, J., 2009. MalAvi: a public database of malaria parasites and related haemosporidians in avian hosts based on mitochondrial cytochromeblineages. Molecular Ecology Resources, 9(5), pp.1353–1358. Available at: http://dx.doi.org/10.1111/j.1755-0998.2009.02692.x.

**Comment by jhpoelen** [comment]
See also http://mbio-serv2.mbioekol.lu.se/Malavi/ .

**Comment by qgroom** [comment]
It looks like you found it.
I've written to the corresponding author and I'll let you know if I get a response.

**Comment by jhpoelen** [comment]
@qgroom Thanks!

**Comment by jhpoelen** [comment]
@qgroom I took a first stab at indexing a part malavi , a public database of malaria parasites. For now, only the parasite-host associations table (aka "hosts and sites table") is indexed. With help of authors, much more can be extracted (e.g., links to accessions, literature, vectors)

You can find the GloBI index configuration at:

https://github.com/globalbioticinteractions/malavi . 

btw - I used a handy little Elton command to auto-generate a template schema mapping using:

```shell
$ elton init --data-url "http://mbio-serv2.mbioekol.lu.se/tmp/Malavi1960735.xls" --data-citation "BENSCH, S., HELLGREN, O. and PÉREZ‐TRIS, J. (2009), MalAvi: a public database of malaria parasites and related haemosporidians in avian hosts based on mitochondrial cytochrome b lineages. Molecular Ecology Resources, 9: 1353-1358. https://doi.org/10.1111/j.1755-0998.2009.02692.x" globalbioticinteractions/malavi
$ vi globi.json <---- edit the auto-generated schema mapping in globi.json 
$  elton review <---- check results
$ git init 
$ git commit -am 'toward indexing malavi; related to https://github.com/globalbioticinteractions/globalbioticinteractions/issues/537;'
$ git branch -M main
$ git remote add origin git@github.com:globalbioticinteractions/malavi.git <--- manually created malavi repo on github
$  git push -u origin main
$ travis enable --com <--- enable automated data reviews
$  travis open --com
``` 

Much more can be automated if needed/necessary, but having an easy way to create a GloBI index config is already much time saved. 

I'll keep this issue open until the data propagated to the GloBI search index.

**Comment by jhpoelen** [comment]
@qgroom PS A first review via travis-ci.com/globalbioticinteractions/malavi - 

```
Review of [globalbioticinteractions/malavi] included:
  - 11125 interaction(s)
  - 0 note(s)
  - 11125 info(s)

Hurray! [globalbioticinteractions/malavi] passed the GloBI review.
```

**Comment by jhpoelen** [comment]
hey Arctos friends @Jegelewicz @dustymc @campmlc , I couldn't help but noticing Arctos specimen being referenced in a GloBI-indexed dataset ```MalAvi: a public database of malaria parasites and related haemosporidians in avian hosts based on mitochondrial cytochromeblineages.``` See this issue for citation info and context.

I wish the authors were a little more explicit about the host specimen ids. Right now, it is hard for me to index them via GloBI. 

See also attached files for context and list. 
[malavi-arctos-specimen-ids.tsv.txt](https://github.com/globalbioticinteractions/globalbioticinteractions/files/5570554/malavi-arctos-specimen-ids.tsv.txt)
[malavi-arctos-references.tsv.txt](https://github.com/globalbioticinteractions/globalbioticinteractions/files/5570555/malavi-arctos-references.tsv.txt)


Here's the list of specimen ids: 

MSB:Bird:24491
MSB:Bird:24694
MSB:Bird:25188
MSB:Bird:37314
MSB:Bird:40434
MSB:Bird:40459
MSB:Bird:40460
MSB:Bird:40461
MSB:Bird:40753
MSB:Bird:40755
MSB:Bird:40757
MSB:Bird:40758
MSB:Bird:40761
MSB:Bird:40764
MSB:Bird:40765
MSB:Bird:40767
MSB:Bird:40769
MSB:Bird:40770
MSB:Bird:40773
MSB:Bird:40778
MSB:Bird:40785
MSB:Bird:41190
MSB:Bird:41191
MSB:Bird:41192
MSB:Bird:41194
MSB:Bird:41196
MSB:Bird:41198
MSB:Bird:41200
MSB:Bird:41206
MSB:Bird:41211
MSB:Bird:41212
MSB:Bird:41214
MSB:Bird:41216
MSB:Bird:41218
MSB:Bird:41220
MSB:Bird:41229
MSB:Bird:41232
MSB:Bird:41233
MSB:Bird:41234
MSB:Bird:41404
MSB:Bird:41406
MSB:Bird:41409
MSB:Bird:41415
MSB:Bird:41425
MSB:Bird:41426
MSB:Bird:41428
MSB:Bird:41431
MSB:Bird:41434
MSB:Bird:41439
MSB:Bird:43414
MSB:Bird:44109
MSB:Bird:44110
MSB:Bird:44111
MSB:Bird:44112
MSB:Bird:44114
MSB:Bird:44115
MSB:Bird:44118
MSB:Bird:44119
MSB:Bird:44121
MSB:Bird:47708
MSB:Bird:47709
MSB:Bird:47711
MSB:Bird:47719
MSB:Bird:47722
MSB:Bird:47725
MSB:Bird:47728
MSB:Bird:47731
MSB:Bird:47738
MSB:Bird:47740
MSB:Bird:47741
MSB:Bird:47742
MSB:Bird:47743
MSB:Bird:47744
MSB:Bird:47748
MSB:Bird:47753
MSB:Bird:47754
MSB:Bird:47756
MSB:Bird:47759
MSB:Bird:47761
MSB:Bird:47769
MSB:Bird:47774
MSB:Bird:47784
MSB:Bird:47785
MSB:Bird:47786
MSB:Bird:47788
MSB:Bird:47791
MSB:Bird:47792
MSB:Bird:47795
MSB:Bird:47801
MSB:Bird:47809
MSB:Bird:47812
MSB:Bird:47817
MSB:Bird:47820
MSB:Bird:47821
MSB:Bird:47824
MSB:Bird:47825
MSB:Bird:47833
MSB:Bird:47836
MSB:Bird:47838
MSB:Bird:47839
MSB:Bird:47843
MSB:Bird:47847
MSB:Bird:47851
MSB:Bird:47854
MSB:Bird:47858
MSB:Bird:47862
MSB:Bird:47865
MSB:Bird:47868
MSB:Bird:47874
MSB:Bird:47877
MSB:Bird:47883
MSB:Bird:47884
MSB:Bird:47890
MSB:Bird:47894
MSB:Bird:47895
MSB:Bird:47896
MSB:Bird:47897
MSB:Bird:47898
MSB:Bird:47900
MSB:Bird:47902
MSB:Bird:47905
MSB:Bird:47909
MSB:Bird:47910
MSB:Bird:47914
MSB:Bird:47917
MSB:Bird:47918
MSB:Bird:47919
MSB:Bird:47926
MSB:Bird:47927
MSB:Bird:47928
MSB:Bird:47930
MSB:Bird:47931
MSB:Bird:47936
MSB:Bird:47938
MSB:Bird:47939
MSB:Bird:47940
MSB:Bird:47941
MSB:Bird:47946
MSB:Bird:47947
MSB:Bird:47949
MSB:Bird:47952
MSB:Bird:47953
MSB:Bird:47956
MSB:Bird:47959
MSB:Bird:47961
MSB:Bird:47962
MSB:Bird:47964
MSB:Bird:47968
MSB:Bird:47970
MSB:Bird:47971
MSB:Bird:47975
MSB:Bird:47976
MSB:Bird:47978
MSB:Bird:47983
MSB:Bird:47985
MSB:Bird:47986
MSB:Bird:47988
MSB:Bird:47989
MSB:Bird:47992
MSB:Bird:48005
MSB:Bird:48006
MSB:Bird:48018
MSB:Bird:48020
MSB:Bird:48026
MSB:Bird:48032
MSB:Bird:48045
MSB:Bird:48061
MSB:Bird:48062
MSB:Bird:48065
MSB:Bird:48074
MSB:Bird:48075
MSB:Bird:48078
MSB:Bird:48080
MSB:Bird:48089
MSB:Bird:48095
MSB:Bird:48105
MSB:Bird:48107
MSB:Bird:48112
MSB:Bird:48114
MSB:Bird:48119
MSB:Bird:48129
MSB:Bird:48131
MSB:Bird:48132
MSB:Bird:48135
MSB:Bird:48142
MSB:Bird:48143
MSB:Bird:48144
MSB:Bird:48146
MSB:Bird:48150
MSB:Bird:48151
MSB:Bird:48152
MSB:Bird:48157
MSB:Bird:48161
MSB:Bird:48167
MSB:Bird:48172
MSB:Bird:48178
MSB:Bird:48180
MSB:Bird:48183
MSB:Bird:48185
MSB:Bird:48204
MSB:Bird:48205
MSB:Bird:48208
MSB:Bird:48218
MSB:Bird:48219
MSB:Bird:48221
MSB:Bird:48222
MSB:Bird:48224
MSB:Bird:48227
MSB:Bird:48229
MSB:Bird:48231
MSB:Bird:48236
MSB:Bird:48242
MSB:Bird:48245
MSB:Bird:48255
MSB:Bird:48259
MSB:Bird:48262
MSB:Bird:48263
MSB:Bird:48264
MSB:Bird:48265
MSB:Bird:48268
MSB:Bird:48275
MSB:Bird:48277
MSB:Bird:48291

**Comment by campmlc** [comment]
It looks like the haemosporidians have not yet been cataloged in MSB:Para, and therefore there are no host/parasite relationships yet for Globi to harvest. I have reached out to the collections staff to see when this process might be completed. 
Here are the records including the current host IDs:
https://arctos.database.museum/saved/MalAvi%20MSB%20Bird%20haemosporidians

**Comment by jhpoelen** [comment]
@campmlc great to see that data via a separate project, MalAvi has uncovered some connections-to-be-made in Arctos. Very exciting to see these connections getting made by you and your colleagues.

**Comment by jhpoelen** [comment]
A first pass at indexing MalAvi is now available via https://www.globalbioticinteractions.org/?accordingTo=globi%3Aglobalbioticinteractions%2Fmalavi&interactionType=ecologicallyRelatedTo . Also see attached screenshots. 

![Screenshot from 2020-11-23 14-39-32](https://user-images.githubusercontent.com/1084872/100023417-cbf4db00-2d99-11eb-928b-668cb934dc36.png)
![Screenshot from 2020-11-23 14-39-19](https://user-images.githubusercontent.com/1084872/100023419-cdbe9e80-2d99-11eb-8faf-00e75b0562e1.png)

So far about 11.1k interactions covering about 1.7k taxa with 99% names linked.
