### ISSUE TITLE
suggest to index United States Geological Survey Pollinators Library

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions#541]
As suggested by @neilcobb -

United States Geological Survey (USGS) Pollinator Library. https://www.npwrc.usgs.gov/pollinator . 

from their website: 

"
Mission

Pollinator declines have emphasized the need for a greater understanding of plant-pollinator networks and land management activities that improve pollinator habitat. The aim of the Pollinator Library is to support management and research of plant-pollinator systems by documenting, synthesizing, and disseminating information on flowers that are utilized by pollinators and other insects. We hope that by providing free access to essential information, the Pollinator Library will lead to an improved understanding of the foraging needs of flower-visiting insects and plant-pollinator systems.
"

**Comment by jhpoelen** [comment]
There a couple of data access methods:

1. downloading a xlsx sheet at http://www.npwrc.usgs.gov/pollinator/sites/default/files/site_files/Pollinator_Library_Visits_Dataset.xlsx 
2. creating custom queries and downloading a subset of all data

I attempted 2. to access all data by including all states that were available using download url:

https://www.npwrc.usgs.gov/pollinator/csv?pollinators=&plants=&states=4006%2C4046%2C3205%2C4009%2C4016%2C4041%2C4019%2C3996%2C4039%2C3186%2C4012%2C3194%2C4048%2C4037&land_use=

Unfortunately, their csv is malformed - they use comma's to list all folks that helped determine some bee/plant name, but do not escape the value, leading to a misalignment like:


Pollinator Library ID | Determined by | Order | Family | Genus | Species | Origin Facility | Date | Time | Collected By | Plant Order | Plant Family | Plant Genus | Plant Species | Land Use | State Collected | County Collected | Elevation (m) | Longitude | Latitude | Ave Wind Speed (km/h) | Air temperature (°C) | Relative Humidity (%) |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
01_1965WI_072 | Karl V. Krombien | Kenneth MacArthur | John T. Medler | Hymenoptera | Apidae | Apis | mellifera |   | 1962-07-17 | 00:00:00 | Lazarus W. Macior | Gentianales | Asclepiadaceae | Asclepias | incarnata | N/A | Wisconsin | Racine | 241 | 42.71 | -88.23 | 0 | 0 | 0
01_1965WI_073 | Karl V. Krombien | Kenneth MacArthur | John T. Medler | Hymenoptera | Apidae | Apis | mellifera |   | 1962-07-17 | 00:00:00 | Lazarus W. Macior | Gentianales | Asclepiadaceae | Asclepias | incarnata | N/A | Wisconsin | Racine | 241 | 42.71 | -88.23 | 0 | 0 | 0
01_1965WI_074 | Karl V. Krombien | Kenneth MacArthur | John T. Medler | Hymenoptera | Apidae | Apis | mellifera |   | 1962-07-17 | 00:00:00 | Lazarus W. Macior | Gentianales | Asclepiadaceae | Asclepias | incarnata | N/A | Wisconsin | Racine | 241 | 42.71 | -88.23 | 0 | 0 | 0

@neilcobb - do you know if this project is active and able to fix this issue? 

For now, I'll grab a static version of the xlsx .

For those that are listening: please do not publish data in xlsx format: it looks nice from the outside, but the data format is convoluted on the inside.

**Comment by neilcobb** [comment]
I have never corresponded with them but I will reach out by Monday and I can copy you if you want

**Comment by jhpoelen** [comment]
@neilcobb thanks for taking an effort to reach out to them. It would be nice to have an automated way to pull in their updates. 

Also note that a first review (see below) indexed 2327 interactions, not the 27k you expected. Note also that the date format they are using are ISO8601 compatible (e.g., ```20120517```) but not yet supported by GloBI. I've opened https://github.com/globalbioticinteractions/globalbioticinteractions/issues/542 to help track this enhancement. 

Reviewing [https://raw.githubusercontent.com/globalbioticinteractions/usgs-pollinator-library/master] using Elton version [0.10.3].
updating [local]... done.
creating review [local]... done.

Review of [globalbioticinteractions/usgs-pollinator-library] included:
  - 2327 interaction(s)
  - 4654 note(s)
  - 2327 info(s)

[globalbioticinteractions/usgs-pollinator-library] has 4654 reviewer note(s):
   1398 date [0009-01-01T00:00:00Z] occurred in the first century AD
   1350 date [0007-01-01T00:00:00Z] occurred in the first century AD
   1100 date [0008-01-01T00:00:00Z] occurred in the first century AD
    694 date [0006-01-01T00:00:00Z] occurred in the first century AD
     74 date [0005-01-01T00:00:00Z] occurred in the first century AD
     38 date [0004-01-01T00:00:00Z] occurred in the first century AD

**Comment by jhpoelen** [comment]
PS Note that the configuration to index the USGS Pollinator Library has been added via https://github.com/globalbioticinteractions/usgs-pollinator-library . Will close this issue once the changes propagate to https://globalbioticinteractions.org . 

@neilcobb thanks again for pointing out this resource - I hope that others will benefit from it.

**Comment by jhpoelen** [comment]
A first version of USGS pollinator library has been indexed by GloBI. 

@neilcobb thanks for the recommendation!

If only they'd publish their data in UTF-8 tsv/csv file . . . then no conversions from a messy xslx format would be necessary. 

fyi @seltmann 

![Screenshot from 2020-11-19 16-01-01](https://user-images.githubusercontent.com/1084872/99739077-ca1cd600-2a80-11eb-830f-cfd18636df0e.png)
![Screenshot from 2020-11-19 16-00-35](https://user-images.githubusercontent.com/1084872/99739078-cb4e0300-2a80-11eb-8706-f3d4ca5676be.png)

**Comment by neilcobb** [comment]
@jhpoelen @seltmann     Jorrit, You are amazing, you really do not give up.
