### ISSUE TITLE
The Sawflies (Symphyta) of Britain and Ireland

### ISSUE THREAD

**Issue by qgroom** [globalbioticinteractions/globalbioticinteractions#578]
I came across this website https://www.sawflies.org.uk/resources/
It includes a Spreadsheet of larval foodplants of these sawflies, which would be useful to index in GloBI,
https://www.sawflies.org.uk/wp-content/uploads/2019/04/Symphyta-larval-foodplants-latest-version.xlsx

**Comment by jhpoelen** [comment]
@qgroom thanks for sharing. I've created a first pass at schema mapping for the sawflies foodplants . 

If you get a chance, please review the schema mappings at https://github.com/globalbioticinteractions/sawflies/blob/main/globi.json#L19 and attached review report.

[sawflies-review.zip](https://github.com/globalbioticinteractions/globalbioticinteractions/files/5748405/sawflies-review.zip)

**Comment by jhpoelen** [comment]
for your convenience, here' the review summary - 

```
   _____ _       ____ _____   _____            _                
  / ____| |     |  _ \_   _| |  __ \          (_)               
 | |  __| | ___ | |_) || |   | |__) |_____   ___  _____      __ 
 | | |_ | |/ _ \|  _ < | |   |  _  // _ \ \ / / |/ _ \ \ /\ / / 
 | |__| | | (_) | |_) || |_  | | \ \  __/\ V /| |  __/\ V  V /  
  \_____|_|\___/|____/_____| |_|  \_\___| \_/ |_|\___| \_/\_/   
 | |           |  ____| | |                                     
 | |__  _   _  | |__  | | |_ ___  _ __                          
 | '_ \| | | | |  __| | | __/ _ \| '_ \                         
 | |_) | |_| | | |____| | || (_) | | | |                        
 |_.__/ \__, | |______|_|\__\___/|_| |_|                        
         __/ |                                                  
        |___/                                                   

reviewing [globalbioticinteractions/sawflies] using Elton version [0.9.1].

review of [globalbioticinteractions/sawflies] included:
  - 811 interaction(s)
  - 14 note(s)
  - 811 info(s)

[globalbioticinteractions/sawflies] has 14 reviewer note(s):
     14 source taxon name missing


If you'd like, you can generate your own review notes by:
  - installing GloBI's Elton via https://github.com/globalbioticinteractions/elton
  - running "elton update globalbioticinteractions/sawflies && elton review --type note,summary globalbioticinteractions/sawflies > review.tsv"
  - inspecting review.tsv

Please email info@globalbioticinteractions.org for questions/ comments.
````

**Comment by qgroom** [comment]
Looks good to me
Thanks!

**Comment by jhpoelen** [comment]
Thanks for reviewing . I am waiting for the sawfly larva foodplant associations to propagate to https://globalbioticinteractions.org before closing this issue.

**Comment by qgroom** [comment]
Thanks!!! It's a nice dataset that I can't imagine is easy to find elsewhere

**Comment by jhpoelen** [comment]
First pass at over 800 interaction indexed from "Andrew J Green. 2020. Larval Foodplants of British and Irish Sawflies. Accessed via https://www.sawflies.org.uk/wp-content/uploads/2019/04/Symphyta-larval-foodplants-latest-version.xlsx on 2020-12-28" is now available via https://globalbioticinteractions.org (see attached screenshots
). 

![Screenshot from 2021-01-04 14-17-02](https://user-images.githubusercontent.com/1084872/103585355-c8c03500-4e97-11eb-90d4-ede5616ba6f5.png)
![Screenshot from 2021-01-04 14-19-18](https://user-images.githubusercontent.com/1084872/103585425-e1304f80-4e97-11eb-86e1-4f0d027dacc2.png)
