### ISSUE TITLE
For those of you listenening to GloBI issues . . . here the santa hamster 

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions#579]
For those of you listening to GloBI issues . . . 

Thanks for your support and contributions and . . . as a sign of appreciation, I want to share a picture of this santa hamster with you . . .  

![santa-hamster](https://user-images.githubusercontent.com/1084872/103245707-d3b61b00-4915-11eb-815a-9d823351614b.jpeg)

**Comment by seltmann** [comment]
@jhpoelen santa hamster gives presents to ?

**Comment by jhammock** [comment]
eats: cookies and milk...

**Comment by jhpoelen** [comment]
indexing ...
