### ISSUE TITLE
discover co-roosting datasets for bats

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions#583]
related to discussion of https://globalbioticinteractions.org/covid19 groups - it appears that co-roosting are interactions of interest for bats. This suggests that including more support for discovering existing co-roosting datasets would be of benefit to ongoing bat-virus research questions.

Actions include:

1. use/introduce co-roosting term in Relations Ontology (cc @cmungall )
2. ask Nancy S. for paper references
3. contact BatBase folks for co-roosting data (cc @seemlesstaylor @rnbwspctrm)

possible related papers - 

https://bioone.org/journals/American-Museum-Novitates/volume-2016/issue-3870/3870.1/Roosting-Ecology-of-Amazonian-Bats--Evidence-for-Guild-Structure/10.1206/3870.1.short 

https://pubmed.ncbi.nlm.nih.gov/23378666/ - looks at this from the simplistic view of sympatry… the co-roosting data will take this to a new level

**Comment by jhpoelen** [comment]
Closest currently supporting RO term related to co-roosting appears to be http://purl.obolibrary.org/obo/RO_0008506 (ecologically co-occurs with). Added issue for help promote the introduction of the term into RO at https://github.com/oborel/obo-relations/issues/419 .

**Comment by jhpoelen** [comment]
A quick review of BatBase literature associated with (co-) roosting includes: (with number of reported interactions)

```
$ elton review globalbioticinteractions/batbase | grep roost | cut -f15 | jq --raw-output .context.referenceCitation | sort | uniq -c | sort -nr
creating review [globalbioticinteractions/batbase]... done.
     53 Lim, V., et al. 2018. Pollination implications of the diverse diet of tropical nectar-feeding bats roosting in an urban cave. PeerJ 6: e4572.
     25 Okon, E. E. 1974. Fruit bats at Ife: their roosting and food preferences. The Nigerian Field 39 (1): 33-40.
     16 Flanders, J. & G. Jones. 2009. Roost use, ranging behavior, and diet of greater horseshoe bats (Rhinolophus ferrumequinum) using a transitional roost. Journal of Mammalogy 90 (4): 888-896.
     13 Sanchez, R. & R. A. Medellín. 2007. Food habits of the threatened bat Leptonycteris nivalis (Chiroptera: Phyllostomidae) in a mating roost in Mexico. Journal of Natural History 41: 1753-1764.
     10 Salsamendi, E., et al. 2008. Diet and prey selection in Mehelyi’s horseshoe bat Rhinolophus mehelyi (Chiroptera, Rhinolophidae) in the south-western Iberian Peninsula. Acta Chiropterologica 10 (2): 279-286.
     10 Funmilayo, O. 1976. Diet and roosting damage and environmental pollution by the straw-coloured fruit bat in south-western Nigeria. The Nigerian Field 41 (3): 136 - 142.
      9 Andriafidison, D., et al. 2007. Diet, reproduction and roosting habits of the Madagascar free-tailed bat, Otomops madagascariensis Dorst, 1953 (Chiroptera: Molossidae). Acta Chiropterologica 9 (2): 445-450.
      7 Law, B. & A. Urquhart. 2000. Diet of the large-footed myotis Myotis macropus at a forest stream roost in northern New South Wales. Australian Mammalogy 22: 212-124.
      5 Morrison, D. W. 1980b. Foraging and day-roosting dynamics of canopy fruit bats in Panama. Journal of Mammalogy 61 (1): 20-29.
      4 Jacobs, D. S., R. M. Barclay & M. C. Schoeman. 2005. Foraging and roosting ecology of a rare insectivorous bat species, Laephotis wintoni (Thomas, 1901), Vespertilionidae. Acta Chiropterologica 17 (4): 101-109.
      4 Bonaccorso, F. J., et al. 2002. Home range of Dobsonia minor (Pteropodidae): a solitary, foliage-roosting fruit bat in Papua New Guinea. Biotropica 34 (1): 127-135.
```

some questions for BatBase stewards/developers: 

1. What is the difference between cohabitation and roosting ? 
2. And, is it try that, while cohabitation is a defined BatBase interaction type, but no interaction have yet been transcribed with the interaction?
3. What is your workflow for transcribing existing literature? Is there a way we can propose/ contribute to extracting co-roosting interactions from existing literature?

**Comment by arw36** [comment]
I believe there is a global effort to collect this info and cave-bat study information from original papers called "Darkside". I will see if I can find a link for that. I have a collection of ~200 co-roosting papers from a dormant review that I would be happy to contribute.

**Comment by jhpoelen** [comment]
@arw36 Nancy Simmons and batbase collaborators have started to do literature review and talking about ways to do the transcription workflows. Would you like to join for our regular weekly meetings and share your ideas / work on co-roosting and other data? Kendra P. has also joined in the recent past. See https://globalbioticinteraction.org/covid19 for meeting times. Alternatively, I can introduce you to Nancy and batbase folks by email. If you like that, please contact me via email listed on https://doi.org/10.1016/j.ecoinf.2014.08.005 . Looking forward!

**Comment by arw36** [comment]
Thanks for the invitation. I can join next week.

**Comment by jhpoelen** [comment]
@arw36 great! Looking forward to virtually meet you next wk.

**Comment by myrmoteras** [comment]
@mguidoti 

Can we set these publications up to add co-roosting metata and ultimately import again to BLR and hopefully have at this point some custom metadata on co-roosting
https://drive.google.com/drive/folders/0AI_SFqH1PljCUk9PVA$

I hope Nancy has the references for them so we do not have the extract them?!

Cheers
Donat

**Comment by nancybsimmons** [comment]
Here is a GoogleDoc for outlining definitions and search terms - https://docs.google.com/document/d/1HjpHVdoPw8MVeL7CWYjf8IqB57CjdWQspRns1eIr7rs/edit

**Comment by jhpoelen** [comment]
note that RO term "co-roosting" http://purl.obolibrary.org/obo/RO_0002801 has been introduced, and a dataset using the term has already been indexed by GloBI  (see https://github.com/oborel/obo-relations/issues/419#issuecomment-802177625) .

**Comment by myrmoteras** [comment]
@jhpoelen do we also have a term "roosting", because this term occurs in the literature and we could automate the annotation, probably right to adding this as custome metadata to treatments in BLR

**Comment by jhpoelen** [comment]
@myrmoteras the scope of this issue is to describe co-roosting associations between organisms. In this context, I imagine that habitatId/habitatName with terms from envo can be used (e.g., cave http://purl.obolibrary.org/obo/ENVO_00000067). Ex. Bat X co-roosts with Bat Y in a cave habitat .

**Comment by jhpoelen** [comment]
Closing this old issue - Aja Sherman and Cullen Geiselman have been continuing this work via https://github.com/globalbioticinteractions/bat-co-roosting-database.
