### ISSUE TITLE
Suggest to include bat host to bed bugs

### ISSUE THREAD

**Issue by qgroom** [globalbioticinteractions/globalbioticinteractions#587]
The following paper lists ten bat hosts to _Cimex lectularius_. It is perhaps a good candidate to be included in GloBI.

Balvín, O., Munclinger, P., Kratochvíl, L., & Vilímová, J. (2012). Mitochondrial DNA and morphology show independent evolutionary histories of bedbug Cimex lectularius (Heteroptera: Cimicidae) on bats and humans. Parasitology Research, 111(1), 457-469.
https://doi.org/10.1007/s00436-012-2862-5

http://web.natur.cuni.cz/~muncling/Balvin_2012.pdf

**Comment by jhpoelen** [comment]
@qgroom Thanks for sharing this pretty neat paper. Would you or someone else like to create a GloBI configuration for indexing this? Happy to help if needed.

**Comment by jhpoelen** [comment]
PS Why not index all articles of the journal "Parasitology Research" ?

**Comment by qgroom** [comment]
I'd be happy to do this paper, but indeed the whole of Parasitology Research would be better, but that's a lot of work! How would it be possible?

**Comment by jhpoelen** [comment]
@qgroom I had a peek at the bat-bedbug data and saw the data needs light manual transcription . Would be great if you or your colleagues could help transcribe this valuable dataset! I didn't realize that we might share bedbugs with bats . . . 

As far as indexing all the data in ```Parasitology Research``` : we'd have to reach out to the editors and publishers and convince them that their publications will be of higher quality and read more if they are indexed by the knowledge they contain instead of text matching on titles, abstract and keywords.

**Comment by qgroom** [comment]
The data has been transcribed and entered in the GloBI template. It also seems as though it has passed the Travis checks.
I'm happy to close this issue if you are.

**Comment by jhpoelen** [comment]
@qgroom thanks for preparing transcribing the bed bugs - bat - human records from Balvín, O., Munclinger, P., Kratochvíl, L., & Vilímová, J. (2012). Mitochondrial DNA and morphology show independent evolutionary histories of bedbug Cimex lectularius (Heteroptera: Cimicidae) on bats and humans. Parasitology Research, 111(1), 457-469.
https://doi.org/10.1007/s00436-012-2862-5 for indexing by GloBI via https://github.com/qgroom/bedbugs .

I'll share some notes with suggestions separately.

**Comment by jhpoelen** [comment]
Bedbugs data has been indexed via GloBI. See attached. 
![Screenshot from 2021-02-17 15-15-19](https://user-images.githubusercontent.com/1084872/108280474-1389c980-7133-11eb-89aa-9eb189f8c2a6.png)
