### ISSUE TITLE
Norwood Farm dataset

### ISSUE THREAD

**Issue by qgroom** [globalbioticinteractions/globalbioticinteractions#592]
Can I suggest another dataset to register with GloBI. 

Pocock, Michael J. O.; Evans, Darren M.; Memmott, Jane (2012), Data from: The robustness and restoration of a network of ecological networks, Dryad, Dataset, [https://doi.org/10.5061/dryad.3s36r118](https://doi.org/10.5061/dryad.3s36r118)

from Norwood Farm, Somerset, UK (51.3128N 2.3206W) during 2007 and 2008

I think GloBI would only be interested in the direct interactions in the dataset, but that is still 1501 interactions.

**Comment by jhpoelen** [comment]
@qgroom thanks for sharing. 

I've prepared an initial configuration to help index the Norwood Farm dataset at https://github.com/globalbioticinteractions/pocock2012 for your review.

It'd be great if you could help make sure that the interaction type mappings are suited. Also, I was wondering whether the "indirect" observations of ectoparasites etc. should be ignored or interpreted as "this ectoparasite is known to visits that plant".

Looking forward to your feedback.

**Comment by qgroom** [comment]
From the Readme.txt 

> Interactions that were not direct represent consumers of herbivores and their links to plants that would not otherwise be retained in the data. For example, it provides the information that parasitoid A was reared from an aphid on plant B. Counting the number of direct interactions gives the figure of 1501 reported in the paper.

In GloBI you would normal have two direct interactions to represent this

**Comment by qgroom** [comment]
The mapping looks fine

**Comment by jhpoelen** [comment]
Thanks for having a look! After your comments, I added eventDate, localityName, lat/lng to the index configuration. I wish more authors would include this valuable contextual information in the data tables. . . Also, following the readme.txt, I ignored all the indirect parasitic interactions by moving them to the interaction_types_ignored.csv table. 

@qgroom Do you want to do the honors to notify Michael Pocock that his farm data is getting indexed by GloBI  ?

**Comment by jhpoelen** [comment]
For completeness, here's the GloBI review generated using check-dataset.sh of https://github.com/globalbioticinteractions/globinizer . Note that only 1148 direct interaction were found. This number excludes the indirect parasitic interactions.



```
$ bash check-dataset.sh globalbioticinteractions/pocock2012
   _____ _       ____ _____   _____            _                
  / ____| |     |  _ \_   _| |  __ \          (_)               
 | |  __| | ___ | |_) || |   | |__) |_____   ___  _____      __ 
 | | |_ | |/ _ \|  _ < | |   |  _  // _ \ \ / / |/ _ \ \ /\ / / 
 | |__| | | (_) | |_) || |_  | | \ \  __/\ V /| |  __/\ V  V /  
  \_____|_|\___/|____/_____| |_|  \_\___| \_/ |_|\___| \_/\_/   
 | |           |  ____| | |                                     
 | |__  _   _  | |__  | | |_ ___  _ __                          
 | '_ \| | | | |  __| | | __/ _ \| '_ \                         
 | |_) | |_| | | |____| | || (_) | | | |                        
 |_.__/ \__, | |______|_|\__\___/|_| |_|                        
         __/ |                                                  
        |___/                                                   
Miller 5.3.0
s3cmd version 2.1.0
using local elton found at [/usr/local/bin/elton]

Review of [globalbioticinteractions/pocock2012] using Elton version [0.10.7] started at [2021-01-21T06:03:40-08:00].

Review of [globalbioticinteractions/pocock2012] included:
  - 1148 interaction(s)
  - 0 note(s)
  - 1734 info(s)

Hurray! [globalbioticinteractions/pocock2012] passed the GloBI review.

For detailed review results please see files in [/home/jorrit/proj/globi/data/pocock2012/review/globalbioticinteractions/pocock2012].



If you'd like, you can generate your own review notes by:
  - installing GloBI's Elton via https://github.com/globalbioticinteractions/elton
  - running "elton update globalbioticinteractions/pocock2012 && elton review --type note,summary globalbioticinteractions/pocock2012 > review.tsv"
  - inspecting review.tsv

Please email info@globalbioticinteractions.org for questions/ comments.
```

**Comment by qgroom** [comment]
That was quick!
Yes, I can let Michael know. I was emailing him about the data, which is how I found it.

**Comment by jhpoelen** [comment]
Pocock et al. 2012 Norwood Farm dataset has been indexed by GloBI available via https://www.globalbioticinteractions.org/?accordingTo=globi%3Aglobalbioticinteractions%2Fpocock2012&interactionType=interactsWith . See also attached images.
![Screenshot from 2021-01-28 11-25-59](https://user-images.githubusercontent.com/1084872/106188501-e3ff2700-615b-11eb-921b-73ac3e32969c.png)


![Screenshot from 2021-01-28 11-26-36](https://user-images.githubusercontent.com/1084872/106188484-dfd30980-615b-11eb-89df-2579a451e53d.png)
![Screenshot from 2021-01-28 11-26-11](https://user-images.githubusercontent.com/1084872/106188491-e1043680-615b-11eb-93c5-3e4bf35d4f42.png)
