### ISSUE TITLE
Suggestion to allow dataset search by DOI

### ISSUE THREAD

**Issue by qgroom** [globalbioticinteractions/globalbioticinteractions#593]
Before adding new data to GloBI it is important to know if GloBI already contains that dataset.
Also, there are other occasions where you might want to browse within a dataset.  Currently, the "any study or source" restriction on the GloBI online search doesn't really help that much.
Why not allow searching by DOI of the dataset?

**Comment by jhpoelen** [comment]
Thanks for sharing your idea to search by DOI! 

When a doi is provided, you should already be able to search interactions by their doi in the ```doi:10.123/345``` or ```https://doi.org/10.123/345``` via the accordingTo field.

**Comment by jhpoelen** [comment]
Here's an example query - 
https://www.globalbioticinteractions.org/?accordingTo=doi%3A10.5281%2Fzenodo.4435128&interactionType=interactsWith

See also attached screenshot. 

![Screenshot from 2021-01-20 11-39-13](https://user-images.githubusercontent.com/1084872/105225926-28fbdb80-5b14-11eb-95a9-9cdad26aedde.png)

Please let me know what you think would make it easier for others to realize these searches are possible and supported.

**Comment by qgroom** [comment]
OK, I didn't realize it was possible and obviously I had not tried hard enough.  Still a pointer to users that it is possible would be good, because in most cases when you try you will get nothing and you won't know if this is because the functionality doesn't exist or the DOI isn't included.

**Comment by jhpoelen** [comment]
@qgroom yes, I agree that a pointer to the search by DOI functionality would be good. Did you have anything specific in mind?

**Comment by qgroom** [comment]
The simplest thing would be to change "Any study or source", to "Any DOI, study or source". But as a naive user I would not know what to put in this field for a study or a source. Would it work with a title? If so "any DOI or title" might be better.

**Comment by jhpoelen** [comment]
@qgroom Just added a mention of searching by DOI on the basic GloBI search page. I am sure there's more that can be done, and please suggest UI design if you or others have ideas to improve the design. Also, pull requests and web ui developer help are more than welcome to make it easier to find species interactions claim. 

![Screenshot from 2021-02-10 14-31-45](https://user-images.githubusercontent.com/1084872/107581796-73212b80-6bad-11eb-9167-ae95b615e0a6.png)
