### ISSUE TITLE
suggest to index Willoughby, A.R.; Phelps, K.L.; PREDICT Consortium; Olival, K.J. A Comparative Analysis of Viral Richness and Viral Sharing in Cave-Roosting Bats. Diversity 2017, 9, 35. https://doi.org/10.3390/d9030035 

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions#599]
Kendra Phelps suggested to index:

Willoughby, A.R.; Phelps, K.L.; PREDICT Consortium; Olival, K.J. A Comparative Analysis of Viral Richness and Viral Sharing in Cave-Roosting Bats. Diversity 2017, 9, 35. https://doi.org/10.3390/d9030035

**Comment by jhpoelen** [comment]
hey @arw36 - let me know if you have any suggestions on how to best index your valuable datasets.

**Comment by arw36** [comment]
Hi, 

I am happy to assist with this. The two datasets from this paper would be bat-virus associations and co-roosting bat species. How would co-roosting be classified as an interaction? Simply "interacts with"? Idk if there is a habitat overlap? Both of the datasets are aggregated from the literature, so would it be more appropriate to load each original paper?

**Comment by jhpoelen** [comment]
hey @arw36 - thanks for your prompt reply.

> How would co-roosting be classified as an interaction? Simply "interacts with"? Idk if there is a habitat overlap? 

I was imaging to use co-occurs with (http://purl.obolibrary.org/obo/RO_0008506) and/or introduce a specific term co-roosting or co-habitation. The latter would be a more specific case of co-occurrence. See also #583 and https://github.com/oborel/obo-relations/issues/419 . Am open to ideas, especially because you have some pretty specific experience in capturing co-roosting claims from literature.


> Both of the datasets are aggregated from the literature, so would it be more appropriate to load each original paper?

I would imagine that original paper will be referenced to maintain the provenance of the virus-host or co-roosting claim. If needed, these papers can be re-visited for additional data extraction or review.

**Comment by arw36** [comment]
@jhpoelen Here is the first pass utilizing the co-occurs interaction. https://github.com/arw36/willoughby-etal-2017-roost-interactions

Does this interaction type automatically make the interaction bi-directional? My raw dataset was unidirectional, but then bi-directional through downstream code. Do I need to go in have duplicate pairs but in the opposite source/target to complete this bi-directionality? Thanks.

**Comment by jhpoelen** [comment]
Thanks for sharing! And yes, GloBI indexes both directions, so no need 
to duplicate the inverse.

PS I noticed that you used interaction term 
http://purl.obolibrary.org/obo/RO_0008506 "ecologically co-occurs with" 
. Is this because we don't have a "co-roosting" term yet? Or because 
this is the appropriate type according to your expert opinion?

**Comment by arw36** [comment]
Ok, thanks. I used that term simply as a place-holder until the co-roosting term is incorporated.

**Comment by jhpoelen** [comment]
@arw36 Here's a first glimpse of your co-roosting data as seen from GloBI's perspective. See attached screenshots from https://www.globalbioticinteractions.org/?accordingTo=globi%3Aarw36%2Fwilloughby-etal-2017-roost-interactions  

![Screenshot from 2021-02-22 11-12-05](https://user-images.githubusercontent.com/1084872/108757731-156ed680-74ff-11eb-9ce7-2f6050ec09c2.png)
![Screenshot from 2021-02-22 11-11-47](https://user-images.githubusercontent.com/1084872/108757737-16a00380-74ff-11eb-9650-4b861a2e2d30.png)

**Comment by arw36** [comment]
Very cool! Do you know why http://treatment.plazi.org/id/690487A5FFDFFF930EFFF9F0FDB6D299 doesn't appear as a species name? Is this an error in my data input?

**Comment by jhpoelen** [comment]
Are referring to records like https://www.globalbioticinteractions.org/?accordingTo=globi%3Aarw36%2Fwilloughby-etal-2017-roost-interactions&interactionType=ecologicallyRelatedTo&sourceTaxon=Myotis%20pilosus (see attached screenshot) ?
![Screenshot from 2021-02-22 11-23-07](https://user-images.githubusercontent.com/1084872/108758913-882c8180-7500-11eb-966e-c7c0fd7f20da.png)

**Comment by arw36** [comment]
Yes, looks like the species name is omitted. Instead, the link to taxonomic
hierarchy given?

**Comment by jhpoelen** [comment]
@arw36 just poked around a bit and reported a bug in the rendering of results on https://globalbioticinteractions.org (see https://github.com/globalbioticinteractions/globalbioticinteractions/issues/605) . As far as I can tell, this is not an issue on your end.

**Comment by jhpoelen** [comment]
@arw36 it looks like your interaction data are indexed as expected, closing issue.
