### ISSUE TITLE
Plants Eat Bees

### ISSUE THREAD

**Issue by seltmann** [globalbioticinteractions/globalbioticinteractions#607]
There are 242 interaction observations where the source and target are flipped and plants are eating, pollinating, or visiting bees. All of these are from a few citations. How can we provide corrections? It is valuable data. See full spreadsheet:

https://docs.google.com/spreadsheets/d/1IKYWkk7kH36dztcfqsMeRO50hUF4HCRBopBTqoWJStI/edit?usp=sharing

Global Web   Database (http://globalwebdb.com): an online collection of food webs.   Accessed via https://www.globalwebdb.com/Service/DownloadArchive on   2017-10-12.
--
http://iNaturalist.org is a place where you can record what you see in nature meet other nature lovers	 and learn   about the natural world.

Sarah E Miller. 6/19/2015. Species   associations manually extracted from datasets   https://www.nceas.ucsb.edu/interactionweb/resources.html.

Katja Schulz. 2020. Collection of refuted   species associations claims provided by Enclyclopedia of Life.

**Comment by jhpoelen** [comment]
@seltmann thanks for sharing these!

First, I'd recommend to publish a refutation dataset. You can do that by taking making a copy of your spreadsheet and flipping the argumentId to https://en.wiktionary.org/wiki/support and updating the referenceCitation to include something like "Seltman, K. 2021. Plants are unlikely consumers of bees."

Second, the last dataset by Schulz was actually a refutation dataset, and will be excluded in future interactions.tsv.gz to avoid confusion.

Third, at quick glance, the Global Web Database appears a data error: all the food web matrices are formatted in the same way, only this one appears to be incorrect. If you want to go the extra mile, you can contact the authors and notify them of the error.

Fourth, re: iNaturalist observations - if you are an iNaturalist user, you can review the related observations and strike up a conversation in the comments to try and persuade the authors to update their records.

Finally, Sarah Miller @millerse has made an immense amount of contributions, but has not been in touch. However, you can open an issue on their repository and describe the suspicious records.

If you feel ambitious, you can include corrected records in the refutation dataset in which the interaction records are flipped. This way, future users can enjoy the fruits of your labor without having to complete rely on authors to update their records. 

Thanks again for sharing your observations and suggestions and curious to hear your thoughts on your next steps.

**Comment by jhpoelen** [comment]
Here's an example of a flipped interaction in iNaturalist observation https://www.inaturalist.org/observations/30846063 - a bee's flower is visited by a habiscus plant. (see attached screenshots)

![Screenshot from 2021-02-24 17-58-04](https://user-images.githubusercontent.com/1084872/109091688-19028900-76ca-11eb-977e-34d70dd8ffd4.png)
![Screenshot from 2021-02-24 17-57-55](https://user-images.githubusercontent.com/1084872/109091692-1b64e300-76ca-11eb-9522-47b3cff9f769.png)

**Comment by jhpoelen** [comment]
@seltmann please comment/re-open this issue if you need more information on how to share a refutation dataset . I was thinking to create a template dataset for refutations, perhaps based on the existing refutation dataset https://github.com/globalbioticinteractions/refuted-interaction-data/blob/master/interactions.tsv .
