### ISSUE TITLE
Remove duplicate TPT repositories from SCAN RSS feed

### ISSUE THREAD

**Issue by seltmann** [globalbioticinteractions/globalbioticinteractions#610]
VertNet example of how to exclude collections from RSS feed: https://github.com/globalbioticinteractions/vertnet/blob/main/globi.json

Location of SCAN RSS feed:
https://github.com/globalbioticinteractions/scan/blob/main/globi.json

**Comment by seltmann** [comment]
List of collections to be excluded from the SCAN RSS feed: BYU,MSU,ANSP,UHIM,UTAH,UWSP

**Comment by seltmann** [comment]
@jhpoelen want to check?

```
{ 
  "format": "rss",
  "citation": "Symbiota Collections of Arthropods Network (SCAN)",
  "url": "https://scan-bugs.org:443/portal/webservices/dwc/rss.xml",
  "hasDependencies": false,
  "exclude": ".*BYU-BYUC.*,.*MSU-MSUC.*,.*ANSP-ENT.*,.*UHIM-UHIM.*,.*UTAH-PIPR.*,.*UWSP-PARA.*",
  "shouldResolveReferences": false
```
}

**Comment by jhpoelen** [comment]
@seltmann nice! Perhaps add parenthesis to make it easier to read? 

```json
{ 
  "format": "rss",
  "citation": "Symbiota Collections of Arthropods Network (SCAN)",
  "url": "https://scan-bugs.org:443/portal/webservices/dwc/rss.xml",
  "hasDependencies": false,
  "exclude": ".*(BYU-BYUC|MSU-MSUC|ANSP-ENT|UHIM-UHIM|UTAH-PIPR|UWSP-PARA).*",
  "shouldResolveReferences": false
}
```

**Comment by seltmann** [comment]
Modifications pushed to [https://github.com/globalbioticinteractions/scan/blob/main/globi.json](https://github.com/globalbioticinteractions/scan/blob/main/globi.json)
