### ISSUE TITLE
index Laura's Bat Handling Dataset

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions#611]
@qgroom can you point me to the bat handling observations?

**Comment by jhpoelen** [comment]
@qgroom another ping about Laura's bat handling observations. Please let me know if you have a list of observations or whether you've made manual annotations on the iNaturalist already (e.g., observation field "handled by: Homo sapiens")

**Comment by qgroom** [comment]
Hi Jorrit,
I missed the first ping
This is the spreadsheet  we have. It's quite crude.
https://docs.google.com/spreadsheets/d/1nX9EnLjKKVUHnv5Iwtcvwt8l-oc3qcytVxxPrPXk3Yc/edit?usp=sharing

**Comment by jhpoelen** [comment]
Thanks! How would you like this dataset to be cited?

**Comment by qgroom** [comment]
Laura first and me second, but after that I have no idea

**Comment by jhpoelen** [comment]
I've created a (preliminary) index configuration at https://github.com/globalbioticinteractions/jeucht2021 with citation:

Laura van der Jeught & Quentin Groom. 2021. Observations of humans handling bats with gloves or bare hands.

I imagine you might want to make your own index configuration at some point. If you do, please let me know and I can deprecate this one.

**Comment by jhpoelen** [comment]
See attached screenshot for indexing search .
![Screenshot from 2021-03-31 15-06-11](https://user-images.githubusercontent.com/1084872/113217361-af2e4f80-9232-11eb-867f-117c5d752523.png)
