### ISSUE TITLE
Character encoding of some iNaturalist records in GloBI don't seem to be UTF-8

### ISSUE THREAD

**Issue by qgroom** [globalbioticinteractions/globalbioticinteractions#612]
When processing some records  from GloBI I got into an encoding problem.
It seems that the name Иван Матершев is not encoded in UTF-8.

I suspect this is a problem inhertited from the iNaturalist data, but perhaps there is a way to catch this before it gets into GloBI.

See these records...
https://www.globalbioticinteractions.org/?accordingTo=https%3A%2F%2Fwww.inaturalist.org%2Fobservations%2F56669475&interactionType=interactsWith

**Comment by jhpoelen** [comment]
@qgroom Thanks for sharing! In firefox browser the Cyrillic characters seem to be rendered ok (see attached screenshot). Please let me know how to reproduce your encoding issue.

![Screenshot from 2021-03-02 10-34-23](https://user-images.githubusercontent.com/1084872/109697377-f8f81d00-7b42-11eb-919a-8610330b793b.png)

**Comment by qgroom** [comment]
Good question.
* load tab seperated snapshot of GloBI into a SQLite database (default UTF8)
* Access SQLite database with Python script
* Create a network in Python script using networkx
* output the network as a dot file using the networkx function write_dot()
* write_dot fails with an encoding problem, unless I use the Python function encode on the `sourceReference` string

As far as I can tell everything in this chain should be able to handle UTF-8

**Comment by jhpoelen** [comment]
Weird. In extracting the records from a recent snapshot tsv, no encoding issue appear:

```
curl "https://depot.globalbioticinteractions.org/snapshot/target/data/tsv/interactions.tsv.gz" | gunzip | grep -E "https://www.inaturalist.org/observations/56669475[^0-9]" > cyrillic.tsv.txt
```

See attached result.
[cyrillic.tsv.txt](https://github.com/globalbioticinteractions/globalbioticinteractions/files/6071280/cyrillic.tsv.txt)

**Comment by qgroom** [comment]
I thought it might be an issue with write_dot https://networkx.org/documentation/stable//_modules/networkx/drawing/nx_pydot.html

But it uses to_string which is default UTF8. I will have to dig deeper

**Comment by jhpoelen** [comment]
@qgroom ok thanks for sharing that you suspect the character encoding might be an issue with networkx's ```write_dot``` method. It appears that the source of the suspicious characters in not GloBI, so I am closing the issue for now. Please re-open / comment on the issue there's remaining issues.
