### ISSUE TITLE
First commit for tick records from the literature

### ISSUE THREAD

**Issue by seltmann** [globalbioticinteractions/globalbioticinteractions#617]
The tick data class at UCSB has prepared a first pass of recording the tick - host biotic interactions from:
Guglielmone AA, Petney TN, Robbins RG. Ixodidae (Acari: Ixodoidea): descriptions and redescriptions of all known species from 1758 to December 31, 2019. Zootaxa. 2020 Nov 5;4871(1): zootaxa.4871.1.1.

https://github.com/ParasiteTracker/tick-interaction-database

**Comment by jhpoelen** [comment]
@seltmann Nice! Thanks for sharing. The dataset should get automatically get reviewed and indexed in the next couple of days.

**Comment by jhpoelen** [comment]
GloBI has started indexing https://github.com/ParasiteTracker/tick-interaction-database . Please see attached screenshots of https://www.globalbioticinteractions.org/?accordingTo=globi%3AParasiteTracker%2Ftick-interaction-database&interactionType=ecologicallyRelatedTo . Please note that some review notes exists (see https://github.com/ParasiteTracker/tick-interaction-database/issues)
