### ISSUE TITLE
suggest to index: EDI Data Portal's Temporal variation in plant-pollinator interactions, Rocky Mountain Biological Laboratory, CO, USA, 2013 - 2015

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions#628]
@zedomel suggested to index: 

```json
{
  "key": "",
  "item_type": "",
  "pub_title": "",
  "pub_doi": "",
  "pub_year": "",
  "pub_abstract": "",
  "pub_keywords_subject": "",
  "pub_authors": "",
  "pub_journal": "",
  "data_repository_host_by": "EDI Data Portal",
  "structure_schema": "TABULAR/INTERACTION_RECORDS",
  "format": "DSV",
  "dataset_title": "Temporal variation in plant-pollinator interactions, Rocky Mountain Biological Laboratory, CO, USA, 2013 - 2015",
  "dataset_description": "These datafiles contain the plant-pollinator interaction data collected by Paul CaraDonna et al. at the Rocky Mountain Biological Laboratory in Gothic, CO, USA during the 2013, 2014 and 2015 growing season. These data were collected to investigate temporal variation in plant-pollinator interactions; specifically, these data were collected in a manner to allow for the construction of weekly plant-pollinator interaction networks in order to investigate fine scale temporal variation in plant-pollinator interactions. The data represent extensive community-wide field observations of animal pollinators visiting flowering plants in a subalpine ecosystem for the majority of the summer growing season (May–September).  ",
  "dataset_keywords": "",
  "dataset_year": 2020,
  "dataset_metadata_eml": "",
  "dataset_type": "plant-pollinator",
  "dwc_interaction_term": "",
  "dwc_interaction_term_values": "",
  "columns_keys": "",
  "columns_keys_to_dwc": "",
  "interactions_types": "visitsFlowerOf",
  "interactions_types_iris": "http://purl.obolibrary.org/obo/RO_0002622",
  "interaction_level": "species-species",
  "record_level": "species",
  "repo_url": "https://doi.org/10.6073/pasta/27dc02fe1655e3896f20326fed5cb95f",
  "dataset_url": "",
  "GloBI issue": "",
  "Notes": "",
  "GloBI URL": "",
  "relational model": "single"
}
```

**Comment by zedomel** [comment]
Same as in #633.
Species name contains `_` (underscore) instead of whitespace (` `).

**Comment by jhpoelen** [comment]
@zedomel thanks for sharing this pattern of folks using underscores instead of whitespaces. Like #633, rebuilding GloBI's Taxon Graph to include these names should link these names to their appropriate counterparts. 

PS Do you think GloBI should treat underscores as whitespaces by default ?

**Comment by jhpoelen** [comment]
@zedomel thanks for creating https://github.com/zedomel/caradonna2020 to help GloBI index  CaraDonna, P.J. 2020. Temporal variation in plant-pollinator interactions, Rocky Mountain Biological Laboratory, CO, USA, 2013 - 2015 ver 1. Environmental Data Initiative. https://doi.org/10.6073/pasta/27dc02fe1655e3896f20326fed5cb95f (Accessed 2021-04-16) !

A first pass at GloBI's indexing of the dataset can be found at:
https://www.globalbioticinteractions.org/?accordingTo=globi%3Azedomel%2Fcaradonna2020&interactionType=ecologicallyRelatedTo (see attached screenshot). 

Closing this issue and switching to https://github.com/zedomel/caradonna2020 specific issue to share/report improvement suggestions.

![Screenshot from 2021-04-19 12-48-25](https://user-images.githubusercontent.com/1084872/115294588-a207d080-a10d-11eb-80be-3e7447da085b.png)
