### ISSUE TITLE
suggest to index: Olito et al. 2015 . Species traits and abundances predict metrics of plant–pollinator network structure, but not pairwise interactions

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions#629]
@zedomel suggested to index:

```json
{
  "key": "K8KHHPZB",
  "item_type": "journalArticle",
  "pub_title": "Species traits and abundances predict metrics of plant–pollinator network structure, but not pairwise interactions",
  "pub_doi": "https://doi.org/https://doi.org/10.1111/oik.01439",
  "pub_year": 2015,
  "pub_abstract": "Plant–pollinator mutualistic networks represent the ecological context of foraging (for pollinators) and reproduction (for plants and some pollinators). Plant–pollinator visitation networks exhibit highly conserved structural properties across diverse habitats and species assemblages. The most successful hypotheses to explain these network properties are the neutrality and biological constraints hypotheses, which posit that species interaction frequencies can be explained by species relative abundances, and trait mismatches between potential mutualists respectively. However, previous network analyses emphasize the prediction of metrics of qualitative network structure, which may not represent stringent tests of these hypotheses. Using a newly documented temporally explicit alpine plant–pollinator visitation network, we show that metrics of both qualitative and quantitative network structure are easy to predict, even by models that predict the identity or frequency of species interactions poorly. A variety of phenological and morphological constraints as well as neutral interactions successfully predicted all network metrics tested, without accurately predicting species observed interactions. Species phenology alone was the best predictor of observed interaction frequencies. However, all models were poor predictors of species pairwise interaction frequencies, suggesting that other aspects of species biology not generally considered in network studies, such as reproduction for dipterans, play an important role in shaping plant–pollinator visitation network structure at this site. Future progress in explaining the structure and dynamics of mutualistic networks will require new approaches that emphasize accurate prediction of species pairwise interactions rather than network metrics, and better reflect the biology underlying species interactions.",
  "pub_keywords_subject": "",
  "pub_authors": "Olito Colin;Fox Jeremy W.",
  "pub_journal": "Oikos",
  "data_repository_host_by": "Dryad",
  "structure_schema": "TABULAR/INTERACTION_RECORDS",
  "format": "DSV",
  "dataset_title": "Data from: Species traits and abundances predict metrics of plant–pollinator network structure, but not pairwise interactions",
  "dataset_description": "Plant–pollinator mutualistic networks represent the ecological context of foraging (for pollinators) and reproduction (for plants and some pollinators). Plant–pollinator visitation networks exhibit highly conserved structural properties across diverse habitats and species assemblages. The most successful hypotheses to explain these network properties are the neutrality and biological constraints hypotheses, which posit that species interaction frequencies can be explained by species relative abundances, and trait mismatches between potential mutualists respectively. However, previous network analyses emphasize the prediction of metrics of qualitative network structure, which may not represent stringent tests of these hypotheses. Using a newly documented temporally explicit alpine plant–pollinator visitation network, we show that metrics of both qualitative and quantitative network structure are easy to predict, even by models that predict the identity or frequency of species interactions poorly. A variety of phenological and morphological constraints as well as neutral interactions successfully predicted all network metrics tested, without accurately predicting species observed interactions. Species phenology alone was the best predictor of observed interaction frequencies. However, all models were poor predictors of species pairwise interaction frequencies, suggesting that other aspects of species biology not generally considered in network studies, such as reproduction for dipterans, play an important role in shaping plant–pollinator visitation network structure at this site. Future progress in explaining the structure and dynamics of mutualistic networks will require new approaches that emphasize accurate prediction of species pairwise interactions rather than network metrics, and better reflect the biology underlying species interactions.",
  "dataset_keywords": "",
  "dataset_year": 2015,
  "dataset_metadata_eml": "",
  "dataset_type": "plant-pollinator",
  "dwc_interaction_term": "",
  "dwc_interaction_term_values": "",
  "columns_keys": "",
  "columns_keys_to_dwc": "",
  "interactions_types": "visitsFlowerOf",
  "interactions_types_iris": "http://purl.obolibrary.org/obo/RO_0002622",
  "interaction_level": "occurrence-occurrence",
  "record_level": "occurrence",
  "repo_url": "https://doi.org/10.5061/dryad.7st32",
  "dataset_url": "",
  "GloBI issue": "",
  "Notes": "",
  "GloBI URL": "",
  "relational model": "single"
}
```

**Comment by zedomel** [comment]
@jhpoelen 

this dataset is a XLS file with multiple sheets in the same document. Is there a way to guide GloBI to use a specific sheet of the document (in this case **Raw Data**)?

**Comment by jhpoelen** [comment]
No explicit guide . . . but we can make one!

Here's what I usually do:

1. export sheet at a tab-separated, UTF-8 encoded file
2. add the exported file to the GloBI configuration repository
3. document the steps in the readme of the GloBI configuration repository to export the xls to tsv

If you'd prefer utf-8 csv, that is ok too. Perphaps easier because many folks and their tools get confused in dealing with "pure" iana tab-separated files. https://www.iana.org/assignments/media-types/text/tab-separated-values .

Note that I am stubbornly refusing to support "scented" (e.g., mixing presentation with data model) xls tables as a way to deter folks from publishing their data in this messy proprietary data format. Perhaps I should reconsider - curious to hear your thoughts on that.

**Comment by zedomel** [comment]
I did exactly that (export to TSV and documented it in README.md).

A repository was created at [zedomel/olito2015](https://github.com/zedomel/olito2015), but it is falling due some missing `targetTaxonName`'s. Please, see  [https://github.com/zedomel/olito2015/issues/1](https://github.com/zedomel/olito2015/issues/1).

Now, about the XLS tables I share the same opinion as you. I prefer the open source file formats, and people should be "forced" to share data using these file formats. 

I will continue the work with the datasets, and after that, we could have an ideia of how many datasets were published using proprietary file formats (e.g. XLS, XLSX, PDF). I think we will a better view of if this need.

thks.

**Comment by jhpoelen** [comment]
Thanks for liberating the data from the xls sheet ; ) 

Some notes:

1. if you use sourceTaxonSpecies instead of sourceTaxonName , elton has enough information to pick the most specific taxon name. Same for targetTaxonName. So, if the taxon rank of the column is fixed, I try to map it to a taxon rank specific column.
2. for readme.md - for the badges to work, please make sure to include the [user] or [org] name of the github repository when running ```elton init .... [username]/[repo name]``` so instead of ```elton init ... olito2015``` try ```elton init ... zedomel/olito2015``` . Suggest to manually fix the readme.md links from ```globi:olito2015``` -> ```globi:zedomel/olito2015``` . Similar with the travis link.

I am glad that you share the same sentiment about the xsl(x) formats. I hope that publishers will also start to see the benefits of straight text files like csv/tsv and no longer accept xls files as supplements / attachments.

I hope that these comments are helpful to you.

**Comment by jhpoelen** [comment]
@zedomel thanks for adding your index configuration for Olito et al. 2015 at https://github.com/zedomel/olito2015 . A first version of the dataset has been indexed by GloBI. Further improvements can be made if needed (I've already proposed some improvements via pull requests).

See attached screenshot of results retrieved via https://www.globalbioticinteractions.org/?accordingTo=globi%3Azedomel%2Folito2015&interactionType=ecologicallyRelatedTo .
![Screenshot from 2021-04-15 15-36-10](https://user-images.githubusercontent.com/1084872/114946623-5c42c380-9e00-11eb-9a3a-860b5b179971.png)
