### ISSUE TITLE
stomach contents data from VertNet

### ISSUE THREAD

**Issue by ahhurlbert** [globalbioticinteractions/globalbioticinteractions#63]
Predator prey links could be pulled out of VertNet.org. The DynamicProperties field of the Darwin Core often contains a phrase "stomach contents:" or "stomach contents=" followed by prey items.

I assume it would be straightforward to pull all of this info out through their API.

**Comment by jhpoelen** [comment]
Now indexing dynamic property values with "stomach content" via https://github.com/globalbioticinteractions/globalbioticinteractions/commit/d6d156aae577d486e6f5f76337f9d2940e7665cf
