### ISSUE TITLE
add pre-packaged sqllite database to https://globalbioticinteractions.org/data 

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions#639]
as suggested by @qgroom

**Comment by jhpoelen** [comment]
Hey @qgroom - 

turns out you can easily create a sqlite database from a csv file. I've added some instructions on the https://globalbioticinteractions.org/data page:

name | description
-- | --
sqlite, the most used database engine in the world. | create a sqlite3 database using: cat interactions.csv.gz \| gunzip \| sqlite3 -csv globi.db '.import /dev/stdin interactions' . If you’d like to reduce your database size, you can drop columns before importing them using powertools like cut or mlr/miller.

Also see attached screenshot.
![Screenshot from 2021-03-24 17-15-10](https://user-images.githubusercontent.com/1084872/112400039-af739b80-8cc4-11eb-836f-38621f3d3ffc.png)

Please comment/re-open if this is not sufficient to address this issue.

**Comment by qgroom** [comment]
Cool! I think I tried import, but I ran out of memory, however, my son has upgraded my machine's memory, so it might work.

**Comment by jhpoelen** [comment]
@qgroom let me know how it goes! I imagine that sqlite doesn't keep it entire database in memory, but I might be wrong . . .
