### ISSUE TITLE
virus names are losing integrity

### ISSUE THREAD

**Issue by cjcarlson** [globalbioticinteractions/globalbioticinteractions#640]
Hey gang - there are two viruses in the dataset that are stored incorrectly in a way that makes me think you have a string being dropped somewhere. West Nile virus is recorded as West virus, and Ross River virus as Ross virus, and both are linked to EOL_V2, so it's probably a fairly contained issue.

**Comment by jhpoelen** [comment]
@cjcarlson thanks for sharing. Where exactly did you see the suspicious West Nile virus -> West virus and Ross River virus -> Ross virus mappings? In the web ui?

**Comment by cjcarlson** [comment]
https://www.globalbioticinteractions.org/?interactionType=interactsWith&targetTaxon=west%20virus

yes

**Comment by jhpoelen** [comment]
@cjcarlson thx. hoping to have a look soon.

**Comment by jhpoelen** [comment]
@cjcarlson thanks to your specific feedback I was able to create a patch to the taxonomic name mapping. Related publications:

Poelen, Jorrit H. (2021). Global Biotic Interactions: Taxon Graph Patches (Version 0.7) [Data set]. Zenodo. http://doi.org/10.5281/zenodo.4655153

Poelen, Jorrit H. (2021). Global Biotic Interactions: Taxon Graph (Version 0.3.31) [Data set]. Zenodo. http://doi.org/10.5281/zenodo.4655150

Keeping issue open until changes have propagated in a day or so.

Thanks again for taking the time to report this name mapping issue.

**Comment by cjcarlson** [comment]
thanks Jorrit!
