### ISSUE TITLE
suggest to index: Middleton, O.S, Svensson, H, Scharlemann, J.P.W, Faurby, S, Sandom, C.J. CarniDIET 1.0: A database of terrestrial carnivorous mammal diets. Global Ecology and Biogeography. https://doi.org/10.1111/geb.13296.

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions#642]
suggest to index:
Middleton, O.S, Svensson, H, Scharlemann, J.P.W, Faurby, S, Sandom, C.J. CarniDIET 1.0: A database of terrestrial carnivorous mammal diets. Global Ecology and Biogeography. https://doi.org/10.1111/geb.13296.

also see https://github.com/osmiddleton/CarniDIET-Database @osmiddleton .

**Comment by jhpoelen** [comment]
@osmiddleton - congratulations on your recent 2021 publication on CarniDIET in Global Ecology and Biogeography. 

Today, I took a look at your rich and extensive database on carnivores, and I have some questions:

1. what is the character encoding for the main csv file? I tried to read the csv as UTF-8 and found that some of the special characters in the source references looked funny. E.g., ```Zamani, Navid, et al. "Predation of montane deserts ungulates by Asiatic cheetah Acinonyx jubatus venaticus in Central Iran."�Folia Zoologica�66.1 (2017): 50-57.``` . Note the �'s.
2. for columns ```scientificNamePrey``` and ```scientificNameCarni```, underscores are used to connect the genus and specific epithet. However, in other fields like ```commonNamePrey``` whitespaces are used. Is there a specific reason for including the underscore?
3. for the primary sources, you parsed out the author, year, title and journal. Would you happen to have associated DOIs? 

I have some other questions, but these are the ones that were on the top of the list. 

Thanks for compiling and sharing such a rich resource on carnivore diets,

-jorrit

PS I created a configuration for CarniDIET to be indexed by GloBI (Global Biotic Interactions) at https://github.com/globalbioticinteractions/CarniDIET-Database . Would you be interested in a pull request to add globi.json (GloBI's config file) to your main repository?

**Comment by osmiddleton** [comment]
Hi Jorrit, 

Thanks for getting in touch about CarniDIET and glad you're interested in it.

1.	The character encoding is currently ANSI. The � in the example highlighted should just be whitespaces so I’m surprised to see them appear.
2.	Species scientific names have an underscore to make it directly relatable to the PHYLACINE database (https://github.com/MegaPast2Future/PHYLACINE_1.2). This was a database constructed by one of my co-authors, Soren Faurby, and an invaluable database for macroecological research with mammals. Common names did not as there was no specific reason to add an underscore.
3.	Unfortunately, we did not include DOIs here. It’s really something we should have realised and added for the first release and will aim to incorporate in the future. 
PS. Absolutely, feel free to do so. Contributing to the GloBI dataset would be great.

Feel free to ask any further questions you have with the dataset. 

Owen

**Comment by jhpoelen** [comment]
hey Owen @osmiddleton - 

Thanks for your prompt reply and for providing the background information. 

Re: funny characters - it turns out that the � characters are not regular white spaces, but a non-breaking space (unicode character ```\xa0```). Perhaps these got in the file by copy-pasting ```&nbsp;``` from some html. 

In commit https://github.com/globalbioticinteractions/CarniDIET-Database/commit/ddafdc8caeca3ab1a09a30774ef4afaf4acf8fd0 , I've replace the ```\xa0``` characters with regular white spaces. This makes the funny � disappear.

**Comment by jhpoelen** [comment]
Initial version of CarniDIET has been indexed by GloBI (see attached and https://www.globalbioticinteractions.org/?accordingTo=globi%3Aglobalbioticinteractions%2FCarniDIET-Database&interactionType=ecologicallyRelatedTo )
![Screenshot from 2021-04-06 10-56-40](https://user-images.githubusercontent.com/1084872/113756992-f00ce500-96c6-11eb-9258-e772eb45fa02.png)

**Comment by osmiddleton** [comment]
Hi Jorrit, 

Thanks for this, great to see CarniDIET being utilised in this way.

I've also merged the pulled request. Thanks a lot for tidying it up! :) 

Owen
