### ISSUE TITLE
targetTaxonSpeciesNames vs targetTaxonName

### ISSUE THREAD

**Issue by seltmann** [globalbioticinteractions/globalbioticinteractions#645]
@jhpoelen what is the difference between the targetTaxonSpeciesNames and targetTaxonName in the interactions.tsv/csv download of all GloBI data?

**Comment by jhpoelen** [comment]
@seltmann targetTaxonSpeciesName is the name of a target species. targetTaxonName is the name of the most granular name. So, if a target is classified on a family level, the taxonTaxonName will be the family name and the taxonTaxonSpeciesName is empty.

**Comment by seltmann** [comment]
Thank you for clarifying!
