### ISSUE TITLE
add support for [http://purl.obolibrary.org/obo/RO_0002303] has habitat

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions#647]
related to https://github.com/AgentschapPlantentuinMeise/ashForestInteractions/issues/2 .

**Comment by qgroom** [comment]
I support this addition. In our case we want to indicate when birds use particular types of trees as nest sites (also relevant to bats!) and when lichens are specific to particular tree species. However, in the case of lichens case "epiphyte of" http://purl.obolibrary.org/obo/RO_0008501 is more appropriate.

It seems "host of" is often used as a substitute, such as https://www.globalbioticinteractions.org/?interactionType=interactsWith&sourceTaxon=Chelonibia%20testudinaria
However, this is not really appropriate as all of the RO subcategories of "host of" are parasitic relationships.

**Comment by jhpoelen** [comment]
@qgroom thanks for sharing your support and context. I've added to RO term to be included in the list of indexed GloBI terms. Please all for some time for the newly supported terms to propagate in GloBI indexes and upcoming Elton releases. 

For this listening/reading - note that this improvement is (yet another) example of the value of GloBI facilitated data reviews. 

e.g., from https://travis-ci.com/github/AgentschapPlantentuinMeise/ashForestInteractions/jobs/496958495#L226

```
[AgentschapPlantentuinMeise/ashForestInteractions] has 630 reviewer note(s):
    573 found unsupported interaction type with id: [http://purl.obolibrary.org/obo/RO_0002303] and name: [has habitat]
     30 found unsupported interaction type with id: [http://purl.obolibrary.org/obo/RO_0002226] and name: [develops in]
     21 found unsupported interaction type with id: [http://purl.obolibrary.org/obo/RO_0002559] and name: [causally influenced by]
      3 found unsupported interaction type with id: [http://purl.obolibrary.org/obo/RO_0002457] and name: [acquires nutrients from]
      2 found unsupported interaction type with id: [http://purl.obolibrary.org/obo/RO_0002457] and name: [Saproxylic]
      1 found unsupported interaction type with id: [http://purl.obolibrary.org/obo/RO_0002624] and name: [lays eggs in]
```
