### ISSUE TITLE
Mojave Desert Tortoise (Gopherus agassizi) 

### ISSUE THREAD

**Issue by aeiche01** [globalbioticinteractions/globalbioticinteractions#664]
![Desert tortoise interactions](https://user-images.githubusercontent.com/52542874/118568567-1aca6e80-b746-11eb-987a-b0cedd470440.png)

I wanted to pass along this link to a paper that followed Mojave Desert Tortoises around and documented what they were eating. Should flesh out more of the known consumptive interactions from this species (there's only one documented tortoise-plant consumptive interaction on the website). Figure 3 has the data required (attached here).

Paper is: C. Richard Tracy, K. E. Nussear, T. C. Esque, K. Dean-Bradley, C. R. Tracy, L. A. DeFalco, K. T. Castle, L. C. Zimmerman, R. E. Espinoza, A. M. Barber, The importance of physiological ecology in conservation biology, Integrative and Comparative Biology, Volume 46, Issue 6, December 2006, Pages 1191–1205, https://doi.org/10.1093/icb/icl054

Link is https://academic.oup.com/icb/article/46/6/1191/719526?login=true

**Comment by jhpoelen** [comment]
@aeiche01 thanks for sharing. I can see that adding these Mojave Desert Tortoise (_Gopherus agassizi_) diet data would help to not only get easier access to what we know about these fascinating creatures, but also help raise awareness for the Tracy et al. 2006 publication.  

Would you happen to have access to the "raw" data referenced in the phrase from Tracy et al. 2006:

>  [...] A total of 22 140 bites were observed being taken by 13 tortoises in June of 1991.[...]

?

If not, please let me know if you have willing and able to help transcribe this valuable data.

**Comment by aeiche01** [comment]
I don't have access to the raw data, but I think my advisor knows one of authors of the paper. I can ask him if he would reach out and ask for the raw data.

I'd be happy to help transcribe it! Would you want me to take figure 3 and turn it into a table?

**Comment by jhpoelen** [comment]
@aeiche01 Glad to hear that you might have some connections to the paper. If their raw data is unavailable, transcribing table 3 into a table would be wonderful. 

Perhaps you can use https://github.com/globalbioticinteractions/template-dataset , https://github.com/globalbioticinteractions/light2019 (uses linked google sheets table) or https://github.com/seltmann/bee-interaction-database as inspiration. 

Happy to help if needed.

**Comment by aeiche01** [comment]
[Desert tortoise interactions.xlsx](https://github.com/globalbioticinteractions/globalbioticinteractions/files/6504482/Desert.tortoise.interactions.xlsx)
Here's an excel document with the consumptive interactions highlighted from figure 3. I hope this is enough information! I'll pass along any raw data if I'm also able to obtain that.

**Comment by jhpoelen** [comment]
@aeiche01 Look great! 

One minor comment is to use ISO8601 (https://en.wikipedia.org/wiki/ISO_8601) for date ranges. 

So, instead of: 

```May-June 1991```

Suggest to say:

```1991-05/1991-06```

Also, how would you like your dataset to be cited? 

E.g.,

```[Your last name, your firstnames]. 2021. Manually transcribed Mojave Desert Tortoise (Gopherus agassizi) interaction records.```

**Comment by jhpoelen** [comment]
Note that the original Tracy et al. 2006 reference would appear along with your dataset citation.

**Comment by aeiche01** [comment]
[Desert tortoise interactions.xlsx](https://github.com/globalbioticinteractions/globalbioticinteractions/files/6504708/Desert.tortoise.interactions.xlsx)

Here's the corrected version!

My name is Eichenwald, Adam Jacob.

**Comment by jhpoelen** [comment]
Thanks! I've prepared a GloBI configuration to index your dataset at https://github.com/globalbioticinteractions/eichenwald2021 for your review.

If you'd like to add/update records, and need help creating updates via github, please don't hesitate to reach out. Happy to help.

Your records should be available in a couple of days.

**Comment by jhpoelen** [comment]
Thanks to @aeiche01 ,  GloBI now indexed a Mojave Desert Tortoise (Gopherus agassizi) diet study . See attached screenshot related to https://www.globalbioticinteractions.org/?accordingTo=globi%3Aglobalbioticinteractions%2Feichenwald2021&interactionType=interactsWith . 

![Screenshot from 2021-05-21 16-42-45](https://user-images.githubusercontent.com/1084872/119207659-ca0f8a00-ba53-11eb-9b20-33a2a5f07154.png)

![Screenshot from 2021-05-21 16-45-38](https://user-images.githubusercontent.com/1084872/119207723-18248d80-ba54-11eb-9b25-b6daed65332c.png)

Looks like the tortoise is a herbivore ; )

Note that some plant names have not yet been matched by GloBI - the matches are updated on the next GloBI taxon graph release (for more info see https://globalbioticinteractions.org/process.
