### ISSUE TITLE
suggest to index SCAN's Bee Pollinator project list

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions#666]
@neilcobb mentioned SCAN's (https://scan-bugs.org) Bee Pollinator project list, a potential list of interest for GloBI indexing.

> I created a new category in SCAN “bee-pollinator projects https://scan-bugs.org/portal/collections/index.php . The Oregon Bee atlas is served on GBIF, so how do you keep up with datasets created on GBIF?  Do you capture all the PLAZI datasets? The Oregon Bee Atlas also used “forage on” but I did not see that term in the GLoBI dropdown.  My guess is that is it synonymous with “visits flowers of”.   You are welcome to grab any of the data sets, I do not think you have https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=280 , https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=278 neither of withich is on GBIF yet and they have floral data

**Comment by neilcobb** [comment]
@jhpoelen  

Hey Neil - 
Thanks for sharing the list of bee-pollinator projects you compiled.
Would it be an idea to have GloBI index each of the referenced datasets ? 
Anticipating the answer is "yes", I created the eerily numbed new issue: https://github.com/globalbioticinteractions/globalbioticinteractions/issues/666 . Is this an omen? And, custom interaction type mappings can be defined to help support your suggested "forage on" -> "visits flower of" interpretation. If you feel forage 
And, GloBI does not index all of GBIF, although José Augusto Salim already has successfully done experiments in combining preston with elton (see https://github.com/zedomel/globi-dwca-index) to index interactions all of iDigBio/GBIF/BioCASe. 
Currently, specific RSS feeds or individual dwca endpoints are configured for GloBI indexing. E.g., https://github.com/globalbioticinteractions/scan and https://github.com/globalbioticinteractions/msb-para .
Also, note that the GloBI dropdown does not include all supported terms. Perhaps better is to use http://www.ontobee.org/search?ontology=RO&keywords=visits&submit=Search+terms . And, finally, if you feel a new term should be added to the Relation Ontology, your can propose new terms (see e.g., https://github.com/oborel/obo-relations/issues/419) directly. Happy to help if you or your collaborators get stuck. 
Hope this helps, and let me know how you intend to use the bee-pollinator data to help inform how to best leverage GloBI indexing/review capabilities. 
thx,
-jorrit

Jorrit,

This all looks good and I will look this over tomorrow or Friday.  It is helpful to see how the pieces fit.  Right now I do not have a clue how to leverage GLoBI, but I am confident that one or more options will surface over the coming weeks. I need to see the recording of the TPT GLoBI presentation for starters.

**Comment by jhpoelen** [comment]
@neilcobb I happened to stumble across https://www.gbif.org/dataset/f1a4ce9a-97cd-4d35-bf5e-561f2f1c6d91  Xerces Society - Bumble Bee Watch , which reminded me of your clever list of Bee Pollinators on SCAN (see attached screenshot of https://scan-bugs.org/portal/collections/index.php .

I was hoping to help index these datasets. Do you happy to have an RSS feed, or other programmatic method, to list all related resources to be indexed? I was unable to find the all the mentioned projects in the public scan RSS feed at https://scan-bugs.org:443/portal/webservices/dwc/rss.xml .

Thanks for putting this list together, and I hope to re-use your work to make it easier to find datasets that document bee-plant interactions.

![Screenshot from 2021-05-26 12-44-09](https://user-images.githubusercontent.com/1084872/119721777-6359ea00-be20-11eb-89bc-10f79bffd698.png)

**Comment by neilcobb** [comment]
@jhpoelen  If they are not in the public RSS feed then I would have obtained the data through an IPT, most likely GBIF but maybe Canadensys.  I am still working on the four new studies, I wanted them set up on GBIF in the process but I guess I could first put them on the RSS feed first.

Fingers crossed that we will get 70k more association records by next month.

Cheers,
Neil

**Comment by jhpoelen** [comment]
Great to hear that you are making progress. I am not quite sure how to proceed. Are you planning to use the associations for some internal projects first, or is the collection of collections already meant to be used /indexed by external projects like GloBI ?

**Comment by neilcobb** [comment]
It was set up for the bee monitoring group,  Brianne Du Clos <brianne.duclos@ucr.edu> will help add collections. Also hoping that these will be test cases to include in RCN proposal that I still hope to launch in July, will include you

**Comment by jhpoelen** [comment]
@neilcobb thanks for sharing the context and fingers crossed for some room to help show the wealth of bee interaction data in existing collection data.

**Comment by jhpoelen** [comment]
@neilcobb I spent some time with your bee pollination list and found the referenced data only partly accessible, at least those with associations that GloBI understand and is able to access.

The bulk of these interactions came from  ```Xerces Society - Bumble Bee Watch - Version 1.9``` (~ 14k associations). Other datasets appear to have been transcribed manually, and not publicly available. I'd be great to have a way to make these data accessible, so that others don't have to redo the valuable work you've done. 

As the Xerces Society data is available via USGS BISON data, I've opted to index the USGS BISON IPT instead of trying to reverse engineer the SCAN lists. See https://github.com/globalbioticinteractions/usgs-bison

Please advise on how to better re-use and index your work.

**Comment by neilcobb** [comment]
@jhpoelen I have no idea what you mean by transcribed manually, and not publicly available.   Can you provide examples? Only a few of these have associations because they used pollinator cups. Two studies that should have most records with host are:
https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=280
https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=278

**Comment by jhpoelen** [comment]
@neilcobb thanks for your prompt reply, and for asking for clarification.

For your example via  https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=280 sourced from:

> Gaiarsa, M.P., Kremen, C. & Ponisio, L.C. Pollinator interaction flexibility across scales affects patch colonization and occupancy. Nat Ecol Evol (2021). https://doi.org/10.1038/s41559-021-01434-y.

I was unable to find a way to retrieve the records via some DwC-A or other methods.

Same applies for https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=278 / Maine State Museum - Brianne Du Clos (MSM-DUCL) . 

Please let me know how I can best index these bee-host datasets.

**Comment by neilcobb** [comment]
@jhpoelen Got it.  forgot that is how you grab data from SCAN.  I do not provide DwC-A files for providers that make their data through another primary aggregator or an IPT. I was still working with the people that produced these datasets before  creating archives.  I can make you a super admin on SCAN and then you can do more things.  But the datasets that have associations I will put up tonight for you and take them down when you are done and then put them back up when the data providers are comfortable doing it permanently

**Comment by jhpoelen** [comment]
Thanks for clarifying. When do you expect the providers to be comfortable sharing permanently? Wouldn't want to share reviews on their datasets if they are not ready for feedback.

**Comment by neilcobb** [comment]
Their data is already public, and I have let them know I served their data and they did not have a problem,   so the Maine data set and the pollinator interaction data set both have DwC-A if you want to grab those.  The others either do not have association data or they are already served on GBIF, like the Bumble Bee Watch data.

**Comment by jhpoelen** [comment]
Excellent! Thanks for making this happen.

**Comment by neilcobb** [comment]
Happy to help

**Comment by jhpoelen** [comment]
All publicly available SCAN DwC-A are indexed by GloBI via - 

https://scan-bugs.org:443/portal/webservices/dwc/rss.xml per configuration

https://github.com/globalbioticinteractions/scan .
