### ISSUE TITLE
accordingTo=inaturalist no longer working

### ISSUE THREAD

**Issue by kueda** [globalbioticinteractions/globalbioticinteractions#668]
At iNaturalist we request records from GLoBI to determine which iNat records have been incorporated into GLoBI so we can then show a link from those records to the corresponding GLoBI interactions. To do this we've been using an API request like this:

https://api.globalbioticinteractions.org/interaction?accordingTo=inaturalist&field=study_url&includeObservations=true&limit=10&skip=0

As of right now, that's not returning any results. As far as I can tell the DwC-A we generate for GLoBI exists and has data, and it looks like iNat records are still in GLoBI. Using the UI it seems like you might have changed the identifier that should be used with `accordingTo` so maybe we should be doing something like

https://api.globalbioticinteractions.org/interaction?accordingTo=globi:globalbioticinteractions/inaturalist&field=study_url&includeObservations=true&limit=10&skip=0

Is that right? If so, is there some way to avoid breaking changes like this in the future?

**Comment by jhpoelen** [comment]
Oops, I just introduced a new index that dropped the inability to do a row-scan #544. 

Thanks for letting me know. You already guessed one way to get to some of the inaturalist records.

https://api.globalbioticinteractions.org/interaction?accordingTo=globi:globalbioticinteractions/inaturalist&field=study_url&includeObservations=true&limit=10&skip=0

This includes all the iNaturalist records indexed directly from iNaturalist. If you'd like to include *all* inaturalist records, indexed via other non-iNaturalist sources, perhaps easier and faster to just do a regex on interactions.tsv.gz. This way, you'd also pick up iNaturalist observations that are referenced in natural history collections, but not directly in iNaturalist itself. 

Curious to hear what you prefer and open to suggestions. 

Something along the lines of:

```
$ curl --silent "https://depot.globalbioticinteractions.org/snapshot/target/data/tsv/interactions.tsv.gz" | gunzip | grep -o -P "https://www.inaturalist.org/observations/[0-9]+" | head
https://www.inaturalist.org/observations/78775212
https://www.inaturalist.org/observations/78756420
https://www.inaturalist.org/observations/78118778
https://www.inaturalist.org/observations/78747562
https://www.inaturalist.org/observations/78775210
https://www.inaturalist.org/observations/48361326
https://www.inaturalist.org/observations/76254544
https://www.inaturalist.org/observations/40321613
https://www.inaturalist.org/observations/46275356
https://www.inaturalist.org/observations/50179635
```

**Comment by kueda** [comment]
Is `globi:globalbioticinteractions/inaturalist` going to be stable for the foreseeable future? If so, probably just easiest for us to switch to that. How frequently does `interactions.tsv.gz` get updated?

**Comment by jhpoelen** [comment]
```interactions.tsv.gz``` is a flat file, no queries required on my end, and is updated automatically about every week or more frequently. 

the paging web api uses the same data, updated as some frequency, and just requires a bunch more web requests, especially at the rate at the number of interactions from iNaturalist are increasing.

**Comment by jhpoelen** [comment]
And yes, I expect ```globi:globalbioticinteractions/inaturalist``` to be supported in the foreseeable future.

**Comment by jhpoelen** [comment]
I can also imagine building a special index for id patterns. I imagine others might benefit from this also. 

Something like:
```
...?accordingTo=idPattern:inaturalist
```

where id patterns are defined in something like:

https://github.com/bio-guoda/preston-identifier-registry/blob/main/registry.tsv

Curious to hear your thoughts.

**Comment by jhpoelen** [comment]
@kueda In looking at your integration code at https://github.com/inaturalist/inaturalist/blob/768b9263931ebeea229bbc47d8442ca6b0377d45/tools/globi_observation_links.rb it might be easiest to go with your initial intuition for now (e.g., ```accordingTo=globi:globalbioticinteractions/inaturalist``` instead of ```accordingTo="inaturalist```) . 

Also, I've added a shortcut/redirect to continue supporting the previous integration by adding a ```accordingTo=globi:globalbioticinteractions/inaturalist``` whenever a ```accordingTo=inaturalist``` is observed.  With this patch, you should be a able to get the desired results with the old/existing behavior.

So, now, as previous expected:
```
$ curl "https://api.globalbioticinteractions.org/interaction?accordingTo=inaturalist&field=study_url&includeObservations=true&limit=10&skip=0" | jq .
{
  "columns": [
    "study_url"
  ],
  "data": [
    [
      "https://www.inaturalist.org/observations/78775212"
    ],
    [
      "https://www.inaturalist.org/observations/78775212"
    ],
    [
      "https://www.inaturalist.org/observations/78756420"
    ],
    [
      "https://www.inaturalist.org/observations/78756420"
    ],
    [
      "https://www.inaturalist.org/observations/78118778"
    ],
    [
      "https://www.inaturalist.org/observations/78118778"
    ],
    [
      "https://www.inaturalist.org/observations/78747562"
    ],
    [
      "https://www.inaturalist.org/observations/78747562"
    ],
    [
      "https://www.inaturalist.org/observations/78775210"
    ],
    [
      "https://www.inaturalist.org/observations/78775210"
    ]
  ]
}

Apologies for the inconvenience: I added some unit test to document this behavior in hopes of not having to repeat this again. 

Also, please drop me a line if you are interested in exploring the idea for iNaturalist to link to observations beyond those that have native biotic association/interaction annotations in iNaturalist. This way, you can see how other datasets link _into_ iNaturalist observations to describe interactions.

**Comment by kueda** [comment]
> Also, please drop me a line if you are interested in exploring the idea for iNaturalist to link to observations beyond those that have native biotic association/interaction annotations in iNaturalist.

Unfortunately at this point I feel all my development time goes toward mitigating the consequences of past mistakes. The only features I'll ever work on will probably be ones that take less than a few hours, and that doesn't sound like one of those.

**Comment by jhpoelen** [comment]
@kueda I can see how maintaining inaturalist is quite a task, especially with increased use, volume, and exposure. 

Perhaps easier would be to include indirect links on my end as part of some "smart" query. 

Thanks for taking the time to respond.
