### ISSUE TITLE
Odd behavior from Globi/RGlobi

### ISSUE THREAD

**Issue by pozsgaig** [globalbioticinteractions/globalbioticinteractions#672]
Using the code get_interactions_by_taxa(sourcetaxon = x, 
                                             interactiontype = "preysOn") in RGlobi I got taxa in my result list's source taxon name which were not part of the x vector. Is this a bug (RGlobi or Globi)? I am using RGlobi 0.2.22.

**Comment by jhpoelen** [comment]
hey @pozsgaig - thanks for taking the time to share your insights and observations. 

If you provide specific examples of expected and unexpected results, we (anyone else listening?) might be able to help figure out what is going on.

**Comment by pozsgaig** [comment]
The species list I queried was 
x<-c("Trichogramma colombiense", "Spodophagus lepidopterae", "Trichogramma demoraesi", "Palmistichus elaeisis", "Alveoplectrus corumbae", "Trichogramma koehleri", "Conura ruffinellii", "Trichogramma galloi", "Pediobius furvus", "Brachymeria flavipes", "Euplectrus comstockii", "Brachymeria ovata", "Conura femorata", "Conura igneoides", "Trichogrammatoidea eldanae", "Conura immaculata", "Trichomalopsis", "Trichospilus", "Trichogramma atopovirilia", "Trichogramma rojasi", "Trichospilus diatraeae", "Conura side", "Euplectrus platyhypenae", "Trichogramma exiguum", "Euplectrus furnius", "Euplectrus", "Trichogramma minutum", "Trichogramma pretiosum", "Trichogramma fasciatum", "Trichogramma", "Gonia crassicornis", "Archytas incertus", "Winthemia leucanae", "Hyphantrophaga hyphantriae", "Winthemia abdominalis", "Winthemia infesta", "Winthemia rufopicta", "Winthemia sinuata", "Eusisyropa blanda", "Archytas marmoratus", "Eucelatoria armigera", "Bonnetia comta", "Chetogena scutellaris", "Lespesia", "Admontia degeerioides", "Archytas apicifer", "Voria ruralis", "Winthemia quadripustulata", "Lespesia aletiae", "Lespesia archippivora", "Tachinidae", "Chetogena claripennis", "Nemorilla pyste", "Carcelia amplexa", "Lixophaga diatraeae", "Gonia", "Archytas", "Gonia sequax", "Nosema laphygmae", "Paecilomyces fumosoroseus", "Nosema trichoplusiae", "Spodoptera littoralis", "Vairimorpha necatrix", "Nomuraea rileyi", "Steinernema riobrave", "Steinernema scapterisci", "Entomophaga aulicae", "Metarhizium anisopliae", "Paecilomyces tenuipes", "Aspila", "Plutella xylostella", "Anagrapha falcifera", "Beauveria bassiana", "Autographa californica", "Spodoptera frugiperda", "Brachymeria reflexa", "Euplectrus gopimohani", "Trichomalopsis hemiptera", "Pediobius amaurocoelus", "Euplectrus euplexiae", "Elasmus", "Trichogrammatoidea brasiliensis", "Trichogramma principium", "Psychophagus omnivorus", "Trichogramma semifumatum", "Conura albifrons", "Trichogramma chilonis", "Pediobius", "Brachymeria", "Euplectrus bicolor", "Nosema destructor", "Nosema infesta", "Microsporidium", "Nosema bombycis", "Granulovirus", "Cypovirus 4", "NPV", "Nosema algerae", "Tolypocladium cylindrosporum", "Trichoplusia ni", "Mamestra brassicae", "Agrotis segetum", "Anticarsia gemmatalis", "Spodoptera exigua", "Invertebrate iridescent virus 6", "Spodoptera frugiperda rhabdovirus", "Spodoptera frugiperda granulovirus", "Spodoptera frugiperda ascovirus 1a", "Invertebrate iridovirus 22", "Paenibacillus larvae", "Dendrolimus punctatus cypovirus 22", "Heliothis virescens ascovirus 3g", "Mamestra configurata nucleopolyhedrovirus B", "Spodoptera exigua iflavirus 1", "Spodoptera exigua iflavirus 2", "Corynorhinus rafinesquii", "Mormoops blainvillei", "Tadarida brasiliensis")

I got the extra species in the returning data frame as source names:
[1] "Plutella xylostella multiple nucleopolyhedrovirus" 
[2] "Trichoplusia ni granulovirus LBIV-12"              
[3] "Helicoverpa armigera multiple nucleopolyhedrovirus"
[4] "Erigone atra"                                      
[5] "Goniochaeta"

**Comment by pozsgaig** [comment]
I think the problem may be with some fuzzy matching when long virus names are queried. Eg. "Spodoptera frugiperda rhabdovirus" will return results from  "Spodoptera frugiperda"

**Comment by pozsgaig** [comment]
May be an unrelated issue but I have just noticed that to the search 
get_interactions_by_taxa(sourcetaxon =  "Spodoptera frugiperda"), 
                                     interactiontype = "hasParasite") 
                                     
The result list included Plutella xylostella and other moths as well. Since both taxa are moths they cannot be each other's parasites.

**Comment by jhpoelen** [comment]
@pozsgaig thanks for sharing the details. Hoping to have a look sooner rather than later, if someone else doesn't beat me to it. Thanks in advance for being patient!

**Comment by jhpoelen** [comment]
@pozsgaig I was able to produce your observation that GloBI searches for _Plutella xylostella_ also include viruses with a name prefixed by _Plutella xylostella_ (e.g., ```Plutella xylostella ... virus```).

For example see screenshots made 23 June 2021 via https://www.globalbioticinteractions.org/?interactionType=pathogenOf&sourceTaxon=Plutella%20xylostella 

![Screenshot from 2021-06-23 13-06-35](https://user-images.githubusercontent.com/1084872/123161109-dfe1e780-d423-11eb-947d-a3c38066e0b6.png)

Note however, that nomer's name mapping with a recent taxon graph (e.g., http://doi.org/10.5281/zenodo.4753955) is producing expected results - 

```
$ echo -e "\tPlutella xylostella multiple nucleopolyhedrovirus" | nomer append 
using default matcher [globi-taxon-cache]
local taxon cache of [https://zenodo.org/record/4655150/files/taxonCache.tsv.gz] building...
cache with [3100229] items built in [66.5] s or [46628.4] items/s.
local taxon cache of [https://zenodo.org/record/4655150/files/taxonCache.tsv.gz] built.
local taxon map of [https://zenodo.org/record/4655150/files/taxonMap.tsv.gz] building...
cache with [3632099] items built in [27.2] s or [133332.1] items/s.
local taxon map of [https://zenodo.org/record/4655150/files/taxonMap.tsv.gz] built.
	Plutella xylostella multiple nucleopolyhedrovirus	SAME_AS	NCBI:379891	Plutella xylostella multiple nucleopolyhedrovirus			root | Viruses | Baculoviridae | Alphabaculovirus | Autographa californica multiple nucleopolyhedrovirus | Plutella xylostella multiple nucleopolyhedrovirus	NCBI:1 | NCBI:10239 | NCBI:10442 | NCBI:558016 | NCBI:307456 | NCBI:379891	| superkingdom | family | genus | species |	https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=379891	
$ echo -e "\tHelicoverpa armigera multiple nucleopolyhedrovirus" | nomer append 
using default matcher [globi-taxon-cache]
	Helicoverpa armigera multiple nucleopolyhedrovirus	SAME_AS	NCBI:559170	Helicoverpa armigera multiple nucleopolyhedrovirus			root | Viruses | Baculoviridae | Alphabaculovirus | Mamestra configurata nucleopolyhedrovirus B | Helicoverpa armigera multiple nucleopolyhedrovirus	NCBI:1 | NCBI:10239 | NCBI:10442 | NCBI:558016 | NCBI:204440 | NCBI:559170	| superkingdom | family | genus | species |	https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=559170	
```

Suggesting that the virus names might have been truncated elsewhere. Continuing root cause analysis . . .

**Comment by jhpoelen** [comment]
Looking into the raw indexed source dataset documenting the suspicious interaction we find reference to virus name ```Plutella xylostella NPV```:

```
$ elton interactions --cache-dir /var/cache/elton/datasets "millerse/Ecological-Database-of-the-World-s-Insect-Pathogens" | grep "Plutella xylostella" | grep "Biever" | grep "hasPathogen" | head -n1
listing interactions [millerse/Ecological-Database-of-the-World-s-Insect-Pathogens]... https://en.wiktionary.org/wiki/support						EOL:448042	Agrotis ipsilon						http://purl.obolibrary.org/obo/RO_0002557	hasPathogen						EOL:956714	Plutella xylostella NPV													GEONAMES:6252001	United States of America			Biever, K.D., Andrews, P.L. 1984. Susceptibility of lepidopterous larvae to Plutella xylostella nuclear polyhedrosis virus. J. Invertebr. Pathol. 44:117-119.	millerse/Ecological-Database-of-the-World-s-Insect-Pathogens	Sarah E Miller. 12/13/2016. Species associations manually extracted from Onstad, D.W. EDWIP: Ecological Database of the World's Insect Pathogens. Champaign, Illinois: Illinois Natural History Survey, [23/11/2016]. http://insectweb.inhs.uiuc.edu/Pathogens/EDWIP.	https://github.com/millerse/Ecological-Database-of-the-World-s-Insect-Pathogens/archive/187c16c8e664860d07e20f8a5ce209836e609c0b.zip	2021-06-19T05:09:54.027Z	e5caddef01085a38b1bece79e9cd268fb1f1a7b49e4165ef9ef5f05739f5fc8e	0.11.0
```

**Comment by jhpoelen** [comment]
where Plutella xylostella NPV is (incorrectly) mapped to _Plutella xylostella_ (see below). This suggests that the NPV virus acronym was dropped in the (imperfect) name mapping process. This suspicious name mapping is consistent with the unexpected results observed by @pozsgaig .  

```
$ echo -e "\tPlutella xylostella NPV" | nomer append --properties nomer.properties
using default matcher [globi-taxon-cache]
	Plutella xylostella NPV	SAME_AS	doi:10.3897/BDJ.3.e6313	doi:10.3897/BDJ.3.e6313			doi:10.3897/BDJ.3.e6313			https://doi.org/10.3897/BDJ.3.e6313	
	Plutella xylostella NPV	SAME_AS	doi:10.3897/zookeys.327.5831	doi:10.3897/zookeys.327.5831			doi:10.3897/zookeys.327.5831			https://doi.org/10.3897/zookeys.327.5831	
	Plutella xylostella NPV	SAME_AS	EOL:956714	Plutella xylostella	species	Kohlmotte @de | diamond-backed moth @en | Polilla de la col @es | Kaalikoi @fi | Fausse-teigne des crucifères @fr | Káposztamoly @hu | Tignola delle crucifere @it | Koolmot @nl | Traça das couves @pt |	Animalia | Arthropoda | Insecta | Lepidoptera | Yponomeutoidea | Plutellidae | Plutella | Plutella xylostella	EOL:1 | EOL:164 | EOL:344 | EOL:747 | EOL:750 | EOL:886 | EOL:95522 | EOL:956714	kingdom | phylum | class | order | superfamily | family | genus | species	http://eol.org/pages/956714	
	Plutella xylostella NPV	SAME_AS	GBIF:1831136	Plutella xylostella	species		Animalia | Arthropoda | Insecta | Lepidoptera | Plutellidae | Plutella | Plutella xylostella	GBIF:1 | GBIF:54 | GBIF:216 | GBIF:797 | GBIF:8860 | GBIF:1831127 | GBIF:1831136	kingdom | phylum | class | order | family | genus | species	http://eol.org/pages/956714	
	Plutella xylostella NPV	SAME_AS	http://taxon-concept.plazi.org/id/Animalia/Plutella_xylostella_Linnaeus_1758	Plutella xylostella			Animalia | Arthropoda | Insecta | Lepidoptera | Plutellidae | Plutella | Plutella xylostella		kingdom | phylum | class | order | family | genus | species	http://taxon-concept.plazi.org/id/Animalia/Plutella_xylostella_Linnaeus_1758	
	Plutella xylostella NPV	SAME_AS	http://treatment.plazi.org/id/601B43E9542E3D0778039A1F66FE1BBC	http://treatment.plazi.org/id/601B43E9542E3D0778039A1F66FE1BBC			http://treatment.plazi.org/id/601B43E9542E3D0778039A1F66FE1BBC			http://treatment.plazi.org/id/601B43E9542E3D0778039A1F66FE1BBC	
	Plutella xylostella NPV	SAME_AS	http://treatment.plazi.org/id/C7E2701C3132A9B3B9737A599A49D56A	http://treatment.plazi.org/id/C7E2701C3132A9B3B9737A599A49D56A			http://treatment.plazi.org/id/C7E2701C3132A9B3B9737A599A49D56A			http://treatment.plazi.org/id/C7E2701C3132A9B3B9737A599A49D56A	
	Plutella xylostella NPV	SAME_AS	INAT_TAXON:126765	Plutella xylostella	species		Animalia | Arthropoda | Insecta | Lepidoptera | Plutellidae | Plutella | Plutella xylostella		kingdom | phylum | class | order | family | genus | species	http://eol.org/pages/956714	
	Plutella xylostella NPV	SAME_AS	IRMNG:10261759	Plutella xylostella	species		Animalia | Arthropoda | Insecta | Lepidoptera | Plutellidae | Plutella | Plutella xylostella	IRMNG:11 | IRMNG:235 | IRMNG:1096 | IRMNG:12144 | IRMNG:104547 | IRMNG:1378784 | IRMNG:10261759	kingdom | phylum | class | order | family | genus | species	http://eol.org/pages/956714	
	Plutella xylostella NPV	SAME_AS	WD:Q1050343	Plutella xylostella	species		| Plutella xylostella	WD:Q10350573 | WD:Q1050343	| species	https://www.wikidata.org/wiki/Q1050343	
```

**Comment by jhpoelen** [comment]
Similarly, ```Spodoptera frugiperda NPV``` appears via 

```
$ elton interactions --cache-dir /var/cache/elton/datasets "millerse/Ecological-Database-of-the-World-s-Insect-Pathogens" | grep "Martignoni" | grep "Spodoptera frugiperda" | grep hasPathogen
listing interactions [millerse/Ecological-Database-of-the-World-s-Insect-Pathogens]... https://en.wiktionary.org/wiki/support					EOL:533408	Spodoptera frugiperda						http://purl.obolibrary.org/obo/RO_0002557	hasPathogen			IV										Martignoni, M.E. and Iwai, P.J. A catalogue of viral diseases of insects, mites and ticks. Appendix 2 [pp. 899-912] In, H.D. Burges (ed.) Microbial Control of Pests and Plant Diseases, 1970-1980. London: Academic Press, 1981. 949 pp.	millerse/Ecological-Database-of-the-World-s-Insect-Pathogens	Sarah E Miller. 12/13/2016. Species associations manually extracted from Onstad, D.W. EDWIP: Ecological Database of the World's Insect Pathogens. Champaign, Illinois: Illinois Natural History Survey, [23/11/2016]. http://insectweb.inhs.uiuc.edu/Pathogens/EDWIP.	https://github.com/millerse/Ecological-Database-of-the-World-s-Insect-Pathogens/archive/187c16c8e664860d07e20f8a5ce209836e609c0b.zip	2021-06-19T05:09:54.027Z	e5caddef01085a38b1bece79e9cd268fb1f1a7b49e4165ef9ef5f05739f5fc8e0.11.0
https://en.wiktionary.org/wiki/support						EOL:533408	Spodoptera frugiperda						http://purl.obolibrary.org/obo/RO_0002557	hasPathogen			EOL:41592611	Spodoptera frugiperda NPV					Martignoni, M.E. and Iwai, P.J. A catalogue of viral diseases of insects, mites and ticks. Appendix 2 [pp. 899-912] In, H.D. Burges (ed.) Microbial Control of Pests and Plant Diseases, 1970-1980. London: Academic Press, 1981. 949 pp.	millerse/Ecological-Database-of-the-World-s-Insect-Pathogens	Sarah E Miller. 12/13/2016. Species associations manually extracted from Onstad, D.W. EDWIP: Ecological Database of the World's Insect Pathogens. Champaign, Illinois: Illinois Natural History Survey, [23/11/2016]. http://insectweb.inhs.uiuc.edu/Pathogens/EDWIP.	https://github.com/millerse/Ecological-Database-of-the-World-s-Insect-Pathogens/archive/187c16c8e664860d07e20f8a5ce209836e609c0b.zip	2021-06-19T05:09:54.027Z	e5caddef01085a38b1bece79e9cd268fb1f1a7b49e4165ef9ef5f05739f5fc8e0.11.0
done.
```

with similar suspicious name mapping of ```Spodoptera frugiperda NPV``` to ```Spodoptera frugiperda```:

```
$ echo -e "\tSpodoptera frugiperda NPV"  | nomer append --properties nomer.properties
using default matcher [globi-taxon-cache]
local taxon cache of [https://zenodo.org/record/4753955/files/taxonCache.tsv.gz] building...
cache with [3107809] items built in [82.1] s or [37877.0] items/s.
local taxon cache of [https://zenodo.org/record/4753955/files/taxonCache.tsv.gz] built.
local taxon map of [https://zenodo.org/record/4753955/files/taxonMap.tsv.gz] building...
cache with [3662691] items built in [30.5] s or [120009.5] items/s.
local taxon map of [https://zenodo.org/record/4753955/files/taxonMap.tsv.gz] built.
	Spodoptera frugiperda NPV	SAME_AS	EOL:533408	Spodoptera frugiperda	species	Heerwurm @de | fall armyworm @en | Gusano de la acelga @es | légionnaire d'automne @fr |	Animalia | Arthropoda | Insecta | Lepidoptera | Noctuoidea | Noctuidae | Spodoptera | Spodoptera frugiperda	EOL:1 | EOL:164 | EOL:344 | EOL:747 | EOL:769 | EOL:873 | EOL:66050 | EOL:533408	kingdom | phylum | class | order | superfamily | family | genus | species	http://eol.org/pages/533408	
```

**Comment by jhpoelen** [comment]
@KatjaSchulz Just checking for EOL refutation/validation rules: are you disputing suspicious interaction claims that describe non-viral pathogens as described by @pozsgaig in this issue?

**Comment by jhpoelen** [comment]
I've prepared a patched version of the GloBI Taxon Graph that no longer contains some of the suspicious virus name mappings:

Poelen, Jorrit H. (2021). Global Biotic Interactions: Taxon Graph (Version 0.3.33) [Data set]. Zenodo. http://doi.org/10.5281/zenodo.5021869

using patch:

Poelen, Jorrit H. (2021). Global Biotic Interactions: Taxon Graph Patches (Version 0.8) [Data set]. Zenodo. http://doi.org/10.5281/zenodo.5021824

Please see respective publications for more information on how the name mappings were updated.

**Comment by jhpoelen** [comment]
After re-running the name matching against an update taxon graph we find:

```
$ echo -e "\tSpodoptera frugiperda NPV"  | nomer append --properties nomer.properties
using default matcher [globi-taxon-cache]
local taxon cache of [https://zenodo.org/record/5021869/files/taxonCache.tsv.gz] building...
cache with [3107809] items built in [60.3] s or [51537.4] items/s.
local taxon cache of [https://zenodo.org/record/5021869/files/taxonCache.tsv.gz] built.
local taxon map of [https://zenodo.org/record/5021869/files/taxonMap.tsv.gz] building...
cache with [3661445] items built in [25.1] s or [145653.8] items/s.
local taxon map of [https://zenodo.org/record/5021869/files/taxonMap.tsv.gz] built.
	Spodoptera frugiperda NPV	NONE	Spodoptera frugiperda NPV	
```

and 

```
$ echo -e "\tPlutella xylostella NPV"  | nomer append --properties nomer.properties
using default matcher [globi-taxon-cache]
	Plutella xylostella NPV	NONE	Plutella xylostella NPV			
```

as expected: the virus names are no longer associated with the host organisms included in their names.

However, when the names are mixed with suspiciously linked EOL taxon ids (aka EOL pages), some issues remain because taxon ids (currently) take precedence over names:

```
$ echo -e "EOL:956714\tPlutella xylostella NPV"  | nomer append --properties nomer.properties
using default matcher [globi-taxon-cache]
EOL:956714	Plutella xylostella NPV	SAME_AS	EOL:956714	Plutella xylostella	species	Kohlmotte @de | diamond-backed moth @en | Polilla de la col @es | Kaalikoi @fi | Fausse-teigne des crucifères @fr | Káposztamoly @hu | Tignola delle crucifere @it | Koolmot @nl | Traça das couves @pt |	Animalia | Arthropoda | Insecta | Lepidoptera | Yponomeutoidea | Plutellidae | Plutella | Plutella xylostella	EOL:1 | EOL:164 | EOL:344 | EOL:747 | EOL:750 | EOL:886 | EOL:95522 | EOL:956714	kingdom | phylum | class | order | superfamily | family | genus | species	http://eol.org/pages/956714	
...
```  

This explains why ```Plutella xylostella NPV``` mentioned in https://github.com/globalbioticinteractions/globalbioticinteractions/issues/672#issuecomment-867140692 is still included in searches for ```Plutella xylostella``` like https://www.globalbioticinteractions.org/?interactionType=pathogenOf&sourceTaxon=Plutella%20xylostella (see screenshot). 

These suspicious interaction records will have to be refuted independently or alternative methods will have to introduced to prevent these suspicious name links from getting indexed. 

![Screenshot from 2021-06-24 09-57-37](https://user-images.githubusercontent.com/1084872/123303473-af0cbb80-d4d2-11eb-94de-bccd36fa5fd4.png)

**Comment by jhpoelen** [comment]
@pozsgaig Thanks again for sharing your findings. I was able to eliminate some of the root causes of your reported "odd behavior" related to virus names. 

A root cause of "fuzzy" matching of virus names still remains, and I've opened a specific issue on that at https://github.com/globalbioticinteractions/globalbioticinteractions/issues/681 . 

Also, please note that a third cause of unexpected results (e.g., Plutella xylostella (a moth) is claimed to be a pathogen of other moths) (see attached screenshot) is a result of suspicious linking of ```Plutella xylostella NPV``` to a EOL taxon page related to one of the virus hosts and name sake's ```Plutella xylostella```  [EOL:956714](https://eol.org/pages/956714, see below). This and other similar moth-moth pathogen interaction claims have been refuted via https://github.com/globalbioticinteractions/refuted-interaction-data/commit/bf6dedbd98f8f69e654cda6f27f27ca842b73a78 .

```
listing interactions [millerse/Ecological-Database-of-the-World-s-Insect-Pathogens]...
 https://en.wiktionary.org/wiki/support						EOL:448042	Agrotis ipsilon						http://purl.obolibrary.org/obo/RO_0002557	hasPathogen						EOL:956714	Plutella xylostella NPV													GEONAMES:6252001	United States of America			Biever, K.D., Andrews, P.L. 1984. Susceptibility of lepidopterous larvae to Plutella xylostella nuclear polyhedrosis virus. J. Invertebr. Pathol. 44:117-119.	millerse/Ecological-Database-of-the-World-s-Insect-Pathogens	Sarah E Miller. 12/13/2016. Species associations manually extracted from Onstad, D.W. EDWIP: Ecological Database of the World's Insect Pathogens. Champaign, Illinois: Illinois Natural History Survey, [23/11/2016]. http://insectweb.inhs.uiuc.edu/Pathogens/EDWIP.	https://github.com/millerse/Ecological-Database-of-the-World-s-Insect-Pathogens/archive/187c16c8e664860d07e20f8a5ce209836e609c0b.zip	2021-06-19T05:09:54.027Z	e5caddef01085a38b1bece79e9cd268fb1f1a7b49e4165ef9ef5f05739f5fc8e	0.11.0
```

@pozsgaig thanks again for being patient and I am looking forward to other observations of suspicious data if you are able and willing to share.
