### ISSUE TITLE
TPT taxonomy incorporate into GloBI name matching process

### ISSUE THREAD

**Issue by seltmann** [globalbioticinteractions/globalbioticinteractions#694]
Hi @Jegelewicz @njdowdy we are ready to incorporate your TPT taxonomies into GloBI to help improve the finding of TPT records. I see several repositories such as [https://github.com/Jegelewicz/tpt-siphonaptera](https://github.com/Jegelewicz/tpt-siphonaptera).

Is this data published somewhere such as on Zenodo so we can link to it? Which files on Github (or some other place) should we be using as an example? and who should we contact in case we have questions?

Thanks again,
Katja

**Comment by Jegelewicz** [comment]
Katja,

Nick and I are no longer actively working on the TPT taxonomy project. The current versions of the various TPT taxonomic lists are being managed by Kat Sullivan kathrynsully95 [at] gmail.com 

Adios,
Teresa

**Comment by seltmann** [comment]
Thank you @Jegelewicz

**Comment by njdowdy** [comment]
I am no longer funded by TPT, but that doesn't mean I'm not still working on it, haha 😄 

@katsullivan is now the best contact for the project. However, I will try to facilitate as well. More to follow soon.

**Comment by seltmann** [comment]
@katsullivan Thanks for your email, moving the conversation here so its easier for everyone to keep track of the discussion.

It is really great that the taxonomies will be incorporated into GBIF/CoL. 

I think what would be a good first step is to publish them via Zenodo. There are lots of reasons for this as Zenodo will track the versions for you, so when you come out with a new release of the louse checklist (for example) people can reference not only recent versions but past versions they may have used as well. When taxonomic information is incorporated into GBIF/CoL it is hard for a user to understand what version of the taxonomic list they are actually using and what its original source is. By publishing on Zenodo first, users can reference the DOI to say very clearly "I used this version of the TPT louse taxonomy."

Another great reason is you can just point people to the name list. So when you get requests (like ours, or GBIF) you can just send us toward the publication on Zenodo. It will make the name lists very broadly available.

I am away Friday through next week but I would be happy to meet and discuss methods for publishing the TPT taxonomy. Jorrit and I will meet again next Friday, September 17 at 1:00 pm PT. We could meet then?

**Comment by jhpoelen** [comment]
See https://github.com/njdowdy/tpt-taxonomy  for a recent location of where the tpt names are kept.

**Comment by jhpoelen** [comment]
Should we introduce hash based identifiers - 

tpt:cut:hash://sha256/f162fdf1bcd8b2051af6002c85ba3f9a2e25483d09d821c610339665533f721b/!L35

? 

This way, can don't have to mint identifiers.


```cut:zip:hash://sha256/f162fdf1bcd8b2051af6002c85ba3f9a2e25483d09d821c610339665533f721b!/acari.csv!/L3```

**Comment by EMTuckerLabUMMZ** [comment]
I reformatted the taxonomy files so all the headers are standardized. They currently located here: https://drive.google.com/drive/folders/1KqMc13T5Y3X8yoIvzHHjTyKvcQoiQufO?usp=sharing
I also have a metadata file with definitions matching to column headers. Since I've adjusted all the files to have standardized headers, the metadata file should apply to all files. I currently have everything uploaded as a .csv formatted file, but I could upload .txt files or something else if that would be better.

**Comment by EMTuckerLabUMMZ** [comment]
I have now added these files to the main TPT github taxonomy page here: https://github.com/njdowdy/tpt-taxonomy
Thanks Nick for thinking of it!

**Comment by jhpoelen** [comment]
Thanks to @njdowdy @Jegelewicz @EMTuckerLab and friends, I was able to add support for Foundational Taxonomic Resources For The Terrestrial Parasite Tracker (TPT) Project

Here's some examples:

list all name relations for Haplothyrus expolitissimus 
```
nomer ls tpt --include-header\
 | grep "Haplothyrus expolitissimus"\
 | mlr --itsv --omd cat
```

| providedExternalId | providedName | relationName | resolvedExternalId | resolvedName | resolvedRank | resolvedCommonNames | resolvedPath | resolvedPathIds | resolvedPathNames | resolvedExternalUrl | resolvedThumbnailUrl |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| acari_6892347 | Haplothyrus expolitissimus | HAS_ACCEPTED_NAME | acari_6892347_2 | Haplothyrus expolitissimus_2 | species |  | Animalia | Arthropoda | Arachnida | Holothyrida | Holothyridae | Haplothyrus | expolitissimus | _2 | kingdom | phylum | class | order | family | genus | specificEpithet | _3 | _4 |
| acari_6892348 | Holothyrus expolitissimus | SYNONYM_OF | acari_6892347 | Haplothyrus expolitissimus | species |  | Animalia \| Arthropoda \| Arachnida \| Holothyrida \| Holothyridae \| Haplothyrus \| expolitissimus |  | kingdom \| phylum \| class \| order \| family \| genus \| specificEpithet |  |  |


number of Mammalia name relations:

```
nomer ls tpt | grep Mammalia | wc -l
```

```
[main] INFO org.globalbioticinteractions.nomer.match.TermMatcherRegistry - using matcher [tpt]
[main] INFO org.globalbioticinteractions.nomer.match.TPTTaxonService - DwC taxonomy already indexed at [/home/jorrit/.cache/nomer/terrestrial_parasite_tracker/terrestrial_parasite_tracker], no need to import.
7890
```

number of name relations mentioning Acari 

```
$ nomer ls tpt | grep Acari | wc -l
[main] INFO org.globalbioticinteractions.nomer.match.TermMatcherRegistry - using matcher [tpt]
[main] INFO org.globalbioticinteractions.nomer.match.TPTTaxonService - DwC taxonomy already indexed at [/home/jorrit/.cache/nomer/terrestrial_parasite_tracker/terrestrial_parasite_tracker], no need to import.
1554
```

match name ```Holothyrus expolitissimus``` against TPT taxonomy - 

```
echo -e "\tHolothyrus expolitissimus" \
 | nomer append tpt --include-header
```

| providedExternalId | providedName | relationName | resolvedExternalId | resolvedName | resolvedRank | resolvedCommonNames | resolvedPath | resolvedPathIds | resolvedPathNames | resolvedExternalUrl | resolvedThumbnailUrl |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
|  | Holothyrus expolitissimus | SYNONYM_OF | acari_6892347 | Haplothyrus expolitissimus | species |  | Animalia \| Arthropoda \| Arachnida \| Holothyrida \| Holothyridae \| Haplothyrus \| expolitissimus |  | kingdom \| phylum \| class \| order \| family \| genus \| specificEpithet |  |  |

**Comment by jhpoelen** [comment]
fyi @seltmann

**Comment by jhpoelen** [comment]
TPT was included in the Nomer list of support matchers over a year ago in 2022.
