### ISSUE TITLE
Any advice on this relationship?

### ISSUE THREAD

**Issue by Jegelewicz** [globalbioticinteractions/globalbioticinteractions#726]
@jhpoelen we are struggling with a relationship - any thoughts? https://github.com/ArctosDB/arctos/issues/1842

**Comment by jhpoelen** [comment]
@Jegelewicz interesting discussion re: found on, phoretic on - I'd favor a dual approach - describe the observation (e.g., adjacent to http://purl.obolibrary.org/obo/RO_0002220, interacts with http://purl.obolibrary.org/obo/RO_0002437), then add an interpretation (e.g., phoretic on)  if needed. 

Please re-open this issue if you'd like to comment / discuss some more.
