### ISSUE TITLE
review Yugra State University Biological Collection (YSU BC) Fungarium at http://ipt.ugrasu.ru:8080/ipt/resource?r=fungariumysu

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions#728]
as mentioned by  @ninacourlee in #722 (comment)

> http://ipt.ugrasu.ru:8080/ipt/manage/resource?r=fungariumysu This dataset wasn't indexed, but it has the same field "habitat", i wonder why 3) was indexed and 4) wasn't. Anyway, as above, i don't think that this field has sense for Globi.
> This dataset is exported from our Specify installation and i have added a new field now to the export >> associatedTaxa. I formatted this field according to DwC from two fields (interaction type and host taxon) [interaction type:Scientific Name]. I imported GloBI vocabulary for interaction types, so that it should be ok for the indexing in the future. For now, i filled in this field with unspecific interactions (interacts with), but i will elaborate this information later (parasitizes, hosts, is symbiont of, etc.). This is the most important thing about species interactions in our database and i look forward it to be indexed by GloBI in the future.

**Comment by jhpoelen** [comment]
At a quick glance, it appears that the http://ipt.ugrasu.ru:8080/ipt/manage/resource?r=fungariumysu is not publicly available: a login is required to access it. See attached screenshot.

![Screenshot from 2021-11-15 08-09-26](https://user-images.githubusercontent.com/1084872/141815312-e3f3b37d-ccbc-444b-af9a-664e1aeeaac5.png)

**Comment by ninacourlee** [comment]
Dear Jorrit, this dataset is public, sorry for the false link (it was in "logged in mode"), please update:
http://ipt.ugrasu.ru:8080/ipt/resource?r=fungariumysu
it is registered in GBIF, and by defaul it should be public before registration.

Also, i have just made an update of this dataset with a new field "associatedTaxa" which contains information about species relationships between fungi and their plant hosts. Is this field format is OK for indexind by Globi? 
>associatedTaxa [interacts with : Vaccinium vitis-idaea]

Please, would you be kind to index this dataset in GloBI. I will elaborate the relationships types in the database in the future, but then it will be  updated automatically.

**Comment by jhpoelen** [comment]
@ninacourlee thanks for your notes, your dataset should be indexed by GloBI . I am hoping to share a review of the dataset somewhere next week. Please poke me if you don't hear from me.

**Comment by jhpoelen** [comment]
Note that I can see your data via http://ipt.ugrasu.ru:8080/ipt/resource?r=fungariumysu as you indicated.

Also, I can see that you've recently made changes (see attached screenshot)

![Screenshot from 2021-11-17 09-37-03](https://user-images.githubusercontent.com/1084872/142252835-2c90d913-9afa-41da-8fd3-5a11639c4c34.png)

**Comment by jhpoelen** [comment]
thanks to @ninacourlee  Many species interaction datasets associated with Yagra State University IPT are now being indexed. 

For example see - 
https://www.globalbioticinteractions.org/?accordingTo=globi%3Aglobalbioticinteractions%2Fysu-bc&interactionType=ecologicallyRelatedTo

@ninacourlee please let me know if you find any suspicious interpretations of your data made by GloBI.

btw - to you think it would be useful to create a Russian language version of GloBI website? If so, do you have any suggestions on who'd be able to help translated the phrases/words in https://github.com/globalbioticinteractions/globalbioticinteractions.github.io/blob/main/_config.yml#L61 ?  I'd be happy to help add the translations.
