### ISSUE TITLE
index A taxonomic revision of Gryonoides Dodd, 1920 (Hymenoptera: Scelionidae)

### ISSUE THREAD

**Issue by seltmann** [globalbioticinteractions/globalbioticinteractions#744]
Please consider indexing the data for our new publication "A taxonomic revision of Gryonoides Dodd, 1920 (Hymenoptera: Scelionidae), with a review of the hosts of Teleasinae." The data for this publication can be found at:

Seltmann KC (2021) Seltmann/taxonomy-darwin-core: Darwin Core Formatted Occurrence Data for Taxonomic Studies (v1.0). Zenodo https://doi.org/10.5281/zenodo.5745963

Thank you!

**Comment by jhpoelen** [comment]
@seltmann I much like your idea to use a github repository to help others create taxonomic checklists without having to install complicated systems.

I've prepared a pull request https://github.com/seltmann/taxonomy-darwin-core/pull/5 to configure your datasets for GloBI indexing.

**Comment by jhpoelen** [comment]
A first version of @seltmann 's taxonomic checklist at https://github.com/seltmann/taxonomy-darwin-core was indexed via 

https://www.globalbioticinteractions.org/?accordingTo=globi%3Aseltmann%2Ftaxonomy-darwin-core&interactionType=ecologicallyRelatedTo

![Screenshot from 2022-01-19 16-30-31](https://user-images.githubusercontent.com/1084872/150240558-6fe8695f-5edc-4a0b-bdb8-540bba48bc1e.png)
