### ISSUE TITLE
Duplicate entries in globi

### ISSUE THREAD

**Issue by qgroom** [globalbioticinteractions/globalbioticinteractions#746]
It looks like a dataset has been included twice in Globi,

See...
https://www.globalbioticinteractions.org/?interactionType=flowersVisitedBy&sourceTaxon=Geranium%20molle&targetTaxon=Bombus%20hortorum

This is just one example, but there are many

**Comment by jhpoelen** [comment]
@qgroom thanks for sharing that @Faizaufa forked @zedomel 's index configuration for 

Redhead, J.W.; Coombes, C.F.; Dean, H.J.; Dyer, R.; Oliver, T.H.; Pocock, M.J.O.; Rorke, S.L.; Vanbergen, A.J.; Woodcock, B.A.; Pywell, R.F. (2018). Plant-pollinator interactions database for construction of potential networks. NERC Environmental Information Data Centre. https://doi.org/10.5285/6d8d5cb5-bd54-4da7-903a-15bd4bbd531b

at https://github.com/zedomel/redhead2018 . 

For now, I've excluded the forked https://github.com/Faizaufa/redhead2018 from indexing for now.

**Comment by jhpoelen** [comment]
will keep this issue open until the changes propagate.

**Comment by jhpoelen** [comment]
Duplication of redhead2018 no longer happens after changes propagated. See attached screenshot of https://www.globalbioticinteractions.org/?interactionType=flowersVisitedBy&sourceTaxon=Geranium%20molle&targetTaxon=Bombus%20hortorum

![Screenshot from 2022-01-25 08-44-57](https://user-images.githubusercontent.com/1084872/151020942-57551047-2c60-4d56-8f62-61b362535d6a.png)

@qgroom please feel free to re-open if this issue remains.
