### ISSUE TITLE
DarwinCore Archive export versioning question

### ISSUE THREAD

**Issue by jhammock** [globalbioticinteractions/globalbioticinteractions#751]
It looks like we missed a memo about the change from v 1.0 to 1.1 of the dwca-by-study snapshot file. Eli is thinking of checking https://www.globalbioticinteractions.org/data, going forward, to find the current url of that archive- unless there's a more official place where that is tracked?

Thanks!

**Comment by jhpoelen** [comment]
@jhammock I did leave that memo on the wall next to my kitchen table for weeks. . . ; )

The data products are now  only listed in the data html page. Would it help to produce some kind of RSS, csv, or json instead? 

Please advise . . .

**Comment by eliagbayani** [comment]
@jhpoelen Any simple service where the latest URL is shown would be nice.
Anyway, we've been using this for a while: 1.0
https://depot.globalbioticinteractions.org/snapshot/target/eol-globi-datasets-1.0-SNAPSHOT-darwin-core-aggregated.zip

And we just now moved to this one: 1.1
https://depot.globalbioticinteractions.org/snapshot/target/eol-globi-datasets-1.1-SNAPSHOT-darwin-core-aggregated.zip

Thanks.

**Comment by jhpoelen** [comment]
@eliagbayani @jhammock thanks for your suggestion to create an easy to parse file to point to stable / snapshot version of GloBI data products. 

As a first attempt, I've introduced a tsv version of the table on https://globalbioticinteractions.org/data . 

See attached screenshot . 



Please let me know if this works for you. If not, please suggest alternate (more standardized?) approach. 

-jorrit

**Comment by eliagbayani** [comment]
@jhpoelen yes the data.tsv will certainly work for us. Thanks a lot.

**Comment by jhpoelen** [comment]
@eliagbayani glad the data.tsv works for you. Please don't hesitate to reach out if there's a better way I can help you get to the data indexes.
