### ISSUE TITLE
index GenBank host associations recorded in Arctos host specimen records 

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions#755]
see https://github.com/ArctosDB/arctos/issues/3550 . 

Arctos has the ability to link specimen to genetic sequences in GenBank. 

For example, https://arctos.database.museum/guid/MSB:Mamm:210229  (a Oligoryzomys longicaudatus) points to https://www.ncbi.nlm.nih.gov/nuccore/EU241651 (an Andes virus sequence). 

Perhaps GloBI can infer a host of relation if the genetic sequence is classified as something other than the classification of the (host) specimen.

fyi @dustymc

**Comment by jhpoelen** [comment]
Note that https://www.ncbi.nlm.nih.gov/nuccore/EU241651 has been indexed by GloBI, but a direct link to their Arctos specimen was not available, only taxon-level information survived via:

Grange, Z.L. et al., 2021. Ranking the risk of animal-to-human spillover for newly discovered viruses. Proceedings of the National Academy of Sciences, 118(15), p.e2002324118. Available at: http://dx.doi.org/10.1073/pnas.2002324118. 

See e.g.,  https://www.globalbioticinteractions.org/?accordingTo=https%3A%2F%2Fwww.ncbi.nlm.nih.gov%2Fnuccore%2FEU241651&interactionType=interactsWith .  and attached screenshot. 

![Screenshot from 2022-02-03 15-51-49](https://user-images.githubusercontent.com/1084872/152448618-df33f77f-fb3a-4d2b-9222-14d91ebc2a48.png)

**Comment by jhpoelen** [comment]
I was able to locate an example of an exported occurrence record related to http://arctos.database.museum/guid/MSB:Mamm:210229 in less that 2 minutes using:

```
$ time preston cat --remote https://deeplinker.bio hash://sha256/d98e3bd2bc717bc11a3338cd43fc488bde1d96cb42d8cbe8301f0d9f9753007f | grep hasVersion | grep msb_mamm | preston grep --remote https://deeplinker.bio -l tsv "EU241689"
[...]
line:zip:hash://sha256/07bda8d0778f72df990315a7c9efb65c39848d4b164ae205ccca63d5544fc845!/occurrence.txt!/L254223http://www.w3.org/ns/prov#value	http://arctos.database.museum/guid/MSB:Mamm:210229?seid=103961	PhysicalObject	2020-05-13 13:20:58	en	http://creativecommons.org/licenses/by-nc/3.0	http://vertnet.org/resources/norms.html	http://arctos.database.museum/guid/MSB:Mamm:210229	MSB	14	MSB	Mammal specimens	PreservedSpecimen		SNV results=no ; sex=male	http://arctos.database.museum/guid/MSB:Mamm:210229?seid=103961	MSB:Mamm:210229			Collector(s): Hantavirus Chile	1	male		wild caught	unknown (frozen)	DGR: Division of Genomic Resources (MSB)=DGR:Mamm:40710; GenBank=EU241637; GenBank=EU241651; GenBank=EU241689; NK=96865; institutional catalog number=SSUC M -		http://www.ncbi.nlm.nih.gov/nuccore/EU241637; http://www.ncbi.nlm.nih.gov/nuccore/EU241651; http://www.ncbi.nlm.nih.gov/nuccore/EU241689http://arctos.database.museum/guid/MSB:Mamm:210229		<i>Oligoryzomys longicaudatus</i> (accepted ID) identified by unknown on 2005-03-10; method: unknown Remark: Former nature_of_id: legacy.<br><i>Oligoryzomys longicaudatus</i> identified by Brian Hjelle, R. Eduardo Palma, Fernando Torres-Perez, Edward C. Holmes <i>sensu</i> <a href="http://arctos.database.museum/publication/10006275">TORRES-PÉREZ et al. 2011</a>; method: features Remark: ID from citation in TORRES-PÉREZ et al. 2011.; Former nature_of_id: type specimen.<br><i>Oligoryzomys longicaudatus</i> identified by Joseph A. Cook, Brian Hjelle, R. Eduardo Palma, Fernando Torres-Perez, Rafael A. Medina, Hector Galeno, Maritza Navarrete, Pablo A. Vial, Marcela Ferres <i>sensu</i> <a href="http://arctos.database.museum/publication/10004389">Medina et al. 2009</a>; method: features Remark: ID from citation in Medina et al. 2009.; Former nature_of_id: type specimen.<br><i>Oligoryzomys longicaudatus</i> identified by not recorded <i>sensu</i> <a href="http://arctos.database.museum/publication/10006332">Palma et al. 2012</a>; method: features Remark: ID from citation in Palma et al. 2012.; Former nature_of_id: type specimen.		2001-07-29	2001-07-29	210	2001	07	29	29-Jul-2001				South America, Chile, Coquimbo, Limari	South America				Chile	Coquimbo	Limari	Fray Jorge. A¿o 2001.	Fray Jorge. A¿o 2001., "Ovalle County"					unknown	Verbatim Coordinates: -30.6495S -71.6873W	-30.64/-71.68	decimal degrees	-30.6400000000	-71.6800000000	unknown	0	unknown	2005-03-03 00:00:00	not recorded	unknown	unverified								unknown	2005-03-10		Former nature_of_id: legacy.	A	unknown	voucher of <a href="http://arctos.database.museum/name/Oligoryzomys longicaudatus">Oligoryzomys longicaudatus</a>, page 2448 in <a href="http://arctos.database.museum/publication/10004389">Medina et al. 2009</a>; voucher of <a href="http://arctos.database.museum/name/Oligoryzomys longicaudatus">Oligoryzomys longicaudatus</a>, page 4112 in <a href="http://arctos.database.museum/publication/10006275">TORRES-PÉREZ et al. 2011</a>; voucher of <a href="http://arctos.database.museum/name/Oligoryzomys longicaudatus">Oligoryzomys longicaudatus</a>, page 2 in <a href="http://arctos.database.museum/publication/10006332">Palma et al. 2012</a>	Oligoryzomys longicaudatus	Animalia; Chordata; Mammalia; Rodentia; Cricetidae; Sigmodontinae;	Animalia	Chordata	Mammalia	Rodentia	Cricetidae	Oligoryzomys	longicaudatus		species	ICZN	urn:uuid:d23fe698-c78b-484d-9e69-1067c73da0a6
[...]
real	1m26.663s
user	1m33.667s
sys	0m1.626s
```

Note the section ```GenBank=EU241637; GenBank=EU241651; GenBank=EU241689;```

**Comment by jhpoelen** [comment]
Here's a list of unique genbank ids from a recent MSB Mamm collection produced using:

```
$ time preston cat --remote https://deeplinker.bio hash://sha256/d98e3bd2bc717bc11a3338cd43fc488bde1d96cb42d8cbe8301f0d9f9753007f | grep hasVersion | grep msb_mamm | preston grep --remote https://deeplinker.bio -l tsv -o "http[s]{0,1}://www.ncbi.nlm.nih.gov/nuccore/[a-zA-Z0-9]+" | grep value | cut -f3 | sort | uniq > msb-mamm-genbank-ids.txt
real	1m24.368s
user	1m31.791s
sys	0m1.065s
```
At first glance, this produces 6293 specimen <> genetic sequence relation just from one mammal collection. 

Here's the first 10:

```
$ cat msb-mamm-genbank-ids.txt |  head
http://www.ncbi.nlm.nih.gov/nuccore/AAM90324
http://www.ncbi.nlm.nih.gov/nuccore/AAM90329
http://www.ncbi.nlm.nih.gov/nuccore/AAM90330
http://www.ncbi.nlm.nih.gov/nuccore/AAM90331
http://www.ncbi.nlm.nih.gov/nuccore/AAYZ00000000
http://www.ncbi.nlm.nih.gov/nuccore/ABD94318
http://www.ncbi.nlm.nih.gov/nuccore/ABD94319
http://www.ncbi.nlm.nih.gov/nuccore/ABD94334
http://www.ncbi.nlm.nih.gov/nuccore/AF007037
http://www.ncbi.nlm.nih.gov/nuccore/AF007038
```

**Comment by dustymc** [comment]
This doesn't seem like something you should have to dig out of DWC, but I'm not sure what to do about that. 

https://github.com/ArctosDB/arctos/issues/2141 is my "best" workable idea to date, and it may be an absolutely horrible idea....

(https://dwc.tdwg.org/rdf/ is a much better approach, but I don't see it as workable with our current resources, and I'm not sure anybody at all can do anything with DWC as RDF - can they??)

Here's some data - obviously not the only possible view, let me know if you want something else pending potential real solutions.

@mkoo

```
create table temp_msbmamm_gb as select 
    flat.guid,
    coll_obj_other_id_num.other_id_type,
    concat(base_url,display_value)
from
    flat
    inner join coll_obj_other_id_num on flat.collection_object_id=coll_obj_other_id_num.collection_object_id
    left outer join ctcoll_other_id_type on coll_obj_other_id_num.other_id_type=ctcoll_other_id_type.other_id_type
where
    guid_prefix in ('MSB:Mamm') and
    coll_obj_other_id_num.other_id_type in ('GenBank','NCBI Sequence Read Archive Run ID','NCBI Biosample')
;
```

[temp_msbmamm_gb.csv.zip](https://github.com/globalbioticinteractions/globalbioticinteractions/files/8005087/temp_msbmamm_gb.csv.zip)

**Comment by jhpoelen** [comment]
See attached and first 10 of a first pass at extracting host-virus relations of MSB-Mamm records via GenBank records which have matching host names - 

[msb-mamm-virus-assoc.tsv.txt](https://github.com/globalbioticinteractions/globalbioticinteractions/files/8005231/msb-mamm-virus-assoc.tsv.txt)

@dustymc curious to hear your thoughts how you might be able to use this information to create more explicit relations like ```(host of) http://www.ncbi.nlm.nih.gov/nuccore/EU394150``` in http://arctos.database.museum/guid/MSB:Mamm:197697 .


sourceOccurrenceId | sourceTaxonId | sourceTaxonName | interactionTypeName | targetOccurrenceId | targetTaxonId | targetTaxonName
-- | -- | -- | -- | -- | -- | --
http://arctos.database.museum/guid/MSB:Mamm:197697?seid=985059 |   | Martes caurina | hostOf | http://www.ncbi.nlm.nih.gov/nuccore/EU394150 | NCBI:241478 | Soboliphyme baturini
http://arctos.database.museum/guid/MSB:Mamm:197697?seid=985059 |   | Martes caurina | hostOf | http://www.ncbi.nlm.nih.gov/nuccore/EU394186 | NCBI:241478 | Soboliphyme baturini
http://arctos.database.museum/guid/MSB:Mamm:144475?seid=585067 |   | Sorex monticolus | hostOf | http://www.ncbi.nlm.nih.gov/nuccore/FJ593499 | NCBI:466215 | Jemez Springs virus
http://arctos.database.museum/guid/MSB:Mamm:144475?seid=585067 |   | Sorex monticolus | hostOf | http://www.ncbi.nlm.nih.gov/nuccore/FJ593500 | NCBI:466215 | Jemez Springs virus
http://arctos.database.museum/guid/MSB:Mamm:144475?seid=585067 |   | Sorex monticolus | hostOf | http://www.ncbi.nlm.nih.gov/nuccore/FJ593501 | NCBI:466215 | Jemez Springs virus
http://arctos.database.museum/guid/MSB:Mamm:206425?seid=1610521 |   | Oligoryzomys longicaudatus | hostOf | http://www.ncbi.nlm.nih.gov/nuccore/EU241665 | NCBI:1980456 | Andes orthohantavirus
http://arctos.database.museum/guid/MSB:Mamm:148558?seid=185910 |   | Sorex caecutiens | hostOf | http://www.ncbi.nlm.nih.gov/nuccore/KM201411 | NCBI:1511732 | Amga virus
http://arctos.database.museum/guid/MSB:Mamm:148558?seid=185910 |   | Sorex caecutiens | hostOf | http://www.ncbi.nlm.nih.gov/nuccore/KM201412 | NCBI:1511732 | Amga virus
http://arctos.database.museum/guid/MSB:Mamm:148558?seid=185910 |   | Sorex caecutiens | hostOf | http://www.ncbi.nlm.nih.gov/nuccore/KM201413 | NCBI:1511732 | Amga virus
http://arctos.database.museum/guid/MSB:Mamm:95475?seid=143282 |   | Sorex araneus | hostOf | http://www.ncbi.nlm.nih.gov/nuccore/GQ293120 | NCBI:450605 | Seewis virus

**Comment by jhpoelen** [comment]
Note that http://www.ncbi.nlm.nih.gov/nuccore/EU394150 (see screenshot) recorded only the host name, but not the host voucher as far as I can tell. 

Related record retrieved via https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=nuccore&id=EU394150&rettype=gb&retmode=text with hash://sha256/506eb91545cbd81313a15630d77f954e75168b675ba1e55ec92fe54687ca8c69	on 2022-02-04T07:09:39.040Z 

```
LOCUS       EU394150                 293 bp    DNA     linear   INV 26-JUL-2016
DEFINITION  Soboliphyme baturini voucher NK122498 cytochrome oxidase subunit I
            (CO1) gene, partial cds; mitochondrial.
ACCESSION   EU394150
VERSION     EU394150.1
KEYWORDS    .
SOURCE      mitochondrion Soboliphyme baturini
  ORGANISM  Soboliphyme baturini
            Eukaryota; Metazoa; Ecdysozoa; Nematoda; Enoplea; Dorylaimia;
            Dioctophymatida; Dioctophymatoidea; Soboliphymatidae; Soboliphyme.
REFERENCE   1  (bases 1 to 293)
  AUTHORS   Koehler,A.V., Hoberg,E.P., Dokuchaev,N.E., Tranbenkova,N.A.,
            Whitman,J.S., Nagorsen,D.W. and Cook,J.A.
  TITLE     Phylogeography of the holarctic nematode, Soboliphyme baturini, a
            parasite of North American marten and Siberian sable
  JOURNAL   Unpublished
REFERENCE   2  (bases 1 to 293)
  AUTHORS   Koehler,A.V., Hoberg,E.P., Dokuchaev,N.E., Tranbenkova,N.A.,
            Whitman,J.S., Nagorsen,D.W. and Cook,J.A.
  TITLE     Direct Submission
  JOURNAL   Submitted (12-JAN-2008) Department of Biology, University of New
            Mexico, MSC03 2020, Albuquerque, NM 87106, USA
FEATURES             Location/Qualifiers
     source          1..293
                     /organism="Soboliphyme baturini"
                     /organelle="mitochondrion"
                     /mol_type="genomic DNA"
                     /host="Martes caurina"
                     /specimen_voucher="NK122498; Museum of Southwestern
                     Biology"
                     /db_xref="taxon:241478"
                     /country="USA"
                     /lat_lon="57.13 N 134.32 W"
     gene            <1..>293
                     /gene="CO1"
     CDS             <1..>293
                     /gene="CO1"
                     /codon_start=2
                     /transl_table=5
                     /product="cytochrome oxidase subunit I"
                     /protein_id="ACB42366.1"
                     /translation="ESVTYLSGKSKVFGPLGMIYAMVSIGILGSFVWVHHMFTVGLDV
                     DTRAYFAAASMIIGIPTGVKVFSWLATLYGTPCSFSPLFCWTLGFVFIFTLGG"
ORIGIN      
        1 tgagagtgtt acttatttga gtggtaagtc taaagtcttt ggtcccttag ggatgattta
       61 tgcaatggtg agtattggta tcctaggaag atttgtatgg gtgcatcata tgtttactgt
      121 tggtttagat gtggatactc gtgcttattt tgcggctgca agtatgatta ttggtattcc
      181 aactggagtt aaagtgttta gctgattagc cactctttat ggtactccat gttctttctc
      241 tcctttattc tgttgaacct taggttttgt gtttattttt actctcggtg gtt
//
```

Also, see attached 
[EU394150.gb.txt](https://github.com/globalbioticinteractions/globalbioticinteractions/files/8005279/EU394150.gb.txt)




![Screenshot from 2022-02-04 10-06-57](https://user-images.githubusercontent.com/1084872/152580432-6cc21332-a189-4d38-9caf-31fed700424a.png)

**Comment by dustymc** [comment]
I don't think that's a problem I can address, but I do think it's something the collections will be interested in.

From my perspective, those data just don't make sense. The cataloged item is given as a marten, not marten-and-worm. The listed publications all claim to have found marten, no mention of worms. There's a relationship to a worm, and it should probably be the object which wears at least one publication and the GenBank identifier, but maybe that's some other worm too.

The correct things seem to be cataloged, but some things need shuffled around by the collections.

"Normal" is probably the worm not cataloged at all, but (maybe) entered as a "part" of the host - perhaps one of 20, at least one of which (probably/hopefully) holds the material which lead to the GenBank record. Sorting that out will involve things like digging through loans, and in many cases that will probably just lead to more messes. That's probably a people-problem, not something machines can reliably deal with.

Going to some funding agency with "our data are a mess" probably won't work out very well. Going to some funding agency with "we'd like to hire someone to fix these 12345 problems that globi dug out of our mess, and develop protocols to prevent such things going forward" seems a lot more actionable; I hope that's where this might lead, but of course that would require some action from the collections (or maybe Arctos as an entity??) as well.

@campmlc @Jegelewicz

**Comment by jhpoelen** [comment]
@debpaul What would it take to add host vouchers to GenBank records given that the list of Arctos host records and nuccore records are known? (see above)

**Comment by jhpoelen** [comment]
e.g., 

now:
```
/organism="Soboliphyme baturini"
                     /organelle="mitochondrion"
                     /mol_type="genomic DNA"
                     /host="Martes caurina"
                     /specimen_voucher="NK122498; Museum of Southwestern
                     Biology"
                     /db_xref="taxon:241478"
                     /country="USA"
                     /lat_lon="57.13 N 134.32 W"
```

suggested:

```
/organism="Soboliphyme baturini"
                     /organelle="mitochondrion"
                     /mol_type="genomic DNA"
                     /host="Martes caurina"
                     /host_specimen_voucher="MSB:Mamm:197697" <--- addition
                     /specimen_voucher="NK122498; Museum of Southwestern
                     Biology"
                     /db_xref="taxon:241478"
                     /country="USA"
                     /lat_lon="57.13 N 134.32 W"
```

**Comment by campmlc** [comment]
@jhpoelen @dustymc Apologies for not being able to attend to this very interesting discussion more thoroughly - I'm dealing with equipment failure in the collection. Here are some comments based on what I've been able to follow.
The current model is to catalog the parasite separately and associate the GenBank accession with the parasite catalog number. But that was not the case for at least a decade before we had parasite databases in Arctos, and that doesn't work for viral sequences, which are not yet being given separate catalog numbers. Adding "host of" a viral or parasite sequence at ncbi makes sense in that case.
But we do have existing relationships in Arctos that specify "host of" and the related guid - see https://arctos.database.museum/guid/MSB:Mamm:197697. Can't these be harvested and used to sort out the existing knownrelationships, so we can focus on the legacy ones?
![image](https://user-images.githubusercontent.com/14808196/152587718-4de06143-36dc-46a9-8c00-a8005280503c.png)

**Comment by campmlc** [comment]
Here is the linked parasite record from the host. What this record needs is to have the GenBank accessions specific to the parasite added to this record and removed from the host record. Again, we need the dedicated person hours to do this, but the model works.
![image](https://user-images.githubusercontent.com/14808196/152588340-595d334b-96cf-4143-9404-fba09d7c5bfd.png)

**Comment by debpaul** [comment]
@jhpoelen et al, I wrote a quick note to Pam Soltis, Jerry Lanfear, Ruth Timme to get an update on what fields were changed to recommended, what fields were added or can be added ... to link specimens as hosts and what other data might be available to cross link such as (SEQ of host, SEQ of parasite, SEQ of virus and of course each of these objects with a repository of any possible tissue of origin / etc).

**Comment by jhpoelen** [comment]
@debpaul Thanks! Curious what they have to say about it.

**Comment by jhpoelen** [comment]
@campmlc Thanks for pointing our the examples, and thanks for being patient we me as I am trying to understand how I can contribute to the discoverability y'all's records.

**Comment by debpaul** [comment]
> Going to some funding agency with "our data are a mess" probably won't work out very well. Going to some funding agency with "we'd like to hire someone to fix these 12345 problems that globi dug out of our mess, and develop protocols to prevent such things going forward" seems a lot more actionable; I hope that's where this might lead, but of course that would require some action from the collections (or maybe Arctos as an entity??) as well.

In other works, stopping the pile up of legacy unlinked data is something compelling for funding. Makes sense. But the backlog could use work so that these data (very valuable historical data) can be realized. Makes sense Dusty.

**Comment by jhpoelen** [comment]
Here's an example of recently indexed host - virus  relation between Arctos and GenBank - demonstrating how GloBI can help enrich links between GenBank accessions to Arctos specimen.

Example - https://arctos.database.museum/guid/MSB:Mamm:148558 

And related query https://www.globalbioticinteractions.org/?accordingTo=http%3A%2F%2Farctos.database.museum%2Fguid%2FMSB%3AMamm%3A148558&interactionType=interactsWith

for GenBank accessions https://www.ncbi.nlm.nih.gov/nuccore/KM201411 

Note that in the remarks of the Arctos host record it says "Remarks: Symbiotype of Artybash virus. Cited as Amga virus in Genbank accessions. "

Does this mean that the (initial) GenBank taxonomic identification is outdated? 

![Screenshot from 2022-02-07 14-25-25](https://user-images.githubusercontent.com/1084872/152883890-cb8e00a0-6607-4f6e-a43b-f7cec3d05082.png)
![Screenshot from 2022-02-07 14-32-26](https://user-images.githubusercontent.com/1084872/152883911-b9f53516-8bd1-4131-97f8-ecbd93c2cf21.png)

![Screenshot from 2022-02-07 14-37-19](https://user-images.githubusercontent.com/1084872/152883971-0773e127-4f00-41ee-9634-f4490c63627f.png)

**Comment by campmlc** [comment]
Re-opening. @jhpoelen  did you resolve the virus name?
What did  you use to resolve to the correct host? I see that the MSB catalog number is cited in the GenBank record in the title (incorrectly, without the full DwC triplet) and again under "strain" which seems an odd place to put it - again, problem with submitting authors not knowing the appropriate format.
However, the correct host was also linked from MSB via the Linkout function to the right. This is where the museum has control over the linkage, and where we can create correct linkages if they do not exist. Can you access these linkouts via GloBI?
![image](https://user-images.githubusercontent.com/14808196/152887158-6d104844-b06a-4c53-9101-04615f21ce99.png)

**Comment by campmlc** [comment]
Thanks for the quick reply - can you confirm that your scripts do indeed
find the linkouts? Because that is critical, since linkouts are the only
way that museum staff have of creating correct links to the specimen if the
author fails to do so correctly. We update our links to GenBank
periodically by downloading accession reports from ncbi and re:uploading
linkouts to matched records from within Arctos. This automatically creates
the reciprocal linkout at GenBank.

**Comment by jhpoelen** [comment]
@campmlc I am using *only* the NCBI links as specified in Arctos records, am not (yet?) using the LinkOut records directly, because I am assuming that these are derived from your Arctos records.

Please confirm that the linkout record submitted to NCBI are derived from links specified in Arctos record.

**Comment by campmlc** [comment]
Yes, that should be the case!

**Comment by jhpoelen** [comment]
@campmlc thanks for confirming.

So if I understand it correctly, the current way that GloBI connects Arctos <> GenBank accessions gives similar result to when the LinkOut records are used instead. 

If there's any suggestions / comment you have before we resolve this first pass at helping to uncover host-virus linked records, please holler.

**Comment by campmlc** [comment]
Yes, that is correct to my understanding. The broader issue of whether the
linkout goes to the host voucher or to the parasite or virus is definitely
something that GloBI can provide that Arctos currently does not make clear
for some legacy records.
