### ISSUE TITLE
Vimeo "2 minute GloBI introduction video" not available

### ISSUE THREAD

**Issue by danstowell** [globalbioticinteractions/globalbioticinteractions#756]
Hi - the Vimeo "2 minute GloBI introduction video" is not available to users who are not logged in to Vimeo. Vimeo says this is because "Video not rated".

I assume someone needs to log in and label it as having no adult content. Thanks

**Comment by jhpoelen** [comment]
@danstowell Thanks for sharing. I've updated the settings to "all audiences" (see attachment).

Please verify and close this issue if you can see the video without logging in.

**Comment by danstowell** [comment]
Thanks! Works.
