### ISSUE TITLE
Problems in dwca-by-study.zip taxa.tsv file

### ISSUE THREAD

**Issue by KatjaSchulz** [globalbioticinteractions/globalbioticinteractions#757]
In the current snapshot of the [dwca-by-study.zip](https://zenodo.org/record/5708970/files/dwca-by-study.zip) there are over 3000 taxa with invalid taxonRank values and it looks like the scientificName values for these records are also messed up. All of these taxa originate from NCBI. Here's an example:
NCBI:1000585 has scientificName:77/2007	and taxonRank:77/2007	
The correct values should be scientificName:Montano orthohantavirus and taxonRank:species
see https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=1000585				

I'm attaching a file with all the problematic taxa I could find.

[GloBIrankProblems.txt](https://github.com/globalbioticinteractions/globalbioticinteractions/files/8005159/GloBIrankProblems.txt)

**Comment by jhpoelen** [comment]
@KatjaSchulz thanks for sharing! Hoping to have a look sooner rather than later.

**Comment by jhpoelen** [comment]
ps. which version of dwca-by-study.zip did you use?

**Comment by jhpoelen** [comment]
I was able to trace the suspicious names to GloBI's interpretation of DRodVir. 

```
$ curl --silent "https://depot.globalbioticinteractions.org/reviews/globalbioticinteractions/drodvir/indexed-interactions.tsv.gz" | gunzip | grep "1000585" | grep "77/2007"
https://en.wiktionary.org/wiki/support						NCBI:99538			 | NCBI:99538	Cricetidae | 	family | specieshttp://purl.obolibrary.org/obo/RO_0002453	hostOf				NCBI:1000585	77/2007	77/2007	 | NCBI:1000585 | 	Hantaviridae | Montano virus | 77/2007	family | species | strain					2007-05-14T00:00:00Z				Mexico Guerrero		http://www.ncbi.nlm.nih.gov/pubmed/32880628	Mauldin MR, McCollum AM, Nakazawa YJ, Mandra A, Whitehouse ER, Davidson W, Zhao H, Gao J, Li Y, Doty J, Yinka-Ogunleye A, Akinpelu A, Aruna O, Naidoo D, Lewandowski K, Afrough B, Graham V, Aarons E, Hewson R, Vipond R, Dunning J, Chand M, Brown C, Cohen-Gihon I, Erez N, Shifman O, Israeli O, Sharon M, Schwartz E, Beth-Din A, Zvi A, Mak TM, Ng YK, Cui L, Lin RTP, Olson VA, Brooks T, Paran N, Ihekweazu C, Reynolds MG, Exportation of Monkeypox virus from the African continent. J Infect Dis 2020,  in Press.	globalbioticinteractions/drodvir	Chen L, Liu B, Wu Z, Jin Q, Yang J, 2017. DRodVir: A resource for exploring the virome diversity in rodents. J Genet Genomics. 44(5):259-264.	https://github.com/globalbioticinteractions/drodvir/archive/e7db3979b80629cf92830e6905568fe199d251b2.zip	2022-01-29T00:33:19.165Z	f0b6bafa0ba29bcec6c61ff18ae7514e4898bdca8340afa60db90d93056848e4	0.12.1
```

note that the ```77/2007``` appears to be the strain name. Also, the linked ncbi id does refer to the species, not the strain.

**Comment by jhpoelen** [comment]
The taxonRank of ```77/2007``` appears to be a parsing error. 

@KatjaSchulz would you like to ignore the strain name altogether to and link to the species instead?

**Comment by jhpoelen** [comment]
Finally, I checked some of the names / tax ids.
 
Some of them using strain name (e.g., ```96/2006```), but appears to link id to a species name (e.g., https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=1000587, NCBI:txid1000587, Huitzilac virus) .

I suspect that the names might have been updated later.

What I can do in globi's taxon graph, is to rematch all ncbi ids to make sure that most current names and taxonomic ranks are provided. 

Please share comments if you have any. Otherwise, please allow for some time for changes to propagate and globi's taxon graph to be updated.

Thanks!

**Comment by KatjaSchulz** [comment]
Thanks for your quick response. I think your theory about names changing on NCBI is plausible. If you could fetch the current name from NCBI that would be great.

**Comment by jhpoelen** [comment]
fyi @KatjaSchulz - still planning to address this taxonomic mapping issue sooner rather than later.

**Comment by jhpoelen** [comment]
Here's the updated taxon graph publication:

Poelen, Jorrit H. (2022). Global Biotic Interactions: Taxon Graph (0.3.36) [Data set]. Zenodo. https://doi.org/10.5281/zenodo.6394935

**Comment by jhpoelen** [comment]
@KatjaSchulz after upgrade to GloBI taxon graph 0.3.36, the following dwc by study snapshot result was generated:

```
$ unzip -p eol-globi-datasets-1.1-SNAPSHOT-darwin-core-aggregated.zip taxa.tsv | mlr --tsvlite cut -f taxonRank | sort | uniq -c | sort -nr
 386228 species
  43681 genus
  41152 
   9590 family
   8038 subspecies
   3032 variety
   2272 order
   1333 class
    479 subfamily
    276 form
    200 tribe
    145 suborder
    136 phylum
    135 superfamily
    129 subgenus
     72 strain
     60 subclass
     41 infraorder
     40 superorder
     33 subtribe
     29 kingdom
     29 forma specialis
     28 subphylum
     12 infraclass
      9 section
      6 subsection
      3 superkingdom
      3 subkingdom
      3 species group
      3 series
      3 infraphylum
      2 superphylum
      2 superclass
      2 subterclass
      2 parvorder
      1 taxonRank
      1 supertribe
      1 epifamily
      1 cultivar
```

The results support that the suspicious taxonRanks that you reported are not longer present. 

For instance, from the GloBIrankProblems.txt file you shared, none of the funny rank name are present. 

Please confirm by closing this issue. If you can't confirm, please provide additional information to help analyze the remaining issue.

```
$ cat GloBIrankProblems.txt | mlr --tsvlite cut -f taxonRank | sort |uniq -c | sort -nr | head
      5 lcs_hejia
      5 bs12
      4 239/08
      4 2
      3 r966
      3 lcs_huangxiong
      3 176/09
      2 uk 2010
      2 rn/haikou/china
      2 r924
```

**Comment by KatjaSchulz** [comment]
It looks like the [dwca-by-study.zip snapshot](https://depot.globalbioticinteractions.org/snapshot/target/eol-globi-datasets-1.1-SNAPSHOT-darwin-core-aggregated.zip) has been updated, but [dwca-by-study.zip stable](https://zenodo.org/record/5708970/files/dwca-by-study.zip) still has the old version. I assume there will be an updated version of the stable file soon?

**Comment by jhpoelen** [comment]
@KatjaSchulz new stable release made on request . . . are you requesting one?

**Comment by KatjaSchulz** [comment]
I'm not sure where exactly our code picks up the GloBI source files and whether a request to update the stable release is part of the workflow. @eliagbayani or @jhammock may know more. We just updated GloBI, and the harvested file still has the rank problems. Since harvesting GloBI is a heavy lift, it probably won't get reharvested for a while, so there is no urgent need to update the stable release immediately.

**Comment by jhpoelen** [comment]
@KatjaSchulz please share which problem remain. I am hoping to resolve issues sooner rather than later to keep the GloBI <> EOL bridge up-to-date.

**Comment by KatjaSchulz** [comment]
Will consult with @eliagbayani & @jhammock and report back if anything needs to be done.

**Comment by jhammock** [comment]
Yes, we use the snapshot, and I think ensuring we find the latest version was recently worked out in #751 .

:)

**Comment by KatjaSchulz** [comment]
Cool, the snapshot is fixed, so there is no further action needed here.

**Comment by jhpoelen** [comment]
@KatjaSchulz Hmm, I guess the stable version should be updated. . . 

Thanks for confirming that you are good to go, and thanks for the nudge to update the stable release. 

Also, please keep those review notes coming any time you see weirdness in the indexed records.

Thanks for being patient.

**Comment by jhpoelen** [comment]
GloBI data pub v0.4 should include the fix now. 

See 

GloBI Community. (2022). Global Biotic Interactions: Interpreted Data Products (0.4) [Data set]. Zenodo. https://doi.org/10.5281/zenodo.6604060
