### ISSUE TITLE
"mute" or exclude forked co-roosting dataset from being indexed

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions#764]
as documented by @arw36  https://covid19taf.slack.com/archives/C011W4GPXDX/p1645634618147429 and attached screenshot

[@Jorrit Poelen (GloBI)](https://covid19taf.slack.com/team/U0128HD3TTJ) How does GLOBI make sure that duplicates don't occur when folks fork an interactions repository? Appears the co-roosting dataset is popping up multiple times from "forks"

![image](https://user-images.githubusercontent.com/1084872/155387636-69920acd-79eb-42d1-8545-7e6d8a5811ef.png)
![image](https://user-images.githubusercontent.com/1084872/155387656-72d07e5c-3c17-4225-a6ac-bbd230c3d0f0.png)

![Screenshot from 2022-02-23 12-53-09](https://user-images.githubusercontent.com/1084872/155387873-d567cd90-e2de-4a47-9932-e9f55d545050.png)

**Comment by jhpoelen** [comment]
@arw36 @kephelps which bat co-roosting dataset would you like GloBI to index?

https://github.com/globalbioticinteractions/bat-co-roosting-database 

or

https://github.com/ecohealthalliance/bat-co-roosting-database

**Comment by arw36** [comment]
https://github.com/globalbioticinteractions/bat-co-roosting-database

**Comment by jhpoelen** [comment]
@arw36 thanks! I've added https://github.com/ecohealthalliance/bat-co-roosting-database to list of datasets to "mute" from indexing via https://github.com/ecohealthalliance/bat-co-roosting-database . The changes should propagate in days. Thanks for being patient and let me know if you have other ideas on how to curate the list of datasets that GloBI indexes. 

Otherwise, please close this issue.

**Comment by jhpoelen** [comment]
I just confirmed that https://github.com/ecohealthalliance/bat-co-roosting-database is no longer being indexed as suggested. 

Closing issue. 

@arw36 please let me know if you have additional datasets that need to be excluded from GloBI indexing.

**Comment by arw36** [comment]
Is there a way to flag when new sources are a fork of an already established source? This is a persistent issue particularly with the template file: 

e.g. : 

https://github.com/qgroom/bat-co-roosting-database 

 @karelTole/template-dataset

 @qgroom/template-dataset
