### ISSUE TITLE
suggest to index CropPol by Ignasi Bartomeus 

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions#777]
as presented during 2022-03-29 by Ignasi Bartomeus 

 Allen-Perkins A, Magrach A, Dainese M, Garibaldi LA, Kleijn D, Rader R, Reilly JR, Winfree R, Lundin O, McGrady CM, Brittain C, Biddinger DJ, Artz DR, Elle E, Hoffman G, Ellis JD, Daniels J, Gibbs J, Campbell JW, Brokaw J, Wilson JK, Mason K, Ward KL, Gundersen KB, Bobiwash K, Gut L, Rowe LM, Boyle NK, Williams NM, Joshi NK, Rothwell N, Gillespie RL, Isaacs R, Fleischer SJ, Peterson SS, Rao S, Pitts-Singer TL, Fijen T, Boreux V, Rundlöf M, Viana BF, Klein AM, Smith HG, Bommarco R, Carvalheiro LG, Ricketts TH, Ghazoul J, Krishnan S, Benjamin FE, Loureiro J, Castro S, Raine NE, de Groot GA, Horgan FG, Hipólito J, Smagghe G, Meeus I, Eeraerts M, Potts SG, Kremen C, García D, Miñarro M, Crowder DW, Pisanty G, Mandelik Y, Vereecken NJ, Leclercq N, Weekers T, Lindstrom SAM, Stanley DA, Zaragoza-Trello C, Nicholson CC, Scheper J, Rad C, Marks EAN, Mota L, Danforth B, Park M, Bezerra ADM, Freitas BM, Mallinger RE, Oliveira da Silva F, Willcox B, Ramos DL, D da Silva E Silva F, Lázaro A, Alomar D, González-Estévez MA, Taki H, Cariveau DP, Garratt MPD, Nabaes Jodar DN, Stewart RIA, Ariza D, Pisman M, Lichtenberg EM, Schüepp C, Herzog F, Entling MH, Dupont YL, Michener CD, Daily GC, Ehrlich PR, Burns KLW, Vilà M, Robson A, Howlett B, Blechschmidt L, Jauker F, Schwarzbach F, Nesper M, Diekötter T, Wolters V, Castro H, Gaspar H, Nault BA, Badenhausser I, Petersen JD, Tscharntke T, Bretagnolle V, Willis Chan DS, Chacoff N, Andersson GKS, Jha S, Colville JF, Veldtman R, Coutinho J, Bianchi FJJA, Sutter L, Albrecht M, Jeanneret P, Zou Y, Averill AL, Saez A, Sciligo AR, Vergara CH, Bloom EH, Oeller E, Badano EI, Loeb GM, Grab H, Ekroos J, Gagic V, Cunningham SA, Åström J, Cavigliasso P, Trillo A, Classen A, Mauchline AL, Montero-Castaño A, Wilby A, Woodcock BA, Sidhu CS, Steffan-Dewenter I, Vogiatzakis IN, Herrera JM, Otieno M, Gikungu MW, Cusser SJ, Nauss T, Nilsson L, Knapp J, Ortega-Marcos JJ, González JA, Osborne JL, Blanche R, Shaw RF, Hevia V, Stout J, Arthur AD, Blochtein B, Szentgyorgyi H, Li J, Mayfield MM, Woyciechowski M, Nunes-Silva P, Halinski de Oliveira R, Henry S, Simmons BI, Dalsgaard B, Hansen K, Sritongchuay T, O'Reilly AD, Chamorro García FJ, Nates Parra G, Magalhães Pigozo C, Bartomeus I. CropPol: A dynamic, open and global database on crop pollination. Ecology. 2022 Mar;103(3):e3614. doi: 10.1002/ecy.3614. Epub 2022 Feb 17. PMID: 34921678.

**Comment by jhpoelen** [comment]
see also Allen-Perkins, Alfonso, Magrach, Ainhoa, Dainese, Matteo, Garibaldi, Lucas A., Kleijn, David, Rader, Romina, Reilly, James R., et al. 2022. “ CropPol: A Dynamic, Open and Global Database on Crop Pollination.” Ecology 103( 3): e3614. https://doi.org/10.1002/ecy.3614 via @mtrekels et al. via https://docs.google.com/spreadsheets/d/1OYj0-i0ped4FNQls2k-emHmpt--TceDrHlZoR8ASKp8/edit#gid=0

**Comment by jhpoelen** [comment]
See duplicate at #946

**Comment by jhpoelen** [comment]
see https://github.com/ibartomeus/OBservData by @ibartomeus .

**Comment by jhpoelen** [comment]
See first attempt at creating GloBI index configuration at:

https://github.com/globalbioticinteractions/OBservData

**Comment by ibartomeus** [comment]
Done! Thanks for taking care of this.
