### ISSUE TITLE
suggest to index Database of Pollinator  > Interactions (DoPI) (https://www.dopi.org.uk/)

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions#780]
As suggested by @ZekeMarshall - 

index Database of Pollinator Interactions (DoPI) (https://www.dopi.org.uk/)

**Comment by ZekeMarshall** [comment]
Follow up email sent today, 2022-06-1.

**Comment by jhpoelen** [comment]
also mentioned in https://docs.google.com/spreadsheets/d/1OYj0-i0ped4FNQls2k-emHmpt--TceDrHlZoR8ASKp8/edit#gid=0 by @mtrekels et al.

**Comment by ZekeMarshall** [comment]
Follow up email sent today 2022-11-14

**Comment by jhpoelen** [comment]
@ZekeMarshall thank you for sending the follow-up email to the DoPI folks! Curious to hear about their response (if any).

**Comment by jhpoelen** [comment]
Just took a first stab at indexing DoPI (or parts of it) via https://github.com/globalbioticinteractions/dopi

@ZekeMarshall please do share thoughts if you have any. 

fyi @zedomel @filipi-soares

**Comment by jhpoelen** [comment]
A first data review -

from the abstract - 

> The dataset under review (aka globalbioticinterac-
tions/dopi) has size 5.36MiB and contains 17847 interactions with 1 (e.g.,
pollinatedBy) unique types of associations between 1240 primary taxa
(e.g., Heracleum sphondylium) and 1887 associated taxa (e.g., Bombus
pascuorum). The report includes detailed summaries of interactions data
as well as a taxonomic review from multiple perspectives.

For more detail, see attached pdf . 

[dopi-review-2023-12-01.pdf](https://github.com/globalbioticinteractions/globalbioticinteractions/files/13533007/dopi-review-2023-12-01.pdf)

**Comment by ZekeMarshall** [comment]
Hi @jhpoelen , this is great to see, thanks for indexing the data! :)
