### ISSUE TITLE
make references clickable  add Arctos branded logos for Arctos references

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions#791]
suggest to make "http://arctos.database.museum/guid/MSB:Mamm:148794" as part of the citation string clickable. 

Also, customize the [📄](http://arctos.database.museum/guid/MSB:Mamm:148794) to be 
![image](https://user-images.githubusercontent.com/1084872/167227569-06ae1f56-f5c2-4704-8c11-954d366f4fdd.png) . 

![Screenshot from 2022-05-06 18-25-28](https://user-images.githubusercontent.com/1084872/167227488-aeb735ba-ac8d-4c38-ac20-a90633b65481.png)

**Comment by jhpoelen** [comment]
I hope there's similar artwork like GloBI's https://github.com/globalbioticinteractions/logo .

**Comment by ewommack** [comment]
corrected link: https://arctos.database.museum/guid/MSB:Mamm:148794

**Comment by jhpoelen** [comment]
https://github.com/ArctosDB/documentation-wiki/tree/gh-pages/images 

https://raw.githubusercontent.com/ArctosDB/documentation-wiki/gh-pages/images/favicon128.png 

https://github.com/ArctosDB/documentation-wiki/blob/gh-pages/images/favicon128.png 

https://github.com/ArctosDB/documentation-wiki/tree/gh-pages/images/icons/arctos

**Comment by Jegelewicz** [comment]
Here is the teeny bear - https://raw.githubusercontent.com/ArctosDB/documentation-wiki/gh-pages/images/favicon16.png

**Comment by Jegelewicz** [comment]
@jhpoelen where is that link coming from? All Arctos links should now be "https". Just want to make sure we aren't sending out old "http" stuff somehow!

**Comment by ewommack** [comment]
should we try for GLoBI logo links in Arctos too?

**Comment by jhpoelen** [comment]
> @jhpoelen where is that link coming from? All Arctos links should now be "https". Just want to make sure we aren't sending out old "http" stuff somehow!

As far as I know, the links are coming from the DwC-A ```references``` column as provided via Vertnet.

**Comment by jhpoelen** [comment]
As suggested, GloBI search pages now insert a tiny little Arctos bear. Also, it makes citations clickable is a link is available.

![Screenshot from 2022-05-06 19-51-47](https://user-images.githubusercontent.com/1084872/167231388-267a285b-b4e2-4351-89ac-bb7b0b44e9f2.png)

**Comment by jhpoelen** [comment]
Closing issue, please comment if you feel additional work needs to be done to implement this feature.

**Comment by jhpoelen** [comment]
> should we try for GLoBI logo links in Arctos too?

Here's some logo's in case you choose to insert some https://github.com/globalbioticinteractions/logo .

**Comment by ewommack** [comment]
I created an Arctos issue with wishlist for the GLoBI link logo: https://github.com/ArctosDB/arctos/issues/4660

not sure if it might be possible, but now it is out there.

**Comment by jhpoelen** [comment]
@ewommack thanks! Logo's are pretty neat especially when they look like cute little bears ; )
