### ISSUE TITLE
Add Symbiota icon to GloBI records

### ISSUE THREAD

**Issue by seltmann** [globalbioticinteractions/globalbioticinteractions#795]
For records coming from a Symbiota portal, can you add the Symbiota icon?

https://symbiota.org/wp-content/uploads/cropped-LogoSymbiotaSquare.jpg-32x32.png

For example, data from the macroalgae portal (in the image below) would have the Symbiota icon before the records.

![Screen Shot 2022-05-20 at 2 16 20 PM](https://user-images.githubusercontent.com/1044474/169611821-29074e28-38db-4d6b-9958-aa277154af53.png)

@egbot GloBI is doing this for Arctos already! @ewommack, @Jegelewicz 
Related issue: https://github.com/globalbioticinteractions/globalbioticinteractions/issues/791

**Comment by jhpoelen** [comment]
@seltmann thanks for your suggestion!

I've added the symbiota logo for links resembling symbiota (with regex including ```occid=[0-9]+```) . 

See attached screenshot 

![Screenshot from 2022-05-20 16-37-26](https://user-images.githubusercontent.com/1084872/169615982-da72b6a5-172e-44d8-b6c4-3190aa9a7a59.png)

@egbot any suggestions on how to make the Symbiota logo more prominent? Do you have a cute bear like Arctos also?

**Comment by jhpoelen** [comment]
@seltmann please close this issue if you feel your issue has been addressed. Otherwise, please comment on how to improve/ change added func. 

see e.g., https://www.globalbioticinteractions.org/?accordingTo=globi%3Aglobalbioticinteractions%2Fucsb-izc&interactionType=interactsWith for  interaction claims backed up by UCSB ICZ specimen.

**Comment by jhpoelen** [comment]
Am closing issue, @seltmann please feel free to re-open if you feel the issue has not been addressed.
