### ISSUE TITLE
integrate with Mangal

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions#81]
In an [OpenTree hack-a-thon idea discussion](https://github.com/OpenTreeOfLife/hackathon/issues/13), @tpoisot and I @jhpoelen connected to explore ways to connect [Mangal](http://mangal.uqar.ca/) with GloBI. I've opened this issue to keep track of the collaboration and promote discussion.

**Comment by tpoisot** [comment]
Since @seltmann restarted this discussion, it could be worth discussing ways of moving forward. I think DWC could be a good (if temporary) solution. Step 1 would be to establish a map between the mangal format and DWC terms.

**Comment by jhammock** [comment]
@tpoisot Jen Hammock here, from eol.org. Just found your paper. Thanks for including us as a names source! You may already know that we consume GloBI data and display it to our visitors. You have all the expertise you need, I expect, but if you have questions about where to put all your attribution (by Contributor X, in MANGAL, using references 1,2,3, via GloBI is a lot of layers) you can holler for me. We've been here before. There's room for everything!

**Comment by tpoisot** [comment]
@jhammock Sounds interesting. I'm a bit time-limited at the moment, but I think it is an interesting project. If it's "only" a matter of serving files in a particular format, it should not be too difficult (especially if you have a template?).

**Comment by jhammock** [comment]
I think there's quite a bit of flexibility if you flow your data via GloBI. @jhpoelen , perhaps you can point us to a sample or two? Are all the GloBI input files public?

**Comment by jhpoelen** [comment]
Yep, all the GloBI input files are publicly available. 

Here's a sample of a flat tabular format we've been using:
interactions.tsv in https://github.com/globalbioticinteractions/template-dataset 

Another example more darwin core archive oriented example is from @seltmann : 
http://amnh.begoniasociety.org/dwc/AEC-TTD-TCN_DwC-A20150318.zip

There's various other file formats. If you pick one of the above, ingesting Mangal data would be a matter of some configuration. Otherwise, we'd have to write a little ingestion / import script. Either would work, as long as the format is machine readable.

Hope this helps.

**Comment by tpoisot** [comment]
Assuming I return a JSON file, that would follow `interactions.tsv` closely, would it work for you?

I can make that a fixed point in the URL schemes, then you should be able to read from it, correct?

**Comment by tpoisot** [comment]
Specifically, this would be the type of JSON:

~~~ json
[

{

    "interactionTypeName": "pollinates",
    "targetTaxonName": "Phacelia secunda",
    "decimalLatitude": "-33.2833",
    "decimalLongitude": "-70.2667",
    "sourceTaxonName": "Scaeva melanostoma",
    "interactionTypeId": "RO_0002455"

},
{

    "interactionTypeName": "pollinates",
    "targetTaxonName": "Senecio bustillosianus",
    "decimalLatitude": "-33.2833",
    "decimalLongitude": "-70.2667",
    "sourceTaxonName": "Scaeva melanostoma",
    "interactionTypeId": "RO_0002455"

},
{

    "interactionTypeName": "pollinates",
    "targetTaxonName": "Stachys albi",
    "decimalLatitude": "-33.2833",
    "decimalLongitude": "-70.2667",
    "sourceTaxonName": "Scaeva melanostoma",
    "interactionTypeId": "RO_0002455"

},
{

    "interactionTypeName": "pollinates",
    "targetTaxonName": "Adesmia conferta",
    "decimalLatitude": "-33.2833",
    "decimalLongitude": "-70.2667",
    "sourceTaxonName": "Scaeva melanostoma",
    "interactionTypeId": "RO_0002455"

},
{

    "interactionTypeName": "pollinates",
    "targetTaxonName": "Calandrinia affinis",
    "decimalLatitude": "-33.2833",
    "decimalLongitude": "-70.2667",
    "sourceTaxonName": "Scaeva melanostoma",
    "interactionTypeId": "RO_0002455"

}
]
~~~

**Comment by jhpoelen** [comment]
@tpoisot looks great! I'd prefer csv, but adding json probably makes sense. Some fields I would expect in addition (if available) would be: citation / doi / source / lifestage etc.). This way, folks can trace the interaction record to the source and be able to access data at most granular level. Also, if you have a targetTaxonId for ITIS, please add it also, preferably in the shorthand. If you'd like to link back to mangal, please provide a specimenId or recordId of sorts along with a url scheme. If you'd like to link on the study level, please provide a referenceURL / id of sorts. Hope this makes sense. Otherwise, please holler.

```json
[{

    "targetTaxonId": "ITIS:123456",
    "targetTaxonName": "Phacelia secunda",
    "interactionTypeName": "pollinates",
    "interactionTypeId": "RO_0002455",
    "sourceTaxonId": "ITIS:123456",
    "sourceTaxonName": "Scaeva melanostoma",
    "decimalLatitude": "-33.2833",
    "decimalLongitude": "-70.2667",
    "observationDateTime": "1933-11-18T06:37:04Z",
    "referenceDoi":"doi:somedoi",
    "referenceCitation":"Donald Duck. 1934. On parasites of ducks. Cartoon Ecology.",
}
]
```

**Comment by jhpoelen** [comment]
If you need some inspiration, I'd suggest to poke around Sarah Miller's @millerse repositories https://github.com/millerse?tab=repositories . Sarah works with @jhammock and added a ton of interaction data using tsv / github method.

**Comment by tpoisot** [comment]
Cool. I will work on that. The other issue is that mangal uses a specification for interaction types which is finer than OBO

For example, here: https://github.com/mangal-wg/mangal-standalone/commit/cd2f985fbfbb126114ac5f71576083243099b799#diff-c5c7912985956937025d37d338764d7bR22

But as for the other things, it won't be an issue. I will definitely add a  `recordId`.

**Comment by jhpoelen** [comment]
@tpoisot nice! looking forward to making mangal discoverable through GloBI. 

I've added some issues (see refs in this thread) with requests for new RO terms. Please feel free to follow my example . . . 

Just curious - it seem to me that herbivory is simply eating plants right? So, this can be derived from the classification of the customer / resource taxa. E.g. if cow is eating a plant, than it is a herbivory interaction. Why would you want to include redundant information in the interaction type?

**Comment by tpoisot** [comment]
Creating the list of interaction types has been an ongoing effort, that took a few months of emailing and in-person meetings. Simply said, we wanted as many types of interactions as possible, because we (the co-authors of the mangal paper) are working on interactions. So sometimes we *can* infer herbivory, sometimes not. On the other hand, we can *always* define trophic = {herbivory + predation}; it's not really redundant information, as it is a very fine-grained classification. Some of the drafts were maybe twice or thrice as long...

**Comment by jhpoelen** [comment]
Thanks for providing the context. Perhaps better to push the mangal types over as is (with an mangal id that resolves to some definition). This would than push the mapping to GloBI side, so that we can simply introduce more granular terms as they become available. So, in summary: suggest to use RO terms when it maps perfectly, otherwise please use the (more specific) mangal interaction types. Curious to hear your thoughts.

**Comment by tpoisot** [comment]
OK, so I could be able to use the internal mangal types, but I would need to add an ID. Got it.

I will try to work on this later this week.

**Comment by tpoisot** [comment]
By the way, what do you think is the best solution? I can serve one file for all interactions but it will get large (we're at ~7500 at the moment, and it will definitely grow in the next three months). Or I can serve a file by dataset. And, possibly, a file for interactions that are not assigned to a dataset.

**Comment by jhpoelen** [comment]
I'd prefer one big csv/tsv file (e.g. [interaction.tsv](https://github.com/globalbioticinteractions/template-dataset/blob/master/interactions.tsv)) that includes all datasets with appropriate attribution (e.g. reference doi, reference citation, reference mangal id, record id). Most published datasets are published as csv (e.g. [Barnes et al. 2008](http://www.esapubs.org/Archive/ecol/E089/051/)). JSON is mostly used for web apis and target javascript-y techie folks. I like the idea to publish data in a format that is fairly technology agnostic and can be opened and used by anyone that can turn on a computer and download a file. 

From experience, I know that a big denormalized file archive hosted at amazon s3 or similar file archive works best to avoid any pagination, joins and database overhead. An advantage of this is that publishing the data to http://figshare.com or similar would be very easy. 

So perhaps a export script that generates a file archive and pushes it to a public place automatically? But hey, if I'd have a choice between getting the data out there fast or wait for a while to get the "perfect" solution, I'd prefer the former.

**Comment by tpoisot** [comment]
Thanks for the feedback. There is something that looks like a plan in my head.

1. I will allow the generation of a big tsv file for each *dataset*. This way, the contributors can take it, submit it to figshare or the like, then get a DOI.
2. I will also probably keep on the big json file for all interactions (tsv would have a lot of missing values, and since it would be served from a cloud machine that I currently pay for myself, I'm wary of any overhead). You could ping that every once in a while, and if it changed, read the new interactions.

Does this sounds reasonable?

**Comment by jhpoelen** [comment]
Definitely sounds reasonable: if it works for you, it'll probably work for GloBI. 

I do want to say that if you are using gzip compression (on the "wire" or in rest), tsv files get pretty small. For example, the taxa.csv.gz file available through http://globalbioticinteractions.org/references.html is 16MB compressed and 212MB uncompressed. For GloBI I have >> GB of data and am currently paying about $1 a month for storage / bandwidth using Amazon S3. So, if this convinces you, I'd recommend to publish a big concatenated tsv of all datasets in addition to the individual tsv per dataset. In large volume data processing software, you'll find that tsv is used quite a bit (e.g. genomics). 

Let me know what you'll end up doing and I'll take a shot at integrating mangal.

**Comment by mjy** [comment]
Did this exploration come to fruition?  Exploring outcomes/consequences for  #373

**Comment by tpoisot** [comment]
We're working on a revised API for Mangal, but have limited bandwidth to integrate with other projects at the moment


(from my phone, pardon brevity, etc)
On Nov 20, 2018, at 10:29, Jorrit Poelen <notifications@github.com<mailto:notifications@github.com>> wrote:

@mjy<https://github.com/mjy> Not yet. I am still waiting to @tpoisot<https://github.com/tpoisot> to reply to my earlier message<https://github.com/jhpoelen/eol-globi-data/issues/81#issuecomment-148440062>.

I do have good experiences with integrating datasets using tsv.gz/bz2 or stream-enabled json.gz/bz2 (one json self-contained object per line). E.g., @carrieseltzer<https://github.com/carrieseltzer> 's https://github.com/globalbioticinteractions/AfricaTreeDatabase using published artifacts at Figshare via Seltzer, Carrie; Wysocki, William; Palacios, Melissa; Eickhoff, Anna; Pilla, Hannah; Aungst, Jordan; Mercer, Aaron; Quicho, Jamie; Voss, Neil; Xu, Man; J. Ndangalasi, Henry; C. Lovett, Jon; J. Cordeiro, Norbert (2015): Plant-animal interactions from Africa. figshare. https://dx.doi.org/10.6084/m9.figshare.1526128 . Also, see wikidata's https://www.wikidata.org/wiki/Wikidata:Database_download#JSON_dumps_(recommended) for json example.

**Comment by jhpoelen** [comment]
GloBI is now indexing Mangal . See https://www.globalbioticinteractions.org/?accordingTo=globi%3Aglobalbioticinteractions%2Fmangal&interactionType=ecologicallyRelatedTo and attached screenshot. 

![Screenshot from 2019-10-20 11-07-21](https://user-images.githubusercontent.com/1084872/67163923-eacca680-f329-11e9-9fd8-6974721610a0.png)
![Screenshot from 2019-10-20 11-05-03](https://user-images.githubusercontent.com/1084872/67163924-eacca680-f329-11e9-8531-567e88fb90e2.png)

fyi @cboettig

**Comment by cboettig** [comment]
@jhpoelen wow, nice! 

Do you have a quick summary of how you addressed some of the issues from the thread -- e.g. does this map/disambiguate between interaction type labels used in Mangal and those in the Globi namespace (sorry, I think globi uses an existing ontology for types but I've forgotten which one now!)?  (Also looks like there's not yet a network-level id?https://github.com/globalbioticinteractions/globalbioticinteractions/issues/418, but that would be cool).

**Comment by tpoisot** [comment]
Mangal has a lot more interaction types, and some additional metadata on everything. Depending on the use case, I think it makes more sense to use it rather than Globi. Just my 2 cents.

**Comment by seltmann** [comment]
Thanks for pointing this out. I did not know the Mangal project existed. Very interesting!

**Comment by cboettig** [comment]
@tpoisot Thanks Tim, that's really cool!  I agree that having a fine-grained interaction type can be super important.  Does Mangal publish the list of all interaction types somewhere?  I was looking at https://mangal.io/doc/api/#interactions which seems to list only 12 types. 

(p.s. I find the tabular format used by Globi to be super convenient to check these kind of things, e.g. 

```r
globi <- vroom::vroom("https://depot.globalbioticinteractions.org/snapshot/target/data/tsv/interactions.tsv.gz")
globi %>% count(interactionTypeName, sort=TRUE)
```

shows me Globi has 34 interaction types:

```
# A tibble: 34 x 2
   interactionTypeName       n
   <chr>                 <int>
 1 eats                1366862
 2 interactsWith        768768
 3 parasiteOf           284376
 4 pathogenOf            83868
 5 hasHost               72418
 6 preysOn               58603
 7 visitsFlowersOf       34028
 8 ectoParasiteOf        22330
 9 coOccursWith          19068
10 pollinates            11593
# … with 24 more rows
```

I'd love to be able to interact with mangal data directly in a similar way. (Though for both databases, it would also be nice if there were an agreed-upon set of implied interaction types, since the listed types are clearly not mutually exclusive!)  


I also agree that additional metadata terms can be critical to see what is going on -- as much as I appreciate  the convenience of vertically integrated databases I've always been wary of lost metadata!  I think having a separate network id instead of just a study id is a big advantage of Mangal; though again, I'm not clear on if there's a better way to discover what other additional metadata fields mangal provides than by skimming the API docs?

**Comment by jhpoelen** [comment]
@cboettig for what it's worth: in the first pass integrating mangal, I mapped the following interaction types. Note how some interaction types are combinations of types / lifestage / target type, so they are mapped to their interaction type. A next interaction would extract lifestage (e.g., scavenger) from the provided interaction type.

source_interaction_type_name | source_interaction_type_id | target_interaction_type_label | target_interaction_type_id
-- | -- | -- | --
competition |   | ecologically related to | http://purl.obolibrary.org/obo/RO_0002321
detritivore |   | eats | http://purl.obolibrary.org/obo/RO_0002470
herbivory |   | eats | http://purl.obolibrary.org/obo/RO_0002470
mutualism |   | mutualist of | http://purl.obolibrary.org/obo/RO_0002442
parasitism |   | parasite of | http://purl.obolibrary.org/obo/RO_0002444
predation |   | preys on | http://purl.obolibrary.org/obo/RO_0002439
scavenger |   | eats | http://purl.obolibrary.org/obo/RO_0002470
symbiosis |   | symbiont of | http://purl.obolibrary.org/obo/RO_0002440
unspecified |   | ecologically related to | http://purl.obolibrary.org/obo/RO_0002321

**Comment by jhpoelen** [comment]
Please submit pull requests if there's better mappings for the interaction types  https://github.com/globalbioticinteractions/mangal/blob/master/interaction_types.csv . 

Also as far as the network_id issue, for now, you can simply group by sourceCitation (e.g., ```https://mangal.io - the ecological interaction database. Accessed at <https://mangal.io/api/v2/network/5013> on 21 Oct 2019``` for now. I am hoping to find a more explicit way to search/group interactions by the network they were published in.  See #418 .

**Comment by jhpoelen** [comment]
@seltmann there's tons of neat projects like Mangal that expose interaction networks / data in their own specific and useful ways . Other examples include http://web-of-life.es , https://globalwebdb.com , https://github.com/FloraVincent/DIDB , and many many more.

**Comment by tpoisot** [comment]
@seltmann the goal is that web of life and globalwebdb will eventually be available through mangal (I think they already are with 100% coverage, in fact)!

**Comment by tpoisot** [comment]
@cboettig / @jhpoelen re. the type of interactions, maybe @steveviss has an idea of how to get it. I don't necessarily agree with the mapping @jhpoelen provided (it's not only lifestages, for example), and I think this is a source of major disagreement among DB which should benefit from being solved. Other than that, the ideas behind globi/mangal are (in my mind) strikingly different - we provide access to metadata-rich information of ecological networks, and globi is aggregating data on interactions. I don't think, for this reason, that feature parity is a priority (and so to anticipate a question I've asked a bit, no, we won't make some elements of mangal more globi-like).

**Comment by jhpoelen** [comment]
@tpoisot I am open to hearing your specific comments on the mappings. I am not quite sure what you mean by "metadata-rich" information. Could you please elaborate?

**Comment by cmungall** [comment]
I am happy to add more specific relationship types to RO, e.g. is in
competition with, eats detritus of(?), ...?

**Comment by tpoisot** [comment]
@jhpoelen we are storing information on the methodology, interaction strength, trait values, environmental context, etc... All of which are important to analyze ecological *networks*.

**Comment by SteveViss** [comment]
Hi @jhpoelen & @cboettig, It will be nice that we use an existing ontology for mangal. For the moment, we controlled the vocabulary using ENUM field. @cboettig, you can easily get the interactions type list with R: `rmangal::avail_type()`. Let me know @jhpoelen if you need something from my side and thanks a lot for the integration !
