### ISSUE TITLE
Max number of rows in R

### ISSUE THREAD

**Issue by BarbaraMeulenbelt** [globalbioticinteractions/globalbioticinteractions#811]
Hi! I'm using R and Rglobi to retrieve Globi data. I am trying to see all the interactions but R always stops at around 1024 rows. Does anybody else have this problem and what can I do about this? I would like to retrieve all the data :)

**Comment by jhpoelen** [comment]
hey @BarbaraMeulenbelt thanks for sharing you concern. 

You're concern reminded my to publish a new release of rglobi with https://github.com/ropensci/rglobi/pull/45 @H-Waters Helen Water's excellent new addition to highlight the need for pagination. Apologies for the delay, hoping to get to it sometime soon.

**Comment by jhpoelen** [comment]
rglobi v0.2.28 has been released on CRAN. This version generates a warning message whenever a limit is reached on the maximum results, and provides pointers to retrieve all the results.

Note also, that you can use data products published via https://globalbioticinteractions.org/data to access *all* data (e.g., interactions.tsv.gz) without have to go through paging Web APIs. 

@BarbaraMeulenbelt please comment on this issue if you feel your concerns has not been addressed. Happy to re-open this issue and continue our conversation. Thanks for your patience.

from https://cran.r-project.org/web/packages/rglobi/index.html - 

![Screenshot from 2022-08-25 09-23-55](https://user-images.githubusercontent.com/1084872/186691266-6b38d25d-ad41-4e7c-a268-1c9416d8e89e.png)
