### ISSUE TITLE
Minckley Lab bee plant data

### ISSUE THREAD

**Issue by seltmann** [globalbioticinteractions/globalbioticinteractions#813]
@jhpoelen please consider indexing https://sas.rochester.edu/bio/sites/minckley/index.php/bee-plant-data/

**Comment by jhpoelen** [comment]
seems to be hosted via google sheets - 

e.g.,

curl -L "https://docs.google.com/spreadsheets/u/0/d/1OgDhj2TUfaZQJBF7XAvzb30ZJoIrccZH7ANCGjJDufs/export?format=tsv" > bees.tsv

**Comment by seltmann** [comment]
Please call it 
Robert L. Minckley San Bernardino Valley from the year 2000 to 2011. https://sas.rochester.edu/bio/sites/minckley/index.php/bee-plant-data/

**Comment by jhpoelen** [comment]
@seltmann thanks! 

Please review https://github.com/globalbioticinteractions/minckly-san-bernardino-valley-2000-2011 .

**Comment by jhpoelen** [comment]
Indexed by GloBI via https://www.globalbioticinteractions.org/?accordingTo=globi%3Aglobalbioticinteractions%2Fminckly-san-bernardino-valley-2000-2011&interactionType=interactsWith


![image](https://github.com/globalbioticinteractions/globalbioticinteractions/assets/1084872/955e2413-e66d-40e3-90e6-b8f58c9f7262)
