### ISSUE TITLE
suggest to review integration with https://arctos.database.museum/guid/UCM:Bird:16319

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions#817]
https://arctos.database.museum/guid/UCM:Bird:16319 contains references to associated parasite specimen. 

But, in the screenshot below, no GloBI link appears. And, it appears that https://arctos.database.museum/guid/UCM:Bird:16319 is not (yet) indexed by GloBI because https://www.globalbioticinteractions.org/?accordingTo=https%3A%2F%2Farctos.database.museum%2Fguid%2FUCM%3ABird%3A16319&interactionType=interactsWith does not yield any results.

![Screenshot from 2022-09-06 15-04-42](https://user-images.githubusercontent.com/1084872/188728382-06e9a5e8-b16e-478a-a867-805c6b6150b6.png)

**Comment by jhpoelen** [comment]
@ebraker On refreshing the GloBI index, the page https://arctos.database.museum/guid/UCM:Bird:16319 now contains a link to GloBI (see screenshot below).

![Screenshot from 2022-09-07 11-57-36](https://user-images.githubusercontent.com/1084872/188937051-2e257689-7f1f-4cf2-a739-375ac7631d3c.png)


Also, https://www.globalbioticinteractions.org/?accordingTo=http%3A%2F%2Farctos.database.museum%2Fguid%2FUCM%3ABird%3A16319&interactionType=interactsWith now yield a result, with the expected unresolved link to UCM:Para (reported separately  in https://github.com/ArctosDB/arctos/issues/5018 ).

![Screenshot from 2022-09-07 11-58-38](https://user-images.githubusercontent.com/1084872/188936987-d6417586-88b1-4ba6-9225-947f0482a4a9.png)

So, as far as I can tell, the link to UCM:Bird:16319 has been re-established as expected. 

Please comment/ holler if there's evidence to suggest that the link is still missing.

**Comment by ebraker** [comment]
Thanks @jhpoelen!
