### ISSUE TITLE
"Uncurated" version of GloBI neo4j

### ISSUE THREAD

**Issue by zedomel** [globalbioticinteractions/globalbioticinteractions#829]
Hi @jhpoelen 

I'm wondering how I can create a "uncurated" version of GloBI neo4j for the DwC-A which I had get from preston instance.

So, I have change the script for find and parse DwC-A. Instead of using `elton interactions` and `elton review` to collect the interactions records found in the DwC-As and the reports, I'm using `elton update -c $ELTON_CACHE_DIR --registry local globi-gbif`. It will create a entry in the local `access.tsv` of `globi-gbif` namespace with `application/globi`:

```tsv
globi-gbif	file:///media/external/projects/globi-gbif/cache/archive/000050cba2f9a0ab1682623294724d960f47d1746e6d65dc1f0fbd88bbc063f7/./		2022-10-18T12:03:27.165Z	appli
cation/globi
globi-gbif	file:///media/external/projects/globi-gbif/cache/archive/000050cba2f9a0ab1682623294724d960f47d1746e6d65dc1f0fbd88bbc063f7/./globi.json	3a3b194f9b0b0fa7aed34f3e18f85cbee9c28
6c74b7cef20a5925c526587f3a0	2022-10-18T12:03:27.328Z	
globi-gbif	file:///media/external/projects/globi-gbif/cache/archive/000050cba2f9a0ab1682623294724d960f47d1746e6d65dc1f0fbd88bbc063f7/./dwca.zip	000050cba2f9a0ab1682623294724d960f47d
1746e6d65dc1f0fbd88bbc063f7	2022-10-18T12:03:27.526Z
``` 

Then I'm using `org.globalbioticinteractions.elton.Elton4N -datasetDir $ELTON_CACHE_DIR` to create a neo4j version with this data. But I need to provide a `-taxonCache` and `taxonMap` in order to the taxonomy incorporate to neo4j db.

For that I'm using [taxon-graph-builder](https://github.com/globalbioticinteractions/taxon-graph-builder) but I'm not sure if this the way things should be done. The `taxon-graph-builder` will create the `taxonMap.tsv.gz` and `taxonCache.tsv.gz` using the names extracted from `elton names -c $ELTON_CACHE_DIR` (all names in DwC-As).

So, how exactly should I do this pipeline to use `Elton4N` to produce a neo4j db?

thanks.

**Comment by jhpoelen** [comment]
@zedomel thanks for sharing your idea! I much like the idea of building another neo4j index from the interaction data you've indexed from GBIF/iDigBio as you described in:

 Salim JA, Seltmann KC, Poelen JH, Saraiva AM (2022) Indexing Biotic Interactions in GBIF data. Biodiversity Information Science and Standards 6: e93565. https://doi.org/10.3897/biss.6.93565 .

Would you want to do any name alignment? Or would just like to use the taxonomic names as provided?

**Comment by zedomel** [comment]
> Would you want to do any name alignment? Or would just like to use the taxonomic names as provided?
What do you mean by name alignment? hehehehe. The `taxon-graph-builder` will use `nomer` to match names in the interactions records against many different catalogues, right? The `Elton4N` will later assign names in taxonMap e taxonCache to the interactions records in the neo4j or not? I'm not sure!

**Comment by jhpoelen** [comment]
@zedomel yes, you can use the taxon-graph-builder to generate taxonMap/Cache for the collection of species interaction data you've discovered in GBIF/iDigBio etc. This would introduce some bias, but will at least make your interaction a little more easier to navigate / search. 

So, if I understand it correctly, you'd like to build your own version of GloBI using only the GBIF/iDigBio dataset and re-use the taxonMap/Cache concept that was introduced to help make species interaction more searchable.

Can you confirm?

**Comment by zedomel** [comment]
@jhpoelen 

> So, if I understand it correctly, you'd like to build your own version of GloBI using only the GBIF/iDigBio dataset and re-use the taxonMap/Cache concept that was introduced to help make species interaction more searchable.
Yes. Is that the way you do for GloBI? Having that setup will be easier to update the results with new additions or version of DwC-A download from the remote preston instance.

Do you see another way to do it? How names are resolved for the datasets published in GitHub/Zenodo before incorporate into GloBI neo4j?

thanks.

**Comment by jhpoelen** [comment]
We can make this work. Can you share one or two examples of the dwca for which you generated globi.json 's ?

**Comment by zedomel** [comment]
@jhpoelen 
`preston cat hash://sha256/002d7f3e3148965d09d33f552b42ec5f050c783e2cc4577b415f8cd0fc5bf198 --remote https://deeplinker.bio> dwca.zip`

*globi.json*:
```json
{
   "format": "dwca",
   "citation": "hash://sha256/002d7f3e3148965d09d33f552b42ec5f050c783e2cc4577b415f8cd0fc5bf198 via hash://sha256/7cd305e9d275763c96e7685847460fcc381b5c97c1460c00441f663c1788800f",
   "url": "dwca.zip"
}
```

Let me know what you are thinking....
thanks.

**Comment by jhpoelen** [comment]
@zedomel thanks for the example. Hmm. I need to think a little about how to best do this. One of the things we'll have to figure out is how to come up with a so-called dataset namespace (e.g., globalbioticinteractions/template-dataset) . Currently, the github/zenodo namespaces (e.g., [user]/[repository] or [org]/[repository] ) are used to group indexed interactions associated with a specific index configuration. Perhaps in your example, we can use the hashes as a namespace . Or, the idigbio/gbif dataset uuids ? Curious to hear your thoughts. 

PS Note that, thanks to @mielliott , you can now also use ```https://linker.bio``` in addition to ```https://deeplinker.bio```. I am using the shorter version because it saves me a few keystrokes.

**Comment by jhpoelen** [comment]
Hey @zedomel - 

I was just talking to @seltmann and found my self saying that we should have elton be handle:

elton interactions hash://sha256/abc123..... --remote https://linker.bio,https://archive.org/

to extract interactions from a preston package/version .

**Comment by zedomel** [comment]
> Hey @zedomel -
> 
> I was just talking to @seltmann and found my self saying that we should have elton be handle:
> 
> elton interactions hash://sha256/abc123..... --remote https://linker.bio,https://archive.org/
> 
> to extract interactions from a preston package/version .

Hi @jhpoelen 
I think that will be very useful. Perhaps it can include an additional parameter `--format` to specify the format of the package/version being used and instruct elton to use a specific parser:

`elton interaction hash://sha256/abc123..... --remote [https://linker.bio,https://archive.org/](https://linker.bio%2Chttps//archive.org/) --format dwca`




> @zedomel thanks for the example. Hmm. I need to think a little about how to best do this. One of the things we'll have to figure out is how to come up with a so-called dataset namespace (e.g., globalbioticinteractions/template-dataset) . Currently, the github/zenodo namespaces (e.g., [user]/[repository] or [org]/[repository] ) are used to group indexed interactions associated with a specific index configuration. Perhaps in your example, we can use the hashes as a namespace . Or, the idigbio/gbif dataset uuids ? Curious to hear your thoughts.
> 
> PS Note that, thanks to @mielliott , you can now also use `https://linker.bio` in addition to `https://deeplinker.bio`. I am using the shorter version because it saves me a few keystrokes.

Locally I have used the hashes (withou hash://sha256 prefix) as namespaces.

**Comment by jhpoelen** [comment]
Please comment / re-open issue if you have additional questions / comments. @zedomel
