### ISSUE TITLE
Create new stable version of GloBI

### ISSUE THREAD

**Issue by seltmann** [globalbioticinteractions/globalbioticinteractions#838]
@jhpoelen in working with the Global Bee Interaction Data, I started using the stable version of Globi to track all bee data indexed. The last stable version was June of 2022. May I suggest publishing a new stable version? I can always use a snapshot and publish it separately.

Thanks!
Katja

**Comment by jhpoelen** [comment]
@seltmann happy to publish a new released of GloBI data index. When do you need it by?

**Comment by seltmann** [comment]
The last ones were published Nov. 17, so sometime around then?

**Comment by jhpoelen** [comment]
@seltmann as requested, just published:

GloBI Community. (2022). Global Biotic Interactions: Interpreted Data Products (0.5) [Data set]. Zenodo. https://doi.org/10.5281/zenodo.7348355

Now with improved verbatim data products! :smile: 

Please let me know you are able to access the new data publications by closing this issue.
