### ISSUE TITLE
Bug regarding matching the Globi data to GBIF or ITIS

### ISSUE THREAD

**Issue by BarbaraMeulenbelt** [globalbioticinteractions/globalbioticinteractions#844]
Hi Jorrit!

As requested, an issue regarding matching the data to GBIF and ITIS matchers :)
When I try to match with COL, I get +/- 73k rows

> cat interactions.csv.gz | gunzip | mlr --icsv --otsvlite cut -f sourceTaxonId,sourceTaxonName,sourceTaxonRank,interactionTypeName,targetTaxonId,targetTaxonName,targetTaxonRank | nomer replace --properties replace-source.properties col | nomer replace --properties replace-target.properties col | grep “COL:.*COL:.*” > COL-id-name-rank-interaction-id-name-rank.tsv

When I try to match with GBIF or ITIS like this:

> cat interactions.csv.gz | gunzip | mlr --icsv --otsvlite cut -f sourceTaxonId,sourceTaxonName,sourceTaxonRank,interactionTypeName,targetTaxonId,targetTaxonName,targetTaxonRank | nomer replace --properties replace-source.properties gbif | nomer replace --properties replace-target.properties gbif | grep “GBIF:.*GBIF:.*” > GBIF-id-name-rank-interaction-id-name-rank.tsv

the system shows to be running:

> [main] INFO org.globalbioticinteractions.nomer.match.TermMatcherRegistry - using matcher [gbif-taxon]
> [main] INFO org.globalbioticinteractions.nomer.match.TermMatcherRegistry - using matcher [gbif-taxon]
> [main] INFO org.globalbioticinteractions.nomer.match.GBIFTaxonService - GBIF taxonomy ids already indexed at [/home/bameulenbelt/.cache/nomer/gbif/gbif], no need to import.
> [main] INFO org.globalbioticinteractions.nomer.match.GBIFTaxonService - GBIF taxonomy ids already indexed at [/home/bameulenbelt/.cache/nomer/gbif/gbif], no need to import.

but it does not produce any results.

King regards, 
Barbara

**Comment by jhpoelen** [comment]
@BarbaraMeulenbelt thanks for sharing the details on the unexpected behavior.

Note that 

```
grep "GBIF:.GBIF:."
```

matches only things like:

GBIF:XGBIF:Y

whereas,

```
grep "GBIF:.*GBIF:.*"
```

matches things like:

```GBIF:[some long string]GBIF:[some other long string]```


In other words, in grep-land a ```.```` matches a single character , and ```.*```` matches many characters .

Can you repeat the script with the ```.*``` match patterns?

**Comment by BarbaraMeulenbelt** [comment]
Hi Jorrit, sorry that was a typo 

> cat interactions.csv.gz\
> | gunzip\
> | mlr --icsv --otsvlite cut -f sourceTaxonId,sourceTaxonName,sourceTaxonRank,interactionTypeName,targetTaxonId,targetTaxonName,targetTaxonRank\
> | nomer replace --properties replace-source.properties gbif\
> | nomer replace --properties replace-target.properties gbif\
> | grep “GBIF:.*GBIF:.*”\
> > gbif-id-name-interaction-id-name.tsv

This is the right code

**Comment by jhpoelen** [comment]
@BarbaraMeulenbelt thanks for the update. 

Can you please include the replace-target.properties and reaplce-source.properties files, so I can try and reproduce your unexpected results?

**Comment by BarbaraMeulenbelt** [comment]
Yep.  

replace-source.properties:

> nomer.schema.input=[{"column": 1,"type":"name"}]
> nomer.schema.output=[{"column":0,"type":"externalId"},{"column": 1,"type":"name"}]


replace-target.properties:

> nomer.schema.input=[{"column": 5,"type":"name"}]
> nomer.schema.output=[{"column":4,"type":"externalId"},{"column": 5,"type":"name"}]
