### ISSUE TITLE
what do you call sleeping in?

### ISSUE THREAD

**Issue by neilcobb** [globalbioticinteractions/globalbioticinteractions#848]
https://link.springer.com/article/10.1007/s11829-022-09936-7

**Comment by jhpoelen** [comment]
Hi @neilcobb - thanks for sharing! Can you please elaborate?

**Comment by neilcobb** [comment]
the flies use the flowers to sleep, not sure if they visit flowers on the
species they sleep

Neil S. Cobb,

Biodiversity Outreach Network <https://www.bon-earth.org/>  Flagstaff AZ
*Business Office*
285 W Rome Way
Paulden, Az   86334

*Operations Office*

11 W Silver Spruce Ave

Flagstaff, AZ   86001


SCAN <https://scan-bugs.org/portal/index.php>  North American Arthropod
Portal

Mobile Office: 928-607-4075

Virtual Office:  *https://us02web.zoom.us/j/81630476460
<https://us02web.zoom.us/j/81630476460>*

ORCID  https://orcid.org/0000-0002-6155-9444

**Comment by jhpoelen** [comment]
Closing stale issue. Please feel free to re-open.
