### ISSUE TITLE
Suggest to index "Plant Parasites of Europe  leafminers, galls and fungi"

### ISSUE THREAD

**Issue by ZekeMarshall** [globalbioticinteractions/globalbioticinteractions#858]
Hi Jorrit,

Have you come across the "Plant Parasites of Europe  leafminers, galls and fungi" website (https://bladmineerders.nl/) before?

All the best,

Zeke

**Comment by jhpoelen** [comment]
@ZekeMarshall Nice find! Do you happen to know Dr. Willem N. Ellis , who appears to be the dataset curator ?

**Comment by ZekeMarshall** [comment]
Hi @jhpoelen , nope. I'll get in contact and see whether he would be willing to have the data indexed! :)

**Comment by jhpoelen** [comment]
@ZekeMarshall thanks for responding and offering to get in touch with Dr. Ellis. Curious to hear about the outcomes and how I can help to index their valuable plant parasite dataset.

**Comment by ZekeMarshall** [comment]
Hi @jhpoelen , I got in touch with Willem Ellis via email, unfortunately he isn't willing to have his dataset indexed by GloBI at this time! Should we keep this issue open?

**Comment by jhpoelen** [comment]
@ZekeMarshall thanks for checking. I labeled the issue with "non-open data" .  Do you think it makes more sense to keep the issue open, or close it?
