### ISSUE TITLE
suggest to index "ATLANTIC POLLINATION: a data set of flowers and interaction with nectar-feeding vertebrates from the Atlantic Forest" https://doi.org/10.1002/ecy.3595

### ISSUE THREAD

**Issue by zedomel** [globalbioticinteractions/globalbioticinteractions#872]
Suggest to index this data paper with plant-vertebrates interaction: [https://doi.org/10.1002/ecy.3595](https://doi.org/10.1002/ecy.3595)

**Comment by jhpoelen** [comment]
It appears that the Atlantic Pollination dataset has been index. 

@zedomel please feel free to re-open / comment to help improve this index configuration.

![image](https://user-images.githubusercontent.com/1084872/230922455-3c6c4c2a-e95e-4748-b4b1-897e26e49883.png)
