### ISSUE TITLE
How to Publish Thamnophis Dietary Data

### ISSUE THREAD

**Issue by theptin** [globalbioticinteractions/globalbioticinteractions#897]
I have gathered predation records from the garter snake genus, Thamnophis, and compiled them into a large excel file. Currently, the database hold 9,570 predation records from 32 of the 35 species of garter snakes. This database will be a part of a publication within the coming months, and I am hoping to make the data accessibel through GloBI upon publishing. Since the data is already in a .csv file, is there a way to prepapre this file for public access upon publishing? Or, will I need to change its format to match the interaction.tsv file example you have provided on the github template page?

**Comment by theptin** [comment]
I'm sure there is some overlap of sources between the datasets already published and this one, but to my knowledge, this is the most comprehensive one thus far. 
I have attatched a file with a few examples of how I have my .csv set up and the data it contains. 
[Example_Records.csv](https://github.com/globalbioticinteractions/globalbioticinteractions/files/11367091/Example_Records.csv)

**Comment by jhpoelen** [comment]
@theptin Thanks for sharing your example! Looks pretty good . . . 

using 
```
curl -L "https://github.com/globalbioticinteractions/globalbioticinteractions/files/11367091/Example_Records.csv"\
 | mlr --icsv --omd cat 
```

I generated the table below using your data:


| Prey_Highest | Prey_Higher | Prey_Phylum | Prey_Class | Prey_Order | Prey_Family | Prey_Genus | Prey_Species | Prey_Species_Current | Prey_Count | Snake_Species | Snake_Subspecies | FullSpName | Age_Class | SVL(mm) | Sex | Location | Latitude | Longitude | Citation | Full_Citation |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| Amphibian  | Frog_Adult | Chordata | Amphibia | Anura | Bufonidae | Incilius | Incilius occidentalis | Incilius occidentalis | 1 | Thamnophis_cyrtopsis | _collaris | Thamnophis_cyrtopsis_collaris | Adult | 799 | Female | "El Charcote," 6 km SW of Zapotitlan Salinas, Zapotitlan, Puebla | 18.33333 | -97.43333 | Abbadie-Bisogno_et_al_2003 | Abbadie-Bisogno, K, Oliver-Lopez, L., Ramierez-Bautista, A. THAMNOPHIS CYRTOPSIS COLLARIS (Black-Necked Garter Snake). DIET. 2003. Herpetological Review 34(1): 74-74 |
| Amphibian | Frog_Adult | Chordata | Amphibia | Anura | Bufonidae | Anaxyrus | Anaxyrus boreas | Anaxyrus boreas | 368 | Thamnophis_elegans | _elegans | Thamnophis_elegans_elegans |  |  |  | Lassen County, California |  |  | Arnold_1991 | Arnold, S. J. (1992). Behavioural variation in natural populations. VI. Prey responses by two species of garter snakes in three regions of sympatry. Animal Behaviour, 44(4), 705–719. https://doi.org/10.1016/S0003-3472(05)80297-0 |
| Fish | Fish | Chordata | Actinopterygii |  |  |  |  |  | 570 | Thamnophis_elegans | _elegans | Thamnophis_elegans_elegans |  |  |  | Lassen County, California |  |  | Arnold_1991 | Arnold, S. J. (1992). Behavioural variation in natural populations. VI. Prey responses by two species of garter snakes in three regions of sympatry. Animal Behaviour, 44(4), 705–719. https://doi.org/10.1016/S0003-3472(05)80297-0 |
| Invertebrate | Earthworm | Annelida | Clitellata | Opisthopora |  |  |  |  | 27 | Thamnophis_brachystoma |  | Thamnophis_brachystoma |  |  |  | Pennsylvania | 40.87475 | -77.80103 | Asplund_1963 | Kennneth K. Asplund. (1963). Ecological Factors in the Distribution of Thamnophis brachystoma (Cope). Herpetologica, 19(2), 128–132. http://www.jstor.org/stable/3890548 |

**Comment by jhpoelen** [comment]
I quickly peeked at your example data, and have some minor comments / questions:

1. DOIs - some reference have dois. Did you consider parsing out the dois and add them in a separate column? e.g. reference doi
2. in prey columns you use whitespace ` ` to delimit genus and specific epithet. With the snakes, you use underscores (`_`). I was wondering whether you have a specific reason for the different name notation.
3. is there any specific taxonomy that you are aligning your names with? If so, suggest to include taxon id in addition to the name (if available). E.g., ITIS:174141 is ITIS taxon id associated with Thamnophis cyrtopsis or http://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=174141 
4. name columns are prefixed with the role of the described organism (e.g., Prey / Snake), however columns Age_Class	SVL(mm)	Sex do not. Suggest to also prefix these as with names to avoid confusion like: is the ageclass associated with the predator or prey? 

Curious to hear your thoughts.

and. . . . the dataset should be relatively easy to index by GloBI as is, assuming that the dataset is openly accessible and published as a csv file.

**Comment by theptin** [comment]
1. I have not considered a separate dog column, but that could be added relatively easily
2. One of the R programs I was using for analysis did not like the space between to delimit genus and species, so we added the "_" but now we could remove the "_" for consensus formatting.
3. I have not used any taxon id, but again, this can be added easily. 
4. That is a good point! I can certainly add that in.

Thank you for these comments! I will work on addressing them. I currently plan to have the raw .csv file published on GitHub, so that would make it available for GloBI correct?

**Comment by jhpoelen** [comment]
@theptin Thanks for your prompt replies.

> One of the R programs I was using for analysis did not like the space between to delimit genus and species, so we added the "" but now we could remove the "" for consensus formatting.

Yes, that makes sense. Suggest to apply the naming convention for prey items also for consistency. 

> I currently plan to have the raw .csv file published on GitHub, so that would make it available for GloBI correct?

Yes, a raw csv file on GitHub would work. Just point to it whenever you are ready to be indexed. 

Thanks again for reaching out.

**Comment by jhpoelen** [comment]
I was thinking about what you said: 

> I'm sure there is some overlap of sources between the datasets already published and this one, but to my knowledge, this is the most comprehensive one thus far.

, and I wanted to emphasize that I think overlap between sources is a good thing, and I am that others will be able to trace your work and perhaps even start new collaborations.

**Comment by theptin** [comment]
Hello,

I have been working on adding the ITIS number for each species in the database like we talked about. But I had another question come up. For my records, I often have multiple prey items in each record. The "Prey Count" column of my .csv is a count of how many of that specific prey item was reported in that source. Do I need to change that format in anyway, or will GloBI be able to recognize that there could be multiple prey items in a single row of the .csv?

**Comment by jhpoelen** [comment]
@theptin great to hear you are making progress! 

> Do I need to change that format in anyway, or will GloBI be able to recognize that there could be multiple prey items in a single row of the .csv?

Other datasets have similar columns, so no need to change anything at this point as far as GloBI indexing goes. 

Thanks for your update.

**Comment by theptin** [comment]
Hello!

I am happy to say our publication has been accepted, so our data is ready for integration into the GloBI system. The most updated version of the .csv file will live here: https://github.com/theptin/Thamnophis-GloBI/blob/main/GloBI_Thamnophis_Diet_records.csv 

Is there anything else I need to do to help get the data uploaded or is that all you need?

**Comment by jhpoelen** [comment]
Thanks for sharing your update @theptin and congratulation with your publication.

Because your schema is not the default GloBI schema, nor expressed in DwC-A (darwin core archive), I'll update the globi.json with a custom schema definition and send you a pull request for your review.
