### ISSUE TITLE
Occurrence associations from NEON Biorepository

### ISSUE THREAD

**Issue by mandrewj** [globalbioticinteractions/globalbioticinteractions#903]
As an example, https://www.gbif.org/dataset/69f3ca43-ed03-4ed1-92c4-58f9bd0eafc1

All records should have an association with another occurrence and those associations should be picked up by GLOBI

This individual specimen: https://www.gbif.org/occurrence/3126764329
is a subsamble of this bulk sample: https://biorepo.neonscience.org/portal/collections/individual/index.php?guid=NEON03SWA

The mammal endo and ectoparasite collection is similar with parasites from linked mammal occurrences: https://www.gbif.org/dataset/b768078a-6e05-4ade-8b70-13eb3279861b

An example https://biorepo.neonscience.org/portal/collections/individual/index.php?guid=NEON06NZU is a mouse host of https://biorepo.neonscience.org/portal/collections/individual/index.php?occid=1021697

**Comment by jhpoelen** [comment]
Thanks Andrew for your tour of the Neon Biorepositories and chat afterwards. And, thanks for providing some detailed pointers to the wealth of species interaction claims conveyed in your digital records. Hoping to have a look at adjusting the GloBI indexing strategies to pick up your annotations.

**Comment by jhpoelen** [comment]
Current GloBI index (dd. 2023-06-27) picked up some expected NEON host associations - 

https://www.globalbioticinteractions.org/?accordingTo=https%3A%2F%2Fbiorepo.neonscience.org%2Fportal%2Fcollections%2Findividual%2Findex.php%3Foccid%3D1021697&interactionType=ecologicallyRelatedTo

![image](https://github.com/globalbioticinteractions/globalbioticinteractions/assets/1084872/4e33a9a8-0641-4234-96b7-3d86702319f4)

Investigating why the scientific name of the linked specimen does not render for NEON06NZU in the host association claim obtained via https://www.globalbioticinteractions.org/?accordingTo=https%3A%2F%2Fbiorepo.neonscience.org%2Fportal%2Fcollections%2Findividual%2Findex.php%3Foccid%3D1021697&interactionType=ecologicallyRelatedTo .

**Comment by jhpoelen** [comment]
After improving GloBI's ability to link associated occurrences, NEON Biorepository records with linked specimen are now . . . linked. 

Here's an example related to the one listed above. Note that the associatedOccurrence reference NEON06NZU has now been enriched to include taxonomic information associated with the _Peromyscus leucopus_ (white footed Deer Mouse) host. 

https://www.globalbioticinteractions.org/?accordingTo=https%3A%2F%2Fbiorepo.neonscience.org%2Fportal%2Fcollections%2Findividual%2Findex.php%3Foccid%3D1021697&interactionType=ecologicallyRelatedTo

![image](https://github.com/globalbioticinteractions/globalbioticinteractions/assets/1084872/59f86829-4489-4ef9-a536-ad5a2dda0ea7)

Thanks for pointing this out these neat linked records @mandrewj .
