### ISSUE TITLE
HOSTS - a Database of the World's Lepidopteran Hostplants 

### ISSUE THREAD

**Issue by ZekeMarshall** [globalbioticinteractions/globalbioticinteractions#910]
Hi @jhpoelen ,

I hope you have been keeping well.

I recently came across the "HOSTS - a Database of the World's Lepidopteran Hostplants" dataset (https://data.nhm.ac.uk/dataset/hosts). This would be great to index!

Apologies if you have seen this before.

All the best,

Zeke

**Comment by jhpoelen** [comment]
Thanks for sharing @ZekeMarshall ! I believe that HOSTS was, at some point, folded into the Natural History Museum Interaction Bank. 

Compare for instance the https://www.globalbioticinteractions.org/?interactionType=interactsWith&sourceTaxon=Acanthopteroctetes and associated screenshot already indexed by GloBI, with the associated records via HOSTS below. 

@ZekeMarshall I do prefer to index data as close to the source as possible, and it appears that the source you pointed out is closer to the source than the synthesized NHM Interaction Bank is. What do you think we should do?

**Comment by jhpoelen** [comment]
hey @ZekeMarshall - I just sent a message to the HOSTS data curators via their website and included a copy below. For some reason, they opted to only make the data available via an email call back, making direct integration with GloBI a little more complex than I had hoped. Do you know why they make it so hard to access their data?

-----

Hi! 

Thank you for making your HOSTS database available under a CC0 license. I tried to download your data, and found that I have to leave my email address and wait for a reply with some download link in it. After about 30 mins, I still haven't received the download link. 

Please make your dataset available for direct download to help facilitate data access.

Thank you!

-jorrit
https://globalbioticinteractions.org

see also https://github.com/globalbioticinteractions/globalbioticinteractions/issues/910

**Comment by jhpoelen** [comment]
@ZekeMarshall can you possibly try to download the full host dataset? Perhaps it is something about my email address or some geospatial thing.

**Comment by ZekeMarshall** [comment]
Hi @jhpoelen , apologies for the slow reply! 

I'm not sure why they opted for the email-only access. I've tried to access the data a few times by submitting my email, no luck so far!

I'll give them an email too!

All the best,

Zeke

**Comment by jhpoelen** [comment]
I received a message from NHM by email on July 21 2023 - 
-----
[...]

 Apologies for the delay in responding.

Until very recently, we were using an outdated download system in various sections of our website, and many users were having problems with it. At the beginning of this week, we finally replaced it with a newer system. If you attempt to download the data again, you should now be able to do so successfully.

With the new system, you also don't have to leave your email address (if you don't want to). There's still a processing queue, but you can access a status page to keep track of its progress rather than waiting for an email, if that's preferable.

Please let us know if you still have any issues!

Thanks,
[....]

**Comment by jhpoelen** [comment]
I was able to complete the HOSTS manual download procedure, and created:

https://github.com/globalbioticinteractions/HOSTS

to capture their results and let GloBI know how to interpret it.

**Comment by ZekeMarshall** [comment]
HI @jhpoelen , sorry for my slow reply! That's great! Will it be easy to integrate into GloBI, if any wrangling is required i'd be happy to help!

**Comment by ZekeMarshall** [comment]
Hi @jhpoelen , that's great! I've just read the review, everything looks good to me, the review is really useful!

**Comment by jhpoelen** [comment]
@ZekeMarshall thanks for taking a peek, and I am glad to hear your found the review useful. Hopefully others will benefit from your suggestion to have GloBI index HOSTS . . .
