### ISSUE TITLE
suggested to index Schwarz, Benjamin et al. (2021). Data from: Temporal scale-dependence of plant-pollinator networks [Dataset]. Dryad. https://doi.org/10.5061/dryad.qz612jmbp

### ISSUE THREAD

**Issue by cmsmith91** [globalbioticinteractions/globalbioticinteractions#920]
Some plant-pollinator data to add to globi. Note that this aggregates data from a bunch of papers so there may be some issues with duplication!
https://datadryad.org/stash/dataset/doi:10.5061/dryad.qz612jmbp

**Comment by jhpoelen** [comment]
@cmsmith91 thanks for pointing out this rich pollination dataset. I've attempted a first index configuration at https://github.com/globalbioticinteractions/schwarz2021 . Would you be interested to review GloBI's perspective on this dataset?

**Comment by cmsmith91** [comment]
Hi Jorrit - yes, sure

**Comment by jhpoelen** [comment]
@cmsmith91 thanks for offering to review the Schwarz et al. 2021 dataset . If all goes well, a review report should be generated over the weekend.

Also, @seltmann had some ideas on using network diagrams to get a feel for the data.

I've included one that shows how bee genera related to flower families. 

The graphs were generated using the bash script:

```bash
# first get a local copy of schwarz2021 
elton pull globalbioticinteractions/schwarz2021

# feel schwarz interactions into compile-network.sh 
elton interactions globalbioticinteractions/schwarz2021\
 | ./compile-network.sh discoverlife genus wfo family\
 | tee schwarz.dot.txt\
 | sfdp -Tsvg\
 > bee-genus-plant-family-schwarz.svg
```
The script strings together [Elton](https://github.com/globalbioticinteractions/elton), [compile-network.sh](https://github.com/globalbioticinteractions/globinizer/blob/2376d2bb988b0c5a97e3349f79facb317a8e7c57/compile-network.sh), and [graphviz's sfdp](https://graphviz.org) . Note that `compile-network.sh` uses [Nomer](https://github.com/globalbioticinteractions/nomer) to align DiscoverLife checklist to the pollinators on the genus level. The plants are aligned using World of Flora Online at the family level.

![bee-genus-plant-family-schwarz](https://github.com/globalbioticinteractions/globalbioticinteractions/assets/1084872/be6f71ec-054b-456f-8849-a3ad1f906019)
![bee-genus-plant-family-schwarz](https://github.com/globalbioticinteractions/globalbioticinteractions/assets/1084872/287eb3ff-f92f-4d3b-a789-0a53f18e9ab5)

**Comment by jhpoelen** [comment]
@cmsmith91 a review report of the Schwarz dataset is available at:

https://depot.globalbioticinteractions.org/reviews/globalbioticinteractions/schwarz2021/

Can you please go through this review report? See also attached archive.zip with pdf / html etc versions.

In particular, I am interested in:

1. Is the review report legible? If not, what change would you suggest to make the report more legible?
2. How does the review help you better understand GloBI's interpretation the Schwarz 2021 dataset?
3. What would you add to the tables / figures to help a reviewer like yourself get a quick sense of the quality of the dataset, the taxonomic scope of the data, etc.?

Thanks so much for reviewing the review . . . I am looking forward to your comments. 

[schwarz-review.zip](https://github.com/globalbioticinteractions/globalbioticinteractions/files/12652214/schwarz-review.zip)

**Comment by cmsmith91** [comment]
Hi Joritt,

Here are my comments

1. Is the review report legible? If not, what change would you suggest to
make the report more legible?

For the most part, yes. The only part that was illegible was the
interaction network, which was too small to read, and there are big blank
spaces before and after it.

2. How does the review help you better understand GloBI's interpretation
the Schwarz 2021 dataset?
It did help understand how the records will show up in GloBI. The review
also made me realize that there's a bunch of "species" in this dataset that
are not identified at all (e.g., animal99). Is it possible to remove those
records from GloBI?

3. What would you add to the tables / figures to help a reviewer like
yourself get a quick sense of the quality of the dataset, the taxonomic
scope of the data, etc.?

It would be nice to have tables or figures showing the geographic scope of
the dataset. I.e., how many sites sampled and over what scale? I think this
dataset is unique because it aggregates 30 or so other datasets and it
would be nice to have that come through more clearly in the report, if
possible. As I mentioned above there are also a bunch of interactions
between things like 'animal123' and plant99. It would be nice if there were
a table that showed really clearly how many records are id'd to
species/genus/family vs not a recognizable species at all.

Hope that's helpful!
Colleen

**Comment by jhpoelen** [comment]
@cmsmith91 thank you for taking the time to review the review of Schwarz et al. 2021 . 

> Is it possible to remove those records from GloBI?

In order to preserve somewhat of a neutral stance, claims/records are not removed, but they can be refuted. In this case, GloBI would attempt to link the names to some applicable taxonomic concept, like Animalia (animal) and Plantae (plant). This way, you'd still have the geospatial/temporal metadata as well as the associated reference. 

> It would be nice to have tables or figures showing the geographic scope of
the dataset

Thanks for sharing, yes, maps make sense. I am assuming temporal range maps would also be useful. 

> It would be nice if there were a table that showed really clearly how many records are id'd to species/genus/family vs not a recognizable species at all.

A table with taxonomic rank coverage statistics ! Yes, thanks for sharing your desire. 

Something like:

| rank | number |
| --- | --- |
| species | 342 (x%) |
| genus | 748 (x%) |
| NA | 431 (x%) |

perhaps?

possibly related to #918 

>The only part that was illegible was the interaction network, which was too small to read, and there are big blank
spaces before and after it.

Oef, yes, these network graphs are hard to read for sure. I am open to ideas to better organize/summarize this network data. 

Thanks again for your time, and please holler if you have any remaining thoughts or ideas.

Meanwhile, I'll try and tweak those review reports with your suggestions. How can I best attribute your ideas?
