### ISSUE TITLE
error when streaming interactions.tsv.gz into mlr  :  mlr: CSV header/data length mismatch 92 != 42 at filename (stdin) line  294204.                                                                      ]

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions#921]
to reproduce:

```
curl https://depot.globalbioticinteractions.org/snapshot/target/data/tsv/interactions.tsv.gz\
 | gunzip\
 | mlr --tsvlite cut -f sourceTaxonName,interactionTypeName,targetTaxonName
```

**Comment by seltmann** [comment]
I may have a related issue in mis aligned columns in the interactions.tsv from the data page/snapshot version. The dataset was downloaded ca. December 18th.

Then created a spreadsheet from the head -5000 > file.txt. Then imported the file.txt into an excel spreadsheet using tab-delimated/utf-8 import. 

[example-bees-plants-GloBI.xlsx.txt](https://github.com/globalbioticinteractions/globalbioticinteractions/files/13757138/example-bees-plants-GloBI.xlsx.txt)

[example-bees-plants-GloBI.tsv.txt](https://github.com/globalbioticinteractions/globalbioticinteractions/files/13757142/example-bees-plants-GloBI.tsv.txt)


I used this script to create a subset of full dataset. I ran shell script from command line, using tools grep, cut, uniq, sort. The script is here: https://github.com/Big-Bee-Network/global-bee-interaction-data/blob/main/bee_data_BID.sh

![Screen Shot 2023-12-22 at 2 24 11 PM](https://github.com/globalbioticinteractions/globalbioticinteractions/assets/1044474/aee249a0-962f-4f17-a449-b46b0649e0ba)

**Comment by jhpoelen** [comment]
@seltmann thanks for sharing your notes. Taking notes myself as I am trying to reproduce your results.

```
curl https://depot.globalbioticinteractions.org/snapshot/target/data/tsv/interactions.tsv.gz > interactions.tsv.gz
zcat interactions.tsv.gz | mlr --tsvlite cat | pv -l > /dev/null
```
yielded no errors, in counting of  all lines in about 5 minutes.

```
13.6M 0:05:18 [42.6k/s]
```

**Comment by jhpoelen** [comment]
I tried to produce your results using the script as documented in https://github.com/Big-Bee-Network/global-bee-interaction-data/pull/7 .

And. . . unfortunately, I am not seeing the data corruption you are seeing. Can you try and re-run the script (as I used it see pull request)? 

I've included the results of 

```
cat indexed_interactions_bees.tsv\
 | head -n5000\
 > indexed_interactions_bees_first_5000.tsv.txt
```

[indexed_interactions_bees_first_5000.tsv.txt](https://github.com/globalbioticinteractions/globalbioticinteractions/files/13757422/indexed_interactions_bees_first_5000.tsv.txt)

I am not seeing any malformed columns / rows. Can you please confirm by re-running your script on "freshly" downloaded data. 

Potential root causes for what you are seeing may be: 1. running two scripts at once, causing multiple script to write into one file 2. corrupted interactions.tsv due to size (it is a big! file when uncompressed). 

Item 2. would be covered by streaming from the original data as I suggested in the updated script. 

Curious to see whether re-running the script solves the problem.

**Comment by jhpoelen** [comment]
Also, I was unable to reproduce the original reported issue

```
curl --silent https://depot.globalbioticinteractions.org/snapshot/target/data/tsv/interactions.tsv.gz\
 | gunzip\
 | mlr --tsvlite cut -f sourceTaxonName,interactionTypeName,targetTaxonName\
 | pv -l\
 > /dev/null
```

yielded,

```
13.6M 0:05:03 [44.8k/s]
```
with no mlr errors were reported.

**Comment by jhpoelen** [comment]
@seltmann please review the outcome of the suspiciously formatted interactions.tsv - re-opening

**Comment by jhpoelen** [comment]
closing stale issue.
