### ISSUE TITLE
Release information of a dataset that uses GloBI dataset

### ISSUE THREAD

**Issue by Ariakei** [globalbioticinteractions/globalbioticinteractions#928]
Hi @jhpoelen 

I'm Kei of Sony Computer Science Laboratories and I research 'Synecoculture' with @to-minami as a team.
(He opened an issue last year about GloBI licensing matter here https://github.com/globalbioticinteractions/globalbioticinteractions/issues/772

Let me inform you that we publicly released a dataset that uses GloBI datasets and has two centrality indeces(namely, betweenness centrality and PageRank) calculated.

Please visit the GitHub URL below for more information. And it'd be appreciated if there's any concern.
https://github.com/SonyCSL/MMS-open-datasets/wiki/Biotic-Interaction-Dataset-with-centrality

Thank you!

**Comment by jhpoelen** [comment]
Hi @Ariakei Kei - 

Thanks for sharing the reference to your wikipage describing use of GloBI data. 

Two questions that came up for me as I was reviewing https://github.com/SonyCSL/MMS-open-datasets/wiki/Biotic-Interaction-Dataset-with-centrality -

1. you mention that you accessed the "stable" version of interactions.tsv.gz on 14 June 2023. According to my records, this means that you used data from:

**Comment by jhpoelen** [comment]
@Ariakei thank you for sharing your update. If you have additional information / thoughts, please do share.

**Comment by Ariakei** [comment]
@jhpoelen Thank you for your response! I aplogize for my late reply.
Actually we are preparing the related materials and necessary action currently. Let me update again once we are ready.

**Comment by jhpoelen** [comment]
@Ariakei thank you for taking the time to respond. I am curious to learn more about your work.
