### ISSUE TITLE
Browser links to multiple wrong external identifiers for taxon "Candidatus Endoriftia persephone"

### ISSUE THREAD

**Issue by kbseah** [globalbioticinteractions/globalbioticinteractions#968]
While familiarizing myself with the query browser, I found an unusual error when the taxon `Candidatus Endoriftia persephone` is used in a query (adding a screenshot in case this the problem is specific to my browser):
https://www.globalbioticinteractions.org/?interactionType=interactsWith&targetTaxon=Candidatus%20Endoriftia%20persephone

![globi_endoriftia_error](https://github.com/globalbioticinteractions/globalbioticinteractions/assets/9416913/2fb16e8a-02c0-4cad-afba-5340f6012566)

Under the taxon name, instead of a single link per external database as expected, there are multiple links. What they all have in common is that the names start with `Candidatus`. This is a designation used only in prokaryotic nomenclature for provisional names of taxa that are not yet in culture, because the prokaryotic code requires a type culture for valid publication ([details](https://lpsn.dsmz.de/text/glossary#candidatus)).

Perhaps Candidatus names are being misinterpreted as Linnean trinomials by the name matcher?

Surprisingly there was no Wikidata item for Candidatus Endoriftia persephone, but I've just created one: https://www.wikidata.org/wiki/Q124846046

**Comment by jhpoelen** [comment]
@kbseah thanks for sharing your observations re: Candidatus names. 

> Perhaps Candidatus names are being misinterpreted as Linnean trinomials by the name matcher?

Yes, perhaps! I'd have to look into the taxon alignment code and make sure that the candidatus prefix is handled properly. 

Meanwhile, perhaps @dimus or @mdoering may have some insights on how their parsers (gn parser  https://github.com/gnames/gnames  and gbif name parser https://github.com/gbif/name-parser resp.) handle the Candidatus names. 


> Surprisingly there was no Wikidata item for Candidatus Endoriftia persephone, but I've just created one: https://www.wikidata.org/wiki/Q124846046

Thanks for adding the wikidata item!

**Comment by dimus** [comment]
Hi @kbseah, from the point of GNparser: [Candidatus Endoriftia persephone](https://parser.globalnames.org/?format=html&names=Candidatus+Endoriftia+persephone&with_details=on)

https://parser.globalnames.org/?format=html&names=Candidatus+Endoriftia+persephone&with_details=on

**Comment by mdoering** [comment]
There is a special property for candidate names in the parsed result: http://api.checklistbank.org/parser/name?q=Candidatus%20Endoriftia%20persephone

The name in the label then is quoted entirely.

**Comment by jhpoelen** [comment]
@dimus Thanks for sharing your example of results of global names parser v1.9.1.

@mdoering Also, thanks for sharing your candidatus example. Which version of the GBIF parser are you using?

**Comment by mdoering** [comment]
checklistbank always uses the very latest release, 3.11.0 at this time: https://github.com/CatalogueOfLife/backend/blob/master/pom.xml#L83
The parser exposed at GBIF lacks a bit behind.

**Comment by jhpoelen** [comment]
Thanks for sharing the version of GBIF parser . Would it be an idea to include this in the result snippets?

**Comment by mdoering** [comment]
The version you mean? You can get that from the API which you can then use to find the corresponding parser and all other dependency versions:
https://api.checklistbank.org/version

Takes you to:
https://github.com/CatalogueOfLife/backend/commit/81e1c72

**Comment by jhpoelen** [comment]
I was imagining embedding the parse version in the parse response. 

currently, 

```
curl https://api.checklistbank.org/parser/name?q=Candidatus%20Endoriftia%20persephone\
 | jq .
```

produces: 

```json
{
  "scientificName": "\"Candidatus Endoriftia persephone\"",
  "rank": "species",
  "genus": "Endoriftia",
  "specificEpithet": "persephone",
  "candidatus": true,
  "code": "bacterial",
  "type": "scientific",
  "label": "\"Candidatus Endoriftia persephone\"",
  "labelHtml": "\"Candidatus Endoriftia persephone\"",
  "parsed": true
}
```

suggest to add some provenance like:

```json
{
  "scientificName": "\"Candidatus Endoriftia persephone\"",
  "rank": "species",
  "genus": "Endoriftia",
  "specificEpithet": "persephone",
  "candidatus": true,
  "code": "bacterial",
  "type": "scientific",
  "label": "\"Candidatus Endoriftia persephone\"",
  "labelHtml": "\"Candidatus Endoriftia persephone\"",
  "parsed": true,
  "generatedBy": "https://github.com/CatalogueOfLife/backend/commit/81e1c72"
}
```

**Comment by jhpoelen** [comment]
@kbseah Apologies for the delay in dealing with the Candidatus issue. Hoping to get to it sooner rather than later. Thanks for being patient.

**Comment by kbseah** [comment]
hi @jhpoelen , there's no need to apologise! Thanks for your continued work in maintaining this resource for everybody.

**Comment by jhpoelen** [comment]
The offending mapping for Candidatus Endoriftia persephone / endoriftia persephone as seen from TaxonMap.tsv.gz in Poelen, J. H. (2023). Global Biotic Interactions: Taxon Graph (0.4.5) [Data set]. Zenodo. https://doi.org/10.5281/zenodo.10045365 

```
 # get GloBI taxon graph 0.4.5
  preston cat\
   --remote https://zenodo.org\
   'hash://md5/feea1349e9c92140ee25df8a66c8773a'\
  > input/taxonMap.tsv.gz
  
  # also available via
  # curl -L https://zenodo.org/records/10045365/files/taxonMap.tsv.gz > input/taxonMap.tsv.gz
```


include, as generated via

```
cat input/taxonMap.tsv.gz\
 | gunzip\
 | grep "endoriftia persephone"
```

includes

```
	endoriftia persephone	EOL_V2:44433321	Candidatus Endoriftia persephone
	endoriftia persephone	IRMNG:11771915	Candidatus
	endoriftia persephone	IRMNG:11877615	Candidatus
	endoriftia persephone	IRMNG:1467030	Candidatus
	endoriftia persephone	IRMNG:1467691	Candidatus
	endoriftia persephone	WD:Q135611	Candidatus Pelagibacter ubique
	endoriftia persephone	WD:Q18601038	Candidatus Pelagibacter
	endoriftia persephone	WD:Q18646590	Candidatus Devosia euplotis
	endoriftia persephone	WD:Q2936284	Hamiltonella defensa
	endoriftia persephone	WD:Q6842280	Midichloria
	endoriftia persephone	WORMS:573762	Candidatus
	endoriftia persephone	WORMS:573763	Candidatus
	endoriftia persephone	WORMS:573770	Candidatus
	endoriftia persephone	WORMS:573771	Candidatus
	endoriftia persephone	WORMS:742983	Candidatus
	endoriftia persephone	WORMS:742984	Candidatus
```

**Comment by jhpoelen** [comment]
Taxon Graph v0.4.6 was released with  317 problematic Candidatus name mappings removed. Please allow for some time for changes to propagate to publicly available GloBI search index at https://globalbioticinteractions.org .

**Comment by jhpoelen** [comment]
Please note that the changes appear to have propagated as support by - 
```
curl -L "https://zenodo.org/record/11552565/files/taxonMap.tsv.gz"\
 | gunzip\
 | grep "Candidatus Endoriftia"\
 | wc -l
```
yielding 2 hits. 

whereas a 2024-06-20 snapshot version of taxonMap.tsv.gz produced - 

```
https://depot.globalbioticinteractions.org/snapshot/target/data/taxa/taxonMap.tsv.gz\
 | gunzip\
 | grep "Candidatus Endoriftia"\
 | wc -l
```

produced "0" lines with the provided search terms. 

Also, the browser query

https://www.globalbioticinteractions.org/?interactionType=interactsWith&targetTaxon=Candidatus%20Endoriftia%20persephone

no longer returns any associated species interaction claims

![image](https://github.com/globalbioticinteractions/globalbioticinteractions/assets/1084872/a962d2c4-abda-4493-9b02-9b3243da843c)

**Comment by kbseah** [comment]
Thanks for the update, @jhpoelen ! Does this mean that the existing interaction records for Candidatus Endoriftia pachyptila will have to be reprocessed by the pipeline, before appearing again?

I checked what claims remain for the host species Riftia pachyptila (https://www.globalbioticinteractions.org/?interactionType=interactsWith&targetTaxon=Riftia%20pachyptila). There is one listed interaction with a bacterium Hamiltonella defensa (an insect symbiont), but the records linked under "supported by" are all relating to Endoriftia persephone. The name Hamiltonella defensa itself is linked to two Wikidata items, one for H defensa (http://www.wikidata.org/entity/Q2936284) but the other is for Midichloria (http://www.wikidata.org/entity/Q6842280), an unrelated bacterium.

**Comment by jhpoelen** [comment]
> Thanks for the update, @jhpoelen ! Does this mean that the existing interaction records for Candidatus Endoriftia pachyptila will have to be reprocessed by the pipeline, before appearing again?

@kbseah Thank you for being patient . . . and for sharing your detailed notes.

About records related to `Candidatus Endoriftia pachyptila` - 

As far as I can tell, there are no records associated with `Candidatus Endoriftia pachyptila` . However, there are records that reference `endoriftia persephone` associated as seen on 2024-06-15T22:40:07.440Z , a name associated with `Candidatus Endoriftia persephone` . 

```bash
cat <(cat verbatim-interactions.tsv.gz | gunzip | head -1)\
 <(cat verbatim-interactions.tsv.gz | gunzip |  grep -i "Endoriftia persephone" | head -1)\
 | mlr --itsvlite --oxtab cat
```
producing 

```
sourceTaxonId                
sourceTaxonIds               
sourceTaxonName              endoriftia persephone
sourceTaxonRank              
sourceTaxonPathNames         
sourceTaxonPathIds           
sourceTaxonPathRankNames     
sourceTaxonSpeciesName       
sourceTaxonSpeciesId         
sourceTaxonSubgenusName      
sourceTaxonSubgenusId        
sourceTaxonGenusName         
sourceTaxonGenusId           
sourceTaxonFamilyName        
sourceTaxonFamilyId          
sourceTaxonOrderName         
sourceTaxonOrderId           
sourceTaxonClassName         
sourceTaxonClassId           
sourceTaxonPhylumName        
sourceTaxonPhylumId          
sourceTaxonKingdomName       
sourceTaxonKingdomId         
sourceId                     
sourceOccurrenceId           
sourceInstitutionCode        
sourceCollectionCode         
sourceCatalogNumber          
sourceBasisOfRecordId        
sourceBasisOfRecordName      
sourceLifeStageId            
sourceLifeStageName          
sourceBodyPartId             
sourceBodyPartName           
sourcePhysiologicalStateId   
sourcePhysiologicalStateName 
sourceSexId                  
sourceSexName                
interactionTypeName          hasHost
interactionTypeId            http://purl.obolibrary.org/obo/RO_0002454
targetTaxonId                EOL:393274
targetTaxonIds               
targetTaxonName              riftia pachyptila
targetTaxonRank              
targetTaxonPathNames         
targetTaxonPathIds           
targetTaxonPathRankNames     
targetTaxonSpeciesName       
targetTaxonSpeciesId         
targetTaxonSubgenusName      
targetTaxonSubgenusId        
targetTaxonGenusName         
targetTaxonGenusId           
targetTaxonFamilyName        
targetTaxonFamilyId          
targetTaxonOrderName         
targetTaxonOrderId           
targetTaxonClassName         
targetTaxonClassId           
targetTaxonPhylumName        
targetTaxonPhylumId          
targetTaxonKingdomName       
targetTaxonKingdomId         
targetId                     
targetOccurrenceId           
targetInstitutionCode        
targetCollectionCode         
targetCatalogNumber          
targetBasisOfRecordId        
targetBasisOfRecordName      
targetLifeStageId            
targetLifeStageName          
targetBodyPartId             
targetBodyPartName           
targetPhysiologicalStateId   
targetPhysiologicalStateName 
targetSexId                  
targetSexName                
decimalLatitude              
decimalLongitude             
localityId                   
localityName                 
eventDate                    
argumentTypeId               https://en.wiktionary.org/wiki/support
referenceCitation            http://www.ncbi.nlm.nih.gov/nuccore/110589133
referenceDoi                 
referenceUrl                 
sourceCitation               Sarah E Miller. 4/18/2016. Species associations from Wardeh, M. et al. Database of host-pathogen and related species interactions, and their global distribution. Sci. Data 2:150049 doi: 10.1038/sdata.2015.49 (2015)
sourceNamespace              millerse/Wardeh-et-al.-2015
sourceArchiveURI             https://zenodo.org/records/258189/files/millerse/Wardeh-et-al.-2015-v1.0.zip
sourceDOI                    
sourceLastSeenAtUnixEpoch    2024-06-15T22:40:07.440Z
```

Before I continue responding to your names, I am wondering: 

> Are you referring to record associated to `Candidatus Endoriftia persephone` instead of `Candidatus Endoriftia pachyptila` ?

**Comment by kbseah** [comment]
Yes you're right, I meant to write "Candidatus Endoriftia persephone" but got mixed up with the name of the host organism. Thanks for checking!

**Comment by jhpoelen** [comment]
@kbseah just to let you know - I am still mulling this over and digging into the origin of these misalignments . . . lots of moving parts and already made some improvements like https://github.com/globalbioticinteractions/nomer/issues/180 .

**Comment by kbseah** [comment]
thanks for keeping me in the loop!

**Comment by jhpoelen** [comment]
I've just released - 

```
Poelen, J. H. (2024). Global Biotic Interactions: Taxon Graph hash://sha256/bba97900d83350f05e1491c1f85f4164d7a5ef7eca876b1c91697fd43d6bd7a1 hash://md5/c49d580192d7031e8952bcce90275f0f (0.5.0) [Data set]. Zenodo. https://doi.org/10.5281/zenodo.12668767
```

which includes a newer version of the GloBI Taxon Graph. 

In this newer version the following relations are established:

retrieved via
``` 
cat\
 <(preston cat --remote https://zenodo.org hash://md5/1dad0d0c26e045785ad4cecf49238540 | gunzip | head -1)\
 <(preston cat --remote https://zenodo.org hash://md5/1dad0d0c26e045785ad4cecf49238540 | gunzip | grep "endoriftia persephone")\
 | mlr --itsvlite --omd cat
```

| providedTaxonId | providedTaxonName | resolvedTaxonId | resolvedTaxonName |
| --- | --- | --- | --- |
|  | endoriftia persephone | NCBI:393765 | Candidatus Endoriftia persephone |
|  | endoriftia persephone | GBIF:10860896 | Endoriftia persephone |
