### ISSUE TITLE
Taxon name "Giant Tube Worm (Riftia pachyptila)" is not being suggested by query interface

### ISSUE THREAD

**Issue by kbseah** [globalbioticinteractions/globalbioticinteractions#969]
(Encountered with issue #968, but filing it separately because it seems to be unrelated.)

When I type the taxon name `Riftia pachyptila` in the search interface, the only suggested result is `Hydrothermal Vent Worm (Riftia pachyptila)`, which returns no hits.

However, if I search for an organism that I know to interact with this species (`Endoriftia persephone`, see linked issue above), I do get a result with the expected species, but it is named `Giant Tube Worm (Riftia pachyptila)` instead.

However, typing `Giant tube worm` into the search form doesn't yield any suggestions.

I expected that typing "Riftia pachyptila" should have shown me all the available names, and/or they are merged into a single entry.

Thanks for your help!

**Comment by jhpoelen** [comment]
@kbseah thanks for sharing your observations.

As far as I can tell, https://www.globalbioticinteractions.org/?interactionType=interactsWith&sourceTaxon=Riftia%20pachyptila does return a bunch of results. See screenshots below. 

Can you please share the query url you used to help me reproduce your suspicious search results?

![image](https://github.com/globalbioticinteractions/globalbioticinteractions/assets/1084872/ee74fd7d-c30d-4ff1-9f30-1b29d06a423c)

and https://www.globalbioticinteractions.org/browse/?interactionType=interactsWith&resultType=json&sourceTaxon=Riftia%20pachyptila 

![image](https://github.com/globalbioticinteractions/globalbioticinteractions/assets/1084872/5ad6b9ef-e28f-4f1e-8d68-82298a9046c1)

**Comment by jhpoelen** [comment]
But perhaps I misunderstand your comments. If so, please clarify.

Thanks for being patient.

**Comment by kbseah** [comment]
Thanks for the quick response!

I think I see where I misunderstood the interface: I thought that one could only select from the list of suggested names that pops up when you start typing in the box. Now that I just type the name `Riftia pachyptila` and hit enter, the search works fine.

Nonetheless I'm curious where the suggested name "Hydrothermal Vent Worm ..." comes from, given that it doesn't return any hits.

**Comment by jhpoelen** [comment]
@kbseah I just create a taxonomic name alignment configuration for _Riftia pachyptila_ at https://github.com/jhpoelen/tubeworm and was able to generate the attached alignment report (automatically). 

[alignment-report.zip](https://github.com/globalbioticinteractions/globalbioticinteractions/files/14605583/alignment-report.zip)

According to the report, the GloBI Taxon Graph contains a alignments with the Encyclopedia of Life name catalog with english common name "Hydrothermal Vent Worm" associated with page http://eol.org/pages/393274 (see attached screenshot). 

Note that GloBI Taxon Graph is using an previous version of the Encyclopedia of Life name catalog, but also note that the Hydrothermal Vent Worm entry is still there. 

If you think this common name is included in error, please contact @jhammock or @katjaschulz so they can review/update their records as they see fit.

![image](https://github.com/globalbioticinteractions/globalbioticinteractions/assets/1084872/de382135-dd87-4ec6-8509-e12b921d71bc)

**Comment by kbseah** [comment]
@jhpoelen I think the common names are fine, no problem there.

Thanks again for your help!

**Comment by jhpoelen** [comment]
@kbseah thanks again for sharing your observations.
