### ISSUE TITLE
GloBI API server appears to be down

### ISSUE THREAD

**Issue by wilsongoode** [globalbioticinteractions/globalbioticinteractions#979]
I have been using the Global Biotic Interactions API in an iOS app I’ve been developing. In general, it has been a great resource and is very interesting to explore. Last night (Wednesday, April 3rd) my program received data it couldn’t decode automatically as JSON. Upon investigation, the bad data was a Cloudflare page alerting me to a server error:
![image](https://github.com/globalbioticinteractions/globalbioticinteractions/assets/45737196/064a4bd6-7039-439e-8ccd-305d6651f51e)

It is clear that some API responses are still in Cloudflare’s cache, but seemingly all new queries are not functioning. For example, the Apis mellifera example query on the GloBI homepage still returns data. 

(the above is a copy of an email I sent to @jhpoelen)

**Comment by jhpoelen** [comment]
@wilsongoode reported that the issue was resolved. Hurrah!

**Comment by wilsongoode** [comment]
Thanks again! What is a good way to donate? I don't know that I have much more to offer at this point, but I may be open to contributing in other ways in the future.
