### ISSUE TITLE
create review report of bee interactions in GloBI as aligned by discoverlife

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions#984]
as discussed with @seltmann 

1. take all of globi interaction data (verbatim)
2. align source/target names with nomer's discoverlife 
3. generate a review report for all interactions with at least one discoverlife match 

More generally, create a review report of globi data (or any interaction dataset) viewed from the perspective of a specific nomer matcher.

**Comment by jhpoelen** [comment]
Answer the question - 

Why does the interaction count deflate from about about 1M to about 600k interactions when doing a sort | uniq on the interaction records containing bee names as aligned by the discover life matcher?

**Comment by jhpoelen** [comment]
outline of script for preparing the review report of bee interactions in GloBI as aligned by discoverlife:

```
cat interactions-verbatim.tsv\
 | nomer replace --input-schema=sourceTaxon.schema gbif-parse\
 | nomer replace --input-schema=targetTaxon.schema gbif-parse\
 | nomer append --input-schema=sourceTaxon.schema discoverlife\
 | nomer append --input-schema=targetTaxon.schema discoverlife\
 | grep discoverlife.org\
 > interactions-with-discoverlife-match.tsv

check-data.sh [interactions-with-discoverlife-match.tsv dataset]
```

**Comment by jhpoelen** [comment]
@seltmann A first pass at a script to select only interactions with some bee/wasp involvement in available for your review at:

https://github.com/Big-Bee-Network/select-bee-interactions.sh

Curious to hear your thoughts . . .

**Comment by jhpoelen** [comment]
Note that I've added a bee-interactions.tsv.gz in https://github.com/Big-Bee-Network/select-bee-interactions.sh with example output of the script. . . the review is running as we speak.

**Comment by jhpoelen** [comment]
Please find review report generated via GitHub Actions at https://github.com/Big-Bee-Network/select-bee-interactions.sh/actions/runs/9420567222 at

[https://github.com/Big-Bee-Network/select-bee-interactions.sh/blob/6e082f03adeae37ec773e8bd1da062d9b2e84bd8/review-report.zip](https://github.com/Big-Bee-Network/select-bee-interactions.sh/blob/6e082f03adeae37ec773e8bd1da062d9b2e84bd8/review-report.zip)

or for a pdf summary, please see [https://github.com/Big-Bee-Network/select-bee-interactions.sh/blob/main/index.pdf .](https://github.com/Big-Bee-Network/select-bee-interactions.sh/blob/6e082f03adeae37ec773e8bd1da062d9b2e84bd8/index.pdf) .

**Comment by jhpoelen** [comment]
and another review report, generated from a 2024-06-07 snapshot via - 

```bash
bash select_bee_interactions.sh https://depot.globalbioticinteractions.org/snapshot/target/data/tsv/verbatim-interactions.tsv.gz\
 | gzip\
 > bee-interactions-2024-06-07.tsv.gz
```

yielded in https://github.com/Big-Bee-Network/select-bee-interactions.sh/blob/d2ffa16ac7ffd538abcd43db430ca1db7fd50b06/bee-interactions-2024-06-07.tsv.gz

**Comment by jhpoelen** [comment]
After applying the additional filter for bee families 

```
[...]
   | grep -E "Andrenidae|Apidae|Colletidae|Halictidae|Megachilidae|Melittidae|Stenotritidae"\
[...]
```

the https://github.com/Big-Bee-Network/select-bee-interactions.sh/blob/c00a2695b86d7a36d93afae82f44e1832e96ab3c/bee-family-interactions-2024-06-07.tsv.gz was created using 

```bash
bash select_bee_interactions.sh https://depot.globalbioticinteractions.org/snapshot/target/data/tsv/verbatim-interactions.tsv.gz\
 | gzip > bee-family-interactions-2024-06-07.tsv.gz
```

According to the generated review report [1], adding the bee family name constraint reduced the number of interactions by about an order of magnitude (from 447k to 25k). This seems odd, because the previous review report included 39k interactions involving Apis mellifera alone. . . 


[1] https://github.com/Big-Bee-Network/select-bee-interactions.sh/blob/4724733f3d1071218fcb8a5617a7b5d3b7180452/bee-family-review-report-2024-06-07.pdf

**Comment by jhpoelen** [comment]
Turns out that the incomplete results of  https://github.com/globalbioticinteractions/globalbioticinteractions/issues/984#issuecomment-2155631938 may have resulted from an incomplete network transfer. 

After switching to using versioned, offline snapshots of the same verbatim interaction data, a more comprehensive review was obtained via https://github.com/Big-Bee-Network/select-bee-interactions.sh/actions/runs/9429684173 see attached screenshot 
![Screenshot from 2024-06-08 15-44-42](https://github.com/globalbioticinteractions/globalbioticinteractions/assets/1084872/b73182c1-93f1-46b3-bb33-4d2fa2fe09f3)

**Comment by jhpoelen** [comment]
report of bee interactions are available via -

https://www.globalbioticinteractions.org/2024/06/07/bees-only-please/

see also 

https://linker.bio/hash://sha256/6544960cb6215e1d2550e3b2f20ad43fbc7ccb762f8a27db802a2a53823ac7db

**Comment by jhpoelen** [comment]
Also see https://discourse.gbif.org/t/bees-only-please-selecting-hundreds-of-thousands-of-possible-bee-interactions-using-a-laptop-open-datasets-and-small-but-mighty-commandline-tools/4505 fyi @seltmann .

**Comment by seltmann** [comment]
Looks good! @jhpoelen 

When are the bee family names applied to the record? Is this also based on DiscoverLife? I would expect the higher taxonomy in the output to also be based on the catalog/s that I am using to do the filtering. 

A next step will then be to update the synonyms with the current valid names for the bees also based on Discover Life. I suspect this would be a column added to each row rather than a replacement of the verbatim name. Eventually this update will want to be done with other catalogs as well, such as world flora online for the associated plant taxa.

**Comment by jhpoelen** [comment]
@seltmann thanks!

> When are the bee family names applied to the record?

in https://github.com/Big-Bee-Network/select-bee-interactions.sh/blob/0ca199f682ed5e24aec8ca30031cbabd1723d655/select_bee_interactions.sh#L90

and 

https://github.com/Big-Bee-Network/select-bee-interactions.sh/blob/0ca199f682ed5e24aec8ca30031cbabd1723d655/select_bee_interactions.sh#L91

the source and target taxonomic alignments are appended to the provided table. 

Then, only lines with at least one successful alignment (i.e., not `NONE`) are selected in the table with the appended rows. 

After that, in https://github.com/Big-Bee-Network/select-bee-interactions.sh/blob/0ca199f682ed5e24aec8ca30031cbabd1723d655/select_bee_interactions.sh#L93 , only lines containing a bee family name are included. 

Finally, the appended rows are truncated in https://github.com/Big-Bee-Network/select-bee-interactions.sh/blob/0ca199f682ed5e24aec8ca30031cbabd1723d655/select_bee_interactions.sh#L94. 

For some reason, I thought the final step would be useful, but now I wonder whether we should keep the appended names so you can see the details of the alignment in the final project.

Would you like to skip the last step to truncate the appended (or aligned) names?

**Comment by seltmann** [comment]
@jhpoelen yes! I think it is useful to keep the appended (or aligned) names.
