### ISSUE TITLE
update neo4j documentation 

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions#988]
Related to @weepy 's 

> [...]
> The reason why you are unable to connect to the neo4j interface is because it is no longer publicly available. Allowing to run open-ended queries (e.g., Cypher queries) on a public neo4j causes the main GloBI website and API to be at the mercy of whoever happens to run a query.  Also, having folks write queries that run against specific versions of neo4j and/or GloBI schema would provide less room for doing software maintenance (e.g., upgrade neo4j, optimize GloBI schema). 
>
> In other words, the neo4j instance that GloBI website / API is using is up and running, but no longer publicly accessible to run queries on it directly. This is also why rglobi > 0.3.x doesn't support running Cypher queries directly anymore (see https://github.com/ropensci/rglobi/releases/tag/v0.3.4) .
> 
> However, you run your own instance by downloading a neo4j db archive from https://globalbioticinteractions.org/data and run it with a supported neo4j version (currently an "ancient" version v3.5.x, but see also  #860 ).
>
> Apologies for the inconvenience, and I hope you understand that GloBI is trying to balance providing easier access to millions of openly available species interaction claims with keeping the overhead/cost of running servers / maintenance down.

> [...]

_Originally posted by @jhpoelen in https://github.com/globalbioticinteractions/globalbioticinteractions/issues/987#issuecomment-2127026226_

**Comment by weepy** [comment]
heya - do you have any pointer about how to install neo4j 3.5 ?! Having
trouble finding anything useful on their website.

**Comment by jhpoelen** [comment]
Sure, what operating system are you running?

**Comment by jhpoelen** [comment]
Here's a post that may be helpful. Please let me know if you have any suggestions to help your future self make this happen.

**Comment by weepy** [comment]
wow thats a clever hack - ive spent the past two hours trying to compile it
from source. downloaded hopefully a working version for 3.5.26 macos

**Comment by weepy** [comment]
hopefully the last question - I downloaded the data archive - and now have
an 8Gb folder called graph.db. How should I best import this ?

**Comment by jhpoelen** [comment]
> hopefully the last question - I downloaded the data archive - and now have an 8Gb folder called graph.db. How should I best import this ?

It's a drop install, so just copy the graph.db folder to 

```
[neo4j dir]/data/databases/
```

On the GloBI server, it looks like:

```
$ find /var/lib/neo4j/data/databases/graph.db/ | head
/var/lib/neo4j/data/databases/graph.db/
/var/lib/neo4j/data/databases/graph.db/neostore.nodestore.db.labels
/var/lib/neo4j/data/databases/graph.db/neostore.propertystore.db.index.id
/var/lib/neo4j/data/databases/graph.db/neostore.relationshiptypestore.db.names.id
/var/lib/neo4j/data/databases/graph.db/neostore.nodestore.db
/var/lib/neo4j/data/databases/graph.db/neostore.counts.db.b
/var/lib/neo4j/data/databases/graph.db/neostore.propertystore.db.strings
/var/lib/neo4j/data/databases/graph.db/neostore.relationshipstore.db.id
/var/lib/neo4j/data/databases/graph.db/neostore.labelscanstore.db
/var/lib/neo4j/data/databases/graph.db/neostore.schemastore.db.id
[...]
```

Please also note that I added some neo4j server download links in the neo4j archive download .

The text/ download links are also listed below - 

Want to run your own? Neo4j Server is available download for  [mac](https://neo4j.com/download-thanks/?edition=community&release=3.5.32&flavour=unix) [windows](htps://neo4j.com/download-thanks/?edition=community&release=3.5.32&flavour=winzip) [ubuntu/debian](https://neo4j.com/download-thanks/?edition=community&release=3.5.32&flavour=deb)

**Comment by weepy** [comment]
<img width="758" alt="Screenshot 2024-05-28 at 13 32 50" src="https://github.com/globalbioticinteractions/globalbioticinteractions/assets/820/0606a5c9-06bb-4efd-9f7f-6f57c1f64e5e">

hoorar success!

**Comment by jhpoelen** [comment]
@weepy yay! :medal_sports: How did you end up doing it?

Are you ready to take over hosting globalbioticinteractions.org now ? :smile_cat:

**Comment by jhpoelen** [comment]
> just did as u said - copied it over and booom !

Good to hear!

> memgraph

Look interesting . . . I'd be open to exploring creating a drop-in data product to get memgraph up and running quickly. Curious to hear your thoughts on that.
