### ISSUE TITLE
Protist-prokaryote symbiosis dataset - new dataset to index

### ISSUE THREAD

**Issue by kbseah** [globalbioticinteractions/globalbioticinteractions#994]
Hello @jhpoelen , 

I have a dataset of symbioses between protists and prokaryotes, compiled from the literature. The database is originally structured as a Wikibase instance on Wikibase.cloud (https://ppsdb.wikibase.cloud/wiki/Main_Page)

For integration with GloBI, I've set up an export (using a SPARQL query) of a subset of the original database to TSV format, following the field names in the GloBI template repository: https://github.com/kbseah/ppsdb-globi-export, though I haven't turned off the "deprecated" flag yet in the `globi.json` file.

My question to you is: how can I include more than one `sourceTaxonId` external identifier per `sourceTaxon`, and likewise for `targetTaxonId`? Taxa in the database are linked to NCBI Taxonomy identifiers and Wikidata items where possible; some are linked to both, to only one of the two, or to neither. Having more than one identifier can help with disambiguation of some of the names, but in the tabular format it appears that only one identifier is possible per `sourceTaxon`.

Perhaps you have some ideas on alternative ways to index my database in GloBI?

Thanks for your help!

**Comment by jhpoelen** [comment]
hey @kbseah thanks for your message.

Can you please share an example of the multiple sourceTaxonNameId  ?

**Comment by kbseah** [comment]
Sure! For example, the species Pelomyxa palustris (https://ppsdb.wikibase.cloud/wiki/Item:Q206) has NCBI taxon ID [168132](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=168132) and Wikidata identifier [Q3898962](http://www.wikidata.org/entity/Q3898962).

In the [TSV export](https://github.com/kbseah/ppsdb-globi-export/blob/main/interactions.tsv) I currently only included the NCBI taxon ID, but can easily modify the SPARQL query to report both.

**Comment by jhpoelen** [comment]
@kbseah thanks for sharing your example. 

Hmm, interesting. This makes me wonder - which id is the primary id and which one is derived from the first. In other words, what is the relationship between the name, and their associated ids. Who is claiming these relationships?

**Comment by jhpoelen** [comment]
Thanks for clarifying. 

For now, I'd suggest to follow the same format as the one used in GloBI's interactions.tsv.gz data product:

```sourceTaxonId``` contains the primary id (if available) (e.g., ```ncbi:tx168132```)

```sourceTaxonIds``` contains a pipe delimited list of primary as well as secondary ids. (e.g., ```PPSDB:Q206 | WD:Q3898962 | ncbi:tx168132```)

I have a feeling that we'd revisit this topic at some point and come up with a more appropriate solution. And, this may take a little while. So, I'd prefer to get the datasets integrated with available methods, and then improve integration methods as we go.

Curious to hear your thoughts.

**Comment by kbseah** [comment]
Thanks for the suggestion, I think that would be fine for now. I agree with your suggestion to index first and improve the integration methods later, because the effort to build a more elaborate integration should be guided by the usage patterns.

My thinking behind including the Wikidata identifiers was to also help disambiguate for the name matching step, especially in cases where an NCBI taxon ID is not available.

Looking forward to having this dataset indexed by GloBI!

**Comment by jhpoelen** [comment]
@kbseah thanks for your notes and encouragement. 

Before I jump into the reference you included - 

Would you have to some specific examples that related to your comment "[...] name alignment is poor, largely because many microbes are not described under formal taxon names but with informal identifiers. [...]" ?

**Comment by jhpoelen** [comment]
FYI - You can find a recent version of taxonomic alignment methods at encoded as a Makefile at:

https://github.com/globalbioticinteractions/taxon-graph-builder/blob/4b5fae9d8bd10a917fbf8d01042753b3be7497bb/Makefile

Note that some attempts are made to deal with commonly used "informal" identifiers, and I was hoping you could review and make suggestions to improve the methods.

It may also be a silly bug, because I would expect that the GloBI alignment process would link 

```Paramoeba sp. -[:same_as]-> Paramoeba -[:same_as]-> 	{NCBI:200890,	Paramoeba}```

But, for some reason, the example extracted from https://www.globalbioticinteractions.org/?accordingTo=globi%3Akbseah%2Fppsdb-globi-export&interactionType=interactsWith&sourceTaxon=Paramoeba%20sp. 

seems to suggest that this linkage was *not* made somehow. 

![image](https://github.com/user-attachments/assets/f030f111-5519-46e7-8b44-e9f4a18b11e8)


e.g.,

```
echo -e "\tParamoeba sp."\
 | nomer append globi-correct --include-header\
 |  mlr --itsvlite --omd cat 
```

| providedExternalId | providedName | relationName | resolvedExternalId | resolvedName | resolvedAuthorship | resolvedRank | resolvedCommonNames | resolvedPath | resolvedPathIds | resolvedPathNames | resolvedPathAuthorships | resolvedExternalUrl |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
|  | Paramoeba sp. | SAME_AS |  | Paramoeba |  |  |  |  |  |  |  |  |

**Comment by kbseah** [comment]
Thanks for the detailed response. Yes the example "Paramoeba sp." would be an example, along with "unclassified prokaryote", or a name like "Heterometopus sp. strain CSS" (https://www.globalbioticinteractions.org/?accordingTo=globi%3Akbseah%2Fppsdb-globi-export&interactionType=ecologicallyRelatedTo&sourceTaxon=Heterometopus%20sp.%20strain%20CSS).

My consideration with the Open Nomenclature signs was that it would help flag cases where the identification to the species level was not certain and so the name mapping should not be used to retrieve sequence records. For example, if Paramoeba sp. were mapped to the NCBI taxon ID for the genus Paramoeba, this would lead to incorrect sequences being retrieved, if someone were to use the NCBI taxon ID mapping to find sequences. Hope that makes sense.

**Comment by jhpoelen** [comment]
Ok, thanks for clarifying. 

I also figured out why the expected (and I know understand possibly misleading) 

```
Paramoeba sp. -[:same_as]-> Paramoeba -[:same_as]-> 	{NCBI:200890,	Paramoeba}
```

was not applied in the GloBI taxon alignment process . . . your dataset at https://github.com/kbseah/ppsdb-globi-export was not yet indexed by GloBI when GloBI taxon graph v0.5.2  was built. And, apparently, no other GloBI indexed dataset used ```Paramoeba sp.``` before. 
 
I hope to find some time to review the reference you shared. 

Meanwhile, I'd appreciate any suggestions  / comment you may have on the existing GloBI taxon alignment methods. Note, that the verbatim names are also available for those who'd like to apply their own name alignment processes.

**Comment by kbseah** [comment]
I see, thanks for the explanation about Paramoeba. To be honest, I'm not too clear about what the Makefile you linked is doing, but if I understand the Nomer readme file correctly, it attempts to match the supported databases by names, but can override this if a taxon ID is given? This would be the behavior I naively expect, especially for NCBI Taxonomy where they have multiple aliases for each taxon.

**Comment by jhpoelen** [comment]
@kbseah thanks for having a look at the Makefile. Bummer that I didn't make it easy for you to review the workflow. What would help make it easier to do so? Comments? 

> it attempts to match the supported databases by names, but can override this if a taxon ID is given?

Yes, it does attempt to match supported databases by name, with an override by id if given and supported by Nomer. 

The idea of the workflow is that first, the id/name pairs are matched as is, then, if no match is found, the name is processed using the "gbif-parse" and "globi-correct" matchers. The gbif-parse matcher attempts to split a name string into their taxonomic parts (e.g., Homo sapiens L. -> Homo | Homo sapiens (taxonomic name parts) , genus | species (taxonomic rank), L. (authorship)) . 

The `globi-correct` matcher does a bunch of different things, including removing unlikely taxonomic names (see https://github.com/globalbioticinteractions/globi-taxon-names/blob/main/non-taxon-words.txt) and mapping commonly used phrases (e.g., "plants") to their taxonomic counterpart (e.g., "Plantae") as defined in https://github.com/globalbioticinteractions/globi-taxon-names/blob/main/taxon-name-mapping.csv . 

Anyways, all this grew out of a desire to integrate disparate datasets to search across them. And . . . is open to discussion, review etc

Again, thanks for your notes, and I hope my comments above help to decipher the Makefile and maybe give some inspiration on how all this should be document to invite review / improvement. 

Curious to hear your thoughts. . .

**Comment by kbseah** [comment]
Thanks for the explanation! I think the procedure is very reasonable, given how diverse the verbatim names are.

Given how the names are matched to the supported databases, I think I will continue using the verbatim names as labels instead of applying the ON signs for now, since those are often taken directly from what is stated in NCBI Taxonomy.

The only suggestion might be to annotate formally named taxa vs. informally named taxa, which is what I do in the Wikibase version of my database.

**Comment by jhpoelen** [comment]
Thanks for sharing your notes on the name alignment process. 

> The only suggestion might be to annotate formally named taxa vs. informally named taxa, which is what I do in the Wikibase version of my database.

When you say "formal", do you mean verbatim or more like accepted name according to some taxonomic resource? 

PS. I've released a newer version of the GloBI Taxon Graph v0.5.3 that includes the names indexed from a version of your protist-prokaryote dataset. E.g.,

```
$ zcat taxonMap.tsv.gz | grep "Paramoeba sp"
	Paramoeba sp.	NCBI:1906369	Paramoeba sp.
	Paramoeba sp.	NCBI:1906369	Paramoeba sp.
	Paramoeba sp.	ITIS:43888	Paramoeba
	Paramoeba sp.	NCBI:200890	Paramoeba
	Paramoeba sp.	COL:6FLL	Paramoeba
	Paramoeba sp.	GBIF:3210450	Paramoeba
	Paramoeba sp.	WORMS:120552	Paramoeba
	Paramoeba sp.	WD:Q1026999	Paramoeba
	Paramoeba sp.	EOL:62536	Paramoeba
```

Poelen, J. H. (2024). Global Biotic Interactions: Taxon Graph hash://sha256/0b58753e4ff5519442689d866c0f1d19ffa7d97f917144df1d1cd56ea756921d hash://md5/b23bd0210c88ca10c3e3253091f4fdfa (0.5.3) [Data set]. Zenodo. https://doi.org/10.5281/zenodo.12806531

**Comment by kbseah** [comment]
Thanks for the taxon graph update!

By "formal" I'm referring to the Latin names for taxa, regardless of their taxonomic status (accepted or not). I hesitated to use "scientific name" because scientists refer many taxa with informal names too, but I didn't want to call these "unscientific"...

**Comment by jhpoelen** [comment]
@kbseah thanks for clarifying your usage of "formal" names. I appreciate your sensitivity here. Common names, vernacular names etc. are not necessarily less scientific/valuable than these latin names. In fact, I seem to remember that many of the latinized names have their roots in commonly used names that pre-date the famous 1758 publication of our Swedish friend.

**Comment by jhpoelen** [comment]
Hmm. Not quite sure why the links associated with Paramoeba sp. are not showing up yet. Keeping issue open for now.

Apologies for the delay . . .

**Comment by jhpoelen** [comment]
For review report see https://depot.globalbioticinteractions.org/reviews/kbseah/ppsdb-globi-export/ and well as attached. 

[ppsdb-review-2024-07.zip](https://github.com/user-attachments/files/16458862/ppsdb-review-2024-07.zip)
